### PR TITLE
[testing] ABD2: linear/scatter dual typed buffer for ARC ([upstream] rebase master January 13th 2016) 

### PR DESCRIPTION
**Pull request by kernelOfTruth**
upload for buildbot-testing the rebased patchset

@tuxoko I apologize in advance if your rebase is still in WIP or not complete

it built fine locally - so I figured it's time for buildbot-testing to prepare an re-adoption/upgrade to the rebased branch

Thanks :+1:

### CODE REVIEW

**Comment by tuxoko** [comment]
There's still bugs in it I haven't located yet.

**Comment by kernelOfTruth** [comment]
There were dozens of changes, several large ones - so I guess it's natural that it'll take a few steps until it works.

If you have no objections I've force-pushed the changes to see how it goes.

**Comment by kernelOfTruth** [comment]
hm, that one rings a bell:

```
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0x159930 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0xd70000 >= 0x2000000)' failed.
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 (0x159930 >= 0x2000000)' failed.
/sbin/ztest[0x408133]
/lib64/libpthread.so.0(+0xf790)[0x7f68ccbe2790]
/lib64/libc.so.6(gsignal+0x35)[0x7f68cc871625]
/lib64/libc.so.6(abort+0x175)[0x7f68cc872e05]
/lib64/libc.so.6(+0x2b74e)[0x7f68cc86a74e]
/lib64/libc.so.6(__assert_perror_fail+0x0)[0x7f68cc86a810]
/sbin/ztest[0x408133]
/lib64/libc.so.6(+0x2b87b)[0x7f68cc86a87b]
/lib64/libzpool.so.2(+0x37638)[0x7f68cdd21638]
/lib64/libzpool.so.2(+0x395d3)[0x7f68cdd235d3]
/lib64/libzpool.so.2(arc_buf_alloc+0x1fa)[0x7f68cdd2a84a]
/lib64/libzpool.so.2(arc_read+0x1d6)[0x7f68cdd2ae76]
/lib64/libzpool.so.2(+0x4bfa5)[0x7f68cdd35fa5]
/lib64/libzpool.so.2(dbuf_read+0xe6)[0x7f68cdd36396]
/lib64/libzpool.so.2(+0x4f2c8)[0x7f68cdd392c8]
/lib64/libzpool.so.2(dbuf_hold_impl+0xe4)[0x7f68cdd38bd4]
/lib64/libzpool.so.2(dbuf_hold_level+0x2a)[0x7f68cdd3981a]
/lib64/libzpool.so.2(dmu_buf_hold_noread+0x96)[0x7f68cdd44a16]
/lib64/libzpool.so.2(dmu_buf_hold+0x42)[0x7f68cdd45032]
/lib64/libzpool.so.2(zap_lockdir+0x83)[0x7f68cddd8ce3]
/lib64/libzpool.so.2(zap_add+0x61)[0x7f68cddda3c1]
/sbin/ztest[0x412599]
/sbin/ztest[0x40ab8d]
/lib64/libzpool.so.2(zk_thread_helper+0x22c)[0x7f68cdd1565c]
/lib64/libpthread.so.0(+0x7a51)[0x7f68ccbdaa51]
/lib64/libc.so.6(clone+0x6d)[0x7f68cc92793d]
child died with signal 6
```


```
ztest: ../../module/zfs/arc.c:3811: Assertion `(arc_stats.arcstat_c.value.ui64) >= 2ULL << 24 
```

referencing: https://github.com/zfsonlinux/zfs/issues/3904 PANIC at arc.c:3760:arc_adapt()

**Comment by behlendorf** [comment]
@kernelOfTruth you may want to add #4197 to your stack.  This should address the PANIC you're seeing, for some reason it appears to be happening much more frequently now in the buildbot.  Id definitely want o get that finalized and merged hopefully next week.

**Comment by tuxoko** [comment]
There's a segfault here http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20x86_64%20%28TEST%29/builds/456/steps/shell_5/logs/stdio
Not sure where does that came from.

**Comment by kernelOfTruth** [comment]
gladly at least one buildbot appeared to not suffer from that PANIC - let's see what the Amazon TEST buildbot will show

@behlendorf sure, will do that - thanks

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/blob/ab5cbbd1078bf007b50b084bb31fd58c7c5652f4/lib/libzpool/kernel.c

zk_thread_join

calls pthread_join

found one related issue: https://github.com/zfsonlinux/zfs/issues/989 ztest failures

judging from http://man7.org/linux/man-pages/man3/pthread_join.3.html

there could be an access, locking issue

perhaps https://github.com/zfsonlinux/zfs/pull/4197 helps somehow , will fold/amend those changes into the 30th patch, that should grab it faster like with the changes in the other pull-request

**Comment by kernelOfTruth** [comment]
Looking good :cake: 

Great work & thanks @tuxoko :+1:

**Comment by kernelOfTruth** [comment]
@sempervictus ping

**Comment by kernelOfTruth** [comment]
closing, superseded by newer pull requests/testing

**Pull request closed without merging**
