### PR TITLE
Support zstd compression (port of Allan Judes patch from FreeBSD)

### PR DESCRIPTION
**Pull request by BrainSlayer**
This is a port of Allan Jude's FreeBSD patch for supporting zstd compression on zfs filesystem. this patch has been tested on arm cortex-a15 and x86_64 platforms in a limited way (copying, verifying data etc.) unlike the original patch this one here will also support the ultra zstd compression settings (level 20 - 22), the rest is a plain original port without any major changes, except for bsd only specific functions which had to be implemented and differences in the zfs implementation at all. i also added the latest code from zstd repository which may have better performance and compression ratio than the original freebsd included zstd version

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by bunder2015** [comment]
Can you please put the pull request template back into your post?  Thanks

**Comment by BrainSlayer** [comment]
@bunder2015 can you tell me where to find a usefull template?

**Comment by bunder2015** [comment]
It's the text in the box you typed your PR into when you click New Pull Request.

**Comment by BrainSlayer** [comment]
@bunder2015 the problem is i cannot find it again once the pull request has been made. still search to find the default one which is used by github

**Comment by BrainSlayer** [comment]
found it. updated

**Comment by BrainSlayer** [comment]
@bunder2015 regarding the code style errors which are related to the original zstd code which is included. is there any formating script which can be used to fix it?

**Comment by gmelikov** [comment]
@BrainSlayer for example, in https://github.com/zfsonlinux/zfs/blob/master/Makefile.am#L80

**Comment by BrainSlayer** [comment]
@gmelikov : found it too. will try to change it in a way to ignore the zstd dir.

**Comment by BrainSlayer** [comment]
does somebody know why some buildbots fail with files they can't find? these files exists like other buildbots are showing

**Comment by BrainSlayer** [comment]
@behlendorf you have have heard of the licensing issues. so it must be self contained, consider also that i use a much newer zstd version as it was interated in linux or freebsd. so if i use the linux kernel implementation if available it may create GPL dependencies. i dont have any problem with that, but other might have

**Comment by behlendorf** [comment]
@BrainSlayer there is no licensing issue.  The `zstd` kernel implementation is dual "Dual BSD/GPL" licensed and explicitly exported for non-GPL modules to use.  There should be no additional dependencies.  If there are the build will fail so we'd find out right away.

```
MODULE_LICENSE("Dual BSD/GPL");
```

For user space `libzstd-devel` is BSD licensed and will be whatever's provided by distribution.  That does cut both ways, for fast moving distributions we'll likely get the version-of-the-week and for enterprise distributions one several years old.  But they're all [expected to respect the format specification](https://github.com/facebook/zstd/issues/999#issuecomment-359538229) and be decompressible.

If possible I think it would be desirable to rely on the system implementations for this.

**Comment by BrainSlayer** [comment]
@behlendorf that wont change the issue that the freebsd and linux kernel zstd versions are outdated. the behavior of zstd compression would be different depending which kernel you're using and if you are using a kernel without zstd support you may have to use a external library or embedded variant in any way too. i thought already about using the linux kernel variant, but decided to use the official zstd code first for my tests and guess what? its faster and the compression ratio is much better.  what about offering it as configure option?

**Comment by BrainSlayer** [comment]
nope it does not depend on the crypto framework and is dual licensed as well

linux:/home/seg/DEV/mpc83xx/src/linux/universal/linux-4.9/lib/lz4 # cat *.c|grep EXPORT_SYMBOL
EXPORT_SYMBOL(lz4_compress);
EXPORT_SYMBOL(lz4_decompress);
EXPORT_SYMBOL(lz4_decompress_unknownoutputsize);
EXPORT_SYMBOL(lz4hc_compress);

for zstd. the zstd code which is integrated works in the same way as you described it for the kernel. it allows you to define a own memory allocator and i also had to modify zstd a little bit since it uses very bad variable names. hundreds of times a variable named "current" is used. unfortunatly there is a very global kernel macro named "current" so zstd does fail to compile at all without modifications. so using zstd from external source tree for older kernels for instance will be tricky. it simply wont compile. this works for freebsd but not for linux due the macro conflict in advance the zstd version used right now does have the feature to use a own memory allocator defined by the caller. i reviewed the kernel implementation quickly just now and guess what. it works in the same way. it allows you to define a memory allocator. the workspace variant is optional but not a requirement. so conclusion. we may use the kernel variant in the same way as we do right now with a own memory allocator (stack space isnt a problem as you described since the current implementation already avoids this problem in the way allan implemented it), but if the kernel does not offer this std module, we have to fallback to a integrated modified zstd code variant due the reserved name problematic caused by bad variable names in zstd. btw (i renamed all occurences of "current" to "c_current")

**Comment by allanjude** [comment]
> 
> 
> @BrainSlayer thanks for starting this port and getting the ball rolling for Linux.
> 
> I looked over the proposed changed I think we should consider tackling this sightly differently than FreeBSD. On Linux both in user and kernel space we already have access to the zstd library. Let's use those libraries instead of maintaining our own. The [in-kernel implementation](https://github.com/torvalds/linux/tree/master/lib/zstd) in particular likely includes additional modifications/optimizations for running in the kernel.
> 
> The only major drawback I see initially is that `zstd` wasn't added until the 4.14 kernel. That would mean older kernels wouldn't be able to access zstd compressed pools. But that seems like a limitation we can initially live with and will quickly solve itself.
> 
> There is the additional issue that newer versions of zstd may compress the data differently than older versions. But that's an issue we're going to need to handle regardless of where the source in maintained.

FreeBSD also has zstd imported into the kernel, and my version of this patch for FreeBSD does use that.

There is a concern however with the fact that in FreeBSD anyway, the version of zstd will change down the road to a newer version. This means that blocks may not recompress to the same checksum. Only a problem for L2ARC w/o compressed ARC, and maybe to some degree nop_write and dedup.

This is why I've considered just importing a snapshot of a specific version of zstd into ZFS.

I think I'd still prefer to use the OS provided zstd, since as it gets upgraded over time it will increase the compression ratios etc. I just have not yet found a way to solve the L2ARC problem. Each possible solution seems to have some draw backs.


Note: the latest version of this patch depends on a new enough version of zstd to support the 'fast' compression levels (added in 1.3.4).

I notice that just 12 days ago, Yann released 1.3.6 "Database Edition", which aims to improve many compression of small blocks. I have not tested it yet, but it may be a large win for datasets and zvols with record sizes of 4, 8, and 16kb.

**Comment by allanjude** [comment]
> 
> 
> @behlendorf that wont change the issue that the freebsd and linux kernel zstd versions are outdated. the behavior of zstd compression would be different depending which kernel you're using and if you are using a kernel without zstd support you may have to use a external library or embedded variant in any way too. i thought already about using the linux kernel variant, but decided to use the official zstd code first for my tests and guess what? its faster and the compression ratio is much better. what about offering it as configure option?

The FreeBSD kernel version is 1.3.4, and will be updated to 1.3.6 (or newer) once the code-freeze is lifted.

**Comment by allanjude** [comment]
> 
> i found a blocking point for the kernel zstd implementation. its really too outdated. it does not support the negative compression levels for fast modes. this is mandatory for allans code since he explicit implements these fast modes. see also his presentation videos (but you may have seen that anyway :-) )

Brian was there in person.

**Comment by BrainSlayer** [comment]
@allanjude i dont expect that the linux kernel maintainers will update the zstd code. this patch here already contains 1.3.6. the whole patch is based on the latest version i found on the freebsd list

**Comment by behlendorf** [comment]
> I found a blocking point for the kernel zstd implementation. its really too outdated. it does not support the negative compression levels for fast modes. 

That's unfortunate, thanks for exploring the option of using the kernel implementation.

In that case, let's at least make sure we trim this down to the essentials.  The kernel only needed to bring in 17 source and header files.  Since this is a newer version so I'd expect it to be bigger, but still roughly that size.  The code coverage builder should give you a good sense of what's actually used if the PR includes test cases.

We may want to consider placing this code in `module/zstd/` and building it as its own kmod.  Similar to what was done with the lua interpreter.

**Comment by BrainSlayer** [comment]
@behlendorf: the makefiles i modified do already only include required files, but not all. to strip it more down i have to edit zstd which maybe a problem for later merges with more recent versions. but if you wish so i can throw out everything is isnt in use in the source files itself

**Comment by BrainSlayer** [comment]
i deleted now all unused files from sourcetree

**Comment by kpande** [comment]
can you squash the PR into a single commit and only submit when you're ready for buildbot testing to avoid running them unnecessarily?

**Comment by BrainSlayer** [comment]
@kpande of course, i just used the build bots to find issues.

**Comment by BrainSlayer** [comment]
@kpande  in addition some build bots really needs to be fixed. they always blame that signed-off-by is missing. the problem is just. its not. i merged now all current changes to a single commit. but new commits will happen once i have to make changes to stay compatible to master branch otherwise the patch will break quickly again

**Comment by kpande** [comment]
nope, use git rebase and force push.

**Comment by BrainSlayer** [comment]
thats what i did. but git is very annoying since i even then get forced to manually edit merges to get back to the original code. so the current patch is single, but you see still some merge actions caused by code changes from upstream. but the patch itself applies clean to the current head. 

https://github.com/zfsonlinux/zfs/pull/8028/commits/8c5a12d6095eaa45e571529befc2e593f21818f8

thats all. no other commit is required

**Comment by BrainSlayer** [comment]
@allanjude please take a look on https://github.com/zfsonlinux/zfs/pull/8028/commits/e2a290dc038c9dd065fed7be6c6f40c32acebe57 this is important for freebsd as well. otherwise ztest will fail since illegal values might be stored in nv attributes. this patch does mask out the levels while storing or reading values. normally this should never happen, but ztest does fuzzing with such bogus values

**Comment by behlendorf** [comment]
@BrainSlayer part of your `git rebase` issue may be that you're working directly on the master branch.  

I'd suggest creating a new `zstd` branch off the latest master and making your changes there.  This makes it easy to keep your local master up to date (since it will always be a fast-forward), and for painless rebasing since you will only need to resolve legitimate conflicts.  You'll need to close this PR out and open a new one for the new branch, which isn't a big deal.

Creating a new branch off master from an existing clone.
```
git checkout master
git pull upstream master
git checkout -b zstd
git cherry-pick 8c5a12d
<apply any additional changes>
```

Rebasing your existing branch on master.
```
git checkout master
git pull upstream master
git checkout zstd
git rebase -i master
git push --force origin zstd
```

**Comment by richardelling** [comment]
for reference (again) https://github.com/zfsonlinux/zfs/wiki/Git-and-GitHub-for-beginners

**Comment by BrainSlayer** [comment]
@behlendorf: thats what i did initially. unfortunatly there where really conflicting changes after my initial patch in the master tree so i had resolv them

**Comment by BrainSlayer** [comment]
@richardelling : you dont need to write me always beginner links. i readed these instructions alot of times.

**Pull request closed without merging**
