### PR TITLE
fix booting via dracut generated initramfs

### LINKED ISSUE #3605: Unable to mount / at boot with Dracut, zfs-dracut 0.6.4-20 under Debian Stretch
I noticed that recet versions of `zfs-dracut` renders the initramfs images (3.19.8, 4.0.5 and 4.1.2) unable to mount the root «/» filesystem, with the error `unable to mount /sysroot`, leaving a Busybox rescue shell; using `zpool import -R / poolname` and even `zpool import -R /sysroot poolname` will import the pool and mount its datasets successfully, but when exit the shell, the system hangs and still unable to boot. This ocurrs in the both my desktop and laptop (both with Debian Stertch and zfs related packages 0.6.4-20).

This problem **does not** ocurr using `initramfs-tools` and `zfs-initramfs`, when the root pool is imported, and then root and descendant filesystems are mounted correctly and the system boots successfully.

I use Dracut because I have better control on the generated initramfs images and smaller size is beter when using with **EFI Stub** in small EFI partition.

img_20150716_172559
img_20150716_172613

### PR DESCRIPTION
**Pull request by prometheanfire**
Dracut and Systemd updated how they integrate with each other, because
of this our current integrations stopped working (around the time
4.1.13 came out).  This patch addresses that issue and gets us booting
again.

Thanks to @Rudd-O for doing the work to get dracut working again and
letting me submit this on his behalf.

Fixes #3605

### CODE REVIEW

**Comment by prometheanfire** [comment]
does this need a recheck?

**Comment by behlendorf** [comment]
@prometheanfire the failures here look unrelated to the patch but I've resubmitted those test runs just to be sure.

**Comment by prometheanfire** [comment]
I imagined as much, thanks

**Comment by behlendorf** [comment]
I should add that I'd feel much better about merging this if we can get a few more more testers/reviewers for this change.

**Comment by prometheanfire** [comment]
Ya, so far this is just @Rudd-O and me testing it as far as I know.

**Comment by Rudd-O** [comment]
For reviewers, here is the right way to review this:

* Patch this into your ZFS tree.
* Build SPL and ZFS DKMS RPMs (`make rpm-dkms`).
* Install a fresh Fedora system, then migrate it to ZFS.  Use the following procedure: https://github.com/zfsonlinux/zfs/pull/4478 *but*, very important, pass the `--use-prebuilt-rpms=/path/to/your/RPMs` argument when you get to the step that invokes `deploy-zfs`.  This guarantees that your system will have the necessary GRUB fixes, while at the same time guaranteeing that you will be testing _your tree_ rather than whatever I have upstream in my own.

Alternatively, you could just use the infamous `zfs-fedora-installer` at github.com/Rudd-O/zfs-fedora-installer, which also accepts the command line tool `--use-prebuilt-rpms=`, to exercise the whole "build a bootable OS" system, then boot the OS using QEMU-KVM (or something similar) on your workstation.  This should get you to bootable image in about 10 minutes tops.

I have verified that this process works on my side, but I run a very idiosyncratic platform, so I cannot guarantee that my system configuration -- no matter how isolated and vanilla I got my build and test system to look -- is not partly responsible for a false test positive.

**Comment by lorenz-at-mpcdf** [comment]
To give you one more data point: I can boot my openSUSE installation on a ZFS root with this patch (but not without it)

**Comment by Rudd-O** [comment]
On 04/06/2016 10:22 AM, lorenz wrote:
>
> To give you one more data point: I can boot my openSUSE installation
> on a ZFS root with this patch (but not without it)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/zfsonlinux/zfs/pull/4478#issuecomment-206292811>
>

Fuk yea.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by behlendorf** [comment]
This change appears to have a caused an issue in #4518.  Could someone familiar with the patch take a look at this.

**Comment by Rudd-O** [comment]
The failing checks seem unrelated to this patch:

```
/var/lib/buildbot/slaves/zfs/Kernel_org_Default_x86_64__BUILD_/build/zfs/module/zfs/zfs_znode.c:1518:17: error: ‘PAGE_CACHE_SIZE’ undeclared (first use in this function)
  off = start & (PAGE_CACHE_SIZE - 1);
                 ^
```

**Comment by Rudd-O** [comment]
I don't think that issue is an issue with the patch, honestly.  Dracut hanging at a part of the initrd creation that has nothing to do with ZFS, that to me sounds very odd and should probably be reported upstream.

**Comment by behlendorf** [comment]
Was it determined that the issue was unrelated to this patch?  If so it seems like this change has received some pretty positive feedback and it can get merged.

**Comment by prometheanfire** [comment]
From what I can determine it is.

Currently packaged dracut in debian cannot boot zfs.  This patch sounds like it doesn't changes that.

My gut feeling about it is that debian has added patches that might conflict with this patch but that's a gut feeling I cannot verify, user has to kill dracut once then restart to generate an image, which can result in a bad image.

It improves the status quo for all distros but debian, where it doesn't seem to change bootability for them, but I can't test :(

In my opinion this gets us at least most of the way there, it may not be perfect but it a good starting point.

**Comment by behlendorf** [comment]
OK, then if everyone who's reviewed this change and post a LGTM I'll add their signed-off-by and get it merged.

**Comment by prometheanfire** [comment]
don't know if mine counts but...

LGTM :+1:

**Comment by behlendorf** [comment]
@prometheanfire the build failures here are definitely unrelated and fixed in master.  If you could rebase this on master we can get a clean test run before merging it.  Also your review definitely counts!

**Comment by prometheanfire** [comment]
rebased (no conflicts), I should have time to test this soon, hopefully tonight.

**Comment by prometheanfire** [comment]
yep, working here :+1:

**Comment by kostyaberger** [comment]
Hi everyone! I'm on Fedora 23, but I've had this boot stumble problem for quite some time now. Must be the same thing, though, as I never use Fedora or RPM-Fusion provided RPMs, but build from git source. Last time was yesterday.

Is there a shortcut to using this patch, or do I need to pull the whole branch? My usage of Git is limited to just downloading remote code.

I must add, however, that for me the problem (in ZoL provided scripts) is that they fail to detect my pool on boot. I know that from the fact that when boot stops and drops me into shell the simple `zpool import` command fails to show any pool. Only `zpool import -d ...` was able to detect the pool.
My pool was originally created under FreeBSD and it's a raw disk rpool taking the whole (unpartitioned) disk, so it's different, maybe, from what is thought to be "the linux" approach. However, GRUB2 makes no difference, so I don't see why zfs boot scripts should, given that zpool utility has this special -d option to it.

thanks for your help and hard work.

**Comment by Rudd-O** [comment]
I have small fixes incoming, which fix additional problems in Fedora 20 and below (I believe this to be very relevant to the CentOS branch of things).  I will submit them as separate pull requests.

**Comment by Rudd-O** [comment]
This commit should follow the merged patch:

https://github.com/Rudd-O/zfs/commit/36fd3c67dcf114d7c84e04e287c9cd96337eacca

**Comment by Rudd-O** [comment]
This commit should follow the previous one:

https://github.com/Rudd-O/zfs/commit/700106939f8016cd5321f0cc7fbced9fa202ddc5

**Comment by Rudd-O** [comment]
Finally, this commit needs to follow the other two ones before this comment:

https://github.com/Rudd-O/zfs/commit/830de2c0d7a34742dcabf0bd1675cad8c2dd6692

That is what enables Dracut to work again in older systems without advanced systemd support in their initial RAM disks.

**Comment by kostyaberger** [comment]
Thank you :). I'll see if i can follow, and if I can I'll report if it works for me on latest Fedora 23.

**Comment by dweeezil** [comment]
I finally got around to trying this (fed6299) on one of my Fedora 23 systems and it worked just fine.

**Comment by prometheanfire** [comment]
Should I integrate all of these into this PR?

**Comment by kostyaberger** [comment]
Doesn't work for me on Fedora 23. 
There is no /usr/lib/dracut/hooks/mount/mount-zfs.sh with this new commit, instead  a special systemd zfs-import-cache.service tries importing zpool using `zpool import -c /etc/zfs/zpool.cache $mypool` -- which fails. At that, just importing with `zpool import $mypool` works well enough.

**Comment by Rudd-O** [comment]
@kostyaberger 

See the three commits I posted above.  Apply them in series after applying the pull request commit.

This will restore the installation of mount-zfs.sh to your Dracut.

Note that, after applying the patch, mount-zfs.sh will be skipped whenever sysroot.mount is active within the initrd.  This should be the case in all modern Fedora systems.  Older Fedora systems, as well as other systems that use Dracut but do not use a systemd Dracut, still need mount-zfs.sh, which is why I have restored it.

**Comment by Rudd-O** [comment]
You know what we need?

We need something that runs https://github.com/Rudd-O/zfs-fedora-installer for each Fedora release beginning with Fedora 17 or something, and validates a particular combo of ZFS and SPL repos, to see if they boot.  The program has a simulated-with-QEMU boot process to create an image that can be later tested again with QEMU.  We need that to be incorporated in the buildbot above.

I can do the necessary work on the zfs-fedora-installer side.

**Comment by kostyaberger** [comment]
A, ok thank you, I'll try this as well.
Sent from Yahoo Mail on Android 
 
  On Mon, Apr 25, 2016 at 1:56, Rudd-O<notifications@github.com> wrote:   
@kostyaberger 

See the three commits I posted above. Apply them in series after applying the pull request commit.

This will restore the installation of mount-zfs.sh to your Dracut.

Note that, after applying the patch, mount-zfs.sh will be skipped whenever sysroot.mount is active within the initrd. This should be the case in all modern Fedora systems. Older Fedora systems, as well as other systems that use Dracut but do not use a systemd Dracut, still need mount-zfs.sh, which is why I have restored it.

**Comment by dilshath** [comment]
I am using centos 7 in physical machine. While creating and saving new partition followed by using "fdisk" command for save and partprobe in Centos 7 (It is installed in KVM), I got this error (at least 3 or 4 times). I appreciate if you guide me how to fix this problem.

Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Starting Dracut Emergency Shell...
Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Generating "/run/initramfs/rdsosreport.txt"
Entering emergency mode, Exit the shell to continue.

dracut:/#

How to resolve this error?

**Comment by behlendorf** [comment]
Merged to master as:

a5a3702 fix booting via dracut generated initramfs

@Rudd-O or @prometheanfire could you please open a new pull request with any additional patches / changed needed.  I've merged this one as is since it received a good bit of manual testing from various people.  That'll provide a good base to build on for any remaining improvements.

@Rudd-O I'm all for adding additional test coverage to the buildbot for this.  If you can craft a shell script similar to the existing test scripts in https://github.com/zfsonlinux/zfs-buildbot/tree/master/scripts which tests this functionality we can add it.  The hard part of course is that you can't reboot the machine or buildbot will tree the test as a failure.

**Comment by prometheanfire** [comment]
@Rudd-O it was just those three patches right?  If you don't want to do the PR I can if you want.

**Comment by kostyaberger** [comment]
You can ask on zfsonlinux mailing list and supply more info on the particular steps you've taken. From your desctiption it isn't very clear. And don't forget to explain where exactly ZFS comes into play.

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 25, 2016 at 14:12, dilshath<notifications@github.com> wrote:   
I am using centos 7 in physical machine. While creating and saving new partition followed by using "fdisk" command for save and partprobe in Centos 7 (It is installed in KVM), I got this error (at least 3 or 4 times). I appreciate if you guide me how to fix this problem.

Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Starting Dracut Emergency Shell...
Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Generating "/run/initramfs/rdsosreport.txt"
Entering emergency mode, Exit the shell to continue.

dracut:/#

How to resolve this error?

**Comment by Rudd-O** [comment]
@behlendorf @prometheanfire the three commits I listed above, listed here:

https://github.com/Rudd-O/zfs/commit/36fd3c67dcf114d7c84e04e287c9cd96337eacca
https://github.com/Rudd-O/zfs/commit/700106939f8016cd5321f0cc7fbced9fa202ddc5
https://github.com/Rudd-O/zfs/commit/830de2c0d7a34742dcabf0bd1675cad8c2dd6692

are necessary to fix other bad boot cases.

I have created a pull request to track the inclusion of these:

https://github.com/zfsonlinux/zfs/pull/4558

**Comment by kostyaberger** [comment]
Regarding "other" boot problems: not being able to import zpool due to its "being used by other system" is solved by adding spl.spl_hostid=$hostid kernel command line option (the exact value of which I borrow from the other system). This one works fine and is a better solution than forceful import using "-f" this way or another.

But since I have to stick with a much older F 21 kernel on Fedora 23, the 4.2+ being all broken, I can't test the last changes above just now.

**Pull request closed without merging**
