### PR TITLE
Zfs 0.6.5.7 release candidate

### PR DESCRIPTION
**Pull request by nedbass**
Open PR for automated testing of 0.6.5.7 release candidate

### CODE REVIEW

**Comment by melkor217** [comment]
Hurray?

**Comment by behlendorf** [comment]
@nedbass the test failures here are all known issues and not regressions.  Fixes for all these test failures can be found in master and _might_ make sense to backport.  You might also want to consider reordering the patch stack so the build fixes are the first patches applied.

* ZFS Test Suite:
  * zpool_add_004_pos - 99d0a9c39ea655fe4545bee31235cd91f2908763
  * zpool_create_023_neg - 82f6f6e654a51b47f9f2d642197852ced80487ee
  * quota_001_pos - 1a04bab34808694f3bf1cef3dc208c9499d103aa
  * quota_003_pos - 1a04bab34808694f3bf1cef3dc208c9499d103aa
  * refreserv_001_pos - 1a04bab34808694f3bf1cef3dc208c9499d103aa

* Build Issues:
  * SPL ppc64 build - zfsonlinux/spl@2a552736b7fc2bcb810cc520abd2ff9e229a9904

* Zloop issues:
  * zloop.sh script - 9c13b489879beadc3eab04ebf16434477b3081db

**Comment by behlendorf** [comment]
I reviewed the patch stack and it LGTM.

**Comment by Ralithune** [comment]
Are there instructions somewhere on how I can install this for testing on an Ubuntu system?

**Comment by nedbass** [comment]
0.6.5.7 released at https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.7

**Pull request closed without merging**
