### PR TITLE
0.6.5.10-rc2

### PR DESCRIPTION
**Pull request by tonyhutter**
### Description
I took @l1k's 0.6.5.10-rc1 patchsets (https://github.com/zfsonlinux/zfs/pull/6033) and made the following changes:

- _Move ziltest.sh to the ZTS framework_ (https://github.com/zfsonlinux/zfs/pull/6033/commits/66fc7bf17a6218e6f8896892b2798b8906a7a5e5) removed since 0.6.5 doesn't have the test suite.
- _Add kmap_atomic in dmu_bio_copy_ (https://github.com/tuxoko/zfs/commit/869f1eba11ceba8b12e710bf82514a1c073b9e64) added at @tuxoko's request in https://github.com/zfsonlinux/zfs/pull/6033#issuecomment-301868961
- Test suite added temporary so that buildbot can run.  I'll remove this before commit. 

Requires-spl: refs/pull/615/head

### Motivation and Context
Update 0.6.5 branch with needed fixes.

### How Has This Been Tested?
Builds on Centos 7.  Will see what buildbot reports.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by tonyhutter** [comment]
I forgot I also need to add:
_Fix harmless "BARRIER is deprecated" kernel warning on Centos 6.8_ 4630098

**Comment by behlendorf** [comment]
@tonyhutter can we also add these two patches.

3d91261 contrib/dracut: fix syntax error in module-setup.sh
24fa203 Guarantee PAGESIZE alignment for large zio buffers

**Comment by tonyhutter** [comment]
@behlendorf I think 3d91261 may not be applicable since the file it fixes (`./contrib/dracut/02zfsexpandknowledge/module-setup.sh.in`) isn't in 0.6.5.

**Comment by nedbass** [comment]
I suggest 2a152383a2bc54d43a7b478bd3c868b7165f2dca since it fixes a vdev_id problem on RHEL 6.9.

**Comment by l1k** [comment]
@behlendorf @tonyhutter The problem is that all the dracut stuff wasn't picked up by the 0.6.5 stable branch, presumably because it's in contrib/. Some distribution maintainers picked it separately for this reason, e.g. @happyaron has been doing a great job keeping that stuff up to date in Debian:
https://anonscm.debian.org/cgit/pkg-zfsonlinux/zfs.git/commit/?id=146eee208ab3

If you want to keep it up to date in 0.6.5 as well, you can easily determine the required patches from the above commit.

**Comment by tonyhutter** [comment]
I think I have most of the low-hanging fruit from the 0.6.5.10 project page included (https://github.com/zfsonlinux/zfs/projects/6).  I'm still looking into the remaining PRs.

**Comment by tonyhutter** [comment]
This is now building for me on Ubuntu 17.04 with a 4.12-rc3 kernel.

**Comment by tonyhutter** [comment]
I just pushed the latest batch of patches, and I think this is it.  I had to massage the patches a little to get them into the old codebase.

@tuxoko can you sanity check https://github.com/zfsonlinux/zfs/pull/6142/commits/86e58c08ae2603d56d57ec80b6540a99e63bf812 to make sure I ported it correctly?

@ahrens same with you for https://github.com/zfsonlinux/zfs/pull/6142/commits/b49c74f50efe321083eb6ddfc9b1958a25bb4389.  Can you give it a quick sanity check?

**Comment by tonyhutter** [comment]
@tuxoko my latest push has the `!aux` fix (now https://github.com/zfsonlinux/zfs/pull/6142/commits/0658a7a5369f807229edf9a4995b2dcb32f97bd2)

**Comment by tonyhutter** [comment]
Released
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.10

**Pull request closed without merging**
