### PR TITLE
Kernel 4.9 ABI: file_operations->aio_fsync removal

### LINKED ISSUE #5393: aio_fsync file operation got removed with 4.9-rc5
With [aio_fsync file operation removed](https://patchwork.kernel.org/patch/9404557/) **zfs** creates now similar errors:

```
/home/phil/dev/git/manjaro/repositories/extra/linux49-extramodules/spl_zfs/src/zfs-0.6.5.8/module/zfs/zpl_file.c:841:2: Fehler: unbekanntes Feld »aio_fsync« in Initialisierung angegeben
  .aio_fsync = zpl_aio_fsync,
  ^
/home/phil/dev/git/manjaro/repositories/extra/linux49-extramodules/spl_zfs/src/zfs-0.6.5.8/module/zfs/zpl_file.c:841:15: Fehler: Initialisierung von inkompatiblem Zeigertyp [-Werror=incompatible-pointer-types]
  .aio_fsync = zpl_aio_fsync,
               ^~~~~~~~~~~~~
/home/phil/dev/git/manjaro/repositories/extra/linux49-extramodules/spl_zfs/src/zfs-0.6.5.8/module/zfs/zpl_file.c:841:15: Anmerkung: (nahe der Initialisierung für »zpl_file_operations.fasync«)
```

... maybe this function is now obsolete?

### PR DESCRIPTION
**Pull request by DeHackEd**
Linux kernel commit 723c038475b78 removed this field.

Signed-off-by: DHE <git@dehacked.net>
Fixes #5393

### CODE REVIEW

**Comment by DeHackEd** [comment]
Build tested against 4.4.x and 4.9-rc5 as a before-and-after pair, but not actually test booted on 4.9 yet.

**Comment by Bronek** [comment]
Can we have a new 0.7.0 release candidate with this fix included, please? I am trying to test 0.7.0 with kernel 4.9

**Comment by behlendorf** [comment]
@Bronek yes, I'll see about cutting an -rc3 release.

**Comment by seanjnkns** [comment]
Any chance of getting this ported to 0.6.5 and deploying a new 0.6.5.9?  Our company would like to move to LTS 4.9 soon and aren't inclined to use any RC version of zfs/spl, so it would be ideal to see this ported to 0.6.5.x along with any other fixes that are slated for that release from #5163, which looks untouched for ~4 months now.

**Pull request merged**
