### PR TITLE
Trivial Version Bump to mark Linux 5.4 support

### PR DESCRIPTION
**Pull request by aerusso**
### Motivation and Context

This is a test of the current release branch on Linux 5.4.  I've already locally tested that it builds, modules load, pools import, and passes trivial read and write smoke tests locally.

### Description
Bumps the version to 0.8.3, and max Linux version to 5.4 in `META`.

### How Has This Been Tested?
Trivially (see description).

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed. **Let's see!**
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Ornias1993** [comment]
It's not trivial to change the ZoL version to a never-going-to-be-released version.
Testing for new kernels should be done before release. It's not guaranteed that 5.4 will still work on OpenZFS2.0 release (even with your patch) and it's not guaranteed that 5.4 will actually be supported on OpenZFS2.0 release.

I Think it will be supported, but it's up to the people preparing the actual release to add these flags right then.

I vote: Close this PR.

**Comment by aerusso** [comment]
@Ornias1993 I opened this PR so that we can see the results of the CI tests on essentially the current release. There don't appear to be any Linux 5.4 specific patches on master, so many people may wind up trying to use 0.8.2 on Linux 5.4 (I sure am!).

Even if the ultimate 0.8.3 release includes other patches, it is helpful for other users to know whether or not 0.8.2 (which this PR is, essentially) passes the standard tests.  On Linux git master, it does for at least some of the target distributions, as of right now.

Unless this is an inappropriate use of the CI infrastructure, please don't close this PR before letting those tests finish.

**Comment by Ornias1993** [comment]
@aerusso 
MASTER is NOT the current release. Not even "essentially". MASTER is in no shape or form 0.8.2 and tests on MASTER can NOT be used as evidence for 0.8.2 compatibility.

> Even if the ultimate 0.8.3 release includes other patches

As I tried to explain: There isn't going to be a 0.8.3, only openzfs2.0 which is going to include A LOT of changes.

> whether or not 0.8.2 (which this PR is, essentially)

Do you have any idea how many functional change differences there are between MASTER (this PR is tested on) and 0.8.2?

> Unless this is an inappropriate use of the CI infrastructure, please don't close this PR before letting those tests finish.

It isn't too much of an issue to send in a test PR, but please, send it as draft (before you send a PR, click the arrow beside on the green button and select "draft") instead....

**Comment by aerusso** [comment]
The most recent version uses the `Requires-kernel:` (is this switch documented anywhere?) and  targets Linux 5.4 specifically.  

Also, unless I'm gravely mistaken, the buildbot should be running zfs-0.8-release, and not zfs master.

**Comment by Ornias1993** [comment]
@aerusso The buildbot tests your change only, which is based on MASTER

**Comment by sempervictus** [comment]
Our 0.8.2 fork with the metaslab changes from master works just fine built directly into a grsec 5.4 binary (non-module in-tree). Zloop didn't whine and at least my laptop seems quite happy with it. Why cut another "release" without backporting actual functionality?

**Comment by Ornias1993** [comment]
> Why cut another "release" without backporting actual functionality?

What do you mean with this?

**Comment by aerusso** [comment]
> Our 0.8.2 fork with the metaslab changes from master works just fine built directly into a grsec 5.4 binary (non-module in-tree). Zloop didn't whine and at least my laptop seems quite happy with it.

@sempervictus Thank you for this bit of information! I'd like to collect this kind of testing data so that people can feel confident moving to a newer kernel. I'm running the test suite here on zfs-0.8-release [1] so that we can be sure that at least the test suite passes.

> Why cut another "release" without backporting actual functionality?

The supported kernel list should be updated to include 5.4, if indeed it is compatible. There is a machine-readable mechanism to indicate support for kernels, which unfortunately cannot be updated without making a release. Distributions like Debian also indicate these differences in supported kernels using this mechanism.

@Ornias1993 
> I doubt these minimum-maximum flags are actually used though... considering the minimum is actually 3.10 on master already.

These flags are used in building Debian packaging. They can obviously be manually bumped, but support of a particular kernel should be indicated by ZoL team directly. The first thing anyone would want to know is "Does the test suite succeed?". 

Also, I'm not sure why you're suggesting that the buildbot is testing something based on master. See below [1].  Is there some bug in the buildbot's reporting of the checked out git revision that I'm not aware of?

[1] This can be confirmed by clicking "Details" next to any of the builds and looking at the `got_revision` build property for ZFS, and confirming it is, indeed, simply a trivial version bump onto zfs-0.8-release, and not zfs master.

**Comment by Ornias1993** [comment]
@aerusso 

> These flags are used in building Debian packaging.

Thanks for that info, didn't know that.

> Also, I'm not sure why you're suggesting that the buildbot is testing something based on master. See below

SHOOT, I just saw you PR'ed against 0.8
So sorry for my commenting, nobody PR's against old versions outside the team.

That being said: All we know is that there isn't going to be a 0.8.3, so this is still kinda useless.

**Comment by aerusso** [comment]
# Summary of tests results

1. `zimport` test fails to import `master` pools on this version. Presumably, this is due to `bookmark_written`, `livelist`, and `log_spacemap`, `redaction_bookmars` and `redacted_datasets`.  

Also, [CentOS 6 x86_64](http://build.zfsonlinux.org/builders/CentOS%206%20x86_64%20%28TEST%29/builds/8956) has some configure error that I don't understand.

2. There are zfstests failures on [Ubuntu 16.04 x86_64](http://build.zfsonlinux.org/builders/Ubuntu%2016.04%20x86_64%20%28TEST%29/builds/9566):

## Tests with results other than PASS that are unexpected:
     FAIL xattr/cleanup (expected PASS)
     FAIL zvol/zvol_ENOSPC/setup (expected PASS)
     SKIP zvol/zvol_ENOSPC/zvol_ENOSPC_001_pos (expected PASS)

If I'm reading this correctly:

1. The `xattr/cleanup` test chokes on a `zxtr` user that is still in use
2. `zvol/zvol_ENOSPC/setup` appears because a mountpoint appears to have not been completely removed before attempting to create it with `mkdir`,
3. The `zvol_ENOSPC_001_pos` is skipped because of the setup failure.

These sound like deficiencies in the the test framework, not incompatibilities in ZFS.

@behlendorf Is it safe to officially say that ZoL 0.8.2 officially supports Linux 5.4?

As a second (apparently somewhat political) question, how would you like to proceed communicating that answer? If rolling another release represents a significant burden to the ZoL team, I can instead simply ferry this response back to the Debian team (and roll a manually updated kernel compatibility).

Maybe there should there be a wiki page listing supported kernels that are released after a ZoL release?

**Comment by Ornias1993** [comment]
@aerusso 
Keep in mind there are two meanings of `supported`.

1. "We actively support it, patch things for it and test for it", which is currently not the case for kernel 5.4 afaik
2. "It might technically work", which might be the case as you have proven.

**Comment by behlendorf** [comment]
> All we know is that there isn't going to be a 0.8.3, so this is still kinda useless.

Let me first clear this up.  There will be an 0.8.3 minor point release containing important bug fixes from the master branch (but no features).  @tonyhutter is working on this now.  OpenZFS 2.0 will be the next major release and it will include several new features.

> `zimport` test fails to import master pools on this version. 

That's right.  This test is expected to fail the way it's currently written.  i.e. the 0.8.x release can't import a pool created by the master branch with features enabled it doesn't understand.  For testing, you can disable this test on the 0.8 branch by including `TEST_ZIMPORT_SKIP="yes"` on its own line in the commit message.  Since it's easy to disable we haven't yet tweaked the CI to do this by default on this branch.  Feel free to force update this PR to get a cleaner run if you like.

>  Ubuntu 16.04 x86_64 failures

These are known false positives we occasionally see from the ZTS.  Fixes for this particular framework issue were applied to master but not yet backported.  So this is OK.

> @behlendorf Is it safe to officially say that ZoL 0.8.2 officially supports Linux 5.4?

Yes, it does.  There are no kABI changes which effect ZFS between 5.3 and 5.4.  But just be aware the CI currently doesn't include a builder which runs the full test suite using the 5.4 kernel.  The newest kernel tested is currently 5.3.12.  That said, @tonyhutter's has run the full test suite successfully on Fedora 31 before release those packages, and it ships with a 5.4 kernel.

> If rolling another release represents a significant burden to the ZoL team, I can instead simply ferry this response back to the Debian team

That would be ideal.  We'd planned to bump the kernel version with the 0.8.3 tag.

> Maybe there should there be a wiki page listing supported kernels that are released after a ZoL release?

Let's use update the official release notes on Github to include this information.  They already list this information and can be updated without tagged a new release.  I've gone ahead and updated the 0.8.2 tag accordingly.

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.2

**Comment by Ornias1993** [comment]
> Let me first clear this up. There will be an 0.8.3 minor point release containing important bug fixes from the master branch (but no features). @tonyhutter is working on this now. OpenZFS 2.0 will be the next major release and it will include several new features.

@behlendorf Maybe I didn't understand correctly, but in that case it seems the presentation last summit was very wrongly put?

**Comment by aerusso** [comment]
> But just be aware the CI currently doesn't include a builder which runs the full test suite using the 5.4 kernel

@behlendorf Could you please clarify your comment with respect to the  `Requires-kernel: v5.4` comment in the commit message? Did this only succeed because someone else already did the legwork to get the 5.4 branch running, or is it erroneously reporting working on the v5.4 branch [SourceStamps, linux, branch](http://build.zfsonlinux.org/builders/Debian%2010%20x86_64%20%28TEST%29/builds/763)?

Also, I'm closing this since its already yielded all the useful information I would be able to get with it (and there's already plans for 0.8.3 that supersede this).

**Comment by behlendorf** [comment]
@Ornias1993 to help clarify, ZoL like many large projects maintains both a release/production branch (currently zfs-0.8-release) and a master/development branch where all new changes are integrated.  

After a change has been merged to the master branch it _may_ be backported to the release branch if resolves a bug, a build issue, or something else important.  New functionality and features are not backported.  This allows distributions to track a stable branch (0.8.1, 0.8.2, etc) and only pick up fixes tested by the OpenZFS developers.  OpenZFS 2.0 will be the next major release/production branch and is planned for next year.

> Did this only succeed because someone else already did the legwork to get the 5.4 branch running, or is it erroneously reporting working on the v5.4 branch

The correct branch was tested.  I was only pointing out that the CI runs the ZTS using the latest distribution provided kernel.  So for example, this branch was tested on Debian 10 but using the 4.19.0-6-amd64 kernel according to the configure log (not a 5.4 kernel).  Similarly Fedora 30 was tested using the 5.3.12-200.fc30.x86_64 kernel, and CentOS with 2.6.32-754.24.3.el6.x86_64.  None of the bots currently install a 5.4 kernel and run the full test suite.  We'll get a 5.4 kernel in the mix once we replace the Fedora 30 builder with Fedora 31, which we haven't quite had an opportunity to do yet.

**Comment by Ornias1993** [comment]
@behlendorf I'm ware of how development works, but thanks for trying anyway ;)

I was a bit put off-track by the statement their wouldn't be a 0.9, I was confusing the minor (backport) and major version comments on the summit sorry! >.<

**Pull request closed without merging**
