### PR TITLE
0.6.5.10-rc1

### PR DESCRIPTION
**Pull request by l1k**
Kernel 4.11-rc7 is out and <a href="https://lkml.org/lkml/2017/4/16/279">may be the last rc in this cycle</a>. I've backported the 4.11 compat fixes and the other items listed on the <a href="https://github.com/zfsonlinux/zfs/projects/6">project page</a> (pulls only, not the issues). This might serve as a starting point for the official 0.6.5.10 release and will hopefully spare others the hassle of resolving the merge conflicts all over again. I've tested this with 4.9 and 4.11-rc6, both compiled without a hitch and seem to run fine so far.

### CODE REVIEW

**Comment by behlendorf** [comment]
@l1k thanks for opening a PR with the proposed patch stack for comment.

**Comment by loli10K** [comment]
I just hit this crash in `zdb` while debugging an issue with a BSD pool:

```
Core was generated by `zdb -ddddd bsd11'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  dump_bpobj_subobjs (os=<optimized out>, object=156, data=<optimized out>, size=<optimized out>) at zdb.c:500
500			(void) printf("\t%llu\n", (longlong_t)subobjs[i]);
[Current thread is 1 (Thread 0x7f79e6dc7780 (LWP 6859))]
(gdb) bt
#0  dump_bpobj_subobjs (os=<optimized out>, object=156, data=<optimized out>, size=<optimized out>) at zdb.c:500
#1  0x000000000040ba7e in dump_object (os=os@entry=0x15ac890, object=156, verbosity=verbosity@entry=5, print_header=print_header@entry=0x7fff3e4d854c) at zdb.c:1958
#2  0x000000000040c069 in dump_dir (os=0x15ac890) at zdb.c:2085
#3  0x0000000000405a23 in dump_zpool (spa=0x157b160) at zdb.c:3108
#4  main (argc=0, argv=<optimized out>) at zdb.c:3854
(gdb) !cat /sys/module/zfs/version
0.6.5.9-1
(gdb) 
```

This issue should be resolved by https://github.com/zfsonlinux/zfs/commit/2986b3fd2587b1da5b6047a5c0b6bbb0b6d9c47e _zdb: segfault in dump_bpobj_subobjs()_. The change seems very small, can we backport this too?

**Comment by l1k** [comment]
@loli10K: The commit looks innocuous enough to me, I've cherry-picked it on top.
If anyone has objections please shout.

**Comment by tuxoko** [comment]
@l1k 
Can you cherry-pick this https://github.com/tuxoko/zfs/commit/869f1eba11ceba8b12e710bf82514a1c073b9e64
This fix the issue https://github.com/zfsonlinux/zfs/issues/6031

**Comment by tonyhutter** [comment]
@l1k you can remove "Move ziltest.sh to the ZTS framework" (https://github.com/zfsonlinux/zfs/pull/6033/commits/e6d57b58dc41004866b8160139091f69e5725cf4) since 6.5 doesn't have the test framework.

**Comment by l1k** [comment]
@tuxoko @tonyhutter sorry, I was swamped with work this week so couldn't respond earlier. Closing in favor of #6142 which Tony opened in the meantime.

**Pull request closed without merging**
