### PR TITLE
Large Block Feature

### PR DESCRIPTION
**Pull request by behlendorf**
Based on #3362 but split in to a it's own pull request so the dependencies can be merged independently first.

### CODE REVIEW

**Comment by kpande** [comment]
is this supposed to apply cleanly on top of #3362 ?

**Comment by behlendorf** [comment]
Yes.  The idea is to land this in two parts since the dependencies are ready but there's still some behavior with blocks larger than 1m which needs to be explained.

**Comment by behlendorf** [comment]
@kpande #3362 has been merged to master so this patch stack now apply cleanly to master and has been refreshed.

**Comment by behlendorf** [comment]
Refreshed again.  This latest version addresses the issue with blocks over 1M in size.  This turned out to be a small Linux specific thing in the vdev_disk.c code.  It's now possible to use block sizes up to 16M blocks and I haven't observed any new issues.  This was the last known issue preventing this feature from being merged so I expect that to happen soon.

**Comment by kpande** [comment]
awesome, thanks @behlendorf - eagerly awaiting merge of this :-)

**Comment by DeHackEd** [comment]
I have a small number of IllumOS pulls I want to make. Once this gets merged they'll be ready to go in with fewer issues so I'll just wait.

**Comment by behlendorf** [comment]
@DeHackEd that's great.  After extensive testing I've merged the large block support to master.  It's safe to use block sizes up to 16M however by default the maximum size is limited to 1M.

f1512ee Illumos 5027 - zfs large block support

**Pull request closed without merging**
