### PR TITLE
Fix name of NFS kernel service for systemd.

### PR DESCRIPTION
**Pull request by ggzengel**
This addresses zfsonlinux/pkg-zfs/issues/192.

Signed-off-by: Grischa Zengel <github.zfsonlinux@zengel.info>

### CODE REVIEW

**Comment by ryao** [comment]
@ggzengel Is this a typo or are there instances in which that service name is actually used? If they are both in use in different places to refer to the same thing, we might want some kind of way of doing either/or. If systemd does not support that, then maybe via some distinction detected via autotools.

**Comment by behlendorf** [comment]
Does systemd allow you to specify multiple services like this?  Also, please squash the commits which you refresh this.

**Comment by ggzengel** [comment]
@ryao First I thought it was a typo, because I use ubuntu and debian. But after some investigation I found that both variants are used.
So I put both services inside.

**Comment by ggzengel** [comment]
@behlendorf They use plural in there description. So it should work.
I'm just learning to use git with eclipse. So I will do squash.

> PartOf=
> Configures dependencies similar to Requires=, but limited to stopping and restarting of units. When systemd stops or restarts the units listed here, the action is propagated to this unit. Note that this is a one-way dependency — changes to this unit do not affect the listed units.

>Before=, After=
>    A space-separated list of unit names.
...

**Pull request closed without merging**
