### PR TITLE
zfs-0.8.3 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Potential patchlist for zfs-0.8.3

### Description
This patchset includes the SIMD patches that everyone is looking for.  All of @behlendorf's SIMD patches are combined into one monolithic patch that was taken from #9515, rather than cherry-picking them individually.  I've also included the follow-on alignment patch that is also needed for SIMD (https://github.com/zfsonlinux/zfs/pull/9515/commits/942f7d7da41281084cc03d38c0b4eedafb2950c5).

### How Has This Been Tested?
Build tested only on RHEL 7.7

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Ornias1993** [comment]
You might want to add `closes #9515` just for convenience sake ;)

**Comment by loli10K** [comment]
@tonyhutter i took the liberty of adding a backport of #9489 to the patch stack

**Comment by andrey42** [comment]
Any chance we can merge two restructuring patches [part1](https://github.com/zfsonlinux/zfs/pull/9198) and [part2](https://github.com/zfsonlinux/zfs/pull/9206) into this patchset ? 

They both have been accepted into master branch, there are several important enhancements, for example [Improve AES-GCM performance](https://github.com/zfsonlinux/zfs/pull/9749) with work in progress state already dependent on new structure.

**Comment by loli10K** [comment]
Following patch cherry-picked from https://github.com/zfsonlinux/zfs/commit/30af21b02569ac192f52ce6e6511015f8a8d5729 should fix the currently failing `cli_root/zfs_receive/zfs_receive_raw` test case:

```diff
diff --git a/lib/libzfs/libzfs_sendrecv.c b/lib/libzfs/libzfs_sendrecv.c
index a93235798..1875f79e7 100644
--- a/lib/libzfs/libzfs_sendrecv.c
+++ b/lib/libzfs/libzfs_sendrecv.c
@@ -3518,6 +3518,7 @@ recv_skip(libzfs_handle_t *hdl, int fd, boolean_t byteswap)
                            P2ROUNDUP(drr->drr_u.drr_write_embedded.drr_psize,
                            8), B_FALSE, NULL);
                        break;
+               case DRR_OBJECT_RANGE:
                case DRR_WRITE_BYREF:
                case DRR_FREEOBJECTS:
                case DRR_FREE
```

**Comment by Ornias1993** [comment]
@andrey42 
The big different between ZoL 0.8.3 and OpenZFS 2.0 would be FreeBSD support.
Parts of features from next major version should only be ported to fix (breaking) bugs imho, not for performance fixes.

Because it opens the door to include more and more parts of new features.

**Comment by tonyhutter** [comment]
@loli10K thanks!
@andrey42 most likely those patches will go in with with the 2.0 release, which is scheduled to happen this year (2020) and will support FreeBSD.  Once #9749 goes in, we'll need to make a judgement call if we want to include it in a point release or wait until 2.0.  If we do decide to include it in a point release, we'll include the relevant bits from the restructuring patches to get it to work.

**Comment by ghfields** [comment]
As someone who primarily uses Ubuntu, I just wanted to remind people of the upcoming 20.04 LTS release.  The [release schedule found here](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule) says the Debian import freeze is scheduled for Feb 27.  0.8.3, if released soon-ish, it could make into Debian then Ubuntu LTS.  Otherwise, it will be incorporated using future HWE kernels.  Using the 18.04 schedule as a template, the first HWE kernel should be available in 20.04.2 in Feb 2021.

No pressure though.... a quality release beats a rushed release!

**Comment by tonyhutter** [comment]
@ghfields thanks for the info!

**Comment by tonyhutter** [comment]
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.3

**Pull request closed without merging**
