### PR TITLE
OpenZFS 6950 - ARC should cache compressed data (testing-only)

### PR DESCRIPTION
**Pull request by behlendorf**
Duplicate of #4768 for testing against master with the CentOS 6.7 fix applied.

### CODE REVIEW

**Comment by don-brady** [comment]
we have this commit as well.  I'll have to see where we differ...

**Comment by don-brady** [comment]
ignore my previous comment.  wrong PR!

**Comment by behlendorf** [comment]
Minimal fixes for the 25458cbef9e59ef9ee6a7e729ab2522ed308f88f conflict applied.

**Comment by angstymeat** [comment]
I'm running this patch against the latest July 25 commits (g25458cb) and I'm seeing a weird thing on all three machines: my load average never drops below 1, and I can't find what is running to cause it.

Two systems are running the 4.6.4-201.fc23.x86_64 kernel, and the third is running 4.6.4-301.fc24.x86_64. One is an Intel Xeon, one an AMD Opteron, and one an Intel i3. Memory in them ranged from 2GB to 32GB.

I'm also seeing radically different cache-hit and ARC-utilization statistics. The systems appear to be caching almost nothing but metadata, and cache hit-rates have dropped considerably (my graphs are showing rates at between 10% to 25% of what I had been seeing without this patch).

All three systems are running pools with LZ4 compression, and overall compression ratios range from 1.09x to 1.83x.

I don't know if the cache values are normal or not now that the ARC is storing compressed data, but the load average definitely seems wrong to me.

I can provide more information about the systems upon request.

**Pull request closed without merging**
