### PR TITLE
fix uninitialized scalar variable in cid 153352

### PR DESCRIPTION
**Pull request by luozhengzheng**
fix coverity defects:

** CID 153352:    (UNINIT)
/module/icp/io/sha2_mod.c: 645 in sha2_digest_atomic()
/module/icp/io/sha2_mod.c: 594 in sha2_digest_atomic()
thanks.

### CODE REVIEW

**Comment by tcaputi** [comment]
This defect is a leftover from the fact that the original ICP port only supported sha256. Since #4760 we actually do support these now. The correct fix for this bug is to do [this](https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/crypto/io/sha2_mod.c#L814), but we also should really go through this file and sha2.c and make sure we didn't miss anything else.

**Comment by luozhengzheng** [comment]
@tcaputi  thanks for your review. i've  gone through and updated it. please review it again,thanks.

**Comment by tcaputi** [comment]
@luozhengzheng 
Thanks for pointing this issue out to us. I had a little free time tonight and I was able to make the fix I was talking about before (which includes this fix). Sorry if I wasted any of your time.

@behlendorf 
I suggest dropping this PR in favor of the comprehensive fix (#5251) which should fix the Coverity defect and allows us to use SHA384 and SHA512 HMACs in the future.

**Comment by luozhengzheng** [comment]
@tcaputi that's the best thing.

**Comment by behlendorf** [comment]
Sounds good.

**Pull request closed without merging**
