### PR TITLE
Add the ZFS Test Suite (WIP)

### PR DESCRIPTION
**Pull request by behlendorf**
Add the ZFS Test Suite and test-runner framework from illumos.
This is a continuation of the work done by Turbo Fredriksson to
port the ZFS Test Suite to Linux.  While this work was originally
conceived as a stand alone project integrating it directly with
the ZoL source tree has several advantages:

  * Allows the ZFS Test Suite to be packaged in zfs-test package.
    * Facilitates easy integration with the CI testing.
    * Users can locally run the ZFS Test Suite to validate ZFS.
      This is currently STRONGLY DISCOURAGED because the ZFS Test
      Suite in it's current form can be destructive.
  * Allows the ZFS Test Suite to be run directly in the ZoL source
    tree enabled developers to iterate quickly during development.
  * Developers can easily add/modify tests in the framework as
    features are added or functionality is changed.  The tests
    will then always be in sync with the implementation.

Full documentation for how to run the ZFS Test Suite is available
in the tests/README.md file.

WARNING: This test suite is designed to be run on a dedicated test
system.  It will modifications to the system including, but not
limited to, the following:

  * Adding new users
  * Adding new groups

WARNING: Currently not all of the test cases are expected to pass.
The existing failures are primarily due to individual tests which
has not yet been ported to Linux.  Several tests which have been
observed to cause deadlocks under Linux have been disabled.  The
following results are representative of the default 'linux.run'
test workload.

  Results Summary
  FAIL     135
  SKIP      44
  PASS     425

  Running Time:      00:27:11
  Percent passed:    70.4%

TODO:
- [ ] Add to the 'Requires' lines to the zfs-test package for all
  support utilities: kpartx, losetup, etc
- [ ] Add wrappers for missing utilties in tests/zfs-tests/cmd/ when
  an equivilant Linux counterpart isn't available.
- [ ] Determine if using kpartx is the way to go.  We want to ensure the
  test suite can run when DISKS refers to a loopback devices or
  physical/virtual disks not just files.  This might allow us to
  simplify/remove the LINUX blocks are be more compatiable (OSX?)
- [ ] Investigate all remaing test failures.  Most failures are expected
  to be due to differences in the environment between illumos and Linux.

Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>

### CODE REVIEW

**Comment by behlendorf** [comment]
@FransUrbo I've taken the __all__ the work you did in https://github.com/zfsonlinux/zfs-test and tried to push it a little father along.  I know the original plan was to keep the ZFS Test Suite separate from the ZoL repository.  But after taking a long hard look at the ZFS Test Suite and the changes you needed to make I'm no longer convinced that's the right approach.

What I've done is take your work and go through the effort of tightly integrating it with the ZoL source tree so it _just works_.  Roughly speaking I made the following changes (and probably a few more).  Normally I would have split this in to multiple patches but the scope of it was a bit overwhelming.

* Replaced all the `Makefile`s with `Makefile.am`s for autoconf.
* Replaced the `zfstest.ksh` with `scripts/zfs-tests.sh` to invoke `test-runner` with the needed environment.
* Renamed `run.py` to `test-runner.py` to avoid confusion.
* Added `test-runner` and all the tests to the existing `zfs-test` package.
* Extended `test-runner.py` with a `-i` option so the runfiles can use relative paths.  This makes it possible to run the ZFS Test Suite in the source tree or when installed from the `zfs-test` package.

This is a huge addition to the ZoL source tree and is still a WIP.  Many tests don't yet pass but it's functional and I'd appreciate your feedback on this in particular because you've been down this path before!  My major remaining concerns are:

* Do we want to keep the LINUX conditional blocks or just update test cases to operate in the correct way for Linux?  What if any other platforms would consider using this (@lundman OSX?)
* We need to be able to set DISKS so it can use virtual/physical/loopback devices.  Using `kpartx` and files while functional for most tests has some drawbacks.
* Resolve or disable the remaining test failures so we can add the ZFS Test Suite to the buildbot.  I'm hopeful we can get some help with this now that the heavy lifting of integrating the framework is done.

**Comment by lundman** [comment]
Yes, we had had quite a lot of tester-conversations since we started working on it about 3 weeks ago. Quite a lot of work needed, a lot of it simple and monotonous. We kept ours separate so far, in between spl and zfs repos.

Some of the minor changes include that many scripts uses shebang to ksh, when ksh sits somewhere else on OSX, so we replaced it with more portable /usr/bin/env ksh. The sort of change that really should be upstream. 

But the biggest issue is perhaps that the test scripts are littered with "dd" commands, to create pools etc. It would be nicer if that was in the "tester utility lib" (create_new_pool(args)). The reason for that is, OSX (HFS+) has no sparse support (!) So running the tests take 4 hours at the moment. We could run the tests on ZFS (like IllumOS does) or use some other clever way, if it was unified in a function.

We've discussed if we should be coordinating with ZOL, or perhaps IllumOS tester project, but there are a lot of changes. Then there is the plan to switch upstream from ZOL to OpenZFS unicorn repo, when it comes live - so if that happens, it is unfair to make ZOL go through a bunch of changes just to abandon it.

For the time being, we have decided to halt tester development (for a few weeks) and let it play out elsewhere(you guys). We have more "fun problems" to fix still :)  So in that sense, you can proceed without worrying how it impacts us. But it is appreciated that you asked.

**Comment by behlendorf** [comment]
@lundman it sounds like your working through many of the same issues I've seen.  The scripts definitely have a large number of dependencies and assumptions about the system baked in to them.  Usually nothing major but the shear volume of them is daunting!

I'm glad we don't have to wrestle with your `dd` issue on Linux.  We have other annoyances like the names of newly created partitions depending on the type of device being partitions (loopback, scsi, etc).  Good times.

I think in an ideal world we'd all be running the same ZFS test suite.  But practically with the effort it would require and the man power available I don't see how that will come to pass.  Which is unfortunate.  I don't think we have to much choice but to proceed with adding it to the ZoL tree.

That said, I think we should keep the other platforms in mind when making changes.  Adding layers of abstraction where appropriate and such.  Perhaps at some point we could converge on a single version!

**Comment by FransUrbo** [comment]
I still think it's better suited as a separate repo. The size is one of the primary ones :). I really really, REALLY don't want "all that crap" in ZoL code…

Besides, the only real reason you've mentioned for having it in the **zfs** repo is so that it would be _easier_ to keep the zfs code and the test suite in sync… That would be nice, but it's really not THAT difficult. Every time you accept a PR that could need a test, just create a new issue in the **zfs-test** repo, referencing the relevant zfs commit… OR, even better, in the PR, before you merge it, mention to the author that "this needs a test written".

That "super integration into the system" is BSD. They ALWAYS do that crap (I've just suppressed that :), and I just can't understand why it's so important to them TO do it… In the beginning [of this project], I was kind'a hopeful or at least "looked forward" to getting ONE **zfs-test** for all of us and getting input on how that could be done, but now…

If you're hellbent on merging it into ZoL code repo, could you at least consider it a git module (like <code>scripts/zfs-images</code>)?

**Comment by behlendorf** [comment]
The only thing I'm hellbent on is getting the ZFS Test Suite integrated in to our development process.  I share your feelings about keeping "all that crap" out of the ZoL repository.  I really hate how the test suite now overwhelms the rest of the code base.  But we need something in place.  Let me try and summarize the goals as I see it.

ZFS Test Suite Goals
* Easy to install and run on a system with ZFS installed.
  * Needed by the buildbot, distribution maintainers, and system integrators.
* Easy to run against binaries in the ZoL source tree.
  * Needed by OpenZFS developers to validate changes before submitting them from review.
* Cross platform support
  * Linux is the initial target platform
  * When making changes for Linux other platforms should be kept in mind.
  * Getting OpenZFSonOSX and ZoL using the same zfs-tests code base would be desirable.
  * Other platforms are welcome to adopt this tree, but they may want to keep their integrated versions.
* The DISKS environment variable may refer to loopback, physical, and virtual devices.
* All tests should be updated so the pass or should be disabled in the appropriate runfile.

I hadn't considered adding the zfs-test repository as a git subpackage but I like the idea a lot.  We should definitely explore that since it should let us address the first two bullets above.  We could graft it in as a top level tests directory and if the OpenZFSonOSX developers were interested they could do the same at some point.  Even just getting two platforms sharing the code would be a huge step.

@FransUrbo let's go ahead and merge the issue-1534 branch in to master for the zfs-test repository.  Then I can open a new pull request against that repository with a patch stack that takes that adds the changes I needed to make, and lays the groundwork for it being usable as a git submodule.  That will probably take me a week or so.

**Comment by FransUrbo** [comment]
> But we need something in place.
> 
Many of the things you changed, we can do in the zfs-test repo. As well as creating rpms and debs in the same way we do it in the zfs repo.

That way it's easy to integrate wherever we need it. Because that's the primary concerns, that it's not very easy to 'install'?
> Easy to install and run on a system with ZFS installed.
> Needed by the buildbot, distribution maintainers, and system integrators.
That would be accomplished if/when we create rpms/debs for the zfs-test suite. It's not really that difficult to make. We have the infrastructure in the zfs repo so it would be easy enough to duplicate that (with modifications) to the zfs-test suite...

But I never bothered to do that, because I figured it was more important to get something that actually worked. I've been waiting for what, a year, a year and a half for more eyes and tests on what need fixing. But since nothing really happened, I kind'a lost interest in it…

Getting it in the zfs repo MIGHT improve this, but I think it's still to early (as in "to dangerous") to give everyone access to it. It needs a lot more tests, open issues and what not that I (or someone else) can go through and fix.

That and that it gives more overhead when implementing/changing things in zfs. But on the other hand, no-one is updating the documentation when they do changes to ZoL anyway (which is more important). So why should "they" keep the test suite updated??

So 'importing' it into the zfs repo is kind'a overkill in my opinion. Having it as a submodule on the other hand, that's a lot more viable. It's still a separate repo, but can be accessed from with ZoL for that think that's needed (which I don't).
> Cross platform support
I've tried my very best. The original idea was for EVERYONE to use this as the source. Although I knew from the start that was going to be next to impossible, that was at least the intention.

But that also need eyes…. From people that actually do development on multiple platforms. Although I can do the work "just fine", I don't have the resources to install *BSD, Illumos, Solaris and what not to actually do the work.

**Comment by FransUrbo** [comment]
> Then I can open a new pull request against that repository with a patch stack that takes that adds the changes I needed to make, and lays the groundwork for it being usable as a git submodule. That will probably take me a week or so.
> 

The [zfs-test] project is in its infancy now, working with pull requests and what not seems to be a little to much overhead at the moment. Once we have something that actually works that we can recommend others [inexperenced] users use, THEN we can start working with pull requests and what not.

But for now, just push directly to the repo. If you're reasonably happy what we have now and want to build from that, that is. And if someone else what to participate in the work, and they have proven to be "trustworthy", just give them push access as well. We don't need to be "protective" about the repo just yet…

**Comment by behlendorf** [comment]
Sounds like a plan.  A standalone repository but one which can also be used as a git submodule.

I've just merged the issue-1523 branch is to master of the zfs-test repository and updated the default branch to be master.  That should make things less confusing to newcomers and get us going.  Feel free to destroy the issue-1523 branch once you no longer need it.

I'll work on rebasing the changes I felt I needed to make on top of zfs-test/master.  I agree that for the moment we don't need/want any significant process getting in the way of us fixing it up.  By all means fix things as you see fit and commit it!  But I do think pull requests can still serve a useful purpose on an adhoc basis when a proposed changes needs to be discussed.  I'll open a pull request for the changes I'm proposing to the repository before merging anything so we can agree on the fundamental approach.

**Comment by behlendorf** [comment]
Closing.  I'll reopen an updated version of this against the zfs-test repository.

**Pull request closed without merging**
