### PR TITLE
Implement --enable-debuginfo to permit us to force building with debuginfo

### PR DESCRIPTION
**Pull request by ryao**
There are two commits here. The second implements --enable-debuginfo for distributions that build modules without debuginfo. The first is a refactor of --enable-debug based on an observation made during the development of the first that --enable-debug=true would paradoxically become --disable-debug. The order is reversed to make cherry picking easier should anyone want to backport only the change to --enable-debug's argument semantics.

### CODE REVIEW

**Comment by behlendorf** [comment]
@ryao is this something which you could still take advantage of?

**Comment by behlendorf** [comment]
Closing as unnecessary until I hear otherwise.

**Comment by ryao** [comment]
@behlendorf I am using this at my new job now. It is definitely something useful.

**Comment by tuxoko** [comment]
@behlendorf 
I think it would be good to have any easy way to force CONFIG_DEBUG_INFO. As I constantly build and test my own ko, I can't rely on the debug package provided by Ubuntu.

**Comment by behlendorf** [comment]
@tuxoko I don't have any objections to adding support for this. Can you confirm that 7098243 works as advertised?  If so let's open a new PR with only that change against master.

I'm not against 57a842a either but we're going to want to preserve the default behavior.

**Comment by tuxoko** [comment]
7098243 works for the ko. The user stuff seems to always have -g in CFLAGS

**Comment by behlendorf** [comment]
Rebased and merged.

**Pull request closed without merging**
