### PR TITLE
Change sharesmb to use REGISTRY shares for better control by user/admin

### PR DESCRIPTION
**Pull request by FransUrbo**
Most notably:
  * Support options to sharesmb
  * SMBFS registry shares instead of user shares.

A registry share is much more configurable than a user share, that basically only accepts path, comment and guest_ok. A registry share supports every option that one would have in smb.conf(5).

The only change, for the user/admin, is that the 'acl' option is no more. Instead there is the 'writeable' boolean.

The commit (162e908) about reopening the sharetab is to fix a problem I've seen quite a lot, but not been able to pinpoint. But it seems like when libzfs opens the sharetab, and libshare replaces it with an updated one, libzfs doesn't see the change/new file. So instead just reopen it before we try to read from it.

### CODE REVIEW

**Comment by behlendorf** [comment]
Bumping to 0.6.5.  @FransUrbo if you could refresh it based on the above comments we can revisit it for the next tag.

**Comment by FransUrbo** [comment]
Na, let's just ignore it. We can wait a year or two for zed to get the functionality instead.

**Comment by jabbas** [comment]
> 

Soo... I've came across that and i see that we are almost in 2023 and we still can't set sharesmb to some options?

**Comment by FransUrbo** [comment]
No :(. @behlendorf couldn't be bothered to give me a decent review for (two?) years and then IMO came up with some BS review just because it wasn't perfect-perfect-perfect.

It's good that PR quality is a priority, but in this case it was at least working perfectly fine in production. Both by me and others. So I simply gave up and left the project. He want to do it perfect, his way? Yeah, we've been waiting for almost ten years for that now and still nothing.. !

I still run my patch(es) in production and every time I upgrade my system I update the patches. However, I haven't had time or interest to do that in a few years - "if it works, don't mess with it" :D.

**Pull request closed without merging**
