### PR TITLE
tiny dracut module cleanup

### PR DESCRIPTION
**Pull request by nmeum**
The code for the dracut module is kind of ugly. This improve some tiny things...

### CODE REVIEW

**Comment by behlendorf** [comment]
@l1k it would be very helpful if you could look over this cleanup.

**Comment by l1k** [comment]
Commit 226a443f641c237ad4c307aa04f1586a25e5bdf5 doesn't work as intended, it will split the input at every occurrence of a backslash or an `n`character. I think the only working alternative to the currently used:
```
local NEWLINE="
"
```
would be:
```
IFS=$'\n'
```
but that's a bashism and should probably be avoided (see below).

As for (reverted) commit e8ec1c96af300fc522580a09b5d9ab704ba28b67, it says in the [Dracut wiki](https://fedoraproject.org/wiki/Dracut) that bashisms SHOULD be avoided in scripts and MUST be avoided in hooks. Harald Hoyer himself has started to selectively use bashisms (associative arrays or the `local` keyword) in scripts. It's probably a good idea to adopt this but not introduce additional bashisms, which is the reason I avoided `IFS=$'\n'`. At a later stage the 90zfs module will probably be submitted for inclusion in Dracut and Harald Hoyer might object against additional bashisms.

As for commit 2a8b3f5991f049004095f1b3459b792ce9d7b534, the [Dracut wiki](https://fedoraproject.org/wiki/Dracut) specifically imposes the rule to "Use one of the inst family of functions to actually install files on to the initrd." So I think this shouldn't be changed.

The other two commits c8500f2962009264c1b33128adf9e4cd447251d0 and 11d04964ed4552e1f1533ae634be7451825f7ae2 are merely syntactic changes and I believe don't alter the semantics, so I'm indifferent on those.

**Comment by nmeum** [comment]
I admit this pull request is a bit messed up 11d04964ed4552e1f1533ae634be7451825f7ae2 and c8500f2962009264c1b33128adf9e4cd447251d0 should be one commit. And the other commits except 2a8b3f5991f049004095f1b3459b792ce9d7b534 were a bad idea in general.

Commit 2a8b3f5991f049004095f1b3459b792ce9d7b534 was actually suggested by Harald Hoyer himself on the `#dracut` irc channel. And if you look at the dracut modules which are shipped with dracut they actually write to `$initdir` directly sometimes as well. Therefore, I believe that it make a lot of sense to do that in this particular case.

**Comment by l1k** [comment]
@nmeum: The `cut` and `printf`commands convert the hostid from hexadecimal numbers to bytes. Maybe you could eliminate obsolete commits (and squash remaining commits as you see fit) with `git rebase --interactive`, then issue a `git push --force` to update the pull request?

**Comment by nmeum** [comment]
I will do that tomorrow, however, should I reinclude 2a8b3f5991f049004095f1b3459b792ce9d7b534 now?

**Comment by l1k** [comment]
@nmeum: That's ultimately for @behlendorf to decide. :)

**Comment by behlendorf** [comment]
@nmeum the only advantage I can see in using a temp file is that it ensures the file is updated atomically.  You'll never see a partial hostid.  However, for the usage here I don't think that's a realistic concern so I'm OK with 2a8b3f5.  This was already addressed over in parse-zfs.sh.

I agree it would be great if you could rebase and force update this branch.

**Comment by nmeum** [comment]
Done.

**Comment by behlendorf** [comment]
Merged

**Comment by l1k** [comment]
Looking at cfbaa3c830e34b1c8920a48fd5e7196287f674eb with a fresh pair of eyeballs, I've noticed the following remaining issue:

The commit removes the double quotes surrounding `${wait_for_zfs}` in [parse-zfs.sh.in](https://github.com/behlendorf/zfs/blob/cfbaa3c830e34b1c8920a48fd5e7196287f674eb/dracut/90zfs/parse-zfs.sh.in#L55). However, that variable is only set to 1 under certain conditions (in the `case` statement above) and undefined otherwise. If it is undefined, the `if` statement will now print an error message like this: `[: -eq: unary operator expected`.

Solution: Either reinstate the double quotes or set `wait_for_zfs=0` at the beginning of `parse-zfs.sh.in`.

That bug is triggered if the 90zfs module was included in the init ramdisk even though the `root=` kernel parameter is set to something else than a ZFS dataset. Not sure under which conditions that happens. (Maybe if dracut is invoked with `--no-hostonly`.)

Apologies for not spotting this earlier.

**Comment by nmeum** [comment]
Yep, indeed. I would prefer adding `wait_for_zfs=0` to the beginning of that file.

**Comment by behlendorf** [comment]
@nmeum @l1k If you could open a pull request with a proposed fix for that case that would be great.

> At a later stage the 90zfs module will probably be submitted for inclusion in Dracut

I'd love to see this happen but I'm personally not that familiar with dracut.  If either of you are pulled in to the dracut community and would like to push ZFS support upstream that would be tremendously helpful.

**Comment by behlendorf** [comment]
Ahh, I see you did in #3093.

**Pull request closed without merging**
