### PR TITLE
mistake in inherited dataset

### PR DESCRIPTION
**Pull request by ikozhukhov**
Signed-off-by: Igor Kozhukhov <igor@dilos.org>

mistake in inherited dataset in test receive-o-x_props_override.ksh

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by loli10K** [comment]
Is this ready for review or still work in progress? I was going to review this change once it's ready but the modified test case is failing consistently on every builder and the pull request template is almost empty, so i'm not sure what kind of issue we are fixing and how.

**Comment by behlendorf** [comment]
@ikozhukhov could you elaborate on the observed issue and the proposed change.  I've updated this to a WIP for now.

**Comment by ikozhukhov** [comment]
we have created datasets by:
`log_must zfs create -p $orig/1/2/3/4`
we have inherited properties on dataset `/4` from parent `/3`
if we have removed dataset `/3`, we have parent `/2` for `/4`
but dataset `/3` is present where we try to check inherited properties and it's me - we have parent `/3` for `/4`
i have added debug prints and checked parent datasets.
probably i missed something and have mistake in test steps?

**Comment by loli10K** [comment]
@ikozhukhov i'm not sure i understand ...

> we have created datasets by:
> log_must zfs create -p $orig/1/2/3/4

Correct

>  we have inherited properties on dataset /4 from parent /3

Not exactly: we inherit from the first parent in the dataset hierarchy with `local` values, which happens to be "2" in our case. Consider the following:

```
root@linux:~# zfs get compression
NAME                      PROPERTY     VALUE     SOURCE
rpool                     compression  lz4       local
rpool/ROOT                compression  lz4       inherited from rpool
rpool/ROOT/debian         compression  lz4       inherited from rpool
rpool/swap                compression  lz4       inherited from rpool
rpool/tmp                 compression  lz4       inherited from rpool
rpool/var                 compression  lz4       inherited from rpool
rpool/var/tmp             compression  lz4       inherited from rpool
```
Every dataset inherit from "rpool", even "rpool/var/tmp" and "rpool/ROOT/debian": they **do not** inherit from their direct parent ("rpool/var" and "rpool/ROOT" respectively). I believe this is the intended behavior, and is the same on illumos:

```
loli@openindiana:~$ uname -a
SunOS openindiana 5.11 master-0-g77ba330702 i86pc i386 i86pc
loli@openindiana:~$ zfs get compression rpool/illumos-dev/code
NAME                    PROPERTY     VALUE     SOURCE
rpool/illumos-dev/code  compression  off       default
loli@openindiana:~$ sudo zfs set compression=gzip rpool
loli@openindiana:~$ zfs get compression rpool/illumos-dev/code
NAME                    PROPERTY     VALUE     SOURCE
rpool/illumos-dev/code  compression  gzip      inherited from rpool
```

>  i have added debug prints and checked parent datasets.

I can't seem to find these prints, did you forget to force-push?

Can we take a step back and try to describe:

1. what is broken, e.g _dataset "rpool/parent/child" is inheriting property X from "rpool" when it should be inheriting from its direct parent instead ("rpool/parent")_
2. how this change is fixing the issue, e.g _zfs get X "rpool/parent/child" now shows the correct inheritance info_

**Comment by ikozhukhov** [comment]
@loli10K you are right, probably my mistake in test steps.
just checked by simple test:
```
root@zfs-test3:/var/tmp/2# zfs create -p t2/1/2/3/4

root@zfs-test3:/var/tmp/2# zfs get compression t2/1/2/3/4
NAME        PROPERTY     VALUE     SOURCE
t2/1/2/3/4  compression  off       default

root@zfs-test3:/var/tmp/2# zfs set compression=on t2/1/2

root@zfs-test3:/var/tmp/2# zfs get compression t2/1/2/3/4
NAME        PROPERTY     VALUE     SOURCE
t2/1/2/3/4  compression  on        inherited from t2/1/2
```
in this case we ca see - changes from parent `/2` available on `/4`
probably i missed some ZoL update on DilOS for correct works of test receive-o-x_props_override.ksh
close this issue

**Pull request closed without merging**
