### PR TITLE
Issue #4243 - Handling negative dentries in a CI file system.

### PR DESCRIPTION
**Pull request by RichardSharpe**
For a Case Insensitive file system we must avoid creating negative
entries in the dentry cache. We must also pass the FIGNORECASE into
zfs_lookup so that special files are handled correctly.

We must also prevent negative dentries from being created when files are
unlinked.

Tested by running fsstress from LTP (10 loops, 10 processes, 10,000 ops.)

Also tested with printks (now removed) to ensure that lookups come to
zpl_lookup when negative should not exist.

Tests:
1.   ls Some-file.txt; touch some-file.txt; ls Some-file.txt
  and ensure no errors.

2.   touch Some-file.txt; rm some-file.txt; ls Some-file.txt
  and ensure that the last ls shows log messages showing the lookup
  went all the way to zpl_lookup.

Thanks to tuxoko for helping me get this correct.

Signed-off-by: Richard Sharpe <realrichardsharpe@gmail.com>

### CODE REVIEW

**Comment by RichardSharpe** [comment]
Made a style mistake.

**Comment by RichardSharpe** [comment]
Trying again.

**Comment by behlendorf** [comment]
@tuxoko it would be great if you could look this over.

@RichardSharpe as a general rule of thumb it's a good idea to always rebase the patches on the latest master code before pushing them.  That helps avoid things like unrelated failures in the kernel.org builders.

**Comment by tuxoko** [comment]
@RichardSharpe 
You also need to add the d_invalidate stuff to zpl_rmdir

**Comment by RichardSharpe** [comment]
@tuxoko. Yes, you are correct. Sigh. If forgot about rmdir.

@behlendorf OK, let me figure out how to rebase it. I think I added an upstream.

**Comment by RichardSharpe** [comment]
OK, I think I have figured out how to merge from upstream ...

**Comment by behlendorf** [comment]
@RichardSharpe you'll want to do something like this to rebase and force update the branch.  The buildbot will notice the updated patch and automatically re-test it.

```
$ git checkout master
$ git pull zfsonlinux master
$ git checkout case-insensitive-changes
$ git rebase master
$ git push --force RichardSharpe case-insensitive-changes
```

**Comment by RichardSharpe** [comment]
@tuxoko 

It turns out that there is an error path in mkdir that also needs to be fixed.

In that path, we have already done a d_instantiate.

The simplest might be to move the d_instantiate to the non-error path after zpl_xattr_security_init and only do it if we are a case sensitive file system.

**Comment by RichardSharpe** [comment]
In fact, isn't it a bug to leave a positive dentry when the directory has been deleted in the error path?

**Comment by RichardSharpe** [comment]
I checked vfs_mkdir. It does not clean up dentries. It assumes that the file system is not not going to add an entry for an object that is not there.

**Comment by tuxoko** [comment]
@RichardSharpe 
The only place a dentry canl be hashed is during lookup. But we don't hash negative dentry during lookup. So whether mkdir success or not. The dentry will be dropped during dput.

**Comment by tuxoko** [comment]
This patch https://github.com/RichardSharpe/zfs/commit/4ebdc0547014c05a1307658a1e35ade4fab4d847 looks good to me.

**Comment by RichardSharpe** [comment]
@tuxoko 

Yes, but isn't an already hashed negative entry passed to mkdir, which we then instantiate (add a real inode to) before we handle the error path?

Then in the error path we actually delete the dirent and, presumably, the inode, leaving a hashed entry in the dcache pointing to a now deleted inode.

**Comment by tuxoko** [comment]
@RichardSharpe 
The dentry passed into mkdir, which is negative, must come from lookup path, but we don't hash negative dentry during lookup, so the dentry cannot be hashed.
d_instantiate makes it positive, but doesn't hash it. So whether mkdir success or not, the dentry remains unhashed.

**Comment by behlendorf** [comment]
This LGTM as well.  Are there any remaining concerns which need to be addressed?

**Comment by tuxoko** [comment]
@behlendorf 
Not that I'm aware of.

**Comment by RichardSharpe** [comment]
Hi, is this likely to get in soon?

**Comment by behlendorf** [comment]
Yes,  I plan to merge it today.   Thanks for your work on this.

**Comment by behlendorf** [comment]
Merged as:

9d36cdb Handling negative dentries in a CI file system.

**Pull request closed without merging**
