### PR TITLE
SUSE kernel module package -kmp convention

### PR DESCRIPTION
**Pull request by stancheff**
### Motivation and Context

SUSE packaging style is to include kernel modules in a package
named PACKAGE-kmp where the Fedora convention is kmod-PACKAGE
and PACKAGE-kmod.

Update the kmodtool to generate packages named using the SUSE
convention style when the host machine is SUSE based.

### Description

Based on PR: https://src.fedoraproject.org/rpms/kmodtool/pull-request/5
 - Rebase to upstream kmodtool.
 - Apply PR to upstream kmodtool
 - Add --devel support to kmodtool
 - Integrate SUSE kmp changes to ZFS.

### How Has This Been Tested?

Build tested on SUSE 15 SP1 and CentOS 7

Existing SUSE builds with 'kmod' naming wiil change to 'kmp' naming and could
break existing scripts or workflows for SUSE users of ZFS.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [X ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [X ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@stancheff I've reviewed and provided some feedback on [the Fedora PR](https://src.fedoraproject.org/rpms/kmodtool/pull-request/5).

**Comment by behlendorf** [comment]
@stancheff can we close out this PR in favor of the upstream changes?

**Comment by Ornias1993** [comment]
@behlendorf 
@stancheff seems to have been off github for some time now and the upstream repo isn't going anywhere either. I think closing because necro + prefered upstream seems fitting.

**Comment by behlendorf** [comment]
@stancheff I'm going to close this out in favor of the proposed kmodtool upstream work.  We can always revisit this based on the final resolution there.  But thank you for the proposed packaging fix.

**Pull request closed without merging**
