### PR TITLE
Open the scripts in zfs_create

### PR DESCRIPTION
**Pull request by ChaoyuZhang**
As the scripts (zfs_create_003_pos.ksh,zfs_create_006_pos.ksh) can run successfully in the linux,
add them to the `linux.run` file to increase test scene.

### CODE REVIEW

**Comment by ChaoyuZhang** [comment]
I have seen the test results, these two scripts failed in  `Amazon 2015.09 x86_64` , the results show as below :
```
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_003_pos (run as root) [00:00] [FAIL]
03:26:46.10 ASSERTION: Verify creating volume with specified blocksize works.
03:26:46.12 SUCCESS: /sbin/zfs create -V 150m testpool.20043/testvol20043
03:26:46.14 SUCCESS: /sbin/zfs destroy -f testpool.20043/testvol20043
03:26:46.16 SUCCESS: /sbin/zfs create -b 1k -V 150m testpool.20043/testvol20043
03:26:46.18 SUCCESS: /sbin/zfs destroy -f testpool.20043/testvol20043
03:26:46.21 SUCCESS: /sbin/zfs create -b 1K -V 150m testpool.20043/testvol20043
03:26:46.23 SUCCESS: /sbin/zfs destroy -f testpool.20043/testvol20043
03:26:46.25 SUCCESS: /sbin/zfs create -b 1024 -V 150m testpool.20043/testvol20043
03:26:46.27 SUCCESS: /sbin/zfs destroy -f testpool.20043/testvol20043
03:26:46.30 SUCCESS: /sbin/zfs create -b 1024b -V 150m testpool.20043/testvol20043
03:26:46.31 ERROR: /sbin/zfs destroy -f testpool.20043/testvol20043 exited 1
03:26:46.31 cannot destroy 'testpool.20043/testvol20043': dataset is busy
03:26:46.31 NOTE: Performing local cleanup via log_onexit (cleanup)
03:26:46.33 SUCCESS: /sbin/zfs destroy -f testpool.20043/testvol20043
```

```
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_006_pos (run as root) [00:00] [FAIL]
03:26:47.43 ASSERTION: 'zfs create -o property=value -V size volume' can successfully 	   create a ZFS volume with correct property set.
03:26:47.45 SUCCESS: /sbin/zfs create -o volblocksize=16K -V 150m testpool.20043/testvol120043
03:26:47.48 SUCCESS: /sbin/zfs destroy -f testpool.20043/testvol120043
03:26:47.50 SUCCESS: /sbin/zfs create -s -o volblocksize=16K -V 150m testpool.20043/testvol120043
03:26:47.51 ERROR: /sbin/zfs destroy -f testpool.20043/testvol120043 exited 1
03:26:47.51 cannot destroy 'testpool.20043/testvol120043': dataset is busy
03:26:47.51 NOTE: Performing local cleanup via log_onexit (cleanup)
03:26:47.54 SUCCESS: /sbin/zfs destroy -f testpool.20043/testvol120043
```

There is onething I can not understand, why the first destroy is failed but the second one is successful with the same command in these two test casese? or it just happened accidentally?

**Comment by behlendorf** [comment]
@ChaoyuZhang since both tests failed while destroying a zvol with EBUSY some process must have the block device open.  The most likely candidate for this is blkid which will be run by udev when a new block device is added to the system.

So this is likely just racy and the test case needs to be updated to wait for blkid to finish running before destroying the volume.  Alternately, you could cherry-pick behlendorf/zfs@f4aa424c5cc64036874316c9ece9b0eb6d6c101f from my repo which adds a new `log_must_busy` function which is useful for handling this exact case which is expected to be transient.

This is almost certainly why these tests where originally disabled.

**Comment by ChaoyuZhang** [comment]
@behlendorf Thanks for your detailed answer, I did not take the udev into consideration before. 
I will cherry-pick `behlendorf/zfs@ f4aa424` from your repo and amend those two scripts.

**Comment by ChaoyuZhang** [comment]
@behlendorf  Those two scripts ran successfully by adding `log_must_busy`. So we can make sure that the reason you said above is verified.

**Pull request closed without merging**
