### PR TITLE
KMC_KVMEM disrupts kv_alloc() memory alignment expectations

### PR DESCRIPTION
**Pull request by loli10K**
### Motivation and Context

I was trying  to test zstd code on a KASAN builder, hit following failure:

```
  VERIFY(IS_P2ALIGNED(ptr, PAGE_SIZE)) failed
  PANIC at spl-kmem-cache.c:228:kv_alloc()
  Showing stack for process 15417
  CPU: 7 PID: 15417 Comm: spl_kmem_cache Tainted: P    B   W  OE     4.19.93
  Hardware name: Bochs Bochs, BIOS Bochs 01/01/2011
  Call Trace:
   dump_stack+0x8b/0xbb
   spl_panic+0x142/0x190 [spl]
   ? spl_dumpstack+0x40/0x40 [spl]
   ? is_module_text_address+0xa/0x20
   ? kernel_text_address+0xd9/0xf0
   ? __list_add_valid+0x77/0xa0
   ? create_object+0x458/0x4a0
   ? kasan_unpoison_shadow+0x30/0x40
   ? kasan_kmalloc+0xa9/0xc0
   ? kasan_unpoison_shadow+0x30/0x40
   ? kasan_kmalloc+0xa9/0xc0
   kv_alloc+0x181/0x190 [spl]
   ? __spl_cache_grow+0x620/0x620 [spl]
   __spl_cache_grow+0x78/0x620 [spl]
   ? firmware_map_remove+0xea/0xea
   ? __spl_cache_grow+0x620/0x620 [spl]
   spl_cache_grow_work+0x27/0x50 [spl]
   taskq_thread+0x741/0xab0 [spl]
   ? taskq_thread_spawn+0xc0/0xc0 [spl]
   ? __switch_to_asm+0x35/0x70
   ...
```

### Description

AFAIK `kmalloc()` has never guaranteed aligned allocations; for this exact reason zfsonlinux/spl@8b45dda removed `kmem_alloc()` calls in `kv_alloc()`.

Until a GFP_ALIGNED flag (or equivalent functionality) is provided by the kernel this commit partially reverts 66955885 and 6d948c35 to prevent `k(v)malloc()` allocations in `kv_alloc()`.

### How Has This Been Tested?

Tested on said KASAN builder loading kernel modules. Kmemleak is reporting some leaks on said builder, pushing as draft for the time being:

```
kmemleak: Found object by alias at 0xffffc900008f2000
CPU: 0 PID: 119 Comm: kmemleak Tainted: P           OE     4.19.93 #1
Hardware name: Bochs Bochs, BIOS Bochs 01/01/2011
Call Trace:
 dump_stack+0x8b/0xbb
 lookup_object+0x86/0xc0
 scan_block+0xcf/0x130
 scan_gray_list+0xd8/0x230
 kmemleak_scan+0x580/0x8e0
 ? scan_gray_list+0x230/0x230
 ? __mutex_lock_slowpath+0x10/0x10
 kmemleak_scan_thread+0x79/0xc0
 kthread+0x1b2/0x1d0
 ? kmemleak_scan+0x8e0/0x8e0
 ? kthread_create_worker_on_cpu+0xc0/0xc0
 ret_from_fork+0x35/0x40
kmemleak: Object 0xffffc90000874000 (size 4194304):
kmemleak:   comm "modprobe", pid 523, jiffies 4294902708
kmemleak:   min_count = 2
kmemleak:   count = 1
kmemleak:   flags = 0x1
kmemleak:   checksum = 0
kmemleak:   backtrace:
     __vmalloc+0x51/0x60
     spl_kmem_alloc_impl+0xea/0x150 [spl]
     arc_init+0x668/0xbd0 [zfs]
     dmu_init+0x8c/0xa0 [zfs]
     spa_init+0x12d/0x1e0 [zfs]
     zfs_kmod_init+0x21/0xf0 [zfs]
     0xffffffffc118000b
     do_one_initcall+0xdd/0x24f
     do_init_module+0xec/0x341
     load_module+0x3d01/0x49e0
     __do_sys_finit_module+0x11e/0x1a0
     do_syscall_64+0x7a/0x160
     entry_SYSCALL_64_after_hwframe+0x44/0xa9
     0xffffffffffffffff
kmemleak: Found object by alias at 0xffffc900008f2000
CPU: 0 PID: 119 Comm: kmemleak Tainted: P           OE     4.19.93 #1
Hardware name: Bochs Bochs, BIOS Bochs 01/01/2011
Call Trace:
 dump_stack+0x8b/0xbb
 lookup_object+0x86/0xc0
 scan_block+0xcf/0x130
 scan_gray_list+0xd8/0x230
 kmemleak_scan+0x580/0x8e0
 ? scan_gray_list+0x230/0x230
 ? __mutex_lock_slowpath+0x10/0x10
 kmemleak_scan_thread+0x79/0xc0
 kthread+0x1b2/0x1d0
 ? kmemleak_scan+0x8e0/0x8e0
 ? kthread_create_worker_on_cpu+0xc0/0xc0
 ret_from_fork+0x35/0x40
kmemleak: Object 0xffffc90000874000 (size 4194304):
kmemleak:   comm "modprobe", pid 523, jiffies 4294902708
kmemleak:   min_count = 2
kmemleak:   count = 2
kmemleak:   flags = 0x1
kmemleak:   checksum = 0
kmemleak:   backtrace:
     __vmalloc+0x51/0x60
     spl_kmem_alloc_impl+0xea/0x150 [spl]
     arc_init+0x668/0xbd0 [zfs]
     dmu_init+0x8c/0xa0 [zfs]
     spa_init+0x12d/0x1e0 [zfs]
     zfs_kmod_init+0x21/0xf0 [zfs]
     0xffffffffc118000b
     do_one_initcall+0xdd/0x24f
     do_init_module+0xec/0x341
     load_module+0x3d01/0x49e0
     __do_sys_finit_module+0x11e/0x1a0
     do_syscall_64+0x7a/0x160
     entry_SYSCALL_64_after_hwframe+0x44/0xa9
     0xffffffffffffffff
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by c0d3z3r0** [comment]
ouch. will have a look at this in the next days.

@BrainSlayer @Ornias1993 check this, too, please

**Comment by Ornias1993** [comment]
@c0d3z3r0 I'm not that great in memory allocation code tbh... But my cents:

@loli10K You state:

> partially reverts 6695588 and 6d948c3 

Yet I see it only reverting parts of https://github.com/zfsonlinux/zfs/commit/66955885e24427a94e938c013da214bd5c0177d4

That being said, the issue you found is an actual issue. 

However, due to changes in ZSTD, it shouldn't be a problem anymore. Afaik kvmalloc is not needed anymore for zstd, right @brainslayer?

**Comment by loli10K** [comment]
> Yet I see it only reverting parts of 6695588

https://github.com/zfsonlinux/zfs/commit/6d948c3519ab7a52c06f68927737a3199ba13f81#diff-0d3aa25717e9c2e44de002ebe3ba096eR205-R206 gets reverted too.

**Comment by Ornias1993** [comment]
@loli10K Shoot, looked over it due to code collapse in github.

I don't think this revert should cause any serieus issues, it would have caused trouble with the previous implementation of zstd, but with the new pooling it should be fine.

Considering @allanjude and @brainslayer have had some brainstorming about general memory allocation refactors after zstd is done, I think it's safe to revert these changes for the time being.

**Comment by BrainSlayer** [comment]
@c0d3z3r0 the assertion is wrong from my point of view. it should only belong to KMEM allocations and its questionably why such a assertion has been added. there is no strict requirement that kv_alloc needs to return a page aligned memory block for all types of allocation flags. so its a sledgehammer code line which was accidently designed to be failed. fix is simple. remove the assert or move it to the KMC_KMEM allocation only

**Comment by BrainSlayer** [comment]
@Ornias1993 correct. right now its no requirement, but its still usefull and since i already mentioned that the error correction is simple. its maybe just more simple to create a PR with a fix. its a one liner

**Comment by behlendorf** [comment]
> there is no strict requirement that kv_alloc needs to return a page aligned memory block for all types of allocation flags.

Arguably this restriction should have been more clearly documented beyond the `ASSERT()` which was added for this purpose.  `kv _alloc()` was always intended to be solely used by the slab implementation which expected page aligned allocations.  That said, page-alignment is really only strictly beneficial for space efficiency reasons when a significant alignment restriction is provided to `spl_kmem_cache_create()`.

Alternately, since `kv_alloc()` is aware of the required alignment via `skc->skc_obj_align` we could update this logic to only force page alignment when `skc->skc_obj_align` is greater than the default `SPL_KMEM_CACHE_ALIGN`.  The matching logic in `kv_free()` would need to be updated accordingly.

**Comment by Ornias1993** [comment]
@BrainSlayer you are talking about the zstd assertion on the wrong github PR.

**Comment by c0d3z3r0** [comment]
@loli10K can you run a test with this, please? https://github.com/zfsonlinux/zfs/pull/9817

**Comment by Ornias1993** [comment]
@c0d3z3r0 You might want throw in a review (as one of the original authors of this code) so w can LGTM.

**Comment by c0d3z3r0** [comment]
> so we can LGTM

[ ] you know what LGTM means :P

**Comment by Ornias1993** [comment]
@c0d3z3r0 Yes i do know that "we can lets get this merged" won't be a good english scentence.
But I think non one but you would've understoot:
" You might want throw in a review (as one of the original authors of this code) so we can GTM. "

**Comment by c0d3z3r0** [comment]
> @c0d3z3r0 Yes i do know that "we can lets get this merged" won't be a good english scentence.
> But I think non one but you would've understoot:
> " You might want throw in a review (as one of the original authors of this code) so we can GTM. "

nope, LGTM means "Looks good to me" ;-)

**Comment by Ornias1993** [comment]
@c0d3z3r0 There are multiple meanings of LGTM ;)

**Comment by c0d3z3r0** [comment]
> @c0d3z3r0 There are multiple meanings of LGTM ;)

"Literally Garbage To Me"? :P :P

Ok, ok.. wasn't aware that LGTM is actually used as "let's get this merged"

**Comment by BrainSlayer** [comment]
urban dictionary says: Looks Good To Me

**Comment by BrainSlayer** [comment]
okay found Lets get this merged and Let's Get This Money too and Literally Garbage To Me and of course Let's Go Team Mish

**Comment by Ornias1993** [comment]
WTF is Team Mish?

**Pull request merged**
