### PR TITLE
compat: Gentoo hardened kernel

### PR DESCRIPTION
**Pull request by ironMann**
API Change: Module parameter set/get methods take const parameter in
Gentoo hardened kernel v4.7.1

Issue #4997

### CODE REVIEW

**Comment by perfinion** [comment]
Why do a check in ./configure? If the parameter can be const isnt it better to always be const even on non-hardened kernels?

**Comment by ironMann** [comment]
@perfinion that triggers the same (reverse) error:

`include/linux/moduleparam.h:237:1: note: expected ‘int (*)(const char *, struct kernel_param *)’ but argument is of type ‘int (*)(const char *, const struct kernel_param *)’`

**Comment by perfinion** [comment]
@ironMann :( oh well, it would have been nice to have everywhere. The same thing happened for the constify fixes I submitted for ICP the other day.  Also technically speaking it is the Grsecurity kernel not gentoo only. Arch has it packaged and several others but thats really a nit picky issue.

@behlendorf The other day in the ICP fix I added the #define directly in that header file. Should we instead aggregate all these hardening fixes in one central header file or just leave it for now?

**Comment by behlendorf** [comment]
LGTM.  @perfinion can I add your signed-off-by?  I'm happy to change the Gentoo reference to Grsecurity kernel in the patch when it's merged.

> Should we instead aggregate all these hardening fixes in one central header file or just leave it for now?

The thought occurred to me when reviewing that patch but for the moment I don't think it's necessary.  So far we only have a few of these sprinkled throughout the code.  But if that changes I think it would be worth revisiting all the changes we'd made for hardened kernels to see if they could refactored in a way which makes sense.

**Pull request closed without merging**
