### PR TITLE
Skip sublist lock for already dirty dnodes

### PR DESCRIPTION
**Pull request by behlendorf**
The dnode_setdirty() function can skip taking the multilist
sublist lock if the dnode is already on the dirty list.  This
optimization can improve the sustained create rate when there
are multiple threads creating objects.

Creation rate:

threads | before  | after
------- | ------- | ------
1       | 28689   | 28678
2       | 54201   | 54282
4       | 105939  | 107627
8       | 184067  | 189421
16      | 210283  | 249655
32      | 197999  | 238819
64      | 203185  | 244112
128     | 204942  | 249444

Refreshed version of #5747.

### CODE REVIEW

**Comment by bzzz77** [comment]
thanks Brian. I'll rebenchmark ASAP.

**Comment by tuxoko** [comment]
@behlendorf 
I'm curious about the correctness of this check. Because `dn_dirty_link` is also used for `os_synced_dnodes` when userquota is on. Should we really skip if the dnode is not on `os_dirty_dnodes` but on `os_synced_dnodes`?

**Comment by ryao** [comment]
@tuxoko Your question is one of whether the code should be doing this in the first place rather than whether this change introduces a regression. That is a very good question that requires some thought. I suggest filing a separate issue for discussion.

**Comment by tonyhutter** [comment]
I benchmarked this using the following script on a 16-core Xeon.  The test pool was a single 10GB backing tmpfile as the vdev:

```
#!/bin/bash

totfiles=$1

if [ "$totfiles" == "" ] ; then
        totfiles=100000
fi

echo "Create $totfiles files"

MKFILES=/tmp/dnode-setdirty/tests/zfs-tests/cmd/mkfiles/mkfiles
for i in 1 2 4 8 16 32 64 128 256 ; do
        echo -n "threads: $i "
        # Milliseconds start
        mstart=$(($(date +%s%N)/1000000))
        for j in $(seq $i) ; do
                # Create $threads number of directories and create
                # $totfiles/$threads number of files in each of those dirs
                let "threadfiles=$totfiles/$i"
                mkdir -p tmpdir$j
                # Spawn off file creation in its own thread
                (cd tmpdir$j && $MKFILES tmpfile $threadfiles && cd ..) &
        done
        # Wait for all threads to complete
        wait
        mend=$(($(date +%s%N)/1000000))
        rate=$(bc -l <<< "scale=2; ($totfiles*1000)/($mend-$mstart)")
        echo "$rate files/sec"
        for j in $(seq $i) ; do
                (rm -fr tmpdir$j) &
        done
        wait
done
```
The script was run from inside the pool mount.  I ran the script three times both with/without the patch and averaged the results.  


| Threads | Before | After | Gain |
| --- | --- | --- | --- |
| 1 | 18172.3 | 18543.2 | 2.04% |
| 2 | 30132.9 | 30126.0  | -0.02% |
| 4 | 54980.3 | 54154.4  | -1.50% |
| 8 | 87853.1 |  90933.3 | 3.51% | 
| 16 | 109375.6 |  110623.8 | 1.14% |
| 32 | 113382.5 |  113422.5 | 0.04% |
| 64 | 113555.9 |  114772.7 | 1.07% |
| 128 | 114294.7 | 115880.8 | 1.39% |
| 256 | 113852.5 | 116015.9 | 1.90% |

I then did the whole thing again and got:

| Threads | Before | After | Gain |
| --- | --- | --- | --- |
| 1 | 18786.9 | 18448.9 | -1.80% |
| 2 | 29403.6 | 30330.1 | 3.15% |
| 4 | 53334.4 | 52770.4 | -1.06% |
| 8 | 91115.3 | 88209.6 | -3.19% |
| 16 | 111317.7 | 111236.6 | -0.07% |
| 32 | 113813.2 | 113551.9 | -0.23% |
| 64 | 115165.4 | 115430.7 | 0.23% |
| 128 | 115084.0 | 115168.3 | 0.07% |
| 256 | 115340.6 | 116328.6 | 0.86% |

@bzzz77 can you describe your test setup for the numbers you posted in https://github.com/zfsonlinux/zfs/pull/5747#issue-205607196?

**Comment by bzzz77** [comment]
@tonyhutter that data aren't actual since 64fc77620 landing. I think the ticket can be closed.

**Comment by behlendorf** [comment]
@tonyhutter @bzzz77 thanks guys.  I'll close this out.

**Pull request closed without merging**
