### PR TITLE
[test] Compile test for vectorized fletcher with #4381

### PR DESCRIPTION
**Pull request by ironMann**
Adaptation of @jxiong's : vectorized_fletcher branch to #4381

### CODE REVIEW

**Comment by behlendorf** [comment]
@ironMann thanks.  It looks like it was fairly straight forward to update.  We'll want to iterate with @jxiong on the fletcher patch itself to enhance it some.  For example integrate it with ztest, probably put the benchmark results in a kstat rather than the console, and put the unit test somewhere it gets regularly run.  But it looks like it integrated nicely with your vectorized algorithms patch.

That said I think we do have a problem with it because when running in the ec2 test instance the `zfs_avx_available()` [check failed](http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20%28TEST%29/builds/871/steps/shell_11/logs/console).  Notice there are only __generic__ results in the console output.

Based on the aws documentation we should have been running on an Intel Xeon E5-2670 v2* which according to the Intel documentation supports avx.  Logging in the instance appears to confirm that yet we didn't enable axv support.

Anybody know why this might be the case?  @ironMann presumably it works as expected on your test system?

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2500.060
cache size	: 25600 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase smep erms xsaveopt
bugs		:
bogomips	: 5000.12
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by behlendorf** [comment]
Whoops.  Sorry about closing that, I mis-clicked.  Reopened.  It  looks like I posted a little too quickly, it looks like `zfs_avx2_available()` failed which makes sense since it _isn't_ supported.  So it did work properly.  Although it's a bit unfortunate the test coverage therefore doesn't cover this.

**Comment by ironMann** [comment]
@behlendorf Exactly, generally when testing for AVX2 it's recommended to also check for AVX since they introduced the wider `ymm` register set. AVX2 is only available since Xeons E5 v3 (Haswell). AFAIK, aws offers them in some instances but I have not seen a buildbot deployed on such machine.

**Comment by ironMann** [comment]
Here are benchmark result from my system `Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz`:
```
[  330.268017] NOTICE: fletcher-4: generic  33542 MB/s
[  330.285012] NOTICE: fletcher-4: avx2     102855 MB/s
[  330.361481] ZFS: Loaded module v0.6.5-1 (DEBUG mode), ZFS pool version 5000, ZFS filesystem version 5
```

**Comment by behlendorf** [comment]
It appears the ec2 d2 instance types support both avx2 and instance storage (which we use).  I'll see about adding one to the automated testing mix.  If we're going to be adding these kind of optimizations it's going to need to be covered by the automated testing.

**Comment by ironMann** [comment]
Closing since #4330 was updated to use #4381

**Pull request closed without merging**
