### PR TITLE
Performance tests, some variables missing PERF_ prefix

### PR DESCRIPTION
**Pull request by tonynguien**
### Motivation and Context

Performance test broken due to a minor bug

### Description

Adding the expected `PERF_` prefix to RANDSEED, COMPPERCENT, and COMPCHUNK 

### How Has This Been Tested?

Performance tests run successfully.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by tonynguien** [comment]
Please hold the merge. My latest run is hitting some failures.

**Comment by behlendorf** [comment]
@tonynguien will do.

**Comment by tonynguien** [comment]
> @tonynguien will do.

Thanks @behlendorf. I missed the changes to `mkfiles.fio`. I've updated the PR and kicked off another performance run.

Will send another update once those tests complete.

**Comment by tonynguien** [comment]
Performance tests completed successfully.

--- Configuration ---
Runfiles:        runfiles/perf-regression.run
STF_TOOLS:       /usr/share/zfs/test-runner
STF_SUITE:       /usr/share/zfs/zfs-tests
STF_PATH:        /var/tmp/constrained_path.Ssve
FILEDIR:         /var/tmp
FILES:           /var/tmp/file-vdev0 /var/tmp/file-vdev1 /var/tmp/file-vdev2
LOOPBACKS:
DISKS:           sdb sdc sdd sde
NUM_DISKS:       4
FILESIZE:        4G
ITERATIONS:      1
TAGS:            perf
STACK_TRACER:    no
Keep pool(s):    rpool
Missing util(s): arc_summary3 mmap_libaio pax quotaon umask uuidgen wait setenforce

/usr/share/zfs/test-runner/bin/test-runner.py  -c "runfiles/perf-regression.run" -T "perf" -i "/usr/share/zfs/zfs-tests" -I "1"
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/setup (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/sequential_writes (run as root) [03:55] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/sequential_reads (run as root) [10:29] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/sequential_reads_arc_cached (run as root) [03:03] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/sequential_reads_arc_cached_clone (run as root) [02:59] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/sequential_reads_dbuf_cached (run as root) [00:37] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/random_reads (run as root) [09:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/random_writes (run as root) [01:14] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/random_readwrite (run as root) [07:50] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/random_writes_zil (run as root) [04:52] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/perf/regression/random_readwrite_fixed (run as root) [09:11] [PASS]

Results Summary
PASS	  11

Running Time:	00:53:16
Percent passed:	100.0%
Log directory:	/var/tmp/test_results/20200123T234028


No test results were found.
Log directory:  /var/tmp/test_results/20200123T234028

**Comment by behlendorf** [comment]
Great.  Then I'll go ahead and merge this once the CI is done with it.

**Comment by tonynguien** [comment]
> Great. Then I'll go ahead and merge this once the CI is done with it.

Thanks @behlendorf!

**Pull request merged**
