### PR TITLE
Make slog test setup more robust

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

The slog tests fail when attempting to create pools using file vdevs that already exist from previous test runs.

### Description

Remove existing vdev files from previous runs in the setup for the slog tests.

### How Has This Been Tested?

Run the slog tests, abort in the middle of the run, run again.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
Actually, I think the preceding lines are where the problem was. It doesn't make sense to check if the devs are dirs. We can just remove them unconditionally.

**Comment by freqlabs** [comment]
@behlendorf Good idea, I can add that to the shared cleanup function as well and test it.

**Comment by freqlabs** [comment]
I've made each slog test responsible for its own setup and ensured they clean up after themselves better.

**Comment by freqlabs** [comment]
And to explain the motivation a little better, the cleanup wasn't running for us because something would deadlock and we'd have to reboot or reset the system. The next test run would then fail because of the files left by the interrupted run.

**Comment by behlendorf** [comment]
@freqlabs looks good, whenever you're ready can you drop the `Requires-builders: style` from the commit so we can get a full test run.

**Pull request merged**
