### PR TITLE
Man pages: zpool/zfs get parameters are optional

### PR DESCRIPTION
**Pull request by GregorKopka**
### Motivation and Context
The 'pool' parameter for `zpool get` and the 'dataset' parameter for
`zfs get` are optional, but the man pages listed them as mandatory.

### Description
Marked the parameters in the respective man pages as optional to make
them reflect the actual behaviour.

Signed-off-by: Gregor Kopka <gregor@kopka.net>

### CODE REVIEW

**Comment by GregorKopka** [comment]
Cut down the title and the description.

I find it a bit silly that the template for pull requests dosn't seem to be compatible with the buildbot STYLE check (lines to long).

Please restart the style check, it should pass now.

**Comment by rincebrain** [comment]
> I find it a bit silly that the template for the pull request description dosn't seem to be compatible with the buildbot STYLE check (lines to long).

The template is for the pull request itself, not for the commit(s).

**Comment by GregorKopka** [comment]
Well then... time for me to start from scratch, isn't it?

**Comment by GregorKopka** [comment]
@behlendorf could the linking from #7912 to here be a typo?

**Comment by behlendorf** [comment]
@GregorKopka yes, sorry about that I made a typo which accidentally linked it.

**Pull request closed without merging**
