### PR TITLE
Remove zfs_vdev_elevator module option

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Issue #8664, #9417.  Due to issue #9417 we should strongly
consider retiring this feature in the 0.8.x series ahead of schedule.
This change has been planned for master, merging it now allows
us to easily backport it if we decide to do so.

### Description

As described in commit f81d5ef6 the zfs_vdev_elevator module
option is being removed.  Users who require this functionality
should update their systems to set the disk scheduler using a
udev rule.

### How Has This Been Tested?

```sh
# echo "foo" >/sys/module/zfs/parameters/zfs_vdev_scheduler
# dmesg | tail -1
[87364.594793] The 'zfs_vdev_scheduler' module option is not supported.
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Historically using the kernel's `cfq` scheduler and ZFS's internal scheduler didn't result in optimal performance.  It was at this time that this option was implemented and the `cfq` scheduler was the default.  However, that was a long time ago and these days the default scheduler is `deadline` or `mq-deadline` (In fact, as of the 5.3 kernel all non-multiqueue schedulers have been retired).

These days `deadline`, `mq-deadline`, `noop`, and `none` all perform well with ZFS, and users should not need to change the scheduler.

Regardless, I did look in to adding a udev rule we could ship.  Doing so it a bit more complicated than you'd expect since there is no one right answer for what it should be set to.  For example, on a CentOS 7 system running a 3.10 kernel with traditional HDDs the available options are:

```
$ cat /sys/block/sda/queue/scheduler 
noop [deadline] cfq 
```

While when running a 5.3 and using virtual vd device the options are entirely different.

```
$ cat /sys/block/vda/queue/scheduler 
[mq-deadline] kyber bfq none
```

I'm sure we could handle this, but given that the defaults are expected to work well I don't think this is something we want to take on any longer.

**Comment by kpande** [comment]
when using anything other than noop or none for my systems, iscsi targets will timeout. it's not really a performance thing, but a usability thing.

**Comment by behlendorf** [comment]
@kpande what mechanism do you use to configure the disk scheduler today to avoid this?

**Comment by kpande** [comment]
well the upstream kernel.org developers essentially force me to compile a kernel with all schedulers disabled since `elevator=noop` does nothing.

**Comment by behlendorf** [comment]
It sounds like even if we shipped a udev rule for this it wouldn't be of any use.

**Comment by Ornias1993** [comment]
@kpande It might be awesome if you could make it an actually full blown bug report. Because that iscsi target timeout doesn't sound like it's expected/wanted behavior...

**Pull request merged**
