### PR TITLE
OpenZFS 7638 - Refactor spa_load_impl into several functions

### PR DESCRIPTION
**Pull request by dinatale2**
Authored by: Pavel Zakharov <pavel.zakharov@delphix.com>
Reviewed by: Paul Dagnelie <pcd@delphix.com>
Reviewed by: George Wilson <george.wilson@delphix.com>
Reviewed by: Matthew Ahrens <mahrens@delphix.com>
Reviewed by: Andrew Stormont <andyjstormont@gmail.com>
Approved by: Dan McDonald <danmcd@joyent.com>
Ported-by: Giuseppe Di Natale <dinatale2@llnl.gov>

OpenZFS-issue: https://www.illumos.org/issues/7638
OpenZFS-commit: https://github.com/openzfs/openzfs/commit/1fd3785ff6

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by dweeezil** [comment]
@dinatale2 FYI, I already have got that one ported, as well as most of the other related Spa load related patches, and have kind of been working on them along with the device evacuation stuff.

**Comment by dweeezil** [comment]
@dinatale2 Also, FYI, my patch stack with this one is at https://github.com/dweeezil/zfs/tree/illumos-7638-and-other-spa-load-related.  I'm still working a https://www.illumos.org/issues/9075.  I'm hoping that these will allow to enable some of the concurrent zdb tests in the ZTS which have been disabled.

**Comment by dinatale2** [comment]
@dweeezil Do you mind opening a PR with the ports that are currently finished? Those may make it easier to port other patches.

**Comment by dweeezil** [comment]
@dinatale2 Yes, that't what I was planning on doing.  I have 8961 and 8962 merged and they seem to work properly.  The big one is 9075.  Among other things, it interferes with MMP because it's the patch that really seriously restructures things.

**Pull request closed without merging**
