### PR TITLE
dnode_setdirty() can skip os_lock if the dnode is on the list already

### PR DESCRIPTION
**Pull request by bzzz77**
creation rate:
threads		before	after
1		28689	28678
2		54201   54282
4		105939  107627
8		184067  189421
16		210283  249655
32		197999  238819
64		203185  244112
128		204942  249444

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by ahrens** [comment]
@behlendorf Are you saying that `list_link_active()` doesn't work on ZoL?  Looking at the code in `lib/libspl/list.c`, it appears to work correctly (`list_remove_node()` zeros out `list_next`).  I don't see whre it's using `list_del()`.

**Comment by behlendorf** [comment]
@ahrens that depends on the expected behavior of `list_remove()` under Illumos.  Is the expectation that after a `list_remove()` that `list_link_active()` on that `list_node_t` will fail?  If so, then that's slightly different behavior then the Linux kernel's list implementation which [we're layered on](https://github.com/zfsonlinux/spl/blob/master/include/sys/list.h#L123) and we should fix this.

The Linux kernel provides two functions for this.  `list_del()` which does not clear the list elements  prev/next pointers and `list_del_init()` which does.  Since one of the most common ways these functions are used is with a `list_del(); list_add()` construct it made sense to split the two cases.  Currently we're using `list_del()` so they're not clearer.

**Comment by behlendorf** [comment]
> I agree. But if not, I think that this patch is a reasonable direction to go.

Agreed!

**Comment by ahrens** [comment]
> Is the expectation that after a list_remove() that list_link_active() on that list_node_t will [return false]?

Yes.  Any ZoL code that relies on list_link_active() would be broken, if that were not true (including dnode_setdirty() - it would become a no-op shortly after creating the dnode!)  However, the code I found for list_del() seems to correctly set the next/prev fields as list_link_active() expects, and thus have the expected behavior: http://src.illumos.org/source/xref/linux-master/include/linux/list.h#122

```
static inline void list_del(struct list_head *entry)
{
	__list_del_entry(entry);
	entry->next = LIST_POISON1;
	entry->prev = LIST_POISON2;
}
```

**Comment by behlendorf** [comment]
@ahrens I'm happy to be mistaken about this.  It turns out I even wrote a [test case](https://github.com/zfsonlinux/spl/blob/master/module/splat/splat-list.c#L361) years ago to verify that this was working properly.  Never mind, carry on!

**Comment by behlendorf** [comment]
@bzzz77 OK the MT spa sync has been merged.  It would be great if you could rebase this on master.

**Comment by behlendorf** [comment]
@bzzz77 I hope you don't mind but I've hijacked your PR and opened #5935 with a rebased version on master which includes the multilist locking changes.  If you have a few minutes it would be great if you could verify there is still a performance improvement from this optimization.  Or alternately, post the test case you were using so someone else can run the tests.

**Pull request closed without merging**
