### PR TITLE
Reorder ZFS ioctls to fix cross-version compatibility

### LINKED ISSUE #8482: Channel Program reordered ioctls
### Describe the problem you're observing
https://github.com/zfsonlinux/zfs/pull/6558 injected ZFS_IOC_CHANNEL_PROGRAM in between ZFS_IOC_DESTROY_BOOKMARKS and ZFS_IOC_RECV_NEW and thus reordered the ioctl numbers for everything under ZFS_IOC_DESTROY_BOOKMARKS. This is very annoying when trying to support more than one ZoL kernel version. Could we move it below ZFS_IOC_POOL_SYNC (the last general-purpose ioctl in 0.7) before 0.8 is released? Otherwise a specific check needs to be implemented to see if ZFS_IOC_CHANNEL_PROGRAM is supported and everything afterwards needs to be incremented.

### PR DESCRIPTION
**Pull request by lorenz**
### Description
Fixes #8482 

### How Has This Been Tested?
If this is merged before 0.8 is released, it should have pretty much no impact on existing tooling (since there was never a released version of ZoL with the broken numbering) and avoids a lot of headaches when trying to support multiple releases.

I've tested the kernel side of this change, since it only changes constants and the original reordering didn't cause any issues I do not anticipate any on the userspace side either.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
@lorenz thanks for catching this!  Yes, `ZFS_IOC_CHANNEL_PROGRAM` should have been added  after `ZFS_IOC_POOL_SYNC`, I agree better to fix this now before it ends up in a tagged release.

You're going to need to update `validate_ioc_values()` in `libzfs_input_check.c` as part of this PR.  This check was added to the test suite to specifically detect this kind of accidental reordering.  (unfortunately it was added a little too late).

**Comment by lorenz** [comment]
I've updated that now as well, but haven't locally tested it. I'll just let the CI run.

**Comment by behlendorf** [comment]
Thanks.  Might just be Github's rendering but it looks like there may be some cstyle white space issues.

**Comment by lorenz** [comment]
I've actually just force-pushed a fix for that, but GitHub seems a bit slow to pick it up.

**Comment by ahrens** [comment]
Do we have any automated tests to ensure that these changes aren't made in the future?

**Comment by behlendorf** [comment]
@ahrens we do.  @don-brady added them, this is why it was necessary to update `libzfs_input_check.c` which contains to required order.  Otherwise this PR would fail the test suite.

**Comment by ahrens** [comment]
I see, so I guess that the change that introduced the problem happened before libzfs_input_check.c was added?  Seems like we would normally want to not allow any changes to existing lines in that file, otherwise someone could reorder the ioctls, and then change the test to pass!

**Comment by behlendorf** [comment]
@ahrens yes, that's exactly what happened.  This issue predates adding the test case.

**Pull request merged**
