### PR TITLE
zfs-0.7.9 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Description
Sample patchset for zfs-0.7.9.  This release will add in support for Fedora 28.  We're targeting early May to get this out.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by morphinz** [comment]
Any chance to include e14a32b? This one is really annoying if you are not using legacy dnodesize.

Thanks.

**Comment by beren12** [comment]
And don't forget https://github.com/zfsonlinux/zfs/commit/7403d0743e2b75b7f5412a14007ba159efb67a7d ;-)

**Comment by DeHackEd** [comment]
I thought 0.7.9 was planned to include the fixer for the 0.7.7 directory contents disappearing bug (#7401)

**Comment by behlendorf** [comment]
So e14a32b is a little bit problematic since it requires us to at least bring in 047116ac76526d869e3f347afb5d81cc2b156fdf and 5121c4fb0c25a369d2e6f61e5b0a79969f0b75b5 which are somewhat intertwined with encryption.  So it's not going to be an easy cherry pick.

7403d07 is recent but very low risk.

@DeHackEd that's the hope.  @ryao if working on a patch to handle the 0.7.7 directory issue. Depending on when it's ready it might end up in the next point release.

**Comment by tonyhutter** [comment]
0.7.9 is out: https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.9

**Pull request closed without merging**
