### PR TITLE
Update arc_c atomically

### PR DESCRIPTION
**Pull request by dweeezil**
Since arc_c can be updated concurrently from multiple threads, there's a
race condition between any check of its value and the subsequent updating
of it.  This patch updates its value using atomic_cas_64() and re-tries
the test if it has been changed by another thread.

Reverts: 935434ef
Fixes: #3904
Fixes: #4161

### CODE REVIEW

**Comment by dweeezil** [comment]
Compiles but otherwise 100% untested.  Let the buildbots have the first go at it.

**Comment by tuxoko** [comment]
@dweeezil 
That's not how you use cmpxchg.

**Comment by tuxoko** [comment]
@dweeezil 
Doing multiple cmpxchg in a row doesn't seems like a good idea. It's better to squash them in one. You should also add `cpu_relax()` when busy-looping. Also, every direct assignment don't work in 32 bit.

**Comment by dweeezil** [comment]
@tuxoko I figured as much but I wanted to get something started.  I also noticed some other use of ```arc_c```` which might be troublesome on 32-bit systems.  I'm beginning to wonder if it would better to simply use a spinlock since it's not as if ```arc_c``` is changed terribly often.  The more I think about it the better an idea that sounds.

**Comment by dweeezil** [comment]
@tuxoko Makes me wonder whether ```ARCSTAT_MAX()``` ought to have a ```cpu_relax()``` in it.

**Comment by tuxoko** [comment]
@dweeezil 
Yeah, spinlock is probably the better approach.

**Comment by dweeezil** [comment]
@tuxoko I agree and will post an updated pull request separately.

**Pull request closed without merging**
