### PR TITLE
Revert 8978

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Confirm commit 693c1fc478 uncovered an existing kmem leak.

### Description

```
(view as text)
unreferenced object 0xffff8801d5a13a90 (size 16):
  comm "sudo", pid 4254, jiffies 4302532476 (age 188.168s)
  hex dump (first 16 bytes):
    01 00 00 00 01 00 00 00 00 00 00 00 e9 03 00 00  ................
  backtrace:
    [<ffffffff8185e02a>] kmemleak_alloc+0x7a/0x100
    [<ffffffff81302868>] __kmalloc+0x258/0x3c0
    [<ffffffff810e1adb>] groups_alloc+0x2b/0x90
    [<ffffffff810e1efb>] SyS_setgroups+0x6b/0x200
    [<ffffffff8186ebb7>] entry_SYSCALL_64_fastpath+0x1a/0xa5
    [<ffffffffffffffff>] 0xffffffffffffffff
unreferenced object 0xffff8801cae3f900 (size 192):
  comm "xattr_zfs_zrege", pid 4791, jiffies 4302532925 (age 186.372s)
  hex dump (first 32 bytes):
    01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  backtrace:
    [<ffffffff8185e02a>] kmemleak_alloc+0x7a/0x100
    [<ffffffff8130248f>] kmem_cache_alloc+0x1ef/0x370
    [<ffffffff810ddefe>] prepare_creds+0x2e/0x170
    [<ffffffff810de837>] prepare_exec_creds+0x17/0x70
    [<ffffffff81343d66>] prepare_bprm_creds+0x56/0xa0
    [<ffffffff81343f30>] do_execveat_common.isra.27+0x180/0xb50
    [<ffffffff81344c39>] SyS_execve+0x49/0x70
    [<ffffffff81004620>] do_syscall_64+0x70/0x140
    [<ffffffff8186ec67>] return_from_SYSCALL_64+0x0/0x6a
    [<ffffffffffffffff>] 0xffffffffffffffff
```

### How Has This Been Tested?

Pending CI results from the Coverage builder which enables the kmem leak checker.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by megari** [comment]
Why? There's little reason to remove test cases even if they happen to expose potentially orthogonal problems. Would analyzing and fixing the new problem and constructing test cases for it (to restore orthogonality) not be a more fruitful course of action?

**Comment by behlendorf** [comment]
The problem was they were causing the CI to consistently fail which was disruptive to other development.  We'll get these tests reapplied once we also have a fix for the orthogonal issue.  @PaulZ-98 is looking in to this.

**Comment by megari** [comment]
Sorry to nag, but were these tests ever restored?

**Comment by behlendorf** [comment]
@megari not yet.  @PaulZ-98 when you get a chance would you mind opening a PR with the reverted patch.  That should at least let us confirm the original reported leak, and we can go from there.

**Comment by PaulZ-98** [comment]
The PR to test #8978 is #9103.   I will rebase it to kick off the CI.  It didn't reveal the leak when first pushed which was July 30, and my own testing at that time failed to show the leak.

**Pull request merged**
