### PR TITLE
Rewrite of function fBytes() in arc_summary.py

### PR DESCRIPTION
**Pull request by scotws**
### Description

Complete rewrite of function fBytes() with the same functionality. Uses short loop instead of if-elif-else construct, removes unused parameter "Decimal", centralizes formatting, adds function documentation string, aims to confirm to PEP8. 

**Note:** Though removal of unused "Decimal" parameter does not affect arc_summary.py itself, there is the possibility that third parties are using this functionality after importing arc_summary.py for their own needs. 

### How Has This Been Tested?

Output of original function and the new function was automatically compared with the values 
`TESTNUMBERS = [0, 1, 100, 1000,
               (2 ** 10)+42,
               (2 ** 10),
               (2 ** 20)+42,
               (2 ** 20),
               (2 ** 30)+42,
               (2 ** 30),
               (2 ** 40)+42,
               (2 ** 40),
               (2 ** 50)+42,
               (2 ** 50),
               (2 ** 60)+42,
               (2 ** 60),
               (2 ** 70)+42,
               (2 ** 70),
               (2 ** 80)+42,
               (2 ** 80),
               (2 ** 90)+42,
               (2 ** 90),
               sys.maxsize] ` 
to ensure identical strings (note "sys.maxint" has been removed in Python 3.0). Test run on Ubuntu 16.04 LTS with stock ZFS version 0.6.5.9-2 with Python 2.7.12 and Python 3.5.2.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by scotws** [comment]
Hope that was it. Out of curiosity, because I'm somewhat new to this, should I upload my test file for the function somewhere as well? Didn't see an obvious place for that in the PR form ...

**Comment by dinatale2** [comment]
@scotws Thanks for the refresh! Your commit message is missing the `Signed-off-by` line in your commit message. As for your test file, you can put in a gist (see the big plus sign next to your portrait on the top left of your github page) and link it in this PR.

**Comment by scotws** [comment]
Ah, thanks. Test routine for the changes: https://gist.github.com/scotws/561302ca82174ad6f9144666e78557c0 (scotws/test_new_fbytes.py)

**Comment by behlendorf** [comment]
@scotws looks reasonable to me.  Instead of merging in master can you rebase this PR on master and force update the PR.

**Comment by scotws** [comment]
@behlendorf Hoped that worked? Sorry, first time with rebase.

**Comment by behlendorf** [comment]
@scotws oh I see, this change is on your master branch.  For future reference you'll want to create a new branch for each PR to make rebasing the changes easier.  I can rebase and squash this one when I bring it in.

**Pull request closed without merging**
