### PR TITLE
4.6 Compat: Fall back to d_prune_aliases() if necessary

### PR DESCRIPTION
**Pull request by dweeezil**
As of 4.6, the icache and dcache LRUs are memcg aware insofar as the
kernel's per-superblock shrinker is concerned.  The effect is that dcache
or icache entries added by a task in a non-root memcg won't be scanned
by the shrinker in the context of the root (or NULL) memcg.  This defeats
the attempts by zfs_sb_prune() to unpin buffers and can allow metadata to
grow uncontrollably.  This patch reverts to the d_prune_aliaes() method
in case the kernel's per-superblock shrinker is not able to free anything.

Fixes: #4726

### CODE REVIEW

**Comment by dweeezil** [comment]
Time to see whether this works for all of the various kernels.

**Comment by behlendorf** [comment]
Thanks for tacking this, the patch LGTM.  I've re-submitted the two failed testers since both failures looked unrelated.

**Comment by tuxoko** [comment]
Nice. LGTM.

**Comment by behlendorf** [comment]
@dweeezil let me know if your happy with this as the final patch and I'll merge it.

**Comment by dweeezil** [comment]
@behlendorf Go for it.

**Comment by behlendorf** [comment]
Merged as:

09fb30e Linux 4.6 compat: Fall back to d_prune_aliases() if necessary

**Pull request closed without merging**
