### PR TITLE
Kernel 4.1 changes

### PR DESCRIPTION
**Pull request by mk01**

### CODE REVIEW

**Comment by behlendorf** [comment]
@mk01 Thanks, when you get a chance could you refresh this to make the style checker happy.

```
./module/zfs/zpl_file.c: 206: unterminated single line comment
```

**Comment by mk01** [comment]
@behlendorf 

just curious, this would be fine with the style check?
```
/ *
  *
  * /
```
?

I will do two one line comments from it - hopefully it don't understand english - to complain that this are not TWO comments ;)

**Comment by mk01** [comment]
@behlendorf 

done.

**Comment by behlendorf** [comment]
@mk01 thanks.  For future reference you can easily run the style checker locally with the `make checkstyle` build target.  It's usually a good idea to check this before pushing a patch.

As for the interface change change effecting older kernels that's OK.  I think it's actually desirable that we use the updated interface as soon as it's available.

**Comment by behlendorf** [comment]
@mk01 Sorry about it took me so long to get a chance to look at this.  The heart of this looks good to me and solves the issue.  I've suggested a few improvements which once made should allow us to merge this.  It would be helpful if you could refresh this patch.  Thanks!

**Comment by behlendorf** [comment]
@mk01 I took the liberty of refreshing this patch and opened #3502 to replace this pull request.  The updated version is based on your initial patch but it incorporates all the feedback above.  It was restructured slightly be more consistent with the surrounding code.  Could you please review it.

**Pull request closed without merging**
