### PR TITLE
Document bookmars a little better at the top.

### LINKED ISSUE #3268: Document bookmarks properly
I know I added an example in the manpage a few months ago, but looking through the manpage again today, I noticed it's not really described anywhere…

Snapshots (together with Clones, Volumes and File systems etc) is described fairly early, but not bookmarks.

If I know exactly what a bookmark IS (but especially the difference between a bookmark and a snapshot), I could do it in a few minutes… Unless someone else jumps to it.

### PR DESCRIPTION
**Pull request by FransUrbo**
WIth the help of @DeHackEd (and his wording) I put together a simple/quick update to the manpage to describe bookmarks.

Signed-off-by: Turbo Fredriksson <turbo@bayour.com>
Closes #3268

### CODE REVIEW

**Comment by FransUrbo** [comment]
@behlendorf Is this good enough as the last patch for 0.6.4?

**Comment by DeHackEd** [comment]
Given that `createtxg` is an otherwise undocumented property I would advise against using it in your description as most users would not understand it.

**Comment by FransUrbo** [comment]
> Given that createtxg is an otherwise undocumented property I would advise against using it in your description as most users would not understand it.
> 

So what do you suggest?

**Comment by DeHackEd** [comment]
Probably that a bookmark records only the point in time when its associated snapshot was made and that this is sufficient for use as the source of an incremental send... Writing isn't my strong point. 

> Bookmarks can be created extremely quickly, and, compared to <b>snapshot</b>, consume no additional space within the pool.

Snapshots, plural?

**Comment by behlendorf** [comment]
Fixed a few spelling mistakes and reworked slightly to (hopefully) address the concerns raised above.  We can always continue to refine this as needed.

b467db4 Document bookmarks a little better in zfs(8)

**Pull request closed without merging**
