### PR TITLE
Fix integer overflow in get_next_chunk()

### PR DESCRIPTION
**Pull request by mazouffre**
### Motivation and Context

Fix [#8778](https://github.com/zfsonlinux/zfs/issues/8778)

### Description

In _get_next_chunk function_ of _dmu.c_, _dn->dn_datablksz_ type is _uint32_t_ and need to be casted to _uint64_t_ to avoid an overflow when the record size is greater than 4 MiB.

### How Has This Been Tested?

[#8778](https://github.com/zfsonlinux/zfs/issues/8778) contains detailed information.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
A couple minor cstyle issue then this looks good.  You can run `make checkstyle` locally before updating the PR to make sure it's happy.

```
./module/zfs/dmu.c: 723: line > 80 characters
./module/zfs/dmu.c: 723: space after cast
```

**Comment by behlendorf** [comment]
@mazouffre can you refresh to PR to resolve the cstyle issue so we can merge your fix.

http://build.zfsonlinux.org/builders/Ubuntu%2017.10%20x86_64%20%28STYLE%29/builds/13442/steps/shell_2/logs/stdio

**Comment by mazouffre** [comment]
Sorry for the delay, I think I have solved the problem of style. This is the first time I use git and github. I am a little lost. Thank you for your help.

**Comment by behlendorf** [comment]
@mazouffre no problem, thanks for taking the time to start learning the tools and opening a PR.  If you can refresh this PR one last time to include your [signed-off-by](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s) this will be ready to merge.

```
git commit --amend --signoff
git push --force
```

**Pull request merged**
