### PR TITLE
[buildbot][testing] zfs master 24.08.2017 + (new initial) prefetch dmu ( issue 6453 )

### PR DESCRIPTION
**Pull request by kernelOfTruth**
Test-drive of the new initial prefetcher implementation by ironMann

### Description
Opening this PR to see if this passes and is ready for **bleeding-edge testing** & **[experimental/testing]** usage

### Motivation and Context
According to https://github.com/zfsonlinux/zfs/issues/6453 [and others] there's a performance regression with 0.7.x branch and prefetching

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
potential issues in 1st change set:

http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20Mainline%20%28TEST%29/builds/3819
http://build.zfsonlinux.org/builders/Fedora%2026%20x86_64%20%28TEST%29/builds/579
http://build.zfsonlinux.org/builders/Ubuntu%2016.04%20x86_64%20%28TEST%29/builds/554
http://build.zfsonlinux.org/builders/Ubuntu%2017.04%20x86_64%20%28TEST%29/builds/607
http://build.zfsonlinux.org/builders/CentOS%206%20x86_64%20%28TEST%29/builds/96
http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20%28TEST%29/builds/100

the Amazon Production test buildbot however succeeded:
http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20Release%20%28TEST%29/builds/3724

new commit (from today) will be pushed soon

**Comment by behlendorf** [comment]
Here's the ASSERT which was triggered.  @ironMann thanks for investigating this!

http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20Mainline%20%28TEST%29/builds/3819/steps/shell_8/logs/console

**Comment by ironMann** [comment]
@behlendorf This is probably a false alarm. Prefetcher was called with `db->db_blkid == DMU_SPILL_BLKID (18446744073709551614)`.

Perhaps this should be prevented at [`dbuf_read()`] ?(https://github.com/zfsonlinux/zfs/blob/2209e40981e887c773914ec0f3b73cedf45ddb7d/module/zfs/dbuf.c#L1229) 

@kernelOfTruth 
I've amended the last commit in the branch so this should not happen...

**Comment by kernelOfTruth** [comment]
@ironMann okay, I've pushed the new commit - thanks for letting me know :)

**Comment by ironMann** [comment]
@kernelOfTruth Sorry, the last commit was amended. Make sure you get 048237fc0abf70976a981dc5148e11c65de87267

**Comment by kernelOfTruth** [comment]
@ironMann no worries, yes, 048237fc0abf70976a981dc5148e11c65de87267 got in :)

**Comment by kernelOfTruth** [comment]
Potential issues in the 2nd round:

http://build.zfsonlinux.org/builders/Fedora%2026%20x86_64%20%28TEST%29/builds/589
http://build.zfsonlinux.org/builders/Ubuntu%2016.04%20x86_64%20Kmemleak%20%28TEST%29/builds/3092

**Comment by behlendorf** [comment]
The [memory leak](http://build.zfsonlinux.org/builders/Ubuntu%2016.04%20x86_64%20Kmemleak%20%28TEST%29/builds/3092/steps/shell_9/logs/kmemleak) looks real, the other failure is a known unrelated issue in the test suite.

**Comment by behlendorf** [comment]
Closing is favor of #6568 opened by @ironMann.

**Pull request closed without merging**
