### PR TITLE
Introduce python style checking

### PR DESCRIPTION
**Pull request by dinatale2**
Introduce a make recipe for flake8 to enable python
style checking. Ensure all python scripts pass flake8.
Return an error code of 0 for arcstat.py -v and
dbufstat.py -v.

### CODE REVIEW

**Comment by dinatale2** [comment]
Updated. Forgot to add my .ksh test files to Makefile.am in cli_user/misc in my initial commit.

**Comment by dinatale2** [comment]
Updated again. Corrected an issue in zfs-script-config.sh.in

**Comment by rlaager** [comment]
The net set of changes is good, I'm in favor of merging this PR.

If you're willing to spend a little time with `git rebase` and `git add -p`, though, I would prefer that all the style changes were in a separate commit (or better, multiple commits)--before the introduction of the checks, of course.

**Comment by dinatale2** [comment]
Thanks for taking a look @rlaager! I went ahead and broke out the commits as you suggested. I also tweaked the test scripts so commands show up in the log file.

**Pull request merged**
