### PR TITLE
Zvol rework (take 2)

### PR DESCRIPTION
**Pull request by ryao**
I did some analysis of the issues that the previous iteration of this had on kernels 2.6.32 - 2.6.35 over the weekend. I believe that it was caused by improperly handling torvalds/linux@7b6d91daee5cac6402186ff224c3af39d79f4a0e. In specific, `REQ_HARDBARRIER == (1 << BIO_RW_BARRIER)` and `REQ_DISCARD == (1 << BIO_RW_DISCARD)`. Consequently, all writes were mapped to discards on those kernels.

This revision makes the following changes since the last one:

1. It adds secure discard support.
2. It should fix the regression on 2.6.32-2.6.35.
3. It removes the zvol_threads taskq.
4. It corrects a typo that caused build failures on certain kernels.
5. It corrects a mistake where VDEV_REQ_FUA is not mapped to REQ_FUA on 2.6.37 and earlier. After this pull request, it will only matter on 2.6.36 and 2.6.37 because the earlier kernels are not able to make this distinction in the bio layer.
6. It removes a couple of autotools checks that were made obsolete by dropping support for kernels older than 2.6.32.

A fairly detailed description of the benefits of the rework is included in the "zvol processing should use struct bio" commit message. It also mentions one regression, which I will reproduce here:

```
Many users report double digit performance gains from this patch. That
efficiency increase comes from removing an entire layer of code, which
contains instrumentation for block IO accounting. That instrumentation
is GPL-exported, so we cannot readd the hooks ourselves. Consequently,
this introduces a regression in terms of IO monitoring. Since zvols are
internally files mapped as block devices, this should be okay. Anyone
who is willing to accept the performance penalty for the block IO
layer's accounting could use the loop device in between the zvol and its
consumer. Alternatively, perf and ftrace likely could be used.
```

If it passes the buildbot, it should be safe to merge.

### CODE REVIEW

**Comment by sempervictus** [comment]
I've been using the abd2 version of this rework since @ryao so graciously pushed the branch this weekend. Results have been impressive - latency under concurrent load is reduced by >20% on average, and on systems which exhibited ZVOL related instability, abusive IO has been running for well over 24h with nothing logged in dmesg yet. I would highly suggest that everyone who builds test stacks try this out and beat it up, it might be the greatest thing to happen to ZVOLs since they became a reality outside the ~~Solaris~~ Illumos world.

**Comment by olw2005** [comment]
@sempervictus @ryao  I'd love to take the abd2 version for a spin.  I believe I found the right branch of zfs:
https://github.com/ryao/zfs/tree/abd2-zvol-rework

Is there a corresponding branch of spl that I should use?

**Comment by kernelOfTruth** [comment]
@olw2005 that one has the previous iteration of ABD2

@ryao could you please refresh your abd2-zvol-rework branch ?

if the zvol rework doesn't need any spl changes spl master should be enough - as far as I know ABD doesn't depend on any spl changes

**Comment by ryao** [comment]
@olw2005 I will try to do that later today.

@behlendorf I just pushed a revision. The commit message for `zvol processing should use struct bio` has been revised to remove historical information about the Illumos taskq import, more clearly describe things, etcetera. I have also removed obsolete comments above `zvol_write()` and `zvol_read()` that reference the taskq threads. No code has changed.

**Comment by olw2005** [comment]
@ryao  Excellent, let me know when you have it ready and I'll give it a good workout.

**Comment by behlendorf** [comment]
@ryao nice work, this turned out very nicely!  Not only is it a nice bit of cleanup and simplification of the code but I am seeing a significant performance improvement.  I'll get it merged once I get your sign off that this is the finalized version.

**Pull request merged**
