### PR TITLE
Add -o offset, -a search options to zdb for use with the -l flag

### PR DESCRIPTION
**Pull request by wrouesnel**
The -o option modifies -l to read the ZFS device label from an offset into the
given device. The actual labels are read from their normal position presuming
the offset is the start of the device.

The -a option causes zdb to try and read ZFS device labels starting from every
byte past the offset, and stops once a valid label is found.

This provides the a byte-offset boundary for creating a containing partition
to allow for successful pool imports.

### CODE REVIEW

**Comment by behlendorf** [comment]
@wrouesnel it would be great if you could rebase this on master.

**Comment by wrouesnel** [comment]
Merged up the current master. Doesn't look like any big changes, but I need to wrap my head around what's changed with the build system at the moment to test locally.

**Comment by ilovezfs** [comment]
@behlendorf @wrouesnel I think I rebased it correctly here, including cstyle cleanups: https://github.com/ilovezfs/zfsonlinux-zfs/tree/zdb-label-search_rebased-20160205

I tested it on OS X, and I believe I've found a bug. It can successfully read labels 0 and 1 but not 2 and 3 because it's using the size of the full device rather than the beginning offset of the next partition.

```
        // regular label print code for what we found.
        psize = statbuf.st_size - offset;
        psize = P2ALIGN(psize, (uint64_t)sizeof (vdev_label_t));
```
statbuf.st_size is the size of the entire device for which I've specified an offset, but the "regular" code assumes this value is size of the partition containing the vdev. If I hard code in the byte offset of the next partition, I get all four labels.

**Comment by ilovezfs** [comment]
@behlendorf @wrouesnel Another issue with the current code is that it returns a lot of false positives. This removes false positives that have zero elements:
https://github.com/ilovezfs/zfsonlinux-zfs/commit/a4a03b218d19928499e00507289baeaf9d3f99d5

A valid label currently has 13 entries. Many of the false positives have 11. So we can filter out those too:
https://github.com/ilovezfs/zfsonlinux-zfs/commit/645f9e62dab06758d2f0ce65ac46ee45df2bec49

Also, we can speed up the search if it's valid to assume at worst 8-sector alignment of partitions:
https://github.com/ilovezfs/zfsonlinux-zfs/commit/1deb7e6b28292f5e6aa3aa4756250c62f2cfa19a

**Comment by behlendorf** [comment]
@ilovezfs thanks for moving this patch forward.  Can you open a new PR with the updated patch and your improvements.

**Comment by wrouesnel** [comment]
Is this PR no longer needed (since @ilovezfs took my idea and did some great improvements on it ) ?

**Comment by behlendorf** [comment]
@wrouesnel I believe what we still need is a version of your original patch with @ilovezfs's improvements.  It would be great if you could rebase this pull request and apply that additional work.

**Comment by behlendorf** [comment]
Closing.  @ilovezfs @wrouesnel if you're still interested in adding this functionality please go ahead and open a new pull request when you have time to work on this.

**Pull request closed without merging**
