### PR TITLE
5313 Allow I/Os to be aggregated across ZIO priority classes

### PR DESCRIPTION
**Pull request by DeHackEd**
Reviewed by: Andriy Gapon <avg@FreeBSD.org>
Reviewed by: Will Andrews <willa@SpectraLogic.com>
Reviewed by: Matt Ahrens <mahrens@delphix.com>
Reviewed by: George Wilson <george@delphix.com>
Approved by: Robert Mustacchi <rm@joyent.com>

References:
  https://www.illumos.org/issues/5313
  https://github.com/illumos/illumos-gate/commit/fe319232

Ported-by: DHE <git@dehacked.net>

### CODE REVIEW

**Comment by DeHackEd** [comment]
TODO: IllumOS's `vdev_queue.c` has functions in different orders. For synchronization we should re-order our code to match.

**Comment by DeHackEd** [comment]
Fix `make checkstyle`, one comment was misaligned

**Comment by behlendorf** [comment]
Just for reference, the Fedora 19 failure in the latest test run is unrelated to this change,

**Comment by DeHackEd** [comment]
Fixed a copy/paste error in `vdev_impl.h` as indicated previously.

**Pull request closed without merging**
