### PR TITLE
Fix statfs(2) for 32-bit user space

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Issues #7122 and #7927.

### Description

When handling a 32-bit statfs() system call the returned fields,
although 64-bit in the kernel, must be limited to 32-bits or an
`EOVERFLOW` error will be returned.

This is less of an issue for block counts since the default
reported block size in 128KiB.  But since it is possible to
set a smaller block size, these values will be scaled when
needing to fit in a 32-bit unsigned long.

Unlike most other filesystems the total possible file counts
are more likely to overflow because they are calculated based
on the available free space in the pool.  In order to prevent
this the reported value must be capped at 2^32-1.  This is
only for statfs(2) reporting, there are not changed to the
internal ZFS limits.

### How Has This Been Tested?

Starting with a clean Ubuntu 18.04 x86_64 install I added the
32-bit user space compatibility libraries.

```
$ sudo dpkg --add-architecture i386
$ sudo apt update
$ sudo apt install libc6:i386
```

Next I manually extracted the 32-bit `df(1)` binary from the
`coreutils_8.26-3ubuntu4_i386.deb` package as a test application.
With an unmodified version of ZFS I was able to immediately
reproduce the issue.

```
$ strace -e trace=statfs64 ./df -Ti /mnt/zfs
strace: [ Process PID=15191 runs in 32 bit mode. ]
statfs64("/mnt/zfs", 84, 0xffe9e358)    = -1 EOVERFLOW (Value too large for defined data type)
./df: /mnt/zfs: Value too large for defined data type
+++ exited with 1 +++
```

After applying the proposed fix which scales the block and file
counts the `EOVERFLOW` was prevented as expected.

```
$ strace -e trace=statfs64 ./df -Ti /mnt/zfs /mnt/ext4
strace: [ Process PID=16839 runs in 32 bit mode. ]
statfs64("/mnt/zfs", 84, {f_type=ZFS_SUPER_MAGIC, f_bsize=131072, f_blocks=24252411, f_bfree=24252410, f_bavail=24252410, f_files=4294967295, f_ffree=4294966286, f_fsid={val=[560721052, 10632861]}, f_namelen=255, f_frsize=131072, f_flags=ST_VALID}) = 0
statfs64("/mnt/ext4", 84, {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=792403690, f_bfree=792381155, f_bavail=752111741, f_files=201326592, f_ffree=201326581, f_fsid={val=[1255411960, 3511091618]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
Filesystem     Type     Inodes IUsed      IFree IUse% Mounted on
tank           zfs  4294967295  1009 4294966286    1% /mnt/zfs
/dev/loop20    ext4  201326592    11  201326581    1% /mnt/ext4
+++ exited with 0 +++
```

Note that using the 64-bit system `df(1)` the reported file counts are
not capped.

```
$ df -Ti /mnt/zfs /mnt/ext4
Filesystem     Type     Inodes IUsed      IFree IUse% Mounted on
tank           zfs  6208618183  1009 6208617174    1% /mnt/zfs
/dev/loop20    ext4  201326592    11  201326581    1% /mnt/ext4
```

Finally, I manually verify the block size and count scaling by changing
the filesystems record size to 512b forcing an overflow.  The reported
block size was dynamically scaled to 1k as required to prevent the overflow.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
@ryao it sounds like there may be multiple issues at play here, the least we can do is address this one.  The patch is specifically intended to address the `-D_FILE_OFFSET_BITS=32` case, as described above.  This case is not handled by the referenced kernel patch, but even if it were we'd want to pick it up for older kernels.

```c
static int put_compat_statfs64(struct compat_statfs64 __user *ubuf, struct kstatfs *kbuf)
{
        struct compat_statfs64 buf;
        if (sizeof(ubuf->f_bsize) == 4) {
                if ((kbuf->f_type | kbuf->f_bsize | kbuf->f_namelen |
                     kbuf->f_frsize | kbuf->f_flags) & 0xffffffff00000000ULL)
                        return -EOVERFLOW;
                /* f_files and f_ffree may be -1; it's okay
                 * to stuff that into 32 bits */
>>>             if (kbuf->f_files != 0xffffffffffffffffULL
>>>              && (kbuf->f_files & 0xffffffff00000000ULL))
>>>                     return -EOVERFLOW;
>>>             if (kbuf->f_ffree != 0xffffffffffffffffULL
>>>              && (kbuf->f_ffree & 0xffffffff00000000ULL))
>>>                     return -EOVERFLOW;
        }
```

Specifically, the most common way for this issue to manifest itself is an overflow of `->f_files`.  This overflow happens relatively easily with ZFS because the number of total files is calculated by dividing the available free space by the minimum dnode size.  It only takes an empty 2TB pool to reach the limit.  I agree that overflowing the block count is far more unlikely, but there's no reason not to handle it.

I've reopened the PR because this resolves a real issue, which is easy to reproduce.

**Comment by ryao** [comment]
@behlendorf Alright, although I am not convinced that we know of any userland softwware that benefits from this. I am thinking that it might be cleaner to have a dataset level option for controlling how things are reported here. That would have a more predictable behavior. If we go this route, I suggest putting it behind a module parameter

**Comment by ryao** [comment]
@behlendorf It is true that Ubuntu is shipping 32-bit libraries, but those libraries should be immune to this. They are designed to be built for both 32-bit and 64-bit architectures. When built for a 32-bit architecture, the build system should always pass `-D_FILE_OFFSET_BITS=64` to ensure parity with the 64-bit versions. If there is a single library that Ubuntu is shipping that is not built with -D_FILE_OFFSET_BITS=64, then that is likely a bug.

The only software that would benefit from this is software built before a 64-bit statvfs was a thing. To my knowledge, such software is not being shipped by any distribution. Also, we do not have any examples of such software being used in production. We can address this, but it is an extreme edge case. I feel that such an edge case belongs behind a kernel parameter. I do not like the idea of implementing this workaround without confirming that someone out there benefits from it. Once it is in the codebase, we could find ourselves in a position of supporting it forever should someone come to depend on it.

**Comment by behlendorf** [comment]
@ryao I tested this fix while developing it on Ubuntu 18:04 by adding the 32-bit architecture, installing the libraries, and then using the `df(1)` from `coreutils_8.26-3ubuntu4_i386.deb`.  I happened to pick `df(1)`, but any 32-bit binary  which calls `statfs64` will not work properly.  And it _should_ according to the multi-arch packaging guidelines set by Debian and used by Ubuntu.  RHEL/CentOS handle things slightly differently (of course) but the kernel side fix is the same.

https://wiki.debian.org/Multiarch/HOWTO

```
$ sudo dpkg --add-architecture i386
$ sudo apt update
$ sudo apt install libc6:i386
```

I'm not sure I fully understand your objections here either.  In the vast majority of cases the only thing we'll be reporting differently is the total number of available objects.  Since this is already a calculated value (freespace / DNODE_SIZE) there never was a _right_ answer to report.  As for the reported block size and count, assuming the default block size no downshifting will occur until the you reach a 512TiB filesystem.  Hopefully, very few people are using 32-bit applications on filesystems this large but even if they choose to this will continue to work.

**Comment by ryao** [comment]
@behlendorf Is this patch part of your kernel?

https://patchwork.kernel.org/patch/9987759/

If it is, then I am surprised. I was under the impression that the 32-bit df would be built with `-D_FILE_OFFSET_BITS=64` so that the machine word size would not determine the size of supported filesystems. If that is case, I would need to dig into this to see why that is the case.

**Comment by behlendorf** [comment]
It was the Ubuntu LTS kernel, 4.15.0-34-generic.  Great, I'm glad we could hash this out.  Thanks for making the time to fully review this.

**Pull request merged**
