### PR TITLE
Retry setting fault LED

### PR DESCRIPTION
**Pull request by cvoltz**
### Description
During testing of the automatic hot-spare activation on the Hewlett Packard Enterprise Apollo 4520, it was discovered that the fault LED was not being reliably set. After investigation, it was determined that when another application is reading the sysfs attribute used to control the LED, a write to the attribute is discarded. This pull request adds a retry loop to the write which repeats if the LED was not updated. Testing indicates, that in the worst case, the loop will execute 4 times but 2 is typical.

To implement the retry loop in a single place, the code which updates the LED was refactored to remove duplication. A few existing `shellcheck` warnings were also resolved and a typo a comment was corrected.

### How Has This Been Tested?
The code was tested on an HPE Apollo 4520 which was fully loaded with drives (46 drives total). The code in the pull request was tested a few thousand cycles by having one application running which would constantly read the status of all the LEDs in the Apollo 4520 and display them while another application would run `statechange-led.sh` to toggle each fault LED. The state of the LED was verified at each state change. Additional testing included creating a zpool with a hot-spare, injecting an I/O error to a specific disk, letting the disk be faulted, then checking the LED status to verify it was properly set.

Per requirements, `shellcheck` was run on the ZEDlet. Some prior existing warnings were fixed and no new notes, warnings, or errors were created. The existing warnings could be fixed but would require adding comment lines which either told `shellcheck` to silence the warning or how to handle it. In a number of cases, the changes suggested by `shellshock` would lessen the readability so no changes were made.

### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [X] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [X] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by tonyhutter** [comment]
Thanks for these changes @cvoltz .  I'll give them a test on our JBOD.

**Comment by tonyhutter** [comment]
Only two changes I would ask for:
1. Log LED change only when the LED is actually set
2. Skip LEDs that are already set correctly in ```process_pool```.
```
diff --git a/cmd/zed/zed.d/statechange-led.sh b/cmd/zed/zed.d/statechange-led.sh
index 722b885..9370925 100755
--- a/cmd/zed/zed.d/statechange-led.sh
+++ b/cmd/zed/zed.d/statechange-led.sh
@@ -79,12 +79,12 @@ function check_and_set_led
 
                if [ "$current" != "$val" ] ; then
                        echo "$val" > "$file"
+                       zed_log_msg "vdev $vdev set '$file' LED to $val"
                else
                        break
                fi
         done
 
-       zed_log_msg "vdev $vdev set '$file' LED to $val"
 }
 
 function state_to_val {
@@ -134,6 +134,12 @@ function process_pool
                fi
 
                val=$(state_to_val "$state")
+
+               if [ "$current_val" == "$val" ] ; then
+                       # LED is already set correctly
+                       continue;
+               fi
+
                check_and_set_led "$vdev_enc_sysfs_path/fault" "$val"
                (( rc |= $? ))

```

**Comment by tonyhutter** [comment]
Thanks.  If you can squash and rebase your commits then we should be good to go.

**Comment by behlendorf** [comment]
Merged.  @cvoltz thanks for the fix!

**Pull request merged**
