### PR TITLE
3525 persistent l2arc.

### LINKED ISSUE #925: allow for persistent l2arc
https://groups.google.com/a/zfsonlinux.org/forum/?fromgroups=#!topic/zfs-discuss/eSYYLdx73r4

References request and a suggestion on how it might be done.

### PR DESCRIPTION
**Pull request by yshui**
For details, see: https://www.illumos.org/issues/3525

Close #925

Ported-by: Yuxuan Shui yshuiv7@gmail.com

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
like mentioned at https://github.com/zfsonlinux/zfs/issues/925#issuecomment-138057760

@grahamperrin kindly pointed out that Nexenta already has a working persistent l2arc implementation since May

https://github.com/Nexenta/illumos-nexenta/commit/f0a9ee9eeed31410aecb7bc0172cec615698aecd NEX-3514 Implement persistent L2ARC

https://github.com/Nexenta/illumos-nexenta/commit/887263262dff3397c305be7129b6fb394189de8e NEX-3514 Implement persistent L2ARC - fix build breakage in libzpool.

https://github.com/Nexenta/illumos-nexenta/commit/9498bb1539167ca88ff9237851a2ac9047859a5a NEX-3514 Implement persistent L2ARC - fix build breakage in libzpool (v2).

https://github.com/Nexenta/illumos-nexenta/commits/master?page=4

**Comment by kerberizer** [comment]
illumos 3525 is now in [code review](https://reviews.csiden.org/r/267/).

**Comment by behlendorf** [comment]
Closing.  We'll pick up this change once it's merged in to illumos.

**Comment by kpande** [comment]
seeing how there has been no activity elsewhere and I really want this, I tried to rebase this against current master and for the most part it is pretty straightforward with two exceptions; l2arc stats tracking and `l2arc_write_buffers()`

for the former it seems that we don't track l2arc stats, at least not the way this intended on doing so originally.

encryption changed how `l2arc_write_buffers()` works and isn't very well commented so I've got no idea what's happening in there.

maybe @yshui can look at this aspect of things.

**Comment by sempervictus** [comment]
@kpande: do you have a branch up with the rebase somewhere? Seems a bit less than trivial at first glance :)

**Comment by kpande** [comment]
yeah it's frustrating that the leadership doesn't care about work being done by others on features, as evidenced by its continual removal from milestones; @lundman made an attempt at a rebase and the branch lives in his repository.

i'm not sure if this code ever made it into illumos, but if so we can just re-port it with the changes for encryption.

**Comment by lundman** [comment]
I put it into
https://github.com/openzfsonosx/zfs/tree/persist_l2arc

which compiles and runs - however, there are two calls that needed to be changed into abd* calls that I was not sure of. If someone with more abd knowledge than I could check it over...

**Comment by gamanakis** [comment]
I wanted to experiment with this, so I rebased it on current master. It compiles and runs, no errors. Also no errors/warnings in dmesg.
It can be found in: 
https://github.com/gamanakis/zfs/tree/persist_l2arc

**Comment by yshui** [comment]
@behlendorf What's the upstream status of l2arc right now? Is there any news you can share?

**Comment by tycho** [comment]
> I wanted to experiment with this, so I rebased it on current master. It compiles and runs, no errors. Also no errors/warnings in dmesg.
> It can be found in:
> https://github.com/gamanakis/zfs/tree/persist_l2arc

Big thank you for doing this! Having a cold L2ARC after kernel upgrades/reboots has been the biggest pain point for my setup for a while, so your work is greatly appreciated.

Is there a bug/feature bounty tracker for ZOL? I'd like to post a bounty to prioritize getting this feature integrated, if it will help.

**Comment by gamanakis** [comment]
Although my rebase runs with no apparent problems, it doesn't make the L2ARC persistent.
Testing with:
```fio --ioengine=libaio --direct=1 --name=test --bs=2M --size=1G --readwrite=randread --runtime=600 --time_based --iodepth=64```
Monitoring with:
```zpool iostat -v 2```
After exporting and reimporting the pool, read speeds are lower and iostat reports the cache is empty.

**Comment by gamanakis** [comment]
I think I am making slow progress on this. Pushed new commits in:
https://github.com/gamanakis/zfs/tree/persist_l2arc
It compiles and it actually makes the L2ARC persistent!
Only downside so far is that upon unloading the zfs module (after exporting the pool) it complains that:
```Objects remaining in abd_t on __kmem_cache_shutdown().```

Further testing would be greatly appreciated. 
This is strictly experimental. Do not use in production. 
If @yshui or @skiselkov could take a look I would greatly appreciate it.

**Comment by Ornias1993** [comment]
> What's the upstream status of l2arc right now? Is there any news you can share?

@yshui You are in luck: Illumnos has been cordially trashed as upstream, so you would very well be able to finish this now :)

**Comment by yshui** [comment]
@gamanakis 

https://github.com/gamanakis/zfs/blob/34d1ca5f7c039658c198f7a9aff562df59162cb0/module/zfs/arc.c#L9227

You probably need to free this.

**Comment by gamanakis** [comment]
Each abd_get_from_buf() call allocates memory that is not freed by zio_wait() later on. There are several in this patch, 2 in blk_commit(), 1 in dev_hdr_read() and dev_hdr_update(), 1 in blk_read() and 1 in blk_prefetch. In each one of this, the abd_t has to be freed properly. This is not trivial to do as it requires a proper zio structure with a callback function.
I am still looking at the code to figure out how this works, but I think this is what is going on.

**Comment by gamanakis** [comment]
I just pushed a new commit addressing those issues, in the quickest way. No error messages anymore.

**Comment by gamanakis** [comment]
I implemented encryption, seems to be working fine. Just pushed the new commit. I would appreciate testing!

**Comment by Ornias1993** [comment]
@gamanakis If you are the one actually developing it, you can make your own PR here.
It's a nogo if everything gets done outside of the bounds of this repo, it messes things up big time.

Great work  btw, how much do you think you have left?

**Comment by gamanakis** [comment]
Will happen soon :)

**Comment by Ornias1993** [comment]
@gamanakis Awesome, love your dev attitude! :)

**Comment by gamanakis** [comment]
New pull request submitted:
https://github.com/zfsonlinux/zfs/pull/9582

**Comment by ahrens** [comment]
Superseded by #9582

**Comment by jittygitty** [comment]
@tycho Bounty was mentioned in this thread, so if interested in crowd-funding zfs please see: https://github.com/openzfs/zfs/issues/13397

**Comment by Ornias1993** [comment]
> @tycho Bounty was mentioned in this thread, so if interested in crowd-funding zfs please see: #13397

Necro’ing old shit is not appreciated

**Comment by jittygitty** [comment]
@Ornias1993 Apologies to anyone upset, was hoping it wouldn't be a nuisance. I had posted in a few tickets where "Bounty" had been discussed in a positive light ( @tyco ), thinking there would be interest in participating in the crowd funding issue I linked.

**Pull request closed without merging**
