### PR TITLE
Factor Linux specific code out of spa_misc.c

### PR DESCRIPTION
**Pull request by mattmacy**
Signed-off-by: Matt Macy <mmacy@FreeBSD.org>

The recent addition of procfs_list to spa_import_progress makes it not portable. This moves that code along with the currently linux only `module_param_call` functions to the platform code.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Part of the original intention was that these interfaces would be portable (like the rest of the kstat code).  While it sounds like that's currently not the case.  Do you have a sense for how difficult it would be to include that support in the FreeBSD SPL?  It could be non-functional, but enough to avoid breaking the build.

**Comment by mattmacy** [comment]
> Part of the original intention was that these interfaces would be portable (like the rest of the kstat code). While it sounds like that's currently not the case. Do you have a sense for how difficult it would be to include that support in the FreeBSD SPL? It could be non-functional, but enough to avoid breaking the build.

FreeBSD has these interfaces defined the way Illumos does and uses them internally. The problem is that the assert in dnode.c is not portable making assumptions about the value of uninitialized memory. That is why I initially talked about just removing the assert.

**Comment by lundman** [comment]
I tried to port the import-progress in the past, but it was a little too linux to be easy. We follow the illumos API, with limitations (only 64bit and strings iirc). But then we struggled a little bit with a recent commit (initialize?) that uses the raw method as well

**Comment by mattmacy** [comment]
> Part of the original intention was that these interfaces would be portable (like the rest of the kstat code). While it sounds like that's currently not the case. Do you have a sense for how difficult it would be to include that support in the FreeBSD SPL? It could be non-functional, but enough to avoid breaking the build.

@behlendorf As I've noted previously, the code you had prior to this was portable. The addition of the procfs_list field makes it unusable outside of Linux. if you would be willing to revert the change that switched it to use a procfs_list, those of us on other platforms would certainly appreciate it. Although I imagine the person who made the change might be grumpy about it.

**Comment by behlendorf** [comment]
That's unfortunate, well if the reality is that we need to move this in to platform specific code so be it.  But before we do so let's get @jgallag88's thoughts on this since he authored the original change.  Are there reasonable changes we could make to address the portability concerns?

**Comment by mattmacy** [comment]
> That's unfortunate, well if the reality is that we need to move this in to platform specific code so be it. But before we do so let's get @jgallag88's thoughts on this since he authored the original change. Are there reasonable changes we could make to address the portability concerns?

Short of hiding procfs_list in a portable abstraction not that I can see.

**Comment by behlendorf** [comment]
> Short of hiding procfs_list in a portable abstraction not that I can see.

We do have an existing user space version which could be used, and it seems like it should resolve the build issues.  That would let us defer revisiting adding a portable abstraction.

**Pull request merged**
