### PR TITLE
Debug issue 5887

### PR DESCRIPTION
**Pull request by tuxoko**
Signed-off-by: Chunwei Chen <david.chen@osnexus.com>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
For easy reference from the kmemleak test results.  I'll submit the kmemleak build again to see if the results are similar.

```
Test: /usr/share/zfs/zfs-tests/tests/functional/rsend/rsend_009_pos (run as root) [00:16] [PASS]
00:55:54.44 ASSERTION: Verify zfs receive can handle out of space correctly.
00:55:55.29 SUCCESS: /usr/share/zfs/zfs-tests/bin/mkfile 268435456 /var/tmp/testdir2529/bfile
00:55:55.51 SUCCESS: /usr/share/zfs/zfs-tests/bin/mkfile 67108864 /var/tmp/testdir2529/sfile
00:55:58.46 SUCCESS: zpool create bpool /var/tmp/testdir2529/bfile
00:55:59.24 SUCCESS: zpool create spool /var/tmp/testdir2529/sfile
00:55:59.38 SUCCESS: /sbin/zfs create bpool/fs
00:55:59.85 SUCCESS: /usr/share/zfs/zfs-tests/bin/mkfile 30M /bpool/fs/file
00:55:59.91 SUCCESS: /sbin/zfs snapshot bpool/fs@snap
00:56:00.24 SUCCESS: eval /sbin/zfs send -R bpool/fs@snap > /var/tmp/backdir-rsend/fs-R
00:56:03.94 cannot receive new filesystem stream: out of space
00:56:03.94 
00:56:04.97 zfs exited
00:56:04.98 SUCCESS: datasetnonexists spool/fs
00:56:04.99 SUCCESS: ismounted spool
00:56:05.76 SUCCESS: /bin/mv /bpool/fs/file /bpool
00:56:05.90 SUCCESS: /sbin/zfs destroy -rf bpool/fs
00:56:05.95 SUCCESS: /sbin/zfs snapshot bpool@snap
00:56:06.24 SUCCESS: eval /sbin/zfs send -R bpool@snap > /var/tmp/backdir-rsend/bpool-R
00:56:09.89 cannot receive new filesystem stream: out of space
00:56:09.96 
00:56:10.99 zfs exited
00:56:11.00 SUCCESS: datasetnonexists spool/fs
00:56:11.01 SUCCESS: ismounted spool
00:56:11.01 NOTE: Performing local cleanup via log_onexit (cleanup)
00:56:11.14 SUCCESS: /sbin/zpool destroy -f bpool
00:56:11.23 SUCCESS: /sbin/zpool destroy -f spool
00:56:11.24 zfs receive can handle out of space correctly.
```

**Comment by tuxoko** [comment]
@behlendorf 
So we do reproduce the issue, but the log doesn't show the part of `rsend_009_pos`.

**Comment by behlendorf** [comment]
What I'd really like to know, and can't tell from the stack traces in the console, is why isn't anything being dequeued.  Is the responsible thread blocked?  Is the queue empty and we have some kind of race?

**Comment by behlendorf** [comment]
@tuxoko let's close this debugging PR for now.  Feel free to open a new one if you have the time to investigate this further.

**Pull request closed without merging**
