### PR TITLE
Fix build with CONFIG_GCC_PLUGIN_RANDSTRUCT

### PR DESCRIPTION
**Pull request by gyakovlev**
### Description

Not sure if it's ok to open PR to this branch, I did anyway.
Sorry If it's a wrong thing to do.

Build fails if CONFIG_GCC_PLUGIN_RANDSTRUCT kernel option is set.
This code does not exist in master anymore, but it fixes release build on some kernels.

```
fs/zfs/zfs/metaslab.c:1055:2: error: positional initialization of field
in ‘struct’ declared with ‘designated_init’ attribute
[-Werror=designated-init]
  metaslab_rt_remove,
```

I added designated initializers and now it compiles.

### Motivation and Context

Fixes: #7069
### How Has This Been Tested?

Compile and run tested, nothing specific. Works fine for me.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [x] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
@gyakovlev thanks, we'll get it added to the next point release.

**Comment by dinatale2** [comment]
@gyakovlev Thanks for the PR! You may want to rebase your patch on the current `0.7-release` branch so the `TEST` builders can correctly build.

**Comment by gyakovlev** [comment]
rebased, looks like single test failure is related to #7528

**Comment by behlendorf** [comment]
@gyakovlev I'm going to close this to simply remove it from the open PR list.  But we will include it in 0.7.10 when @tonyhutter is putting together the tag.

**Pull request closed without merging**
