### PR TITLE
Wait for all znodes to be released before tearing down the superblock

### LINKED ISSUE #3281: PANIC on umount due to iput taskq
We're occasionally seeing stack traces like:
```
[ 4810.313652] VERIFY(list_is_empty(list)) failed
[ 4810.313672] PANIC at list.h:88:list_destroy()
[ 4810.313681] Showing stack for process 30963
[ 4810.313684] CPU: 0 PID: 30963 Comm: umount Tainted: P           OE  3.19.2-201.fc21.x86_64 #1
[ 4810.313686] Hardware name: Red Hat RHEV Hypervisor, BIOS 0.5.1 01/01/2007
[ 4810.313688]  ffffffff8176e025 000000008756bd80 ffff88005183bc08 ffffffff8176e025
[ 4810.313692]  0000000000000000 ffffffffa05024f7 ffff88005183bc18 ffffffffa02ff8f4
[ 4810.313695]  ffff88005183bda8 ffffffffa02ff9bb 00000000ee83ee83 000000008756bd80
[ 4810.313698] Call Trace:
[ 4810.313706]  [<ffffffff8176e025>] ? dump_stack+0x45/0x57
[ 4810.313709]  [<ffffffff8176e025>] dump_stack+0x45/0x57
[ 4810.313719]  [<ffffffffa02ff8f4>] spl_dumpstack+0x44/0x50 [spl]
[ 4810.313724]  [<ffffffffa02ff9bb>] spl_panic+0xbb/0x100 [spl]
[ 4810.313730]  [<ffffffff81776c37>] ? ftrace_call+0x5/0x34
[ 4810.313737]  [<ffffffffa02ff905>] ? spl_panic+0x5/0x100 [spl]
[ 4810.313957]  [<ffffffffa0464b8c>] ? zfs_fuid_destroy+0x21c/0x2f0 [zfs]
[ 4810.313992]  [<ffffffffa0476547>] zfs_sb_free+0x307/0x310 [zfs]
[ 4810.314027]  [<ffffffffa0476c39>] zfs_umount+0xe9/0x1a0 [zfs]
[ 4810.314075]  [<ffffffffa0476b55>] ? zfs_umount+0x5/0x1a0 [zfs]
[ 4810.314108]  [<ffffffffa04a38fe>] zpl_put_super+0xe/0x40 [zfs]
[ 4810.314113]  [<ffffffff8121ba36>] generic_shutdown_super+0x76/0x100
[ 4810.314115]  [<ffffffff8121b9c5>] ? generic_shutdown_super+0x5/0x100
[ 4810.314118]  [<ffffffff8121bd66>] kill_anon_super+0x16/0x30
[ 4810.314149]  [<ffffffffa04a3a5e>] ? zpl_kill_sb+0x1e/0x30 [zfs]
[ 4810.314180]  [<ffffffffa04a3a5e>] zpl_kill_sb+0x1e/0x30 [zfs]
[ 4810.314187]  [<ffffffff8121c159>] ? deactivate_locked_super+0x49/0x60
[ 4810.314190]  [<ffffffff8121c159>] deactivate_locked_super+0x49/0x60
[ 4810.314193]  [<ffffffff8121c5ac>] deactivate_super+0x6c/0x80
[ 4810.314197]  [<ffffffff8123a353>] ? cleanup_mnt+0x43/0xa0
[ 4810.314200]  [<ffffffff8123a353>] cleanup_mnt+0x43/0xa0
[ 4810.314202]  [<ffffffff8123a402>] ? __cleanup_mnt+0x12/0x20
[ 4810.314205]  [<ffffffff8123a402>] __cleanup_mnt+0x12/0x20
[ 4810.314209]  [<ffffffff810b89a4>] task_work_run+0xd4/0xf0
[ 4810.314214]  [<ffffffff81014cf7>] do_notify_resume+0x97/0xb0
[ 4810.314219]  [<ffffffff81774aa7>] int_signal+0x12/0x17
```

E.g.:
http://buildbot.zfsonlinux.org/builders/centos-7.0-x86_64-builder/builds/1817/steps/shell_17/logs/stdio
http://buildbot.zfsonlinux.org/builders/fedora-18-x86_64-builder/builds/2996/steps/shell_17/logs/stdio
http://buildbot.zfsonlinux.org/builders/fedora-21-x86_64-builder/builds/920/steps/shell_17/logs/stdio

Commit @fd23720 (with my own Signed-off-by!) resolved a deadlock (#1988) by moving draining the iput taskq outside `z_teardown_lock`:
```
zpl_put_super
+ zfs_umount
  + zfs_sb_teardown
    + taskq_wait(dsl_pool_iput_taskq(dmu_objset_pool(zsb->z_os)));    # current
    + rrw_enter(&zsb->z_teardown_lock, RW_WRITER, FTAG);              # ZFS_ENTER blocked
    + taskq_wait(dsl_pool_iput_taskq(dmu_objset_pool(zsb->z_os)));    # original
```

With the drain outside this lock there's nothing to prevent further work being submitted between the `taskq_wait` and the `z_teardown_lock` being obtained, leading to the PANIC above if the taskq isn't empty by the time we're freeing resources in `zfs_sb_free`.

It seems the correct solution is to move the drain back inside `z_teardown_lock` and resolve the original deadlock some other way...

The `z_teardown_lock` is used in ZFS_ENTER/ZFS_EXIT to prevent further processes submitting work to ZFS whilst we're unmounting the filesystem. The only time `z_teardown_lock` is held for write (i.e. blocking ZFS_ENTER) is in `zfs_sb_teardown` above.

The original deadlock was caused by `dsl_pool_iput_taskq` calling `iput`:
```
taskq_dispatch(dsl_pool_iput_taskq..., (task_func_t *)iput, ...);
+ iput 
  + iput_final
    + write_inode_now(inode, 1);
      + writeback_single_inode( wbc.sync_mode == WB_SYNC_ALL ) 
        + __writeback_single_inode
          + do_writepages
            + zpl_writepages          # via a_ops->writepages
              + ZFS_ENTER             # deadlock
              + zpl_putpage
                + zfs_putpage
                  + ZFS_ENTER         # deadlock
```

The ZFS_ENTER in `zfs_putpage` was added in @4c837f0d, with the comment:
```
    It also adds the missing ZFS_ENTER()/ZFS_EXIT() macros which
    aren't strictly required due to the VFS holding a reference.
    However, this makes the code more consistent with the upsteam
    code and there's no harm in being extra careful here.
```

I.e. it seems there's no actual need for ZFS_ENTER in `zfs_putpage`.

`zpl_writepages` was added in @119a394:
```
static int
zpl_writepages(struct address_space *mapping, struct writeback_control *wbc)
{       
        znode_t         *zp = ITOZ(mapping->host);
        zfs_sb_t        *zsb = ITOZSB(mapping->host);
        enum writeback_sync_modes sync_mode;
        int result;     

        ZFS_ENTER(zsb);
        if (zsb->z_os->os_sync == ZFS_SYNC_ALWAYS)
                wbc->sync_mode = WB_SYNC_ALL;
        ZFS_EXIT(zsb);
        sync_mode = wbc->sync_mode;
        
        /*
         * We don't want to run write_cache_pages() in SYNC mode here, because
         * that would make putpage() wait for a single page to be committed to
         * disk every single time, resulting in atrocious performance. Instead
         * we run it once in non-SYNC mode so that the ZIL gets all the data,
         * and then we commit it all in one go.
         */     
        wbc->sync_mode = WB_SYNC_NONE;
        result = write_cache_pages(mapping, wbc, zpl_putpage, mapping);
        if (sync_mode != wbc->sync_mode) {
                ZFS_ENTER(zsb);
                ZFS_VERIFY_ZP(zp); 
                if (zsb->z_log != NULL)
                        zil_commit(zsb->z_log, zp->z_id);
                ZFS_EXIT(zsb);

                /*
                 * We need to call write_cache_pages() again (we can't just
                 * return after the commit) because the previous call in
                 * non-SYNC mode does not guarantee that we got all the dirty
                 * pages (see the implementation of write_cache_pages() for
                 * details). That being said, this is a no-op in most cases.
                 */
                wbc->sync_mode = sync_mode;
                result = write_cache_pages(mapping, wbc, zpl_putpage, mapping);
        }
        return (result);
}
```

It's not clear to me why the first ZFS_ENTER instance is there. Perhaps to protect against `z_os` disappearing? However `zpl_writepages` is either being called before we start to unmount or it's being called as part of the final cleanup before we unmount, i.e. `z_os` is always valid. I think this first ZFS_ENTER can be safely removed.

We can see from the `iput` call chain above, `zpl_writepages` is called with `wbc->sync_mode == WB_SYNC_ALL`. This means we get into the `if (sync_mode != wbc->sync_mode)` section of `zpl_writepages` where we hit the second ZFS_ENTER protecting the `zil_commit`. However following this, we change the sync mode back to WB_SYNC_ALL and call `write_cache_pages` again, which also does a `zil_commit` (via the `zfs_putpage` where we've also removing ZFS_ENTER):
```
write_cache_pages
  zpl_putpage
    zfs_putpage
      if (wbc->sync_mode != WB_SYNC_NONE)
        zil_commit
```

I.e. I think the second `ZFS_ENTER`, and the `zil_commit` it's protecting, can be removed.

Overall, ZFS_ENTER is used to protect against further activity being added to our file system whilst we're tearing it down. It shouldn't be used to prevent "in progress" work being completed, e.g. that being finished off by the iput taskq.

At least that's what I think. It would be good to get some other eyes on this!

### PR DESCRIPTION
**Pull request by chrisrd**
By the time we're tearing down our superblock the VFS has started releasing all our inodes/znodes. Some of this work may have been handed off to our iput taskq so we need to wait for that work to complete. However the iput from the taskq can itself result in additional work being added to the taskq:
```
dsl_pool_iput_taskq
 iput
  iput_final
   evict
    destroy_inode
     zpl_inode_destroy
      zfs_inode_destroy
       zfs_iput_async(ZTOI(zp->z_xattr_parent))
        taskq_dispatch(dsl_pool_iput_taskq..., iput, ...)
```

Let's wait until all our znodes have been released.

Signed-off-by: Chris Dunlop <chris@onthe.net.au>
Closes #3281

### CODE REVIEW

**Comment by chrisrd** [comment]
The one failing buildbot is due to #3304

**Comment by chrisrd** [comment]
The idea behind the `schedule()` was to avoid spinning in a tight loop if `z_nr_znodes` isn't yet zero and the iput taskq hasn't yet had a chance to run. Although, if my analysis is correct and there's only ever a need to wait on the iput taskq twice (the first round clears everything it can, but adds parents of dir-based xattrs to the iput taskq, the second round takes them off and never adds more because you never have xattrs on xattrs) then the schedule isn't needed because we're guaranteed to have the parents already in the taskq by the time we've done waiting the first time. In fact, rather than a `while` loop, the code could be (suitably commented):

```
if (zsb->z_os) {
        taskq_wait(dsl_pool_iput_taskq(dmu_objset_pool(zsb->z_os)));
        /*      
         * Iputs run from the taskq may have put the parents of
         * dir-based xattrs into the taskq: wait for these
         */     
        if (zsb->z_nr_znodes > 0) 
                taskq_wait(dsl_pool_iput_taskq(dmu_objset_pool(zsb->z_os)));
}
```

That would also resolve the `unmounted == TRUE` issue as we're not then spinning waiting for `z_nr_znodes` to fall to zero.

What do you think?

**Comment by behlendorf** [comment]
That sounds reasonable, I like this patch much better.  If we can avoid looping so much the better.

**Comment by chrisrd** [comment]
How's that?

**Comment by behlendorf** [comment]
@chrisrd better, although everything failed due to the ASSERT which is interesting.  My guess is either the root inode is still around or possible additional passes are required to free the xattrs.

**Comment by chrisrd** [comment]
Pushing @492aece to test an alternative to waiting for `z_nr_znodes` to fall to zero just so we can safely destroy the `z_all_znodes` list: rip these out altogether. The previously proposed change to wait until `z_nr_znodes` falls to zero left `zpl_nr_cached_objects()` and `zfs_resume_fs()` as the only places the `z_nr_znodes`/`z_all_znodes` infrastructure was used at all.

`zpl_nr_cached_objects()` could or should be removed anyway, according to @dweeezil in https://github.com/zfsonlinux/zfs/pull/3308#issuecomment-94287976.

That leaves only `zfs_resume_fs()`, and calling `zfs_rezget()` for what was each entry in `z_all_znodes`. For this test I've just ripped this out. But perhaps we should do the `zfs_rezget()` via iterating `sb->z_sb->s_inodes`?

**Comment by behlendorf** [comment]
@chrisrd completely removing this list is a bit of cleanup I've long been wanting to tackle!  I'm all for it but it's going to take a little care.  You've made a good start of this though so I'll make some comments inline with your patch.

**Comment by chrisrd** [comment]
I've put the `z_all_znodes` removal (#3296) aside for the moment, and going back to the original concept. 

I wasn't able to get the ASSERT failure with @02f7bab3 in my own testing that the buildbots were getting, so I've pushed the same thing again with some added debug logging (@2dbfa6c).

For the record these were the previous ASSERT failures with @02f7bab3 (is there any way of seeing this via github, other than recording it like this?):

* [fedora-18-x86_64-builder build 3084 ] (http://buildbot.zfsonlinux.org/builders/fedora-18-x86_64-builder/builds/3084)
* [fedora-19-x86_64-builder build 3103 ] (http://buildbot.zfsonlinux.org/builders/fedora-19-x86_64-builder/builds/3103)
* [fedora-20-x86_64-builder build 3142 ] (http://buildbot.zfsonlinux.org/builders/fedora-20-x86_64-builder/builds/3142)
* [fedora-21-x86_64-builder build 1015 ] (http://buildbot.zfsonlinux.org/builders/fedora-21-x86_64-builder/builds/1015)
* [ubuntu-12.04-amd64-builder build 2918 ] (http://buildbot.zfsonlinux.org/builders/ubuntu-12.04-amd64-builder/builds/2918)
* [ubuntu-12.10-amd64-builder build 3107 ] (http://buildbot.zfsonlinux.org/builders/ubuntu-12.10-amd64-builder/builds/3107)
* [ubuntu-13.04-amd64-builder build 3046 ] (http://buildbot.zfsonlinux.org/builders/ubuntu-13.04-amd64-builder/builds/3046)
* [ubuntu-13.10-amd64-builder build 3031 ] (http://buildbot.zfsonlinux.org/builders/ubuntu-13.10-amd64-builder/builds/3031)
* [ubuntu-14.04-amd64-builder build 2605 ] (http://buildbot.zfsonlinux.org/builders/ubuntu-14.04-amd64-builder/builds/2605)
* [ubuntu-14.04-amd64-current-builder build 2507 ] (http://buildbot.zfsonlinux.org/builders/ubuntu-14.04-amd64-current-builder/builds/2507)

**Comment by behlendorf** [comment]
@chrisrd with the updated patch you never ever be able to trigger that ASSERT since you'll always wait enough rounds.  And according to the buildbot log the worst case ever observed here was just three rounds which sounds about right.

I think the patch is in good shape and is almost ready to be merged.  It's a nice, safe, minimal change which closes this possible race.  If you could just drop the debug code, rebase on master, and re-push the patch we can get one more test run before merging it.

**Comment by chrisrd** [comment]
@behlendorf 4 rounds actually (counting from zero). Patch modified as suggested, rebased, and pushed.

I'm a bit concerned because I don't understand why two rounds (the second to clean up xattr parents) aren't sufficient as previously proposed. Any ideas?

**Comment by behlendorf** [comment]
Round 0 - iput() on the child xattr inode
Round 1 - iput() on the parent xattr directory inode
Round 2 - iput() on the file inode itself for this xattr directory
Round 3 - This one I'm not sure about, maybe we're off by 1 somewhere?

**Comment by chrisrd** [comment]
@behlendorf Whilst I haven't investigated, your round 2 explanation sounds reasonable. The mystery round 3 is a concern, but I don't think it's a barrier to this patch going in.

**Comment by behlendorf** [comment]
@chrisrd agreed.  As long as the testing comes back clean I'll get this merged.  It's probably better to structure this as a while loop anyway because if the maximum depth ever increases at some point it will be automatically handled.

**Comment by chrisrd** [comment]
@behlendorf "if the maximum depth ever increases"... looks like you're not the first to consider that! I just noticed in `zfs_lookup()`:
```
        if (flags & LOOKUP_XATTR) {
                /*
                 * We don't allow recursive attributes..
                 * Maybe someday we will.
                 */
                if (zdp->z_pflags & ZFS_XATTR) {
                        ZFS_EXIT(zsb);
                        return (SET_ERROR(EINVAL));
                }
```

[This thread] (http://thread.gmane.org/gmane.os.illumos.zfs/4771/focus=4806) has some `taskq_wait` stuff of some relevance to this pull request (also directly related to #3254 / @0c66c32, but it seems we're safe there).

What do you think of the `taskq_wait_empty` approach in #3379 / @ffbf646cb, on top of this current pull request? Of course it doesn't mean we can do away with looping on `z_nr_znodes` unless we work out exactly what's going on there, but it should be interesting to see what the debug logging spits out.

**Comment by chrisrd** [comment]
The debug logging reveals the buildbots don't exercise the `!unmounting` case at all. A `recv -F` does that for us, which then leads us to #3380.

What's the best way to add some tests along the lines of the script in #3380 to the buildbots?
* add it to `zconfig.sh`? It seems that script is for basic sanity checks rather than anything that could/should evolve to something more comprehensive
* create another test script in `scripts`? How to add it to the buildbots?
* expand `xfstests`? It looks like we might be running a custom version, where is it?

**Comment by behlendorf** [comment]
I doubt recursive attributes will ever happen, but they might.  Who knows.

> What do you think of the taskq_wait_empty approach.

Are you sure illumos taskqs behave this way?  When I implemented them I based it on the man page description of the behavior.  If we've gotten the actual semantics wrong then I'd be inclined to get them right rather than add an interface none of the other implementations have (although we have already done some of this).

"The ddi_taskq_wait() function waits for all previously scheduled tasks to complete. Note that this function does not stop any new task dispatches." - [ddi-taskq-wait-9f](http://docs.oracle.com/cd/E23824_01/html/821-1477/ddi-taskq-wait-9f.html)

> What's the best way to add some tests along the lines of the script in #3380 to the buildbots?

The right thing to do would be to get the zfs-test suite integrated with the buildbot.  Which remains a ton of work.

The easy thing to do would be to add `zfs rollback` to the command runs by the zfsstress test @nedbass put together.  This scripts can be found here and you can open a pull request.  Arguably all the various test scripts should be pulled in to the organizations repository and cleaned up.

https://github.com/nedbass/zfsstress

As for this patch as it stands it appears to have passed testing and is a good first step.  Are you OK with merging it as it is and taking it from there?

**Comment by chrisrd** [comment]
Yup, happy for merging as is.

[The thread mentioned above] (http://thread.gmane.org/gmane.os.illumos.zfs/4771/focus=4806) talks about the Illumos `taskq_wait`:

> But reading the code I'd state the function of taskq_wait more like: taskq_wait() waits until no more tasks are scheduled and all running tasks finished. It would only be a problem if anyone would schedule a task after all running tasks have finished, but that doesn't happen as we always schedule new tasks from within running tasks.
> 
> The code in taskq_wait looks like this:
```
mutex_enter(&tq->tq_lock);
while (tq->tq_task.tqent_next != &tq->tq_task || tq->tq_active != 0)
        cv_wait(&tq->tq_wait_cv, &tq->tq_lock);
mutex_exit(&tq->tq_lock);
```

That definitely looks like it's looping until the taskq empties, and I've confirmed current Illumos still does that. Given that `ddi_taskq_wait` is nothing more than a wrap around `taskq_wait`, it definitely looks like the docs are inaccurate about it's behaviour.

**Comment by behlendorf** [comment]
Merged as:

f0da4d1 Wait for all znodes to be released before tearing down the superblock

About the taskq behavior that sort of thing might result in us accidentally introducing a but going forward.  I wonder what the impact of always blocking until the queue is empty would do to performance.

**Pull request closed without merging**
