### PR TITLE
zfs-0.7.13 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
zfs-0.7.13 proposed patchset

### Description
These are the proposed 0.7.13 fixes.  This will get ZFS building again under Fedora 29.  It's also up-to-date with the  current Fedora 30 (rawhide) builds, but can't be totally built and loaded due to https://github.com/zfsonlinux/zfs/issues/8360 and https://github.com/zfsonlinux/zfs/issues/8329.  

We may want to wait on releasing 0.7.13 until https://github.com/zfsonlinux/zfs/issues/8360 is fixed.  

Also, I'd be nice if ZFS folks would review and test https://lore.kernel.org/lkml/20190123173707.GA16603@gmail.com/ under GCC 9.0 so that we can get https://github.com/zfsonlinux/zfs/issues/8329 fixed in the kernel.  This is preventing all kernel modules from building under GCC 9.0.  

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
I might have missed it but it looks like #8227 is missing from this PR.

**Comment by tonyhutter** [comment]
@behlendorf it's in the SPL PR (https://github.com/zfsonlinux/spl/pull/713)

Looks like I have the wrong format for my Requires-spl line though... let me fix that.

**Comment by tonyhutter** [comment]
Looks like I need to fix some style warnings from missing test-runner.py patches:
http://build.zfsonlinux.org/builders/Ubuntu%2017.10%20x86_64%20%28STYLE%29/builds/11413

**Comment by beren12** [comment]
could we also squeeze https://github.com/zfsonlinux/zfs/pull/8447 into 0.7.13?

**Comment by tonyhutter** [comment]
@beren12 I'll mark it for the next release.  However since #8447 is still under review, and hasn't had any soak time in master yet, it's most likely going to go into 0.7.14 or 0.8.0.

**Pull request closed without merging**
