### PR TITLE
Fixes for spurious failures of resilver_restart_001 test

### LINKED ISSUE #9677: resilver_restart_001 intermittently fails
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15
Architecture	| x86
ZFS Version	| 5a089773
SPL Version	| 

### Describe the problem you're observing
resilver_restart_001 fails sometimes, possibly a race in verify_restarts()

### Describe how to reproduce the problem
The test fails intermittently.

### Include any warning/errors/backtraces from the system logs
```
04:11:20.87 NOTE: expected 1 resilver start(s) after offline/online, found 1
04:11:22.08 Added handler 59 with the following properties:
04:11:22.08   pool: testpool
04:11:22.08   vdev: 8f34acbcad36f507
04:11:22.08 SUCCESS: zinject -a -d /var/tmp/file-3 -e io -T read -f 0.25 testpool
04:11:23.46 removed all registered handlers
04:11:23.46 SUCCESS: zinject -c all
04:11:23.48 NOTE: expected 1 resilver start(s) after zinject, found 1
04:11:27.93 SUCCESS: zpool sync testpool
04:11:27.94 NOTE: expected 2 resilver start(s) after resilver, found 1
04:11:27.94 expected 2 resilver start(s) after resilver, found 1
04:11:27.95 NOTE: Performing test-fail callback (/usr/share/zfs/zfs-tests/callbacks/zfs_dbgmsg.ksh)
```

### PR DESCRIPTION
**Pull request by Ornias1993**
This opens a PR on the fix by @jwpoduska for reference and testing purposes.
If he wants to open another himself i'll close this one.

Signed-off-by: John Poduska <jpoduska@datto.com>
Closes #9677

### Motivation, Context and Description
 Two issues were found:
- The event log wasn't large enough, so resilver events were missing
- One 'zpool sync' wasn't enough for resilver to start after zinject

- Also include some grammar fixes for comments.

For more information see:
Issue: #9677

### How Has This Been Tested?
Not yet

### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [X] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [X] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [X] I have updated the documentation accordingly.
- [X] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [X] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [X] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by jwpoduska** [comment]
Yup, why don't you close this, it seems like bad form.

**Comment by Ornias1993** [comment]
> If he wants to open another himself i'll close this one.

I don't care about "form", if you open one i'll ofc close thsi one...

**Comment by jwpoduska** [comment]
Perhaps I'm doing something wrong, but it seems that github won't let me create a new PR with this one open.

**Comment by Ornias1993** [comment]
Strange, i'll look into that one day...

**Comment by behlendorf** [comment]
@Ornias1993 actually because of how Github handles PR metadata it's logistically helpful to the maintainer if they're opened by the original author.  Otherwise, the "Author" field in the commit will be set incorrectly when merging through the web interface.  As long as the original author is still active it's best to let them open the PR.

**Pull request closed without merging**
