### PR TITLE
Dummy for spl 569

### PR DESCRIPTION
**Pull request by tuxoko**
Signed-off-by: Chunwei Chen <david.chen@osnexus.com>
Requires-spl: refs/pull/569/head

### CODE REVIEW

**Comment by behlendorf** [comment]
I suspect this change might actually be causing the [CentOS 6.7 failure](http://build.zfsonlinux.org/builders/CentOS%206.7%20x86_64%20%28TEST%29/builds/2617).  I'll resubmit the build and see if it's reproducible.

**Comment by tuxoko** [comment]
@behlendorf 
That's not possible. The original `#include <linux/uidgid.h>` doesn't include anything because it's indirectly included, so removing it won't change anything. Otherwise, it wouldn't build at all.

**Comment by tuxoko** [comment]
Not to mention the code won't get compiled in CenOS 6.7

**Comment by behlendorf** [comment]
Indeed.  It does appear to be an unrelated testing failure caused by ec2 and the buildbot.  Great, then we'll get a clean test run next time.

**Comment by behlendorf** [comment]
Closing, patch merged to the SPL.

**Pull request closed without merging**
