### PR TITLE
Fix module/avl/avl.c warning: ‘where’ may be used uninitialized in this function

### PR DESCRIPTION
**Pull request by kernelOfTruth**
add correct

avl_insert(tree, new_node, where);

to

avl_insert(tree, new_node, &where);

in module/avl/avl.c

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/issues/3609

**Comment by drescherjm** [comment]
In my opinion this is not the correct fix. avl_insert does not take a pointer like avl_find.

**Comment by kernelOfTruth** [comment]
@drescherjm in that case illumos-gate is incorrect ?

https://github.com/illumos/illumos-gate/search?utf8=%E2%9C%93&q=avl_insert%28tree%2C+new_node%2C+where%29%3B

**Comment by behlendorf** [comment]
We __don't__ differ here from illumos and `where` is being passed correctly.  What gcc is almost certainly upset about is that it's possible for `avl_find()` to return without setting `where` leaving it undefined.  The right fix here is to initialize it prior to the calling `avl_find()` like this.

```diff
diff --git a/module/avl/avl.c b/module/avl/avl.c
index abf74bf..86183fe 100644
--- a/module/avl/avl.c
+++ b/module/avl/avl.c
@@ -630,7 +630,7 @@ avl_insert_here(
 void
 avl_add(avl_tree_t *tree, void *new_node)
 {
-       avl_index_t where;
+       avl_index_t where = 0;
 
        /*
         * This is unfortunate.  We want to call panic() here, even for
```

**Comment by behlendorf** [comment]
Closing.  This is not the correct fix.

**Pull request closed without merging**
