### PR TITLE
resource leak with CID 147609-06

### PR DESCRIPTION
**Pull request by heary-cao**
issues:
fix coverity defects
coverity scan CID:147609, Type:resource leak
coverity scan CID:147606, Type:resource leak

Signed-off-by: cao.xuewen <cao.xuewen@zte.com.cn>

### CODE REVIEW

**Comment by rlaager** [comment]
The close(devnull) changes are only okay because zed_log_die() calls exit(). Another option might be to annotate zed_log_die() with a /* coverity[+kill] */ comment.

**Comment by behlendorf** [comment]
@rlaager I'm not sure that marking `zed_log_die()` as a killpath will resolve the issue.  I assume `exit()` is marked as such by default and it's called by `zed_log_die()`.  But maybe not.  @ColinIanKing we could look in to uploading a modeling file to the Coverity analysis to try and address this entire class of issue.

**Comment by ColinIanKing** [comment]
On 11/10/16 20:18, Brian Behlendorf wrote:
> @rlaager <https://github.com/rlaager> I'm not sure that marking
> |zed_log_die()| as a killpath will resolve the issue. I assume |exit()|
> is marked as such by default and it's called by |zed_log_die()|. But
> maybe not. @ColinIanKing <https://github.com/ColinIanKing> we could look
> in to uploading a modeling file to the Coverity analysis to try and
> address this entire class of issue.

+1 On the modeling file. I'll try and figure out how to do this sometime
in the next few weeks.

Colin

**Comment by behlendorf** [comment]
@ColinIanKing I'd suggest starting by adding `exit()`, `zed_log_die()`, `panic()` as killpaths first and see where we're at.

**Comment by ColinIanKing** [comment]
On 11/10/16 20:18, Brian Behlendorf wrote:
> @rlaager <https://github.com/rlaager> I'm not sure that marking
> |zed_log_die()| as a killpath will resolve the issue. I assume |exit()|
> is marked as such by default and it's called by |zed_log_die()|. But
> maybe not. @ColinIanKing <https://github.com/ColinIanKing> we could look
> in to uploading a modeling file to the Coverity analysis to try and
> address this entire class of issue.

I've uploaded an appropriate modeling files for zfs and spl and re-run
the analysis but it didn't make any difference.

Colin

**Comment by behlendorf** [comment]
Merged without the zed changees.  @ColinIanKing thanks for trying the modeling file.

**Pull request merged**
