### PR TITLE
(#4203) zvol logical block size should be the same as physical block size

### PR DESCRIPTION
**Pull request by kpande**
This is just a quick implementation of #4203

Signed-off-by: Kash Pande kash@tripleback.net

### CODE REVIEW

**Comment by kpande** [comment]
@behlendorf looks like this change is not so trivial

**Comment by behlendorf** [comment]
@kpande apparently not.  Here's the [stack](http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20x86_64%20%28TEST%29/builds/3863/steps/shell_7/logs/console) for reference and further investigation when someone has time.

**Comment by kpande** [comment]
@behlendorf this change is definitely necessary though

**Comment by behlendorf** [comment]
@kpande if we're going to allow for the logical block size to be something other than 512 we'll want to make it configurable.

**Comment by sempervictus** [comment]
@behlendorf: we use the original patch provided on a number of systems with no issue. Agreed that its something we want to make configurable, but this _should_ get upstreamed, just as a tunable with safe defaults.

**Comment by sempervictus** [comment]
Poking around at how options are handled, i guess this would be most flexible as an attribute per ZVOL, something along the lines of _vollogsize_ to match _volblocksize_...? Have it set 512 as a default, or mirror volblocksize, and allow tuning on the fly since we can't adjust the actual blocksize, but we can adjust how we present it at the logical tier if need be (when switching iSCSI targets for instance)

**Comment by kpande** [comment]
i'm not able to do that kind of development, though I can test anything that is submitted..

**Comment by kpande** [comment]
@dweeezil maybe you can look into how much work this would be to implement :+1:

**Comment by behlendorf** [comment]
@kpande @sempervictus is there any way to configure the various iSCSI targets such that they honor the specified `/sys/block/<dev>/queue/optimal_io_size`?  This really is the intended interface for a block device to advertise to consumers the optimal I/O size to use for sustained performance.  We're setting this to the internal ZFS block size already, and it has advantage of keeping the logical block size set to 512 for maximum compatibility.

Also do you happen to know if the various ISCSI targets frequently close and then reopen the ZVOL?  This currently results in all buffers for the ZVOL being dropped from the ARC which wouldn't be good for performance.

**Comment by sempervictus** [comment]
Iscsi targets generally don't release volumes at runtime, but I could see something like cinder being used to grab and release them, rotating them around consumer VMS. Not the most common case... It also depends on how the source devices are used in that you can retain hold of a backing dev after removing its export. I see lio under cinder reference backing stores even after removing the iscsi target export, though not sure of the lock state at that point.

I believe lio exports at the logical block size by default, whereas scst needs manual config (and throws stack traces under heavy sync load from initiators so can't be used in prod to back RAC ASM and the like). I'll check into the lio bit this evening.


-------- Original Message --------

**Comment by kpande** [comment]
i've never seen that scenario, once LIO or IET grab onto the ZVOL it doesn't give it up until an admin or script detaches it

the concern is that modifying multiple iscsi targets is going to be harder than making the logical block size tunable.

**Comment by kpande** [comment]
@sempervictus I'm using LIO (as was the original poster in #4203) and the reason I opened this PR was to test the change since I require a certain block size to be available to Windows for MSSQL.

**Comment by sempervictus** [comment]
@kpande: AFAIK targets won't allow more than 4k today... I believe I tried 8k before on lio and didn't get the results I'd hoped for.

-------- Original Message --------

**Pull request closed without merging**
