### PR TITLE
Test stabilization patches for 0.7.0 rc5 and current builder configs [WIP]

### PR DESCRIPTION
**Pull request by ofaaland**
### Description

A collection of patches that address current build and test issues.   Pushed to test combined success in the automated tests and check for other failures hidden by issues addressed via these patches.

### Motivation and Context

Currently PRs trigger frequent failures in the automated testers even without any code change.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by dinatale2** [comment]
@ofaaland Looks like the CentOS 7 Mainline Builder failed. Appears to be due to issue #5396.

**Comment by dinatale2** [comment]
@ofaaland I produced a patch for `zfs_mount_001_neg` which is failing on the Ubuntu 17.04 TEST builder. Not sure if it will fix it or not, but if you want to give it a shot, it's there.

https://github.com/dinatale2/zfs/commit/d0942e6fd578a14d891378e6c1db9aaaf46e9ffa

**Comment by dinatale2** [comment]
Rerunning CentOS 7 Mainline (ztest failed for known issue), Fedora 26 (ran out of disk space), and Ubuntu 17.06 (failed zfs_mount_001_neg).

**Comment by ofaaland** [comment]
On second try of fedora26/centos7mainline/ubuntu1706:
* Fedora 26 and Centos 7 Mainline both ran out of space
* Ubuntu 17.06 failed three ZTS tests
** events_001_pos
** events_002_pos
** zvol_misc_002_pos

**Comment by dinatale2** [comment]
@ofaaland The `zvol_misc_002_pos` failure is due to a change in error codes from `fsck`. PR #6350 has a fix for that if you want to cherry pick it. 

I'm looking into the event tests now to see if I can figure out what is going on.

**Comment by ofaaland** [comment]
Failures on third pass:
* fedora26 out of space
* Ubuntu 17.04 events{1,2}

**Comment by ofaaland** [comment]
Fourth pass only Fedora 26 builder failed, after rsend_020_pos PASSed.  I'm unable to tell what caused the failure - there were no ENOSPC or similar messages as with prior Fedora failures.

**Comment by ofaaland** [comment]
I haven't figured out why the `vdev_probe()` change would cause ztest failures, but I learned a little more about the config locks involved and I believe it explains why the problem appeared with MMP and suggests that the `vdev_probe()` patch is the wrong fix.

The ZIO pipeline takes and releases `SCL_ZIO` if `ZIO_FLAG_CONFIG_WRITER` is not set:
```
module/zfs/zio.c=zio_vdev_io_start(zio_t *zio)
--
module/zfs/zio.c-               if (!(zio->io_flags & ZIO_FLAG_CONFIG_WRITER))
module/zfs/zio.c:                       spa_config_enter(spa, SCL_ZIO, zio, RW_READER);
--
module/zfs/zio.c=zio_vdev_io_assess(zio_t *zio)
--
module/zfs/zio.c-       if (vd == NULL && !(zio->io_flags & ZIO_FLAG_CONFIG_WRITER))
module/zfs/zio.c:               spa_config_exit(zio->io_spa, SCL_ZIO, zio)
```

and indeed there are many, many calls to `zio_nowait()` in the code.  I looked at several, and their callers, and callers callers, etc., and found them to take no config locks at all.

Note that `zio_vdev_io_asses()` is a later stage than `zio_vdev_io_done()` and so the `vdev_probe()` call is under the `SCL_ZIO` lock.

On the other hand, `ZIO_FLAG_CONFIG_WRITER` is required by an assert in `vdev_label_write()`; and code involved in configuration or vdev state changes all take config locks directly or through a convenience function like `spa_vdev_state_enter()`.  These wait, usually via `txg_wait()` calls.

And finally, `vdev_uberblock_sync()` makes a series of `vdev_label_write()` calls and then uses `zio_wait()`.

So I suspect that all the existing code that issues async I/Os either does not write to the label, and so the pipeline takes care of the locking for it without a waiter; or it writes to the label and so blocks in some manner, although not necessarily a waiter attached to the zio.

I propose that the correct fix is to revert your `vdev_probe()` patch and exit `SCL_STATE` in `mmp_write_done()`.

**Comment by ofaaland** [comment]
See #6394 for MMP locking fix PR.

**Comment by dinatale2** [comment]
I think the `rsend` test problems are due to issues in cleanup similar to the `zfs_mount_011_neg` test case. I'm thinking of going thru all the `rsend` test cases and fixing all the cleanup functions.

Also, I haven't seen the `events` test cases fail since you introduced the increase in the delay before collecting the zed log. Have you seen any failures since then?

**Comment by behlendorf** [comment]
Closing.  Test cases fixes have been merged to master and #6394 contains the MMP locking fix PR.

**Pull request closed without merging**
