### PR TITLE
[ABD2] git-rebase of #3441 ABD: linear/scatter dual typed buffer for ARC (ver 2)

### PR DESCRIPTION
**Pull request by kernelOfTruth**
This is the rebase on the current zfs master (December 11th 2015) to

make sure that all build or other issues are caught by the buildbot.

In https://github.com/zfsonlinux/zfs/pull/3441 on the last force push the buildbot

seemingly didn't work correctly ...

### CODE REVIEW

**Comment by tuxoko** [comment]
oops, didn't update assertion.

**Comment by kernelOfTruth** [comment]
updated & force-pushed to reflect the latest state and commits from

https://github.com/tuxoko/zfs/commits/abd2

https://github.com/zfsonlinux/zfs/pull/3441 ABD: linear/scatter dual typed buffer for ARC (ver 2)

**Comment by kernelOfTruth** [comment]
@behlendorf Is it possible for the buildbots not to bail out if they encounter "only" style errors ?

I mean, what prevents them to do the (TEST) after the (BUILD) tests afterward ?

This also would save an additional run and help to see whether there are more problems besides style

**Comment by behlendorf** [comment]
They don't bail out after trivial errors.   Every commit is built but only the top one has all the tests run against it.   See the README in https://github.com/zfsonlinux/zfs-buildbot for details.

**Comment by kernelOfTruth** [comment]
@behlendorf thanks for the clarification - alright, so "best" practice (in special cases) to find out issues is to make commits independent from each other and gradually push them so each of them has the (TEST)s run

It's rather strange that the (TEST) buildbots haven't run against the latest commit "Fix wrong assertion after the sg merge patch" or at least it wasn't indicated

**Comment by behlendorf** [comment]
@kernelOfTruth they should have run but it seems buildbot still has some rough edges integrating with ec2 so it's not 100% reliable.  Hopefully we'll get those worked out.

**Comment by kernelOfTruth** [comment]
Force-updating - addressing

```
./module/zfs/abd.c: 738: unparenthesized return expression
./module/zfs/abd.c: 790: unparenthesized return expression
```

for ```EFAULT``` to ```(EFAULT)``` in https://github.com/kernelOfTruth/zfs/commit/c307adcd8d008342009dac604632bdca94172698 Add access_ok check before __copy_{to,from}_ user_inatomic

this hopefully lets the commits pass and continue with the tests :+1:

**Comment by kernelOfTruth** [comment]
Come on !

Build bots, pretty please test the last commit, too :/

**Comment by kernelOfTruth** [comment]
closing

**Pull request closed without merging**
