### PR TITLE
Arc summary draft v2

### PR DESCRIPTION
**Pull request by p4tino**
I amended the issues which were brought in my previous pull request and modified the output to ignore pages.

### CODE REVIEW

**Comment by nedbass** [comment]
Please squash the last 3 commits into earlier commits.

**Comment by p4tino** [comment]
Alright, good for another review. I merged the three commits recommended, and I implemented _tunable_summary() in place of _sysctl_summary().

**Comment by nedbass** [comment]
Looks good to me other than the minor commit message issue in a42ae69.

**Comment by nedbass** [comment]
Looks like you have some trailing whitespace to clean up.

**Comment by nedbass** [comment]
Also `_system_memory` is dead code and should be removed.

**Comment by p4tino** [comment]
I'm looking at _system_memory, where in the patch stack should I remove the code? There doesn't appear to an obvious commit where that happened, should I just create a new one?

**Comment by nedbass** [comment]
You could either squash it into 'enable l2arc stats' since that's where it gets disabled (and which could use a better commit message).  Or you could do it in a separate patch.  Your call.

**Comment by p4tino** [comment]
@nedbass Alright, ready for the next round. A few notes, I removed _system_memory in 'enable l2arc stats', and modified the commit message.
I modified error handling on the /sbin/modinfo call so that it responds to command return codes.I kept the try-except block in to catch other Popen errors which may arise.

**Comment by nedbass** [comment]
Looks good to me. :+1:

**Comment by behlendorf** [comment]
@p4tino Almost there.  I pulled the latest branch and did some basic testing and discovered long opts aren't handled despite being listed in the help.  Please add support for all the listed long opts (--help, etc), the other python scripts accomplish this as follows:

```diff
@@ -1119,7 +1119,7 @@ def main():
             args['d'] = True
         if opt == '-p':
             args['p'] = arg
-        if opt == '-h':
+        if opt in ('-h', '--help'):
             usage()
             sys.exit()
 ```

Also update the the --help output so it's formatted the same as the `arcstat.py -h` and `dbufstat.py -h` help.  Fix the capitalization, indentation, add a few examples.   Consistency is important, and really means a lot to the end user.

**Comment by p4tino** [comment]
@behlendorf Sorry, I was out yesterday. An update, I'm working on it but getopt makes it non-trivial to add long-form arguments. It should be done today.

**Comment by p4tino** [comment]
@behlendorf Alright, should be good for another review. I can't believe I forgot to implement long options.

**Comment by behlendorf** [comment]
Looking good, thanks @p4tino.  I've merged this as:

a485efc Merge branch 'arc_summary_draft_v2'
a644585 Replace sysctl summary with tunables summary.
65dc685 Force all lines to be 80 columns
6427f39 Add a help option with usage information
3bfc7f1 Refactor arc_summary to simplify -p processing
53dc113 Modified arc_summary.py to run on linux
edd5b80 Add arc_summary.py from FreeNAS

**Pull request closed without merging**
