### PR TITLE
Reinstate raw receive check when truncating

### PR DESCRIPTION
**Pull request by tcaputi**
This patch re-adds a check that was removed in 369aa50. The check
confirms that a raw receive is not occuring before truncating an
object's dn_maxblkid. At the time, it was believed that all cases
that would hit this code path would be handled in other places,
but that was not the case.

Signed-off-by: Tom Caputi <tcaputi@datto.com>

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ahrens** [comment]
> At the time, it was believed that all cases
that would hit this code path would be handled in other places,
but that was not the case.

Could you describe in the comment how we get into the case where this is not handled?

**Comment by kpande** [comment]
wasn't my test case added?

**Comment by tcaputi** [comment]
@ahrens I still don't have a reproducer, but my current theory is that this can happen if you write some data to the last block of a file and then later replace that data with zeros with compression on. I believe that this will cause the block to be replaced with a hole, even though its not technically a truncation. The receive side will still just get an aggregated DRR_FREE record that includes the hole, so without this check it will attempt to do a real truncation.

@kpande What test case? I'm sorry I don't remember.

**Comment by ahrens** [comment]
@tcaputi That makes sense.  The way you've described it sounds straightforward to reproduce.  Could you verify and then add a comment explaining this?  E.g. something like `Usually, the last FREE record will be at the maxblkid, because the source system sets the maxblkid when truncating.  However, if the last block was freed by overwriting with zeros and being compressed away to a hole, the source system will generate a FREE record while leaving maxblkid after the end of the FREE record.  In this case we need to leave the maxblkid as indicated in the OBJECT record, so that it matches the source system, so that the cryptographic hashes will match.`

**Comment by tcaputi** [comment]
@ahrens I will add the comment. I verified that this problem can occur, but i needed to use `pv` to slow down the zfs receive rate enough to ensure that a txg sync happened between the DRR_OBJECT record and the DRR_FREE record. I'm not sure how to add that to a ZTS test case.

**Comment by tcaputi** [comment]
For documentation, this is the script I  used to reproduce the issue:

```
zpool create -f pool sdb
echo password | zfs create -o compression=on -o encryption=on -o keyformat=passphrase pool/test

yes | dd of=/pool/test/yes.txt bs=128k count=4 iflag=fullblock
zpool sync pool
zdb -e -ddddddd pool/test 2
cat /dev/zero | dd of=/pool/test/yes.txt bs=128k seek=3 count=1 iflag=fullblock
zpool sync pool
zdb -e -ddddddd pool/test 2

zfs snap pool/test@1
zfs send -w pool/test@1 | pv -L 400 | zfs recv pool/recv
echo password | zfs mount -l pool/recv
```

**Comment by aabc123** [comment]
> but i needed to use `pv` to slow down the zfs receive rate enough to ensure that a txg sync happened between the DRR_OBJECT record and the DRR_FREE record

I'm generally using pv between send/receive as well when I've been hitting this.

**Pull request merged**
