### PR TITLE
for testing only - dbuf hash mutexes to dbuf hash rwlocks

### PR DESCRIPTION
**Pull request by ofaaland**
Change lock used to protect dbuf hash chains from mutexes to rwlocks.

### CODE REVIEW

**Comment by richardelling** [comment]
Can you address the goal for this change? In general, rw locks are more expensive (read: slower) than mutexes. If the goal is somehow related to performance, how you plan to test?

**Comment by ofaaland** [comment]
@richardelling, you're correct the goal is to improve performance.  I observed, via perf and lockstats, that the hash mutexes were among the most heavily contended locks.  This change would allow dbuf_find() calls to operate concurrently even on the same hash chain.

I agree it's not clear this change will help overall.  I'll first test with many concurrent threads all executing the same type of operation via ZPL (e.g. many concurrent creates, many concurrent mkdirs, etc.).  If there's a significant improvement there, then I'll work out a more thorough test plan and provide data.

**Comment by dracwyrm** [comment]
@ofaaland This is from a Windows 10 VM running on a ZVol

The first set of numbers is with the latest master branch of SPL and ZFS and these two Pull Requests:
https://github.com/zfsonlinux/zfs/pull/4316 (makes ZVols use dbuf) and https://github.com/zfsonlinux/zfs/pull/4272
```
   Sequential Read (Q= 32,T= 1) :  4766.097 MB/s
  Sequential Write (Q= 32,T= 1) :   321.523 MB/s
  Random Read 4KiB (Q= 32,T= 1) :   218.697 MB/s [ 53392.8 IOPS]
 Random Write 4KiB (Q= 32,T= 1) :   192.934 MB/s [ 47103.0 IOPS]
         Sequential Read (T= 1) :  1425.285 MB/s
        Sequential Write (T= 1) :   720.391 MB/s
   Random Read 4KiB (Q= 1,T= 1) :    35.600 MB/s [  8691.4 IOPS]
  Random Write 4KiB (Q= 1,T= 1) :    28.496 MB/s [  6957.0 IOPS]
```

The next set of stats is with the same two pull requests and yours added in. I ran the test several times in several ways, but random with 32 queues could not be improved. The Sequential 32 Queues was less than the previous stats, but increasing the threads to 10 fixed that. However, when there is only one queue, the results are very noticeable.
```
   Sequential Read (Q= 32,T=10) :  5204.053 MB/s
  Sequential Write (Q= 32,T=10) :  1675.636 MB/s
  Random Read 4KiB (Q= 32,T=10) :   239.984 MB/s [ 58589.8 IOPS]
 Random Write 4KiB (Q= 32,T=10) :   145.462 MB/s [ 35513.2 IOPS]
         Sequential Read (T= 1) :  1995.572 MB/s
        Sequential Write (T= 1) :  1177.909 MB/s
   Random Read 4KiB (Q= 1,T= 1) :    50.062 MB/s [ 12222.2 IOPS]
  Random Write 4KiB (Q= 1,T= 1) :    35.460 MB/s [  8657.2 IOPS]
```
Especially the writes. The first set of stats was run several times over a course of days and they average to around there. These stats were run several times as well.

I don't know if any of this helps, but I find it interesting. I have issues with 0.6.5 and above, so I'm looking for anything that reduces latency and overhead.

Cheers.

**Comment by behlendorf** [comment]
@dracwyrm additional testing results are always appreciated, and these are encouraging.  For posterity what kernel were you testing with?

I'll also second @richardelling's comment about in general rwsems being slower that mutexes.  But there are always exceptions and this may be one of those times, this lock has been observed to be highly contended and allowing concurrent readers would help.  @dracwyrm I ask specifically about the kernel version because in the 3.15 kernel the rwsem implementation was optimized to support optimistic spinning.  That's helped close the performance gap between mutexes and rwsems.   See torvalds/linux@4fc828e.

**Comment by ryao** [comment]
@richardelling While each invocation of `rwlock_enter()` is more expensive than `mutex_enter()`, a reduction in `dbuf_find()` latencies might make up for that under heavy load.

@dracwyrm In order for benchmark results to show that a change is is useful, numbers are needed for the before/after on each change thought to improve things. Otherwise, one that hurts performance could go by undetected. It is fine to benchmark HEAD, then HEAD + 1 PR, then HEAD + 2 PRs, then HEAD + 3 PRs rather than all 8 combinations though.

There would be some instances where the improvement from one change might lessen the improvement from another (e.g. switching from `dmu_read_uio_dbuf()` to `dmu_read_uio()` avoiding a dbuf_hold() that calls `dbuf_find()`), but it at least gives us some idea of whether something is a relative improvement or not.

You also should benchmark with the same number of threads in each instance. That said, those numbers suggest things are heading in the right direction.

**Comment by dracwyrm** [comment]
I used gentoo sources 4.4.1. I wanted to see if the audio drive has improved...

T means number of threads and Q means the number of queues
The second set of stats, the tests that have T=10 ended up being considerably slower than the first set of stats for the Q=32 part of the tests when the thread count was 1, so I raised it to 10, which helped sequential but not random. However, when both Q=1 and T=1, the patch in question just blows the first set of stats out of the water. I'm guessing because they are in the same hash, where 32 queues is causing more hashing on the ZFS side of things??? This is done in MS Windows so the test is opening up 32 queues of data to write to what Windows thinks is a real disk and is writing to the disk the way Windows does. How does ZFS see this? It must be computing something really heavy.

I had to use the PR to change ZVols to using dbuf because if I read this PR right, this makes everything using a dbuf use a different locking mechanism. If I didn't use the other PR then this patch would have no effect on ZVols as it stands in the current master branch, right?

I'll run some more tests tomorrow with and without this PR. And without the disable read ahead patch just to get a more baseline reading. If I don't need the other PR to make this patch work with ZVols, then I'll remove those patches as well. I won't remove them until I get work back if I understood this right.

I have done a lot of tracing on my system and for whatever reason, I have a high latency rate. Once data starts to flow, it's alright in speed, however it's the access to that data that takes a long time. It's something that the 0.6.4 branch didn't suffer from. Which is why I read a lot on these various PRs and test them out. I've been going through my kernel config and ZFS settings trying to find the cause for the latency. I even have a different between the latest 0.6.4 and the latest 0.6.5 branches that I will be studying. Though, the one thing that I read in this PR is that perf showed high mutex usage which is what I've seen.

**Comment by ryao** [comment]
@dracwyrm 

> If I didn't use the other PR then this patch would have no effect on ZVols as it stands in the current master branch, right?

No.

When I first read that question, I thought you were asking if #4316 made #4317 useless. The answer to that other question is no too. There are multiple places in the code that use `dbuf_find()`. The two places I changed are literally just two of them. If you generate a flame graph showing all places `dbuf_find()` is called, you would likely see the others. Here are some instructions:

https://wiki.gentoo.org/wiki/ZFSOnLinux_Development_Guide#Flame_Graph_of_all_threads_with_a_unique_name

Instead of doing `grep '^txg_sync;'`, do `grep 'dbuf_find'`. That would make the flame graph.

Anyway, each place where you see `dbuf_find()` in the flame graph is a place that would be affected by #4317. #4316 should eliminate two of them.

**Comment by dracwyrm** [comment]
Hi all,

Doing this testing, I think I found a bug/issue that needs to be reported.
I applied the "Disable Linux Read Ahead" patch to the master branch and it was the only patch. It hands down killed performance on all 8 tests that Crystal Disk Mark does. This patch makes it so that only the built in ZFS prefetch is doing all the prefetching. To me, this means that there is a regression in prefetching and could be the issue I am having with freezes and general poor performance with anything newer than 0.6.4.2.

Also, I had to switch LibVirt IO Mode to Threads instead of Native as Native mode would crash during most tests and was unusable most of the time.

All tests with 'perf top' results can be found here: [http://pastebin.com/d4YY8Z4r](url). The perf data does show that certain locks run a lot. Surprisingly, I only saw mutex locks when I had the rwlocks patch installed.

To pull out the highlights. As you can see, some patches enhance things and some hurt things. A mix of some would make things better. I did try to disable as much as possible, but Windows does like to do things randomly, so each test had to be done several times to ensure consistency. The disable Linux read ahead is at the end and you can clearly see how it killed Windows performance. I would like to run these tests more times over the course of days to see if anything changes. Though, I think I might start hitting the ceiling of performance of both Windows ability to write/read from disks and the speed of the raidz1 system.

This is what it's like to run Windows on a ZVol with these patches:
```
No patches
   Sequential Read (Q= 32,T= 1) :  5245.373 MB/s
  Sequential Write (Q= 32,T= 1) :   965.242 MB/s
  Random Read 4KiB (Q= 32,T= 1) :   232.358 MB/s [ 56728.0 IOPS]
 Random Write 4KiB (Q= 32,T= 1) :   108.694 MB/s [ 26536.6 IOPS]
         Sequential Read (T= 1) :  2008.880 MB/s
        Sequential Write (T= 1) :  1235.692 MB/s
   Random Read 4KiB (Q= 1,T= 1) :    52.201 MB/s [ 12744.4 IOPS]
  Random Write 4KiB (Q= 1,T= 1) :    37.170 MB/s [  9074.7 IOPS]

Mutex Patch
   Sequential Read (Q= 32,T= 1) :  5251.212 MB/s
  Sequential Write (Q= 32,T= 1) :   609.214 MB/s
  Random Read 4KiB (Q= 32,T= 1) :   229.724 MB/s [ 56085.0 IOPS]
 Random Write 4KiB (Q= 32,T= 1) :    97.676 MB/s [ 23846.7 IOPS]
         Sequential Read (T= 1) :  1969.386 MB/s
        Sequential Write (T= 1) :   636.785 MB/s
   Random Read 4KiB (Q= 1,T= 1) :    51.700 MB/s [ 12622.1 IOPS]
  Random Write 4KiB (Q= 1,T= 1) :    40.247 MB/s [  9825.9 IOPS]

Switch to DBuf
   Sequential Read (Q= 32,T= 1) :  5240.961 MB/s
  Sequential Write (Q= 32,T= 1) :   893.659 MB/s
  Random Read 4KiB (Q= 32,T= 1) :   227.680 MB/s [ 55585.9 IOPS]
 Random Write 4KiB (Q= 32,T= 1) :   115.130 MB/s [ 28107.9 IOPS]
         Sequential Read (T= 1) :  2135.028 MB/s
        Sequential Write (T= 1) :   286.042 MB/s
   Random Read 4KiB (Q= 1,T= 1) :    49.571 MB/s [ 12102.3 IOPS]
  Random Write 4KiB (Q= 1,T= 1) :    35.871 MB/s [  8757.6 IOPS]

Combined
   Sequential Read (Q= 32,T= 1) :  5389.725 MB/s
  Sequential Write (Q= 32,T= 1) :   735.086 MB/s
  Random Read 4KiB (Q= 32,T= 1) :   235.722 MB/s [ 57549.3 IOPS]
 Random Write 4KiB (Q= 32,T= 1) :    98.707 MB/s [ 24098.4 IOPS]
         Sequential Read (T= 1) :  1969.704 MB/s
        Sequential Write (T= 1) :  1083.438 MB/s
   Random Read 4KiB (Q= 1,T= 1) :    54.156 MB/s [ 13221.7 IOPS]
  Random Write 4KiB (Q= 1,T= 1) :    33.444 MB/s [  8165.0 IOPS]

Disable Linux Read Ahead
   Sequential Read (Q= 32,T= 1) :  4016.099 MB/s
  Sequential Write (Q= 32,T= 1) :   717.027 MB/s
  Random Read 4KiB (Q= 32,T= 1) :    98.832 MB/s [ 24128.9 IOPS]
 Random Write 4KiB (Q= 32,T= 1) :   107.077 MB/s [ 26141.8 IOPS]
         Sequential Read (T= 1) :  1951.540 MB/s
        Sequential Write (T= 1) :   988.623 MB/s
   Random Read 4KiB (Q= 1,T= 1) :    48.038 MB/s [ 11728.0 IOPS]
  Random Write 4KiB (Q= 1,T= 1) :    35.165 MB/s [  8585.2 IOPS]
```

All in all, I think I will not be using the Disable Linux Read Ahead patch anymore.

Are there any other tests you want done? I will try to do them.

For full disclosure, if you want to see how I modified the ebuilds to install the patches and use master branch, I will upload those as this is Windows I am posting from, I will need to do it from Linux later.

Cheers.

**Comment by dracwyrm** [comment]
Okay, I got tired of CrystalDiskMark's inconsistent results. So I found another program that measures the latency as well, so it's easier to tell what's going on. The results are a lot closer. They show that these patches don't have a large impact of a guest running on a ZVol which is the most used scenario for a ZVol.

Just a thought. Since modern mutex implementations tend to be by hybrid-mutexs, so sometimes spin-locks, sometimes atomic... Since a mutex now can be a middle man to a spin-lock and this is a testing PR, would it be good to try spin-locks instead of a mutex? Spin-locks are very cheap to call, more cheap than a mutex. If the data is a certain type (I forget), there are very basic to more complex spin-locks, so you might be able to get away with the cheapest one available.

I read that rwlocks tend to really shine in multi-core, multi-threaded code. Are the parts of ZFS that is using these locks multi-core and multi-threaded? A multi-threaded program running on one core will not see benefits of a rwlock, or even a mutex. Can all the code be made thread safe and multi-cored and multi-threaded? Would that help performance?

Anyways, the new tests don't export to a text file, so screenshots of the program are made and uploaded to an imgur album. These have the access times, which I feel are way too high, especially the write times. Is there any way to bring these times down?

[http://imgur.com/a/uLzRL](url)

Some surprising results in there. This PR tends to hurt performance a bit, but combining it with the convert to all dbuf calls of the other PR tends to do better than the other PR alone. Are those dbuf functions using the new rwlocks of this PR then? If so, then the combination along with all the other times rwlocks are used is a benefit???

Also, I switched back to a 4.1.17 kernel with ZFS 0.6.4.2. I tried both LibVirt IO Mode settings: Native and Threads. Native runs way better than Threads. So, using that same logic, 0.6.5.x and above should run better under Native mode than Threads mode. However, Native mode is slow and crashes. None of these patches fixed that. I need to trace down what is causing those crashes to see if Native mode will run faster for 0.6.5 and above.

Cheers.

**Comment by ryao** [comment]
@dracwyrm I have said in the past that your crash with "native" mode on zvols is likely because the zvols have become too fast for your Windows stack in 0.6.5. I still think that, but I should clarify that I am talking about the time between the request handler returning and the signal for request completion being sent, which is effectively zero as of 0.6.5.

Prior to 0.6.5, zvol_request would queue the IO for the zvol taskq (which only existed on Linux) and return. Anything blocked on it such as your Windows device driver l would only resume execution when this returns unless it has its own IO queue (which Indoubt in the case of virtue-blk). Then at some point, the taskq would send the IO to the DMU and blocks until the DMU returned. At this point, the taskq would call the function required to setup a completion. Anything above ZFS would see noticeable time between these events. In 0.6.5, this was changed to have zvol_request send the IO to the DMU, mark the IO as being finished and then return. The kernel should not send a completion earlier than the zvol_reqrst function's return. However, the effect is that the completion occurs instantaneously as far as the caller is concerned, which is the behavior other ZFS systems have. A consequence is that this could trigger bugs if any race conditions involving these two events are present in stack above the zvol. That is the only signficant behavior change between 0.6.4 and 0.6.5 and my guess is that your Windows stack has a bug of that nature. If that is what is happening, you should be able to use native mode with the loop device between the zvol and QEMU. Performance would suffer though. Another thing that might make the problem disappear is to try ACHI emulation instead of virtio-blk (which I recall you saying elsewhere that you use). In either case, you would get a request queue placed between the zvol and the Windows storage stack. This would workaround any races involving IO completions being too fast.

**Comment by ofaaland** [comment]
My first stab at performance tests showed no improvement.

I tested the patch via ZPL on a RHEL6.7-based system with kernel 2.6.32-573.8.1.2chaos.ch5.4.x86_64.  The pool was backed by ramdisks.  The testing tool I used was one called "mdtest" which runs a user-specified number of threads and then cycles through mkdir, stat, rmdir, open/close, stat, unlink.  I varied threads from 4 to 32.  The test was on a 32-core machine.

Between tests with the same thread count, where the only difference was with/without this patch (PR #4317), I saw no difference greater than the standard deviation between identical test runs.

I plan to test again with kernel 4.1 using the same test methodology, and possibly also with dbench, but that won't happen until next week.

@dracwyrm, yes, the data structure protected by these locks is potentially accessed by many threads, running on separate cores, concurrently.    And yes, ZFS uses many threads and was written to do so.

**Comment by ryao** [comment]
@ofaaland I suggest profiling your tests with perf and generating a flame graph of just the frames containing `dbuf_find`. I added an entry to my development notes on the Gentoo wiki explaining how to do this:

https://wiki.gentoo.org/wiki/ZFSOnLinux_Development_Guide#Flame_Graph_of_all_frames_with_a_specific_function

Also, I suggest making your test pool with `ashift=12` and setting recordsize=4KB  to match the page size of the ramdisk. This would ensure that there is no read-modify-write overhead that could dominate before locking bottlenecks.

If you use SELinux, you might also want to experiment with xattr=sa. The overhead of the Solaris extended attribute directory is known to be fairly high, but extended attributes are simply not heavily exercised on most Linux systems, so eliminating that overhead by storing IRIX-style extended attributes via the system attribute code ought to be useful.

**Comment by richardelling** [comment]
@ryao great question: We probably should ask ourselves "do we need to call dbuf_find() at all?" I'd like to address that elsewhere, after some more analysis.

Back to the change of mutex to rw locks...
In general, the frequency of taking locks isn't an issue as long as they are held for a short time. This is why we worry about the amount of time spent blocking on locks rather than the number of locks taken. A move to the more-costly rw locks will scale poorly as the concurrency and latency increase: more concurrent work (we routinely run 1000+ threads), sockets (rough, worst-case estimates 2x for 2, 4x for 4) and cores (to a lesser degree than sockets). In other words, testing on 32 threads on a single socket, 4 core system can behave very different than 1000 threads on dual socket with 16 cores.

So, if the goal is to reduce time spent waiting on locks, the measurement needs to only measure that. Measuring overall performance can easily mask the results and even a single cache miss can skew the results significantly. NB, flamegraphs can be too coarse to see this, lockstat is perhaps the best view.

The other question we've asked ourselves here is whether the size of the hash table is too large or too small. Fortunately, we do have kstats to measure this and it is adjustable by zfs_arc_average_blocksize. This sizing is still a guess, but hopefully a better OOB guess now (8k) than the 64k guess from way-back-when.

**Comment by ryao** [comment]
@ofaaland @richardelling It occurs to me that we can use equations governing hash collision probabilities to model the benefit at varying levels of concurrency:

http://preshing.com/20110504/hash-collision-probabilities/

We have a 5.9% of at least one collision when we have 32 threads hashed to 8192 locks, assuming that our hash function produces a uniform distribution. If we increase the parallelism to 128 threads, there is a 63% chance of at least 1 collision.

That is probably somewhat deceptive because a single 2-way collision at any given time probably is not very bad in comparison to higher order collisions. It also ignores that multiple concurrent threads exercising this code do not necessarily all hit the critical section in the same time window. What we really need for these calculations to matter is some sort of histogram describing how many threads are actually in or trying to enter the critical section at the same time in a given workload.

Also, as a side note, that probability function appears to converge to 100% far faster than I would expect, but the math looks valid. My guess is that the rapid convergence comes from the probability of missing the existing selections so many times, but if anyone doubts that, they could check the validity of that experimentally with a decent quality random number generator. Just generate 32x 13-bit numbers 1000 times and count the number of times any of the 32 13-bit numbers are the same. You can do the same with 128x 13-bit numbers. If the math is right and the random number generator does a decent job of being uniform, the numbers should be close to the theoretical predictions. If they are wildly off, the equations are wrong and we need to go back to basics.

**Comment by richardelling** [comment]
NB, zfs_arc_average_blocksize is not the hash table size. The latter is calculated from the ARC size (+/-) and powers of two. For example, on one of my test machines, the size is 33,554,431. In any case, the hash table stats are important to understanding how well the sizing guess works.

**Comment by behlendorf** [comment]
Closing since this was primarily for testing.  This is still available for reference and comment but I'd like to get it out of the list of open PRs.

**Comment by jumbi77** [comment]
@dracwyrm Can you maybe test it again with the changes ryao mentioned [here](https://github.com/zfsonlinux/zfs/pull/4272) (last comment)?

**Pull request closed without merging**
