### PR TITLE
remove pools without a bootfs from BOOTFS variable creation

### PR DESCRIPTION
**Pull request by prometheanfire**
Use the same method used in zfs-load-key.

Closes: https://github.com/zfsonlinux/zfs/issues/7085

### CODE REVIEW

**Comment by prometheanfire** [comment]
gimme a min to test this, should have a verified result some time tonight, @woefulderelict mind testing on a multi-pool system?

**Comment by WoefulDerelict** [comment]
Not at all. I will nab this and test it shortly.

**Comment by prometheanfire** [comment]
it looks like two things happened with systemd-236

1. the systemctl command changed from `/usr/bin` to `/bin`
2. systemd-ask-password isn't working now

**Comment by WoefulDerelict** [comment]
Arch Linux appears to be forcing systemctl to /usr/bin/ along with the rest of the toolchain. Unfortunate that systemd-ask-password is failing.

I've synced up to [522db29275b81c18c2bf53a95efa1aedeb13b428](https://github.com/zfsonlinux/zfs/commit/522db29275b81c18c2bf53a95efa1aedeb13b428) cherry picked the patch and tested it on the same system with success. The system booted without the zfs-import-cache.service throwing any errors.

**Comment by WoefulDerelict** [comment]
/bin is a symlink to /usr/bin on Arch Linux systems so the proposed change is unlikely to break anything.

**Comment by prometheanfire** [comment]
is it a symlink within the dracut shell as well? (lsinitrd doesnt show that for me)

```
drwxr-xr-x   2 root     root            0 Jan 26 23:58 bin
lrwxrwxrwx   1 root     root           15 Jan 26 23:58 bin/awk -> ../usr/bin/gawk
```

**Comment by prometheanfire** [comment]
ok, my problem was that plymouth needed to be rebuilt with the new paths for systemd.  this PR should be good to go.

**Comment by WoefulDerelict** [comment]
By default Arch Linux uses an initramfs CPIO image generated with [mkinitcpio](https://wiki.archlinux.org/index.php/mkinitcpio). /bin/systemctl resolves properly and zfs-import-cache.service starts without error.

**Comment by behlendorf** [comment]
@prometheanfire @WoefulDerelict if I understand correctly from the comment above this PR has been tested and is ready to merge?  Can you please confirm.

**Comment by prometheanfire** [comment]
confirmed here

**Pull request merged**
