### PR TITLE
Fix LZ4_uncompress_unknownOutputSize caused panic

### PR DESCRIPTION
**Pull request by loyou**
Fix LZ4_uncompress_unknownOutputSize caused panic

Sync with kernel patches for lz4:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/log/lib/lz4

including:
4a3a99 lz4: add overrun checks to lz4_uncompress_unknownoutputsize()
d5e7ca LZ4 : fix the data abort issue
bea2b5 lib/lz4: Pull out constant tables
99b7e9 lz4: fix system halt at boot kernel on x86_64

Signed-off-by: Feng Sun <loyou85@gmail.com>

### Description

Sync with kernel lz4 lib patch.

### Motivation and Context

#5973 

### How Has This Been Tested?

set compression with lz4 and run basic file operations.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by gmelikov** [comment]
@loyou if you want to rebase, you need:
```
git remote add zfsonlinux https://github.com/zfsonlinux/zfs.git
git fetch -all
git rebase zfsonlinux/master
```
and `git push -f` after that.

**Comment by loyou** [comment]
yes, thanks @gmelikov , there are conflicts because of latest lz4.c spelling check patch.
I have forced push for clear code.

**Comment by tuxoko** [comment]
While this change looks fine with me, the next linux release will include a much newer version of lz4. I wonder if we want to move to the same version so we can track the one in kernel easier.

**Comment by kernelOfTruth** [comment]
Referencing:

https://lkml.org/lkml/2017/2/5/139 [PATCH v7 0/5] Update LZ4 compressor module
https://lwn.net/Articles/714619/ Update LZ4 compressor module

**Pull request merged**
