### PR TITLE
Merge SPL into ZFS [WIP]

### PR DESCRIPTION
**Pull request by ofaaland**
### Description

Merge the SPL into ZFS to eliminate the extra work required when SPL code must change due to kernel or distro changes, and to simplify the build process.

Work In Progress.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by chrisrd** [comment]
Can/should we be importing the SPL history rather than simply importing the files at a point in time?

**Comment by jspiros** [comment]
@chrisrd It has been a while since I've done it, and there are a couple different approaches that can be taken, but it is certainly possible to retain SPL history in a combined git repository. `git subtree` or `git merge --allow-unrelated-histories` are two tools that could be used off the top of my head. I do think doing it, one way or another, would be the right way to go, if combining SPL and ZFS is happening either way. (Note: I have nothing to do with this effort, just commenting.)

**Comment by ofaaland** [comment]
@chrisrd @jspiros, thanks for the suggestions.  I'll take a look once I've got the functional issues corrected.

**Comment by behlendorf** [comment]
Keeping the history would be nice.  Particularly if we could somehow limit it only the specific files we want to merge.

**Comment by tuxoko** [comment]
>somehow limit it only the specific files we want to merge

You should be able to just remove those files you don't want before merge.

Also, we should probably use `git merge` instead of `git subtree`, since spl and zfs have similar directory structure, and we probably want to merge the directory structure instead of making spl exist in a subdirectory.

It's very simple in principle. Just add spl repo as a remote. Fetch it, and merge it into zfs master like a normal branch. Though there will likely be quite a lot of conflict in the common files like Makefiles and stuffs.

**Comment by chrisrd** [comment]
Which files shouldn't be merged? (Apart from obvious things like empty `.h` files, e.g. `spl/include/sys/fm/util.h`)

FYI, you  can start looking at the merge (with history) using, in your zfs repository:
```
git remote add spl https://github.com/zfsonlinux/spl.git
git fetch spl
git checkout -b spl-merge
git merge --allow-unrelated-histories spl/master
```

I found this useful for looking through the conflicts:
```
less +/'^(<<<<<|=====|>>>>>)' $(git status | sed -rn 's/^[[:space:]]*both added:[[:space:]]*//p')
```

To my mind, it should be relatively straight forward to merge the technical parts. As a licensing neophyte the trickier part of the merge is deciding what to do with the GPL vs CDDL licensing issue. E.g. files which appear in both repositories which look to have have come from upstream on the zfs side with, I guess, implied copyright, vs newly written, with explicit copyright header, on the spl side, e.g. `config/Rules.am`

**Comment by behlendorf** [comment]
> Which files shouldn't be merged? 

I don't think we need to bring over the SPLAT sources.  This test framework was extremely useful when initially implementing the various primitives, but now that we have good test coverage for ZFS in place it's much less useful.  Except for specific cases ZFS itself does a much better job validating that code is working as intended.

> As a licensing neophyte the trickier part of the merge is deciding what to do with the GPL vs CDDL licensing issue.

It would be best to keep the SPL code and headers entirely separate in their own sub-directory.  We'll need to double check that every file has the correct license at the top, and we're going to want to add a top-level LICENSE file clearly describing which parts of the source tree are covered by which license.  This would also be a good time to reach out to anyone who's contributed to the SPL and determine if we can dual license everything from the SPL as CDDL / GPL.

**Comment by ofaaland** [comment]
Pushed an update to allows packages to be built and include SPL.
I haven't yet attempted to use the tips above to get the spl commit history in.

**Comment by dinatale2** [comment]
@ofaaland Can you retire the `freemem` macro in `include/sys/vmsystm.h`? I'm moving it's functionality to `module/zfs/arc.c`.

**Comment by behlendorf** [comment]
Closing.  I'll open a new PR for this in the next few weeks.

**Pull request closed without merging**
