### PR TITLE
Proposed 0.6.5.9 tag [WIP]

### PR DESCRIPTION
**Pull request by behlendorf**
### Description

Proposed 0.6.5.9 tag for review, comment and automated test results.  Requires the matching SPL PR zfsonlinux/spl#601.

### Motivation and Context

Provide compatibility with Linux kernel's released after the 0.6.5.8 tag.

### How Has This Been Tested?

All commits have been cherry-picked from the master branch and have received significant testing. Commits have been modified as needed to apply to the 0.6.5-release branch.  PR submitted to verify the patches on a wide range of distributions, kernels and architectures.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Build fixes (support for newer versions of the Linux kernel)

### CODE REVIEW

**Comment by tuxoko** [comment]
https://github.com/zfsonlinux/zfs/commit/7e5ea7be7f69231b66c1affddb870fcea8c3a4d8 Fix ZFS_AC_KERNEL_SET_CACHED_ACL_USABLE check
https://github.com/zfsonlinux/zfs/commit/919efe93cb1263a3cfa1b8edf4b0a636a9e579cd zfs_inode_update should not call dmu_object_size_from_db under spinlock
https://github.com/zfsonlinux/zfs/commit/a806cb6a89589d4e1e57a01161b4ce0e2d53523a Don't count '@' for dataset namelen if not a snapshot
https://github.com/zfsonlinux/zfs/commit/05100ec8f06589896fcd2a847a12c5b6fcb67b81 Fix wrong operator in xvattr.h
https://github.com/zfsonlinux/zfs/commit/c360af541117a0978b7fe146b59c12ad2f80d162 Fix fchange in zpl_ioctl_setflags
https://github.com/zfsonlinux/zfs/commit/6c01a4af2b5466fbdceba7304fa8b0dfb0dac839 Fix zmo leak when zfs_sb_create fails
https://github.com/zfsonlinux/zfs/commit/933ec999511f3d29de005bfa8966ae007b161c0f Retire .write/.read file operations
https://github.com/zfsonlinux/zfs/commit/c7af63d62aba273554d6c8457e26c870ed207b40 Fix write(2) returns zero bug from `933ec99`

**Comment by Lalufu** [comment]
Are there 4.10 compat patches that should go into this as well? It's supposed to be out at the 13th or 20th of February.

**Comment by behlendorf** [comment]
@tuxoko thanks.  All of those suggested fixes look reasonable and I've applied them to the stack.

Additionally, I've added the bio compatibility code which is needed for 4.10 kernels to maximize this tags longevity.  This brings `vdev_disk.c` almost inline with the master version except for some statistics code and the ABD changes.

**Comment by Lalufu** [comment]
.... maybe I should have waited 10 seconds :)

**Comment by behlendorf** [comment]
@Lalufu you're just too fast!  If you have a few minutes could you review #5719.  It hasn't yet been merged but it should resolve some issues users have reported with dataset not mounting at boot time.  I'd like to add it to this tag is possible.

**Comment by jumbi77** [comment]
#4482 is also tagged with 0.6.5.9 but not referenced here.

**Comment by behlendorf** [comment]
The testing results from #5719 look good.  Builds are passing for all supported architectures and for the latest kernel.org kernels.  I'll be making the official 0.6.5.9 based on the patches in this patch stack.

@jumbi77 I looked in to porting the #4482 changes and decided to not apply them for this tag due to a significant number of conflicts.  Those fixes are in master and couple be backported to a future 0.6.5.x tag if someone resolves the conflicts.

**Comment by tuxoko** [comment]
@behlendorf for #4482 these should be pretty applicable on 0.6.5.9
https://github.com/zfsonlinux/zfs/commit/cb0b802ce9f2ca171ee3b5611cd9d540e0b05aa1
https://github.com/zfsonlinux/zfs/commit/9ca87863ae673cbaf04ea2d7d77f26f71228ea0c
https://github.com/zfsonlinux/zfs/commit/648c34c4166ebeb676fa91fa1876b57b21a486d1

**Comment by behlendorf** [comment]
@tuxoko thanks for doing the back port of these patches.  I've added them to the squashed branch for testing and if everything looks good there I'll get them in this tag.

**Comment by behlendorf** [comment]
Tagged https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.9.

**Pull request closed without merging**
