### PR TITLE
Illumos 5269 - zpool import slow

### PR DESCRIPTION
**Pull request by DeHackEd**
5269 zpool import slow
Reviewed by: Matthew Ahrens <mahrens@delphix.com>
Reviewed by: George Wilson <george@delphix.com>
Reviewed by: Dan McDonald <danmcd@omniti.com>
Approved by: Dan McDonald <danmcd@omniti.com>

References:
  https://www.illumos.org/issues/5269
  illumos/illumos-gate@12380e1

Ported-by: DHE <git@dehacked.net>

### CODE REVIEW

**Comment by behlendorf** [comment]
#3397 has been merged so there is no longer a need for the dependency patch.  Aside from the taskq_wait() issue this patch looks good to me.  We'll need to somehow sort that it before it can be merged.

**Comment by DeHackEd** [comment]
Rebased to clean up the patch stack, but the `taskq_wait()` issue remains

**Comment by behlendorf** [comment]
@DeHackEd let's address the `taskq_wait()` issue by updating the SPL to conform to the illumos behavior.  I've opened zfsonlinux/spl#453 for this.

**Comment by kernelOfTruth** [comment]
looking forward to this pull-request since importing of the pools take quite a while for me ! :+1:

**Comment by behlendorf** [comment]
Now that zfsonlinux/spl@a876b0305e94eea9505e7ecbae93cf7a1d24f743 has been merged to master task_wait() will block until the entire taskq has been drained (like illumos, unlike FreeBSD).  This resolves the outstanding portability issue allowing this patch to be merged.

9c43027 Illumos 5269 - zpool import slow

**Pull request closed without merging**
