### PR TITLE
Use Multi-buffer sha256 support from SPL

### PR DESCRIPTION
**Pull request by dong-liuliu**
### Description

Let sha256 checksum using multi-buffer api if it is exported by SPL
### Motivation and Context

 Using multi-buffer type, performance of sha256 will be increased 2~7 times.
Now a patch for multi-buffer sha256 facility in kernel space is implemented and submitted to SPL.
Its userspace facility and sha512 parts will be following up after this patch is reviewed and commented.

### How Has This Been Tested?

Run FIO sequential write test, on Intel Xeon server (Haswell E5-2699 v3, 18 core), with 6x SSD :

Sha256 | CPU-sys% | BW(MB/s)
-- | -- | --
multi-buffer version | 27 | 1859
icp version | 71 | 1876

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by loli10K** [comment]
@dong-liuliu you can add `Requires-spl: refs/pull/646/head` to the commit message to tell the buildbot this requires changes from https://github.com/zfsonlinux/spl/pull/646.

See https://github.com/zfsonlinux/zfs/wiki/Buildbot-Options#requiring-spl-versions

**Comment by behlendorf** [comment]
@dong-liuliu very nice!  So we're currently in the process of pulling the SPL source in to the ZFS tree #6479.  I'd like to defer making this change until we have everything in one source tree.

**Comment by dong-liuliu** [comment]
Thank you, @behlendorf,  @loli10K  . Let's check it after #6479  process

**Comment by kernelOfTruth** [comment]
Are the buildbots even checking the proper functionality of sha256 checksums with the new multibuffer api ?

a quick search for sha256 didn't turn up anything: ```https://github.com/zfsonlinux/zfs-buildbot/search?utf8=%E2%9C%93&q=sha256&type=```

**Comment by dong-liuliu** [comment]
No, the buildbots just checked that if not configure with multi-bufer hash, this patch won't impact ZFS.
Checking work on new multibuffer api needs a configured SPL which is configured and built with ISA-L crypto's object file.

**Comment by behlendorf** [comment]
Right, but once the SPL is in-tree we'll want to give some thought as to if it's possible to configure a builder to provide test coverage for this.

**Comment by behlendorf** [comment]
@dong-liuliu sorry about the delay but the spl has now been merged to the zfs repository.  If you're still interested in getting this support included please go ahead and open a new PR against ZFS.

**Pull request closed without merging**
