### PR TITLE
Linux 3.19 compat: file_inode was added

### LINKED ISSUE #2959: error: 'struct file' has no member named 'f_dentry'
This on latest (head) linux source (git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git).

```
/usr/src/zfs/module/zfs/../../module/zfs/zpl_file.c: In function 'zpl_ioctl_getflags':
/usr/src/zfs/module/zfs/../../module/zfs/zpl_file.c:625:25: error: 'struct file' has no member named 'f_dentry'
/usr/src/zfs/module/zfs/../../module/zfs/zpl_file.c: In function 'zpl_ioctl_setflags':
/usr/src/zfs/module/zfs/../../module/zfs/zpl_file.c:661:25: error: 'struct file' has no member named 'f_dentry'
```

Temporary solution as in https://github.com/torvalds/linux/commit/78d28e651f97866d608d9b41f8ad291e65d47dd5:

```
diff --git a/module/zfs/zpl_file.c b/module/zfs/zpl_file.c
index cabe9bf..a55f8a7 100644
--- a/module/zfs/zpl_file.c
+++ b/module/zfs/zpl_file.c
@@ -622,7 +622,7 @@ zpl_fallocate(struct file *filp, int mode, loff_t offset, loff_t len)
 static int
 zpl_ioctl_getflags(struct file *filp, void __user *arg)
 {
-       struct inode *ip = filp->f_dentry->d_inode;
+       struct inode *ip = filp->f_path.dentry;
        unsigned int ioctl_flags = 0;
        uint64_t zfs_flags = ITOZ(ip)->z_pflags;
        int error;
@@ -658,7 +658,7 @@ zpl_ioctl_getflags(struct file *filp, void __user *arg)
 static int
 zpl_ioctl_setflags(struct file *filp, void __user *arg)
 {
-       struct inode    *ip = filp->f_dentry->d_inode;
+       struct inode    *ip = filp->f_path.dentry;
        uint64_t        zfs_flags = ITOZ(ip)->z_pflags;
        unsigned int    ioctl_flags;
        cred_t          *cr = CRED();
```

Notes from @ryao on IRC:

```
[12:27:27] <ryao> FransUrbo: I think that is what we will want to do unless we want another autotools check. f_inode is not in 2.6.32.
[12:28:28] <ryao> FransUrbo: Another option is to bring the macro into include/linux/file_compat.h in the SPL.
```

### PR DESCRIPTION
**Pull request by Mic92**
fixes #2959

### CODE REVIEW

**Comment by FransUrbo** [comment]
Thanx @Mic92. @behlendorf, we need this into 0.6.4 and I'll start testing right away...

**Comment by Mic92** [comment]
@FransUrbo I forgot to add the compatibility header file to include/linux/Makefile.am

**Comment by ilovezfs** [comment]
If you force push, GitHub will automatically update the pull request.

**Comment by FransUrbo** [comment]
@maci0 Ok, could you force-push the changes? I haven't gotten this far yet. I had to create a new latest Linux kernel. Can't find the 3.19-rcSOMETHING i built a couple of months (weeks? :) ago and that's going to take a while..

**Comment by Mic92** [comment]
@ilovezfs @FransUrbo done. My internet connection broke in the same second.

**Comment by FransUrbo** [comment]
Works like a charm on both <code>3.18.0-rc3</code> and <code>3.19.0-rc7+git26cdd</code> (the very, very latest GIT version). This on ZoL GIT master (with some of my own stuff).

**Comment by behlendorf** [comment]
@Mic92 Nice, this is exactly what I had in mind.  Could you please just fix the two style issues which were flagged and repush the patch.

```
./include/linux/fs_compat.h: 34: indent by spaces instead of tabs
./include/linux/fs_compat.h: 34: unparenthesized return expression
make: *** [checkstyle] Error 1
```

**Comment by Mic92** [comment]
@behlendorf done

**Comment by behlendorf** [comment]
@Mic92 Thanks for taking care of this.  I've merged your fix, the only minor change I made was moving the wrapper function in to `vfs_compat.h`.  Arguably it should be in `file_compat.h` but that's still part of the SPL layer for now.

534759f Linux 3.19 compat: file_inode was added

**Pull request closed without merging**
