### PR TITLE
Support accessing .zfs/snapshot via NFS

### PR DESCRIPTION
**Pull request by yshui**
Since @andrey-ve has been quiet recently, I decide to step up to address the remaining issues in his patchset (#1655).

I have re-organized the commits and re-phrased some of the commit log. For those commits I changed, I have appended my signed-off line to them.

Please review, thanks.

### CODE REVIEW

**Comment by behlendorf** [comment]
@yshui I was just looking this over again to see if we can get it in for 0.6.4 and noticed you have fixsnap2 and fixsnap3 branch.  It looks to me like fixsnap3 was the exploratory branch for using `lookup_one_len()` which didn't pan out.  Could you confirm that, and then rebase this pull request against master with that latest proposed patch stack.

**Comment by yshui** [comment]
@behlendorf Yes, fixsnap3 is where I experimented with ```lookup_one_len()```

I have rebased this pull request.

**Comment by behlendorf** [comment]
@yshui Thanks, I'm looking forward to getting the buildbot results.  Personally, I'd really like to get this in.  I assume you've been using it successfully for quite some time now.

**Comment by behlendorf** [comment]
@yshui This looks like it's coming along nicely, I've made a few comments for issues I found while starting to test this.

**Comment by behlendorf** [comment]
Replaced by #3737.

**Pull request closed without merging**
