### PR TITLE
[wip][test] Prefetch dmu

### PR DESCRIPTION
**Pull request by ironMann**
Run testers

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by ironMann** [comment]
> The [memory leak](http://build.zfsonlinux.org/builders/Ubuntu%2016.04%20x86_64%20Kmemleak%20%28TEST%29/builds/3092/steps/shell_9/logs/kmemleak) looks real, the other failure is a known unrelated issue in the test suite.

@behlendorf I'm not very familiar with this code. Could it be that this particular leak is caused by missing `dmu_buf_rele(db, FTAG)` in the continue branch [here](https://github.com/zfsonlinux/zfs/blob/2209e40981e887c773914ec0f3b73cedf45ddb7d/module/zfs/dmu_objset.c#L2034) ?

**Comment by behlendorf** [comment]
@ironMann yes, that error path could cause this and should call `dmu_buf_rele(db, FTAG)`.  Although it's not clear why it didn't also leak the dnode, maybe that leak just wasn't logged for some reason.  Oddly this bug exists in master and I don't recall ever seeing it marked before, you may have gotten very unlucky in the test run.  But I'm glad we found it!

**Comment by ironMann** [comment]
my patch, in that version, added an additional allocation in `dnode_create()` path. That probably triggered kmemleak. I'll add the fix here and retest.

**Comment by behlendorf** [comment]
@ironMann I've resubmitted the build for Ubuntu 14.04 i386 and Ubuntu 17.04 x86_64 which hit known existing problems.

The [large_dnode_008 failure](http://build.zfsonlinux.org/builders/Ubuntu%2016.04%20x86_64%20Kmemleak%20%28TEST%29/builds/3119) on the kmemleak builder however is more interesting.  This PR appears to have significantly increased the normal run time of this test from 5-6 minutes to over 10 on the debug kmemleak TEST builder.  This exceeded the allowed time per test.  You can see the same effect to a less degree on the Amazon TEST builder.  The run time increases from 7-8 seconds on master to 12 in this PR.

**Comment by ironMann** [comment]
@behlendorf Locks. Or lack thereof :) 
This simple patch to bail from `dmu_zfetch()` if prefetch lock is taken significantly reduces the `large_dnode_008` time on my vm. Here's the function latency profile before:

```
# /usr/share/bcc/tools/funclatency -u dmu_zfetch
Tracing 1 functions for "dmu_zfetch"... Hit Ctrl-C to end.
^C
     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 18       |                                        |
         4 -> 7          : 1925     |**********                              |
         8 -> 15         : 4583     |************************                |
        16 -> 31         : 1988     |**********                              |
        32 -> 63         : 1821     |*********                               |
        64 -> 127        : 2578     |*************                           |
       128 -> 255        : 4318     |**********************                  |
       256 -> 511        : 3944     |********************                    |
       512 -> 1023       : 2826     |**************                          |
      1024 -> 2047       : 7602     |****************************************|
      2048 -> 4095       : 6463     |**********************************      |
      4096 -> 8191       : 581      |***                                     |
      8192 -> 16383      : 1159     |******                                  |
     16384 -> 32767      : 1217     |******                                  |
     32768 -> 65535      : 1040     |*****                                   |
     65536 -> 131071     : 781      |****                                    |
    131072 -> 262143     : 600      |***                                     |
    262144 -> 524287     : 26       |                                        |
```
and after:
```
# /usr/share/bcc/tools/funclatency -u dmu_zfetch
Tracing 1 functions for "dmu_zfetch"... Hit Ctrl-C to end.
^C
     usecs               : count     distribution
         0 -> 1          : 3549167  |****************************************|
         2 -> 3          : 58677    |                                        |
         4 -> 7          : 145238   |*                                       |
         8 -> 15         : 244921   |**                                      |
        16 -> 31         : 92246    |*                                       |
        32 -> 63         : 23015    |                                        |
        64 -> 127        : 21688    |                                        |
       128 -> 255        : 27279    |                                        |
       256 -> 511        : 8877     |                                        |
       512 -> 1023       : 861      |                                        |
      1024 -> 2047       : 346      |                                        |
      2048 -> 4095       : 156      |                                        |
      4096 -> 8191       : 79       |                                        |
      8192 -> 16383      : 21       |                                        |
     16384 -> 32767      : 3        |                                        |
```

**Comment by sempervictus** [comment]
This PR has been running on a number of systems for a couple of months, seems pretty stable to me...

**Comment by behlendorf** [comment]
@sempervictus can you share any before any after performance data for you workload?

@ironMann how do you want to proceed with this?

**Comment by sempervictus** [comment]
Unfortunately i cannot build or run bpf programs on the target systems - they're 4.9 with the unofficial grsec patches maintained by minipli with the BPF hardening functionality on (breaks bcc tools). Is there a good analagous test which i can run sans eBPF?

Subjectively, i can say this helps reduce wait on searches in deep filesystems. Not sure if it has an impact on how ZVOLs prefetch, but with the current stack we're actually seeing our consumers' iowait down to single or low double digits in workloads that were previously 30%+ wait. 

@ironMann: could i ask you to rebase this on master?

**Comment by ironMann** [comment]
@behlendorf @sempervictus I started this PR as an experiment to generalize the prefetcher streaming logic using range trees. Prefetching logic in this PR at the current state might be the most suitable for HPC workloads. But, while chasing some ztest heavy-metadata results, I noticed a lot of repeated accesses to the same block and that taking notice and bailing out early wins big. I suspect this is the case with the iowait reduction @sempervictus is seeing. Using this with ZVOLs can use a lot of memory in a pathological access pattern, so I'd be careful there.

Replacing the block prefetcher is a tricky business, especially because it's was recently rewritten. I'm not currently able to collect stats for different use-cases, so further development would be an educated guess, at best. Perhaps porting the `arc_read()` avoidance techniques to the current prefetcher would yield similar results.

@sempervictus Can you share `zfetchstats` and related `arcstats` (`hits, misses, sync_wait_for_async, demand_hit_predictive_prefetch`) from your production system? This should pinpoint the reason for the improvement you are seeing.

**Comment by sempervictus** [comment]
@ironMann: i can pull some of that, but presently seeing a conflict in module/zfs/dmu_zfetch.c when trying to merge against master.

**Comment by kernelOfTruth** [comment]
@sempervictus yep, that's caused by https://github.com/zfsonlinux/zfs/commit/1c27024e22af4386b592b30d40e6a0820ceb48c1 "Undo c89 workarounds to match with upstream"

**Comment by ironMann** [comment]
Sorry for the delay, rebased here as well

**Comment by sempervictus** [comment]
@ironMann: still seems to be conflicting, another rebase needed, or something messed up in my master?

**Comment by kernelOfTruth** [comment]
@sempervictus yes, this time it's due to https://github.com/zfsonlinux/zfs/commit/d4a72f23863382bdf6d0ae33196f5b5decbc48fd Sequential scrub and resilvers

and it requires some more work: in module/zfs/range_tree.c

**Comment by sempervictus** [comment]
@ironMann: with the crypto stuff in master now, any chance you could refresh the PR? Thank you

**Comment by behlendorf** [comment]
@ironMann if you're still interested in working on this proposed performance optimization please go ahead and open a new PR whenever you're ready.  In the meanwhile, I'm going to close this PR.

**Pull request closed without merging**
