### PR TITLE
NEON vectorized RAID-Z1/2/3 parity computation for ARM64.

### PR DESCRIPTION
**Pull request by fshh520**
This is my implementation of vector algorithm on arm64-v8a machines,
and it's reference to the submission of rdolbeau
(SSE, AVX-128 & AVX2 vectorized RAID-Z1/2/3 parity computation).
Thank you for your sharing.

Algorithm passed preliminary test,
and  will to carry out a detailed test certification in the future.

Signed-off-by: huhai <huhai@kylinos.cn>

### CODE REVIEW

**Comment by ptx0** [comment]
awesome! do you have any performance tests?

**Comment by fshh520** [comment]
The algorithm is improved by about 10% to 20%，If we can solve the problem of cache miss too high, about 50% to 60% increased. A few hours later, I will mention a Issues

**Comment by behlendorf** [comment]
@fshh520 @rdolbeau the vectorized RAIDZ infrastructure to support this has been merged to master.  Along with sse and avx2 optimized implementations there are now the utilities and tests to validate any new implementation.  If your interested in adding support for NEON you'll want to rebase this work on master and take advantage of the new infrastructure added in ab9f4b0b824ab4cc64a4fa382c037f4154de12d6.

**Comment by rdolbeau** [comment]
A new version of my NEON code is in #4801

**Comment by behlendorf** [comment]
Closing.   Replaced by #4801.

**Pull request closed without merging**
