### PR TITLE
Add Pushbullet notification support to ZED

### PR DESCRIPTION
**Pull request by dun**
I was playing with [Pushbullet ](https://www.pushbullet.com/) recently and thought this would be great for ZED notifications. It supports several [clients](https://www.pushbullet.com/apps) and has an open [API](https://docs.pushbullet.com/).

This patch stack begins with cleaning up the existing ZEDLETs, refactoring common code blocks into ```zed-functions.sh```, adopting a more consistent coding style, updating exit codes, etc. All scripts now run cleanly through [ShellCheck](http://www.shellcheck.net/).

The old "email" ZEDLETs are replaced with new "notify" ZEDLETs. A notification can now be sent via email and/or Pushbullet. Additional notification methods will likely be added in the future.

Pushbullet notifications are enabled by setting ```ZED_PUSHBULLET_ACCESS_TOKEN``` and (optionally) ```ZED_PUSHBULLET_CHANNEL_TAG``` in ```zed.rc```. The Pushbullet implementation requires awk, curl, and sed executables to be installed in the standard PATH.

zed pb1 checksum
zed pb2 spare
zed pb3 resilver

### CODE REVIEW

**Comment by FransUrbo** [comment]
My stuff is to old :(. Need iOS 7.1 (I have 6.1.3) and OSX 10.9 (I have 10.7.5). At least the Safari client seems to be working.

Trying this, by offline and then online a disk in the pool, I get the resilver finished via email, but NOT (that I can see) in Pushbullet…

Trying to reconstruct what this do (by adding some debugging messages), I came up with this:

```
curl -u "<my token>:" -X POST "https://api.pushbullet.com/v2/pushes" --header "Content-Type: application/json" \
    --data-binary "{'channel_tag': '<my tag>', 'type': 'note', 'title': 'test', 'body': 'testtest'}"
```

That gave me:

```
{"error":{"type":"invalid_request","message":"Failed to decode JSON body.","cat":"(=^###=)"}}
```

**Comment by FransUrbo** [comment]
Removing the extra ':' in the token string, I get:

```
Enter host password for user '<my token>':
```

**Comment by FransUrbo** [comment]
Never mind. Don't know if it was all my tests or 'kicking' pushbullet that eventually made it work. But it works…

Although, there's no tabbing etc in the notify. Is that a limitation on pushbullet?

**Comment by behlendorf** [comment]
> Although, there's no tabbing etc in the notify. Is that a limitation on pushbullet?

Yes, I believe push bullet strips it.

**Comment by behlendorf** [comment]
@dun nice work!  This looks really nice.    I've merged this branch to master after doing some basic functional testing.  In the process I fixed the minor nit a mentioned about the README by adding it as an EXTRA_DIST.

While this is definitely a step in the right direction it may be somewhat disruptive.  Let's keep a close eye on the tracker for the next few months for for any new issues/regressions this may have accidentally introduced.

52d5a1c Merge branch 'zed-pushbullet'
ce119da Combine data-notify.sh with io-notify.sh
090b191 Add notification to io-spare.sh
a0d065f Add support for Pushbullet notifications
20967ff Replace "email" ZEDLETs with "notify" ZEDLETs
aded9a6 Cleanup ZEDLETs

**Comment by dun** [comment]
@FransUrbo Re: tabbing. You can embed tabs in the notification message with a "\t" character sequence. But the web interface removes leading whitespace when displaying notifications, whereas the Android app appears to use a tab stop of 3 spaces. I don't have anything with which to test the iOS app.

**Pull request closed without merging**
