### PR TITLE
Add support for ppc64le

### PR DESCRIPTION
**Pull request by harsha544**
Currently the build fails on ppc64le arch  #5174 . Inorder to overcome the issue, one has to make the below changes.

### CODE REVIEW

**Comment by harsha544** [comment]
@behlendorf Thank you for your pointers I will ensure to integrate them.

**Comment by behlendorf** [comment]
@harsha544 closing for now.  Go ahead and open a new PR when you have an updated ppc64le fix which doesn't break the build for the architectures.

**Comment by harsha544** [comment]
@behlendorf I was waiting for my internal legal approvals to be in place before I upload my patch.
Thank you.

**Comment by behlendorf** [comment]
Then it sounds like I jumped the gun closing this.  I'll just reopen this and you and update this PR when that get's sorted out.

**Comment by harsha544** [comment]
@behlendorf  Thank you very much for re-opening this PR. I will post my updates to you.

**Comment by harsha544** [comment]
@behlendorf  Thank you very much for re-opening this PR. I will post my updates to you.

**Comment by behlendorf** [comment]
@harsha544 any update of this?

**Comment by behlendorf** [comment]
Closing due to inactivity.  @harsha544 please go ahead and open a new pull request when you have internal approval to release your patch.

**Pull request closed without merging**
