### PR TITLE
Add the ZFS Test Suite

### PR DESCRIPTION
**Pull request by behlendorf**
Add the ZFS Test Suite
    
    Add the ZFS Test Suite and test-runner framework from illumos.
    This is a continuation of the work done by Turbo Fredriksson to
    port the ZFS Test Suite to Linux.  While this work was originally
    conceived as a stand alone project integrating it directly with
    the ZoL source tree has several advantages:
    
      * Allows the ZFS Test Suite to be packaged in zfs-test package.
        * Facilitates easy integration with the CI testing.
        * Users can locally run the ZFS Test Suite to validate ZFS.
          This is currently STRONGLY DISCOURAGED because the ZFS Test
          Suite in its current form IS destructive.
      * Allows the ZFS Test Suite to be run directly in the ZoL source
        tree enabled developers to iterate quickly during development.
      * Developers can easily add/modify tests in the framework as
        features are added or functionality is changed.  The tests
        will then always be in sync with the implementation.
    
    Full documentation for how to run the ZFS Test Suite is available
    in the tests/README.md file.
    
    WARNING: This test suite is designed to be run on a dedicated test
    system.  It will make modifications to the system including, but
    not limited to, the following.
    
      * Adding new users
      * Adding new groups
      * Modifying the following /proc files:
        * /proc/sys/kernel/core_pattern
        * /proc/sys/kernel/core_uses_pid
      * Creating directories under /
    
    NOTES:
      * Not all of the test cases are expected to pass and by default
        these test cases are disabled.  The failures are primarily due
        to assumption made for illumos which are invalid under Linux.
        When updating these test cases it should be done in a way which
        is as generic as possible so the patch could be submitted back
        upstream.
      * There are several test cases which have been disabled because
        they can trigger a deadlock.  A primary example of this is to
        recursively create zpools within zpools.  These tests have been
        disabled until the root issue can be addressed.
      * Illumos specific utilities such as (mkfile) should be added to
        the tests/zfs-tests/cmd/ directory.  Custom programs required by
        the test scripts can also be added here.
      * SELinux should be either is permissive mode or disabled when
        running the tests.  The test cases should be updated to conform
        to a standard policy.
      * Redundant test functionality has been removed (zfault.sh).
      * Existing test scripts (zconfig.sh) should be migrated to use
        the framework for consistency and ease of testing.

### CODE REVIEW

**Comment by behlendorf** [comment]
@tuxoko @dweeezil @ryao @nedbass what are your thoughts on adding all of the ZFS Test Suite to the ZFS on Linux repository.  It's a huge addition to the tree but adding the this test framework makes it easy to add test cases with a commit and have them be run.

**Comment by dweeezil** [comment]
@behlendorf I've not been following this too closely but it does sound very interesting to me.  Pretty much all my dev systems are "dedicated test systems" so I'll give this a good looking at within next few days.  I don't use managed packages (deb, rpm, etc.) on any of my deb systems so I'll not be able to comment much on the packaging integration.

**Comment by ryao** [comment]
@behlendorf I am okay with adding this to the tree, but it probably should have some changes from its current form. @avg-I is right now experimenting with this at work, so he could elaborate more, but this is dependent on RPM/DEB packaging (requiring alien and fakeroot on anything that isn't a RPM distribution from what I can gather), missing ksh causes test cases to be reported as passing and we probably should try to reduce the opportunity for an accidental `make check` to do destruction operations by requiring an environment variable along the lines of `MACHINE_IS_DISPOSABLE=yes` to be set.

**Comment by avg-I** [comment]
@behlendorf @ryao what would be correction instructions for installing zfs-tests on Gentoo?
The documented way of doing `make pkg-utils` fails for me in two ways:
-  it seems that `config/tgz.am` wants to convert `zfs-devel-*.rpm` to a `.tgz` file, but such rpm is not being built
- the build process insists that I have to install `libattr-devel`, I've installed `sys-apps/attr` but that does not help

**Comment by behlendorf** [comment]
Thank you for the feedback.  It sounds like we're in general agreement that merging some version of the existing ZFS Test Suite in to the git tree is a good idea.  The benefits of making this easy to run and maintain should greatly aid development.  I expect to push an updated version of this patch sometime this week which addressed several of outstanding concerns.  So I'd hold off on a detailed review until then, however the broad outlines of the patch will be the same.

> run make check out of habit whenever building something from source under the assumption that it is safe. 

Good idea.  I'll make sure that the default behavior is to not run these tests.  When porting this to Linux an effort was made to have a minimal impact on the system, however I'm not 100% familiar with every test case which is why I included the warnings.

> This is dependent on RPM/DEB packaging and assuming anything not using RPM uses DEB

It's not dependent on it RPM/DEB style packaging but it can take advantage of it.  You can run the ZFS Test Suite either by installing it on your system as a RPM/DEB package or with a simple `make install`.  Alternately, the scripts have been updated such that they can also be used in-tree.  You'll just need to make sure the zfs modules are loaded and the various udev rules are installed.

> what would be correction instructions for installing zfs-tests on Gentoo?

That's a good question for @ryao.  I wouldn't think much would need to be added since it all built on the standard autotools infrastructure.  I'd expect `configure; make; make install` to work although we might want to add an option to better control the install path.  If it needs to be further extended to support Gentoo by all means lets hash out what's needed.

> Missing ksh causes test cases to be reported as passing and failures

Unfortunately `ksh` is a hard dependency.  Quite a lot of care was taken to minimize changes made to the test scripts.  Just like with the ZFS core code this will make it easier to pull in improvements from upstream.  Rewriting everything in POSIX shell might be nice but it would be huge amount of work for very little gain.  We'll have to live with needing to install `ksh` when running the tests.  However, there's nothing preventing new test from being written in something else.

> I have to install libattr-devel

The error message here is a bit CentOS specific since it output the CentOS package needed.  It, along with a few others, should probably be reworked to either list the needed library name or perhaps instructions for common distributions.  In this case it needs the libattr library because there is one test case which uses `fsetxattr(2)` (we should add some more).  The files needed are as follows, how they're packaged for Gentoo I don't know.

```
/usr/include/attr/attributes.h
/usr/include/attr/error_context.h
/usr/include/attr/libattr.h
/usr/include/attr/xattr.h
/usr/lib64/libattr.so
```

**Comment by behlendorf** [comment]
This PR is getting pretty close to finalized.  It still needs a few more iterations to ensure all the enabled test cases regularly pass the buildbot, but it's close.  I'd appreciate any additional feedback people have.  Once merged we'll be running the test suite automatically against every new PR and merge.  Plus we'll have the needed infrastructure in place to start adding test cases when new features are proposed.

**Comment by avg-I** [comment]
@behlendorf I've tried the latest version and it's much better, thank you!
Once problem: it seems that the code expects partitions (created with parted) to be named e.g. vdbp1 but in my environment they are named like vdb1. (Yes, I am running Linux in a VM with virtio disks).

**Comment by behlendorf** [comment]
@avg-I thanks for testing it.  Yes, you're exactly right I should have mentioned that in the commit comment.  The test suite still expects a illumos style slice naming, i.e. a known constant suffix (s0 | p1) to be appended to the device.  So it works fine on loopback devices since they end with a digit, but not with normal devices which end with a character.  We definitely need to add support for that but I was thinking about leaving it to a follow up patch.

**Comment by avg-I** [comment]
@behlendorf thank you for the explanation, makes sense :-)
BTW, it seems that one of the `zpool_import` tests (not sure which) causes the kernel to enter an infinite loop (probably with interrupts disabled) if I configure my test VM with a single CPU. There is no problem with multiple CPUs. The symptoms are that the guest system becomes completely unresponsive while churning a host CPU.

**Comment by behlendorf** [comment]
@avg-I if you could identify which test causes the issue we can disable it for now.

What I'd like to do is get this patch merged even though we've had to disable a few tests.  Then with the help of people like yourself work through the disabled test cases and either update them for Linux or if they're triggering a bug fix it.  It would be great to be running the full entire suite, not just 80% of it.  Then it would be great to expand the test coverage as new features are added.

**Comment by ryao** [comment]
@avg-I That would not be the first time we have had things hang with just 1 CPU core, although it is the first time I have heard of it being an infinite loop rather than a deadlock.

That said, I had not seen replies to this thread until now.

> what would be correction instructions for installing zfs-tests on Gentoo?

If the system is disposable, then `make install` is likely fine. I am updatingthe Gentoo packaging, so I should have an answer on this soon.

**Comment by avg-I** [comment]
Yes, I do not suggest that any changes have to be made now, just shared my experience.
I reproduced the problem twice so far, in one case the last logged test case was `zpool_import_007_pos` and in the other case it was `zpool_import_009_neg`. Not sure what to make of it.

**Comment by avg-I** [comment]
@ryao thank you! Yes, `make install` does work. I borrowed a few configure flags from the ebuild file, so that the suite is installed into the correct location.

**Comment by behlendorf** [comment]
Merged as:

6bb24f4 Add the ZFS Test Suite

I've also enabled the ZFS Test Suite buildbot step by default so everyone will outstanding PRs will need to refresh them against master to avoid failing this buildbot step.  We may discover some new intermittent test failure in the suite so we'll need to address these as they are uncovered.  Help with this would be greatly appreciated!  This is a big step in the right direction.

**Comment by ryao** [comment]
Awesome. :)

**Comment by kernelOfTruth** [comment]
Excellent :+1:

**Pull request closed without merging**
