### PR TITLE
Add `zfs allow` and `zfs unallow` support

### PR DESCRIPTION
**Pull request by behlendorf**
ZFS allows for specific permissions to be delegated to normal users
with the `zfs allow` and `zfs unallow` commands.  In addition, non-
privileged users should be able to run all of the follow commands:
    
  * zpool [list | iostat | status | get]
  * zfs [list | get]
    
Historically this functionality was unavailable on Linux.  In order
to add it the secpolicy_* functions need to be implemented and mapped
to the equivalent Linux capability.  Only then could the permissions on
the `/dev/zfs` be related and the internal ZFS permission checks used.
    
Even with this change some limitations remain.  Under Linux only the
root user is allowed to modify the namespace (unless it's a private
namespace).  This means the mount, mountpoint, canmount, unmount, and
remount delegations cannot be supported with the existing code.  It
may be possible to add this functionality in the future.
    
This functionality was validated with the cli_user and delegation test
cases from the ZFS Test Suite.  These tests exhaustively verify each
of the supported permissions which can be delegated and ensures only
an authorized user can perform it.
    
Two minor bug fixes were required for test-running.py.  First, the
Timer() object cannot be safely created in a `try:` block when there
is an unconditional `finally` block which references it.  Second,
when running as a normal user also check for scripts using the
both the .ksh and .sh suffixes.
    
Finally, existing users who are simulating delegations by setting
group permissions on the /dev/zfs device can revert that customization
when this change is applied.

### CODE REVIEW

**Comment by tuxoko** [comment]
Linux upstream API changed
https://github.com/torvalds/linux/commit/1fa64f198b9f8d6ec0f7aec7c18dc94684391140

**Comment by tuxoko** [comment]
I was actually pondering on this issue recently, so I'm going to try this out.

**Comment by tuxoko** [comment]
@behlendorf 
It seems we need to set /dev/zfs to rw-rw-rw- in order to work?

**Comment by behlendorf** [comment]
@tuxoko thanks, I'd definitely appreciate a careful review.  As for the `/dev/zfs` device it does need to be permission 0666 and it should have been.  The /dev/zfs udev rule was updated to set MODE=0666, although clearly that didn't work and I'm not quite sure why that didn't work.

**Comment by tuxoko** [comment]
@behlendorf 
My 90-zfs.rules didn't get updated when I do ./configure, not sure why?
Also, I just added `.mode = 0666,` to zfs_misc and it worked.

**Comment by tuxoko** [comment]
Ok, so the udev/rules.d/Makefile.am has recipe for the rules files, but they don't have dependency, so they will never be updated. But I think we should add them to configure.ac so it will automatically generated during ./configure

**Comment by behlendorf** [comment]
I've refreshed this patch and add the udev files to configure.ac.

**Comment by maxximino** [comment]
"only allows you to check your current content.  This poses an issue" s/content/context/
"In order to verify this functionality workss as designed the ZFS" s/workss/works/

A more relevant comment: this will introduce a behavior change for some configurations.
I've seen mentioned in bugs/ML somewhere that people used to change udev rules to have a different GID and give mod 660 to allow administration from less privileged users.
This change would break that workflow [was never officially supported AFAIK, but it's better to announce it widely / add compatibilty rather than know through angry users posting in the bug tracker] and the only possibility after this change is to give CAP_SYS_ADMIN, which is essentially root-equivalent and can't be restricted in scope to "only zfs-related things" (till proper delegation support is in place! which might be easier now).
So.. not sure about the best course of action here, but please be aware of this :)

**Comment by behlendorf** [comment]
@maxximino will fix the commit comment on the next refresh.  It would be great if you could review the rest of the patch as well.

Good point regarding the alternate permissions/sudo scheme people have been using.  Even if that's never been an official supported thing we should take it in to account.   The ideal thing to do would be to finish this and get delegations working, I'll spend a little time investigating what's still required.

**Comment by behlendorf** [comment]
OK, this patch finally LGTM.  All the new test cases pass reliably and everything is behaving as expected in my testing.  I was unable to add support for delegations which modify the global namespace due to permission checks in `mount(8)` but aside from that everything works.  Please review.

**Comment by lhoward** [comment]
One thing that bit me with this is that, because unmount cannot be delegated, neither can destroy, which my backup script uses to destroy old snapshots. I ripped the relevant code out of the zfs tool into a setuid helper that only destroys snapshots, but obviously it would be great to have delegated mount support at some point.

**Comment by behlendorf** [comment]
I agree this would be nice to have.  Unfortunately the standard Linux permission checks done in the VFS make it really difficult to delegate mount/unmount permissions.  We can probably find a workable way to support this but it will take a fair bit of work.

**Comment by maxximino** [comment]
(related to my previous comment on 6 Apr 2016 )
I think the release notes for 0.7.0 could have explained the gotcha for who was using the previous workaround to allow users to do privileged operations. I fear some people will have a not-so-smooth upgrade experience. Maybe edit the release notes where possible?

**Comment by behlendorf** [comment]
@maxximino that's a good idea, this slipped my mind when writing the release notes.  I'm happy to update them to include a warning about this.  Could you propose something we could add to the **Changes in Behavior** section.

**Comment by maxximino** [comment]
How about 
`/dev/zfs permissions changed from 0600 to 0666 to let ZFS do access control in kernel space and make "zfs allow" and "zfs unallow" work properly. If you have been changing permissions / group owner of the device file yourself, note that your change won't work correctly anymore and breaks proper behavior of "zfs allow". From this release, you should be able to satisfy your use-case with the officially supported "zfs allow".` ?
I am not saying anything about operations that require mount/unmount because I think they wouldn't have worked with the permission change anyway .

**Comment by behlendorf** [comment]
Sounds good.  I made some very minor tweaks to the working and updated the [release notes](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.0).  Thanks!

**Comment by CMCDragonkai** [comment]
Just wanted to ask, can ZFS on linux allow non-root users to create datasets and snapshots and clones and mount them? Can this be integrated into user namespaces into the future?

One interesting usecase for ZFS snapshots and clones I was thinking was when working with big datasets. I'm dealing with really large CSVs, and sometimes I need to make a change to them. It would be nice if I could just rapidly snapshot directory, make a ephemeral clone, and work on that. And if I'm happy with the results, I can promote the clone.

However there seems to be several limitations. I'm working as non-root, and these commands seems to be limited to root user. Further I cannot easily make a directory into a new dataset. Finally I'm using legacy mount points which forces me to use `mount -t` commands. If these things were to be fixed, it would make ZFS really useful for any kind of work which cannot be done with source code version control but would be good to have these features.

**Pull request merged**
