### PR TITLE
[RFC] 'Fixes' for initramfs creation

### PR DESCRIPTION
**Pull request by cwedgwood**
---

**INCOMPLETE***

This 'kinda' works for me.

I'm pushing this out now in the hope someone can help work out what the right approach is in a few places.

---

### Motivation and Context

initframfs creation on Debian systems does not presently work because a critical file is missing

Partially addresses: #7904 

### Description

RFC right now, changes are for illustrative purposes.  It will however build a functional initramfs.

### How Has This Been Tested?

Local build testing, inspection of output and limited VM boot testing.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rlaager** [comment]
Fixing the missing file seems clearly correct. Adding `set -e` seems reasonable. (Personally, I use `set -eu` in every shell script I write.) I'm less certain about the "error if missing" approach. Having `zpool.cache` be required is wrong.

**Comment by cwedgwood** [comment]
@rlaager thanks for the comments:
* agree `set -eu` seems better
* removed `zpool.cache`

re: "error if missing" - if we don't do that, we build initramfs which don't work; surely an error at such a time as someone can address/fix it it better than finding out after a reboot it's not working?

force-pushed the update, not sure if github noticed...

**Comment by cwedgwood** [comment]
what i pushed earlier wasn't supposed to work, it was for people to eyeball and comment on

however, in trying to make it work cleanly ... well, it's not clear or working

i'm wondering if instead we should just remove `contrib/initramfs` entirely?

**Comment by rlaager** [comment]
> * agree `set -eu` seems better

If it works with `set -u`, that's fine. I wasn't suggesting `set -u`, just saying I use it personally for everything in addition to `set -e`. So your idea of using `set -e` is generally reasonable. (Though it's always possible that the initramfs script, or initramfs-tools generally, won't work with `set -e` without significant changes.)

> * removed `zpool.cache`

My point was that `zpool.cache` should not be required. It should be in the optional list.

> re: "error if missing" - if we don't do that, we build initramfs which don't work; surely an error at such a time as someone can address/fix it it better than finding out after a reboot it's not working?

Sure. If whatever problem you're catching is definitely fatal on boot, yes, it's better to catch it earlier.

> i'm wondering if instead we should just remove `contrib/initramfs` entirely?

No. This is _the_ initramfs script used by Debian and Ubuntu, at least.

**Comment by kpande** [comment]
it would be great if all distributions would use dracut for booting from ZFS. Debuntu both have it in packages.

**Comment by dreamcat4** [comment]
Can this one get some higher priority attention? Because otherise the missing file causes a kernel panic during boot. And that leads to broken (not bootable) system. Without any prior warnings / error messages to indicate anything was missing during previous building of initramfs.

**Comment by cwedgwood** [comment]
@dreamcat4 IIRC, I couldn't find a robust way to make sure zfs-functions was always present for packaging so this patch is incomplete (the change to add it work, but the file isn't always generated).

**Comment by c0d3z3r0** [comment]
@dreamcat4 @cwedgwood could you both test, if #9089 solves this for you, please?

**Comment by cwedgwood** [comment]
I'm going to close this in favor of #9089 which is more appropriate.

**Pull request closed without merging**
