### PR TITLE
Avoid dladdr() in ztest

### PR DESCRIPTION
**Pull request by dweeezil**
Under Linux, at least, dladdr() doesn't reliably work for functions which
aren't in a DSO.  Replace it with portable constructs using explicit
address comparison which should work properly on any platform.

### CODE REVIEW

**Comment by dweeezil** [comment]
I've been running a lot of ```ztest``` lately and got tired of not being able to tell what it is doing.  Yes, this patch is a hack but it's a hack which works, should be portable and minimizes the changes with the upstream code (the initializer doesn't change).

**Comment by behlendorf** [comment]
Honestly I'd rather just change the initializer if `dladdr()` isn't reliable.    Yes this will cause it to differ from upstream but I keeps the code clean and understandable.  Plus it's the kind of thing we could push upstream.  What about doing something like this instead.

```
diff --git a/cmd/ztest/ztest.c b/cmd/ztest/ztest.c
index b6f2e23..ee9df58 100644
--- a/cmd/ztest/ztest.c
+++ b/cmd/ztest/ztest.c
@@ -347,8 +347,12 @@ uint64_t zopt_often = 1ULL * NANOSEC;              /* every
 uint64_t zopt_sometimes = 10ULL * NANOSEC;     /* every 10 seconds */
 uint64_t zopt_rarely = 60ULL * NANOSEC;                /* every 60 seconds */
 
+#define ZTI_FUNC(func) \
+    zti->zi_func = n;  \
+    zti->zi_funcname = #n;
+
 ztest_info_t ztest_info[] = {
-       { ztest_dmu_read_write,                 1,      &zopt_always    },
+       { ZTI_FUNC(ztest_dmu_read_write),       1,      &zopt_always    },
        { ztest_dmu_write_parallel,             10,     &zopt_always    },
        { ztest_dmu_object_alloc_free,          1,      &zopt_always    },
        { ztest_dmu_commit_callbacks,           1,      &zopt_always    },
```

**Comment by dweeezil** [comment]
Yeah, I'd rather do it that way, too.  I was likely going to re-push it anyway doing exactly that after I thought about my original gross patch.

**Comment by dweeezil** [comment]
OK, 8a03b9a looks a lot better.

**Comment by behlendorf** [comment]
Thanks, that's soooo much nicer.

**Pull request closed without merging**
