### PR TITLE
l2arc_apply_transforms: Fix typo in comment

### PR DESCRIPTION
**Pull request by allanjude**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
@allanjude when you get a moment it would be great if you could refresh this to address @rlaager's comment.

**Comment by rlaager** [comment]
@behlendorf In fairness, could you just fix it as you merge (in one commit or two)? I mean, this is pretty trivial.

**Comment by allanjude** [comment]
Done

**Comment by behlendorf** [comment]
@allanjude thanks!  @rlaager you're right, and I almost did exactly that but never quite got to it.  And I figured there wasn't any real rush in fixing a typo.

**Pull request merged**
