### PR TITLE
Fix issues accessing .zfs/snapshot over NFS

### PR DESCRIPTION
**Pull request by behlendorf**
Addresses several issues which have been exposed in the .zfs/snapshot implementation.

### CODE REVIEW

**Comment by tuxoko** [comment]
@behlendorf 
Could you add this patch also https://gist.github.com/tuxoko/5abf0535b963416795c8
Thanks.

**Comment by behlendorf** [comment]
@tuxoko absolutely, added.  It would be great if you could review the other patches in this stack.  They're all straight forward.

**Comment by tuxoko** [comment]
Other than the zfsctl_snapshot_hold, this looks good to me.

**Comment by behlendorf** [comment]
Merged as:

245b7ab Hold the zfs_snapentry_t before dispatch
1997660 Fix snapshot automount race cause EREMOTE
5ed27c5 Change zfs_snapshot_lock from mutex to rw lock
f22f900 Fix zfsctl_lookup_objset() deadlock
5e94284 Set 'zfs_expire_snapshot=0' to disable auto-unmount

**Pull request closed without merging**
