### PR TITLE
Async ZVOL Minors

### PR DESCRIPTION
**Pull request by behlendorf**

### CODE REVIEW

**Comment by bprotopopov** [comment]
@behlendorf, I did not intend to make https://github.com/behlendorf/zfs/commit/f1ddfb8b4950d9e57025e04c39f2fab44e8daa86 work without the https://github.com/bprotopopov/zfs/commit/33d2228d150561210d924210e270cd439118cbcd. Maybe if you reorder the first commit with the work on asynchronous zvol minor operation that follows, it will be better. 

I am looking a your suggestions in this pull request, which at this point do not leave much space for ambiguity :)

**Comment by bprotopopov** [comment]
@behlendorf, looking at the Async zvol minors commit https://github.com/behlendorf/zfs/commit/ff06a46e995271e20771aec8d9a56b82985d3508

Indeed, you have moved the async invocations for datasets/snapshots to the sync context. I understand your intent much better now, I think it is an interesting twist on my original proposal, and it streamlines the code in quite a bit of places. I agree with the approach. 

I have added some comments to see what you think.

**Comment by behlendorf** [comment]
@bprotopopov great, I'm happy we're on the same page.  Let me see about refreshing these changes and building on them a little bit.  This is definitely still a WIP which needs some polish but I think it's coming along.

**Comment by bprotopopov** [comment]
@behlendorf, I do not mean to have you implement the changes above and test the result. I wanted to confirm my understanding and agree on the outcome.

**Comment by odoucet** [comment]
Hi,

Just wanting to let you know a quick test I just performed on a VM. Zpool with a single disk.

Created 300 zvol, with 30 snapshots each : 
```
$ zfs list |wc -l
302
$ zfs list -t all |wc -l
6252
```

comparing time needed for zpoo import : 

Version | First run | Following runs
---------- | ---------- | ---------------
PATCH* |  0m11.567s |  0m8.975s
0.6.5.4-1 | 0m13.176s | 0m12.745s

PATCH* : SPL:v0.6.5-42_gd112232 / ZFS: v0.6.5-154_gf1ddfb8


Yes, this is just a quick test, and I hope to test your PR on a duplicate of production data (10 mirrors, 160 zvol, ~ 100 filesystems, 6k snapshots total) very soon.

**Comment by bprotopopov** [comment]
@odoucet, are you doing I/O to zvols concurrent with zfs rename ? This was one known trigger for the deadlocks that I addressed with the async minor operaions

**Comment by odoucet** [comment]
@bprotopopov nope, my test did not involve any IO operations nor zfs commands, only "time zpool import". zfs rename is not an operation I do very often in production tbh. Would you like me to test further on this matter ?

**Comment by behlendorf** [comment]
@bprotopopov it would be great if you could grab d6bde32 and run with it.  I'm not going to have much time to devote to this in the upcoming week and I think we're on the same page now.  I've squashed everything but the deadlock changes in to a single commit and updated this pull request.  I decided it didn't make much sense to keep everything separate anymore since there so much overlap in the patches.

**Comment by bprotopopov** [comment]
@behlendorf, sounds good, will do

@odoucet, the deadlock that prompted the async minor work was between zfs rename and zfs_open() to unrelated zvols, even in different pools. So, it would be great if you could amend your test with renames of one zvol and I/O (small amount  -  to cause frequent open/close, e.g. dd a few blocks) to some other zvol. Additionally, it would help to have a few snapshots off the of the zvol under rename created, with zvol's snapdev property on. If that runs for a few hundred iterations I would declare no regressions.

**Comment by kernelOfTruth** [comment]
Some more anecdotal "evidence":

import of my /home pool usually takes around 25-35 seconds (more of the latter recently),

now it's close to 20 seconds !

Nice improvement :cake:

**Comment by behlendorf** [comment]
Closing.  See original PR #3830.

**Pull request closed without merging**
