### PR TITLE
Linux 4.5 compat

### PR DESCRIPTION
**Pull request by behlendorf**
Add support for Linux 4.5 kernels.  To summerize:

- iops->follow_link() replaced by .get_link() with slightly different behavior.
- xattr_handler->list() simplified.

These changes have been lightly tested for 3.10 and the latest kernel.org kernel.  Due to the significant cleanup of the autoconf code I expect the buildbot will uncover at least one build issue for a specific kernel.

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
FYI:

got the following compilation error on my current WIP-branch:
https://github.com/kernelOfTruth/zfs/commits/tuxoko_zfs/abd_next_16.01.2016%2BIllumos-4950-2605%2B4.5-kernel

running kernel is 4.4.0

```
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_user_list’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:6: error: ‘list_list_size’ undeclared (first use in this function)
      list_list_size, name, name_len));    \
      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:683:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_user_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:6: note: each undeclared identifier is reported only once for each function it appears in
      list_list_size, name, name_len));    \
      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:683:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_user_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:22: warning: passing argument 3 of ‘__zpl_xattr_user_list’ makes integer from pointer without a cast
      list_list_size, name, name_len));    \
                      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:683:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_user_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:678:1: note: expected ‘size_t’ but argument is of type ‘const char *’
 __zpl_xattr_user_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:28: warning: passing argument 4 of ‘__zpl_xattr_user_list’ makes pointer from integer without a cast
      list_list_size, name, name_len));    \
                            ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:683:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_user_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:678:1: note: expected ‘const char *’ but argument is of type ‘size_t’
 __zpl_xattr_user_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:88:10: error: too few arguments to function ‘__zpl_xattr_user_list’
  return (__ ## fn(dentry->d_inode,    \
          ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:683:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_user_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:678:1: note: declared here
 __zpl_xattr_user_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_trusted_list’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:6: error: ‘list_list_size’ undeclared (first use in this function)
      list_list_size, name, name_len));    \
      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:750:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_trusted_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:22: warning: passing argument 3 of ‘__zpl_xattr_trusted_list’ makes integer from pointer without a cast
      list_list_size, name, name_len));    \
                      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:750:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_trusted_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:745:1: note: expected ‘size_t’ but argument is of type ‘const char *’
 __zpl_xattr_trusted_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:28: warning: passing argument 4 of ‘__zpl_xattr_trusted_list’ makes pointer from integer without a cast
      list_list_size, name, name_len));    \
                            ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:750:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_trusted_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:745:1: note: expected ‘const char *’ but argument is of type ‘size_t’
 __zpl_xattr_trusted_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:88:10: error: too few arguments to function ‘__zpl_xattr_trusted_list’
  return (__ ## fn(dentry->d_inode,    \
          ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:750:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_trusted_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:745:1: note: declared here
 __zpl_xattr_trusted_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_security_list’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:6: error: ‘list_list_size’ undeclared (first use in this function)
      list_list_size, name, name_len));    \
      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:820:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_security_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:22: warning: passing argument 3 of ‘__zpl_xattr_security_list’ makes integer from pointer without a cast
      list_list_size, name, name_len));    \
                      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:820:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_security_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:815:1: note: expected ‘size_t’ but argument is of type ‘const char *’
 __zpl_xattr_security_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:28: warning: passing argument 4 of ‘__zpl_xattr_security_list’ makes pointer from integer without a cast
      list_list_size, name, name_len));    \
                            ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:820:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_security_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:815:1: note: expected ‘const char *’ but argument is of type ‘size_t’
 __zpl_xattr_security_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:88:10: error: too few arguments to function ‘__zpl_xattr_security_list’
  return (__ ## fn(dentry->d_inode,    \
          ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:820:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_security_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:815:1: note: declared here
 __zpl_xattr_security_list(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_acl_list_access’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:6: error: ‘list_list_size’ undeclared (first use in this function)
      list_list_size, name, name_len));    \
      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1189:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_access);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:22: warning: passing argument 3 of ‘__zpl_xattr_acl_list_access’ makes integer from pointer without a cast
      list_list_size, name, name_len));    \
                      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1189:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_access);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1175:1: note: expected ‘size_t’ but argument is of type ‘const char *’
 __zpl_xattr_acl_list_access(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:28: warning: passing argument 4 of ‘__zpl_xattr_acl_list_access’ makes pointer from integer without a cast
      list_list_size, name, name_len));    \
                            ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1189:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_access);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1175:1: note: expected ‘const char *’ but argument is of type ‘size_t’
 __zpl_xattr_acl_list_access(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:88:10: error: too few arguments to function ‘__zpl_xattr_acl_list_access’
  return (__ ## fn(dentry->d_inode,    \
          ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1189:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_access);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1175:1: note: declared here
 __zpl_xattr_acl_list_access(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_acl_list_default’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:6: error: ‘list_list_size’ undeclared (first use in this function)
      list_list_size, name, name_len));    \
      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1206:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_default);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:22: warning: passing argument 3 of ‘__zpl_xattr_acl_list_default’ makes integer from pointer without a cast
      list_list_size, name, name_len));    \
                      ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1206:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_default);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1192:1: note: expected ‘size_t’ but argument is of type ‘const char *’
 __zpl_xattr_acl_list_default(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:89:28: warning: passing argument 4 of ‘__zpl_xattr_acl_list_default’ makes pointer from integer without a cast
      list_list_size, name, name_len));    \
                            ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1206:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_default);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1192:1: note: expected ‘const char *’ but argument is of type ‘size_t’
 __zpl_xattr_acl_list_default(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:88:10: error: too few arguments to function ‘__zpl_xattr_acl_list_default’
  return (__ ## fn(dentry->d_inode,    \
          ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1206:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_default);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1192:1: note: declared here
 __zpl_xattr_acl_list_default(struct inode *ip, char *list, size_t list_size,
 ^
In file included from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zpl.h:39:0,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_vnops.h:34,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:81:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_user_list’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:85:48: warning: control reaches end of non-void function [-Wreturn-type]
 fn(const struct xattr_handler *handler, struct dentry *dentry,  \
                                                ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:683:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_user_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_trusted_list’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:85:48: warning: control reaches end of non-void function [-Wreturn-type]
 fn(const struct xattr_handler *handler, struct dentry *dentry,  \
                                                ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:750:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_trusted_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_security_list’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:85:48: warning: control reaches end of non-void function [-Wreturn-type]
 fn(const struct xattr_handler *handler, struct dentry *dentry,  \
                                                ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:820:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_security_list);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_acl_list_access’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:85:48: warning: control reaches end of non-void function [-Wreturn-type]
 fn(const struct xattr_handler *handler, struct dentry *dentry,  \
                                                ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1189:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_access);
 ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c: In function ‘zpl_xattr_acl_list_default’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/linux/xattr_compat.h:85:48: warning: control reaches end of non-void function [-Wreturn-type]
 fn(const struct xattr_handler *handler, struct dentry *dentry,  \
                                                ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.c:1206:1: note: in expansion of macro ‘ZPL_XATTR_LIST_WRAPPER’
 ZPL_XATTR_LIST_WRAPPER(zpl_xattr_acl_list_default);
 ^
/usr/src/linux-4.4.0_dtop-I.2/scripts/Makefile.build:258: recipe for target '/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/zpl_xattr.o' failed
```

**Comment by kernelOfTruth** [comment]
It's even failing when using the patches against latest master,

so it could be the latest changes in master causing this,

thus: opened up a buildbot testing https://github.com/zfsonlinux/zfs/pull/4238

**Comment by behlendorf** [comment]
Refreshed to fix typo in macro.  That should fix the build issue for that kernel.

**Comment by kernelOfTruth** [comment]
@behlendorf your branch compiled fine and the rebased patches, too (behlendorf_zfs/linux-4.5-compat_17.01.2016_rebase-16.01.2016)

Thanks !

**Comment by behlendorf** [comment]
@dweeezil @tuxoko if either of you could review this I'd appreciate it.

**Comment by tuxoko** [comment]
@behlendorf 
I don't understand why you have two kinds of get_link and AC test. Isn't get_link introduced in 4.5?

**Comment by behlendorf** [comment]
@tuxoko there were two versions of it in.  It was first introduced by commit torvalds/linux@6b2553918d8b4e6de9853fd6315bec7271a2e592 and then changed in commit torvalds/linux@fceef393a538134f03b778c5d2519e670269342f.  The good news is that only the latter should ever show up in a tagged kernel but we should handle both regardless.

I should also mention these changes are a little bigger than is strictly necessary.  I took the opportunity to clean up and document the code so it's more maintainable.

**Comment by dweeezil** [comment]
I just started looking at this and see we now have a problem introduced by torvalds/linux@34c0fd54. The ```pfn_t``` type has been converted to a single-member struct.

**Comment by behlendorf** [comment]
@dweeezil man they move fast, luckily the `pfn_t` breakage is an easy fix.  That's something we don't currently use and can just remove.  I've updated the pull request accordingly and added a counterpart PR zfsonlinux/spl#524.  @tuxoko this might cause some trouble with the ABD patches since they do directly manipulate pages.

**Comment by behlendorf** [comment]
Rebased on master and refreshed to include the security_list issue found by @tuxoko.

**Comment by dweeezil** [comment]
I'll look this over again later.  Other than the issue @tuxoko pointed out, the rest looked OK to me.  I do actually want to build it, however, and in particular, examine the output of the autoconf scripts.

**Comment by behlendorf** [comment]
Refreshed with s/xattr_hander/xattr_handler.  Assuming the update version passes the buildbot and @dweeezil @tuxoko don't have any remaining issues I'd like to merge this so the kernel builders stop failing.

**Comment by tuxoko** [comment]
@behlendorf 
This looks good to me. But personally I'd wait till rc1 comes out, just to make sure.

**Comment by dweeezil** [comment]
@behlendorf The code LGTM.  I'm still going over the autoconf tests.

**Comment by behlendorf** [comment]
@dweeezil OK, just let me know when you're happy with them, I'll hold off until I hear from you.  @tuxoko   if they change something else before rc1 we can always address it then,

**Comment by dweeezil** [comment]
@behlendorf All the autoconf tests LGTM.

**Comment by behlendorf** [comment]
Thanks guys, merged as:

zfsonlinux/spl@de77e24 Linux 4.5 compat: pfn_t typedef
ae3a373 Linux 4.5 compat: pfn_t typedef
4967a3e Linux 4.5 compat: xattr list handler
beeed45 Linux 4.5 compat: get_link() / put_link()

**Pull request closed without merging**
