### PR TITLE
Fix typo in zfs-module-parameters man page

### PR DESCRIPTION
**Pull request by bunder2015**
### Description
Fix typo in zfs-module-parameters man page

### Motivation and Context
Makes my eyes not bleed

### How Has This Been Tested?
None should be necessary as it's a man page.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [x] My code follows the ZFS on Linux code style requirements.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [x] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by ptx0** [comment]
this needs more reviewers.

**Comment by ryao** [comment]
@ptx0 Good point.

@ahrens @tuxoko @nedbass @dweeezil @prakashsurya @ironMann @rlaager @dun @dajhorn @gunnarbeutner @tonyhutter @tcaputi @don-brady Would any of you care to contribute to a potential attempt at breaking the most reviewed patch in OpenZFS record? ;)

**Comment by behlendorf** [comment]
Merged, we'll have to make due with only 27 reviews!  Thanks.

**Comment by ryao** [comment]
I can say that this patch had the most of any that I have ever seen. It probably broke the old record. Someone will need to check to see if any patches have more reviewers to confirm. I'll be happy to let someone else volunteer to do that though.

**Pull request merged**
