### PR TITLE
Fix zfs-mount-generator for datasets with spaces

### LINKED ISSUE #8708: zfs-mount-generator breaks on spaces
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.18.0-15
Architecture	| amd64
ZFS Version	| 0.8.0\~rc4-1~rlaager1.18.04.1
SPL Version	| 0.8.0\~rc4-1~rlaager1.18.04.1

### Describe the problem you're observing
If the dataset `name` and/or `mountpoint` properties contain a space, `zfs-mount-generator` breaks. No `.mount` unit is generated for that dataset or subsequent datasets (at least in the same file).

### Describe how to reproduce the problem
Create a dataset with a space in the name. Run `/lib/systemd/system-generators/zfs-mount-generator`.

### Include any warning/errors/backtraces from the system logs
The kernel logs contain:
`zfs-mount-generator: invalid canmount`

### PR DESCRIPTION
**Pull request by rlaager**
This fixes `zfs-mount-generator` to handle datasets with a `name` and/or `mountpoint` property containing a space.

Fixes #8708

### Motivation and Context
This fixes zfs-mount-generator to handle datasets with a name and/or mountpoint property containing a space. See #8708.

### Description
The cache file is already tab separated, so by setting IFS to a tab, it stops splitting the fields on spaces.

**Note: My original implementation (with IFS prior to the `process_list` call) has been replaced by @aerusso with input from @chrisrd. See the comments below.**

### How Has This Been Tested?
I have several datasets with spaces in the name and mountpoints. After making this change, the generator operates properly.

I tested the generator with both `dash` and `bash`. This uses `printf` because the alternative construction of `IFS=$'\t'` is a bashism.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rlaager** [comment]
@aerusso Can you take a look at this, since you wrote the code originally?

**Comment by aerusso** [comment]
This is absolutely a good change. It's odd that I was worried about wildcards, but not spaces, in the mount path (hence the `set -f` noglob).

**Comment by chrisrd** [comment]
Setting the IFS could be lifted out of the `cachefile` loop as a micro optimisation, and perhaps a comment added along the lines of "cachefile is tab delimited: pass as separate args to process_line", but either way...

LGTM

**Comment by aerusso** [comment]
Adding a comment is a good idea, but IFS cannot be set before the `$(ls "${FSLIST}")` call. 

What would work is not disabling globbing, using a glob in the `for` loop, and *then* disabling globbing inside the loop. That gives a more robust processing of files in `/etc/zfs/zfs-list.cache/` (though this doesn't matter much because pools may only have alphanumeric characters, dash `-`, underscore `_`, and period `.` in their names). Something like 62850fa6c47b0a45bdf6514778c55f45b3b9ed32 might work, and avoids a call to `ls`.

**Comment by chrisrd** [comment]
Good point on my so-called "micro optimisation"!

In your new version I imagine the `set -f` is protecting against unwanted expansions in `$fs`. That probably also deserves a comment.

Maybe the safest/cleanest would be to call `process_line()` with a single arg, and split that in `process_line()` itself (and, whilst we're at it, also ensure we're only processing files), e.g.:

```
process_line() {
  IFS="$(printf '\t')" read -r \
    dataset \
    p_mountpoint \
    p_canmount \
    p_atime \
    ... \
<<END
$1
END
...
}

...

for cachefile in "${FSLIST}/"* ; do
  [ -f "${cachefile}" ] || continue
  while read -r fs; do
    process_line "${fs}"
  done < "${cachefile}"
done
```

**Comment by rlaager** [comment]
@aerusso 62850fa6c47b0a45bdf6514778c55f45b3b9ed32 works. I like that better. How/where did you push that commit? Are you open to making a PR with that? (If so, I'll close this in favor of that.)

**Comment by chrisrd** [comment]
Much cleaner way of splitting a single arg in `process_line()`:
```
process_line() {
  # fields are tab delimited
  IFS="$(printf '\t')"
  set -- $1
  dataset="${1}"
  p_mountpoint="${2}"
  p_canmount="${3}"
  p_atime="${4}"
  p_relatime="${5}"
  p_devices="${6}"
  p_exec="${7}"
  p_readonly="${8}"
  p_setuid="${9}"
  p_nbmand="${10}"
  ...
}

**Comment by aerusso** [comment]
https://github.com/aerusso/zfs/tree/pulls/IFS-v2

**Comment by rlaager** [comment]
@aerusso Yes, please make a PR and I'll close this. I updated this PR with your commit, and I was intending on approving it here, but it seems I cannot approve my own PR.

**Comment by rlaager** [comment]
Closing in favor of #8718 submitted by aerusso directly.

**Pull request closed without merging**
