### PR TITLE
Fix i_flags issue caused by 64c688d

### PR DESCRIPTION
**Pull request by tuxoko**
### Description

Fix zfs_xvattr_set to set S_IMMUTABLE and S_APPEND flags correctly.

Reinstate zfs_set_inode_flags and use it when zfs_xvatter_set and also when
setting up inode in zfs_znode_alloc and zfs_rezget.

Fix wrong operator in xvattr.h

### Motivation and Context

https://github.com/zfsonlinux/zfs/pull/5470
https://github.com/zfsonlinux/zfs/issues/5469

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by tuxoko** [comment]
Piggyback a dummy test for https://github.com/zfsonlinux/spl/pull/590

**Comment by behlendorf** [comment]
@dweeezil we could definitely do it in a separate PR but it sure would be nice to handle it right now as well as add a few test cases.

**Comment by tuxoko** [comment]
@behlendorf 
That is not a regression, it's a bug introduced with the chattr support...

**Comment by tuxoko** [comment]
Is zfstest file run with root? If so how do I drop privilege?

**Comment by behlendorf** [comment]
@tuxoko you can use the `user_run` function to drop privilege.  The `userquota/userspace_001_pos.ksh` is a pretty good example.  You'll need to make sure to add/remove the test user in `setup.ksh/cleanup.ksh` respectively.

**Pull request merged**
