### PR TITLE
Linux 4.8 compat

### PR DESCRIPTION
**Pull request by behlendorf**
An additional Linux 4.8 compatibility patch and the removal of some dead compatibility checks for old unsupported kernels.

### CODE REVIEW

**Comment by behlendorf** [comment]
@dweeezil @tuxoko OK, one more round of kernel compatibility patches.  The only critical one here is the `posix_acl_valid()` patch, but I took the opportunity to retire some compatibility checks for pre-2.6.32 kernels which are no longer needed.

**Comment by tuxoko** [comment]
@behlendorf 
The patches looks good.
But I'm kind of confused with the use of user_ns in kernel.
Now the i_uid_read uses s_user_ns, which means on-disk value will be stored in terms of s_user_ns, but it seems posix acl still store its value in terms of init_user_ns, I don't understand how it would work if the filesystem is remounted in another namespace.

**Comment by maxximino** [comment]
@tuxoko, see my comment in #4177 for details TL;DR: zfs code always receives the blob with UIDs relative to init_user_ns must emit a blob relative to init_user_ns. VFS takes care of the rest.

**Comment by tuxoko** [comment]
@maxximino I already know that. My question is about the discrepancy between uid/gid which uses s_user_ns, and posixacl which uses init_user_ns.

**Comment by behlendorf** [comment]
Things appear to be changing in the very latest kernels.  At least part of the story is documented in the recent torvalds/linux@6e4eab577a0cae15b3da9b888cff16fe57981b3e commit which added `s_user_ns`, and commit torvalds/linux@81754357770ebd900801231e7bc8d151ddc00498 which switched the uid/gid from using `init_user_ns` to `->s_user_ns`.

**Comment by behlendorf** [comment]
Merged as:

4b908d3 Linux 4.8 compat: posix_acl_valid()
e85a639 Retire HAVE_CURRENT_UMASK and HAVE_POSIX_ACL_CACHING

**Pull request closed without merging**
