### PR TITLE
Grsecurity compat: Call mount.zfs and umount.zfs directly

### LINKED ISSUE #4377: grsec: cannot enter .zfs/snapshot/X
when trying to enter .zfs/snaphot/X i get:
`too many levels of symbolic links`

in dmesg there are alot of:

`grsec: denied exec of usermode helper binary /bin/sh located outside of permitted system paths
`
manual mount of the snapshots works

### PR DESCRIPTION
**Pull request by stiell**
Grsecurity does not permit calling `/bin/sh` via `call_usermodehelper()`. Instead, call `/sbin/mount.zfs` and a new minimal helper `/sbin/umount.zfs` directly.

`umount.zfs` simply works by validating arguments and passing them to `/bin/umount -t zfs -i`.

Redirecting to `/dev/null` does not seem to be necessary. I tested by printing to `stdout` and `stderr` from a binary called by `call_usermodehelper()` and could not see the output in the console or any logs.

Fixes  #4377

### CODE REVIEW

**Comment by tuxoko** [comment]
Why do you want to create umount.zfs? I don't see any reason to do so.

**Comment by stiell** [comment]
Under Grsecurity, the kernel can't use anything in `/bin`, including `sh` and `umount`. Binaries in `/sbin` are allowed. The possibility of adding `/sbin/umount.zfs` was first mentioned in #1919.

**Comment by behlendorf** [comment]
Yes, I originally suggested adding `/sbin/umount.zfs` to handle this.  However, what I had in mind was a full blown mount helper like `mount.zfs` which actually issues the `umount(2)` system call.  This would lay some of the ground work needed if we wanted to optionally support things like illumos more aggressive force umount behavior (#2435).

**Comment by tuxoko** [comment]
But how does it behave on Arch? I remember Arch put everything in /usr/bin and other *bin are just symlinks.

**Comment by stiell** [comment]
Grsecurity will resolve symlinks before testing, but `/usr/bin` is among the permitted paths.

**Comment by Mic92** [comment]
+1 for reducing the number of programs to mount/unmount zfs.
As all executables required are controlled by zfs then I would use the variable sbindir configured in autotools rather then relying that distributors have a symlink from /sbin/mount.zfs

**Comment by behlendorf** [comment]
Closing in favor of the approach described in https://github.com/zfsonlinux/zfs/pull/4568#issuecomment-252047193.

**Review by johnlegend3476 — CHANGES_REQUESTED** [review]
Kemarkranium38@gmail.com

**Pull request closed without merging**
