### PR TITLE
Linux 5.3 compat

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Resolve Linux 5.3 build failures.  @kusumi would you mind reviewing this.

### Description

This PR contains three changes but only fa0047f0cc50a8dd3f8da0f82a88aefd111200d4 is required to resolve the build issue with 5.3.  The other two changes were included as additional cleanup in order to avoid potential future problems.  Over the years the rwsems have seen numerous changes and going forward it's desirable to be more resilient to kernel changes.

* fa0047f0cc50a8dd3f8da0f82a88aefd111200d4 Linux 5.3 compat: rw_semaphore owner
* e4d18399c30b57cb65aac37f4cd36c6d5e1de400 Linux 5.3 compat: retire rw_tryupgrade()
* 4459f2b44812f58f9e4da5f3a276ed8e8a16e612 Retire unused spl_{mutex,rwlock}_{init_fini}

### How Has This Been Tested?

Locally ran portions of the ZTS using the 5.3.0-0.rc0.git4.1.vanilla.knurd.1.fc30.x86_64 kernel.  Pending CI results to verify other kernels.  No significant performance regression was observed after disabling `rw_tryupgrade`.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by ahrens** [comment]
<3 the code simplification here, but have you evaluated the potential performance implications of never upgrading rwlocks?

**Comment by behlendorf** [comment]
> have you evaluated the potential performance implications of never upgrading rwlocks?

Yes, via code inspection of the callers.  There are 4 callers of `rw_tryupgrade()`, of which I believe only one, `dmu_zfetch()`, may have an impact on performance.  They are:

1) `dmu_zfetch()` - When creating a new zstream in `dmu_zfetch()`, if the code is unable to upgrade the `zf->zf_rwlock` the dnode's `dn_struct_rwlock` is dropped and reacquired, then the code rescans for a matching prefetch stream.  This behavior could be improved.

2) `zap_tryupgradedir()` - Most callers already hold the lock as a writer, and zap upgrades aren't expected to be a high frequency events so any impact here is expected to be minimal.

3) `dnode_new_blkid()` - Negligible (if any) change in behavior, on upgrade failure the read lock is dropped and immediately acquired as a writer.

4) `zfs_fuid_find_by_domain()` - Results in one additional call to `avl_find()` on failure, only reachable from `zfs_set_userquota()`.

If you can suggest a test case to stress `dmu_zfetch()` I'm happy to perform the testing.  Though, I'd like to address any loss in performance by updating the caller and not re-introducing `rw_tryupgrade()`.

**Comment by ahrens** [comment]
@behlendorf A good workload to exercise this is random reads or writes of 8k blocks (on recordsize=8k) with several threads (>=8 threads on an 8-CPU system worked well for me).

I happen to be working on some changes to the dmu_zfetch locking anyway (because even the current rwlock implementation has extreme performance pathologies).  So it's probably OK if this regresses performance of that somewhat.

**Comment by behlendorf** [comment]
@ahrens using the suggested workload (random 8k reads, 8k recordsize) I compared performance with and without this PR.  Tested using an ec2 c5d.xlarge instance type (4 vcpu, local NVMe instance storage, Amazon Linux 2,  4.14.128-112.105.amzn2.x86_64 kernel).  Based on these quick results I don't see any appreciable impact on performance.

processes |master (MiB/s) | patched (MiB/s)
--- | --- | --- 
1 | 52.9 | 52.3 |
2 | 109.0 | 109.5 |
4 | 189.9 | 191.1 |
8 | 188.3 | 186.7 |
16 | 186.9 | 187.4 |
32 | 189.2 | 191.9 |
64 | 190.3 | 188.4 |
128 | 189.8 | 188.6 |
256 | 191.0 | 190.1 |
512 | 195.2 | 192.8 |


<details open>
<summary>8k-read.fio</summary>
<pre>
[global]
filename=file
group_reporting=1
fallocate=0
overwrite=0
rw=randread
directory=/tank/fs/
runtime=10
bs=8192
ioengine=libaio
iodepth=1
sync=0
direct=1
size=32G
numjobs=${JOBS}

[job]
</pre>
</details>

Note: I also didn't observe any pathological degradation of perform when threads > ncpus.

**Pull request closed without merging**
