### PR TITLE
Add zfs_sb_prune_compat() function

### PR DESCRIPTION
**Pull request by behlendorf**
For kernels which do not implement a per-suberblock shrinker the
shrink_dcache_parent() function was used to attempt to reclaim
dentries.  This was found not be entirely reliable which could
lead to performance issues on older kernels running meta-data
heavy workloads.

To address this issue a zfs_sb_prune_compat() function has been
added to implement this functionality.  It relies on traversing
the list of znodes for a filesystem and adding them to a private
list with a reference held.  The private list can then be safely
walked outside the z_znodes_lock to prune dentires and drop the
last reference so the inode can be freed.

This provides the same synchronous behavior as the per-filesystem
shrinker and has the advantage of depending on only long standing
interfaces.

The number of threads in the iput taskq has also been increased
to speed up the handling of asynchronous iputs.  This improves
the rate of meta data reclaim regardless of the kernel version.

Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>

### CODE REVIEW

**Comment by behlendorf** [comment]
@dweeezil could you please review this.  It address the issues with `zfs_sb_prune()` for old kernels without a per-filesystem shrinker.  Without the patch, on CentOS 6, `dbench 64` blows right through the meta limit right up to arc_max since reclaim is largely ineffective.  With the patch I can run the same test with the arc_meta_limit cranked down to a tiny value and get the same behavior as newer kernels.

```
dbench -x -D /tank/dbench/  64 -t 1800
```

**Comment by odoucet** [comment]
can you be more precise on what "newer kernel" means ? In which version was introduced per-suberblock shrinker ? thank you !

**Comment by behlendorf** [comment]
@odoucet this patch is targeted for kernels older that Linux 3.1 (which is mentioned in a commit comment).  Commit 90947b2357157a376fdd23dadbcfedad82652525 which was just merged solves a similar problem for 3.12 and newer kernels.

**Comment by dweeezil** [comment]
@behlendorf This LGTM.  I generally don't run old enough kernels on my test systems to try it but it sounds like it helped your test scenario.  On a semi-related note, one item on my large-scale testing to-do list is to find other candidates for ```multilist_t``` and I have a feeling the ```z_all_znodes``` list might be a candidate.

**Comment by behlendorf** [comment]
@dweeezil refreshed.  I took a slightly different approach with the updated version and I like it much better.  It also has passed an hour of so of torture testing just fine and I'll leave it running (although I don't expect any issues).  If you could look it over again I'd appreciate it.

Initially I was just going to wrap the list_node_t I added with an `#ifdef` but that looked pretty horrible.  Instead I opted not to use a list at all and allocated a small private array of pointers.  This does introduce a small memory allocation but it several big advantages.

* All the compatibility code is now confined to a small block in `zfs_vfsops.c`.  That's good for portability and preventing upstream merge conflicts.
* Removes the need to take the `znode->z_lock` since the array is private.
* Avoids increasing the size of a znode_t in all cases.

Other changes include:

* Added autoconf check for `d_prune_aliases()` just to be extra careful.
* Made the !HAVE_SPLIT_SHRINKER_CALLBACK && !HAVE_SHRINK && !HAVE_D_PRUNE_ALIASES case fatal at build time to ensure we always have a valid pruning mechanism.
* Renamed `zfs_sb_prune_compat()` to `zfs_sb_prune_aliases()`.
* Split the iput taskq tweak in to its own patch where it should have always been.

> On a semi-related note, one item on my large-scale testing to-do list is to find other candidates for multilist_t and I have a feeling the z_all_znodes list might be a candidate.

That's an excellent idea.  Definitely `z_all_znodes` is a candidate and that probably makes sense for upstream.  But under Linux I think we'd frankly be better off retiring it outright and using the existing super block lists.

**Comment by dweeezil** [comment]
@behlendorf LGTM.  I like the 207a3ae scheme much better.  The af8e61d commit also LGTM.

**Comment by behlendorf** [comment]
@dweeezil thanks for the review.  I've added your signed-off-by and merged these changes:

218b4e0 Add zfs_sb_prune_aliases() function
4c6a700 Increase the number of iput taskq threads

**Pull request closed without merging**
