### PR TITLE
Make arc_summary.py compatible with python3

### LINKED ISSUE #4084: arc_summary.py isn't python3 compatible
~ # python --version
Python 3.4.3

~ # head -1 $(which  arc_summary.py)
#!/usr/bin/python

~ # arc_summary.py 
  File "/bin/arc_summary.py", line 1135
    except IndexError , e:
                      ^
SyntaxError: invalid syntax

### PR DESCRIPTION
**Pull request by dasjoe**
To make arc_summary.py compatible with python3 some minor fixes were
required, this was done automatically by `2to3 -w arc_summary.py`.
Fixes #4084.

Signed-off-by: Hajo Möller <dasjoe@gmail.com>

### CODE REVIEW

**Comment by behlendorf** [comment]
Neat I didn't even know such a tool existed.   We should check the handful of other python scripts as well.

**Comment by rlaager** [comment]
I didn't test this, but I did review the diff, and it looks good to me.

The "as" syntax makes this require Python 2.6. That's in Debian squeeze and at least CentOS 6, so that seems fine to me.

**Comment by behlendorf** [comment]
That should be OK since we only need to support back to 2.6 for Debian squeeze and CentOS 6.

**Comment by behlendorf** [comment]
Merged as:

7cf2ffa Make arc_summary.py and dbufstat.py compatible with python3

**Pull request closed without merging**
