### PR TITLE
Fixes according to kmemleak and kasan

### PR DESCRIPTION
**Pull request by tuxoko**
Fix out-of-bound access in zfs_fillpage
Fix memleak in zpl_parse_options
Fix memleak in vdev_config_generate_stats

### CODE REVIEW

**Comment by tuxoko** [comment]
Fix #4705 #4706 #4707

**Comment by behlendorf** [comment]
These all LGTM.  @tonyhutter could you also please look these over.

@tuxoko with these fixes applied are there any other issues reported by kmemleak or kasan?

**Comment by tuxoko** [comment]
These are the only things I saw, but my test coverage is probably not that much. I haven't run zfs-tests yet.

**Comment by tuxoko** [comment]
My VM paniced as soon as I try to run zfs-tests. It seems the stack sky rocketed when kasan and kmemleak are enabled.

**Comment by ptx0** [comment]
fixes my issue

**Comment by tonyhutter** [comment]
Nice work @tuxoko  LGTM

**Comment by behlendorf** [comment]
Merged as:

6a79672 Fix memleak in vdev_config_generate_stats
06ee003 Fix memleak in zpl_parse_options
540c392 Fix out-of-bound access in zfs_fillpage

**Comment by tuxoko** [comment]
So the problem with zfs-tests is not really stack issue, it's an unknown bug in the kernel that has been fixed.

**Pull request closed without merging**
