### PR TITLE
Godfather's child I/Os that  may can't done and lost chance to reexecute again

### PR DESCRIPTION
**Pull request by liaoyuxiangqin**
@behlendorf A new pull request and code commit for https://github.com/zfsonlinux/zfs/pull/5043 , please review again and give advice, thanks!

### CODE REVIEW

**Comment by behlendorf** [comment]
@liaoyuxiangqin can you describe how you were able to trigger this issue or even better provide a test case so we can verify the proposed fix.  Please also rebase this branch on master so we can get a clean test run with the buildbot.

**Comment by liaoyuxiangqin** [comment]
@behlendorf  This issue is occasional occurs when i testing as  following test case. At first, when accessing the ZFS filesystem via NFS(v3/v4), disconnect and connect the pool's member disk link repeatedly at the same time, so that the pool was suspended after first step.  In the second step, perform zpool clear to clear pool errors and which will resume suspended zio, and during the second step also disconnect and connect the pool's member disk link repeatedly. After such tests many times, the pool occasional  occured zio can't done and lost chance to reexecute again, and the spa sync thread will suspend due to wait this zio to execute done.

**Comment by behlendorf** [comment]
@grwilson can we get your thoughts on this.

**Comment by grwilson** [comment]
From what I read it appears that there is a circumstance when a Godfather I/O can end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag. Am I understanding the problem correctly? If so, this seems like the bug and I want to understand more about how we get into that situation.

**Comment by liaoyuxiangqin** [comment]
right, your understanding of this problem is correct. This problem is occasional occurs on Test scenarios as following  described.  
 At first, when accessing the ZFS filesystem via NFS(v3/v4), disconnect and connect the pool's member disk link repeatedly at the same time, so the pool was suspended after first step and may be exist  multiple logical zio's io_reexecute flag set ZIO_REEXECUTE_SUSPEND and add to spa_suspend_zio_root's child io list. 

In the second step, perform zpool clear to clear pool errors and which will reexecute all previously suspended i/o, and during the second step also disconnect and connect the pool's member disk link repeatedly. under this circumstances, these suspended logical zio may return different io_error value, and  its io_reexecute flag may set different bit.  Because of Godfather I/O inherit child's  io_reexecute flag, so it  can end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag.

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by liaoyuxiangqin** [comment]
The above of my commented is described from the angle of the testing, and because this issue is occasional occurs, so i just described the testing scenarios can't fully confirmed the issue. 

can you describe the possibility of a  Godfather I/O will end up having both ZIO_REEXECUTE_NOW and ZIO_REEXECUTE_SUSPEND set in its io_reexecute flag from the angle of the code logic. thanks!

**Comment by behlendorf** [comment]
Superseded by #5687.  The proposed fix remains identical to what was proposed in this PR I've just done some wordsmithing of the commit comment.

**Pull request closed without merging**
