### PR TITLE
[WIP] ZFS master 31.08.2015+illumos 4950

### PR DESCRIPTION
**Pull request by kernelOfTruth**
[Pushing an updated branch to see whether I can make sense of the error message]

Reviewed by: Adam Leventhal <adam.leventhal@delphix.com>
Reviewed by: George Wilson <george.wilson@delphix.com>
Reviewed by: Sebastien Roy <sebastien.roy@delphix.com>
Reviewed by: Boris Protopopov <bprotopopov@hotmail.com>
Approved by: Dan McDonald <danmcd@omniti.com>
Ported-by: Richard Yao <richard.yao@clusterhq.com>

Porting notes:
1. ZoL currently does not log discards to zvols, so the portion of this patch that
modifies the discard logging to mark it as freeing space has been discarded.

2. may_delete_now had been removed from zfs_remove() in ZoL. It has been
reintroduced.

3. We do not try to emulate vnodes, so the following lines are not valid
on Linux:

	mutex_enter(&vp->v_lock);
	may_delete_now = vp->v_count == 1 && !vn_has_cached_data(vp);
	mutex_exit(&vp->v_lock);

This has been replaced with:

	mutex_enter(&zp->z_lock);
	may_delete_now = atomic_read(&ip->i_count) == 1 && !(zp->z_is_mapped);
	mutex_exit(&zp->z_lock);

References:
https://www.illumos.org/issues/4950
https://github.com/illumos/illumos-gate/commit/4bb73804952172060c9efb163b89c17f56804fe8

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
>[Pushing an updated branch to see whether I can make sense of the error message]

seems like it helped,

there not that stuck error message anymore which doesn't make little sense in regard to this pull-request

pushed a few changes ...

**Comment by sempervictus** [comment]
@kernelOfTruth: have any good test cases for us to validate that this works without discarding blocks we might want to keep? Things which deal with discard, trim, and other sub-vdev-level ops should probably be tagged as "able to eat your cat" - we've recently had a bunch of corruption and data loss from being stupid and finding the co-morbidity in ABD+loop_fix-for-4.1 prior to the actual ABD loop fix being published :).

**Comment by kernelOfTruth** [comment]
@sempervictus haha - I get were you're coming from - I've seemingly also lost some data with that loop fix incident - albeit (luckily) not too important

To be honest I haven't thought about additional test-cases to check for those eventualities, the only thing countering these so far is in using additional backup media with different filesystems from ZFS (also no zvols, etc.)

Only @ryao 's part is verified to be working (haven't tried to almost entirely fill pools and do send, receive, rollback, etc. operations) - the other commit is still work on progress and incomplete, as indicated by the buildbots

**Comment by kernelOfTruth** [comment]
not sure how to address (line 1698, 1699)

```
vp->v_count--;
ASSERT0(vp->v_count);
```

since we're not using that

**Comment by kernelOfTruth** [comment]
@behlendorf I believe the buildbots went out to lunch for quite a long time now

are they broken ? (also no follow-up updates on the other pull-requests)

**Comment by kernelOfTruth** [comment]
sad that the buildbots can't work on an older code-base - would have been easier that way, seems like I must rely on GCC and compile-time testing then ...

yes, yes - another rebase seems to be in order :disappointed:

**Comment by kernelOfTruth** [comment]
superseded by https://github.com/zfsonlinux/zfs/pull/3891 [WIP] ZFS master 02.10.2015+illumos 4950

**Pull request closed without merging**
