### PR TITLE
[WIP] Add library for high level ZFS tasks

### PR DESCRIPTION
**Pull request by johnramsden**
Add functions to library for high level ZFS tasks to abstract away the complexities of libzfs to make it easier to write programs using a C library.

### Motivation and Context

Currently, if someone wants to implement features such as taking snapshots, and creating datasets, they have to use `libzfs`, requiring them to have knowledge of the inner workings of the ZFS codebase. In
addition to this, the only documentation is the code. An interface to abstracts away the internals would make writing unsafe code - when a developer tries to write code using ZFS - much less likely. Right now
there are alternatives like calling out to the `zfs` command, but that isn't exactly ideal.

I attempted writing a program that uses `libzfs` directly, and eventually found that it is quite complex, and difficult to use directly.

If a higher level library were to be written that performs many of the functions of the `zfs` command, it would make writing programs using ZFS much easier. Something like `libzfs_cmd_zfs_clone(...)`, `libzfs_cmd_zfs_clone(...)`, `libzfs_cmd_zfs_*(...)` for example.

### Description of Changes

In order to achieve these higher level ZFS functions, the code that is currently used to do the different, cli subcommands will be moved to `libzfs_cmd.c`, and new functions will be added to the library. 

The cli code will do the parsing of commandline options, and will then call the associated `libzfs_cmd` function. In this manner the code can be reused for writing C programs, and that same code will be used to do the zfs subcommands.

### How Has This Been Tested?

Minimally. It is a work in progress.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by mskarbek** [comment]
+100
Also, such a library should cover `zpool` operations and that would make my life much easier.

**Comment by alek-p** [comment]
Have you considered using channel programs as they could perform these high level tasks as well

**Comment by johnramsden** [comment]
@alek-p I had not, I'll look into the idea.

**Comment by mskarbek** [comment]
@alek-p channel programs don't cover pool operations. Binding to libzfs is AFAIR discouraged and libzfs_core also do not provide pool manipulation functionality. It would very appreciate the ability to manipulate pools (create, destroy) using some high-level programmatic interface.

**Comment by sdimitro** [comment]
@mskarbek libzfs_core does provide some support for pool manipulation (e.g. pool_reopen, pool_checkpoint, etc...). I think we should consider adding more functionality there instead of introducing another library. Is there any reason you think the functionality that you are looking for could not be added to libzfs_core?

**Comment by mskarbek** [comment]
@sdimitro no, if there is a place for such support in libzfs_core then I'm happy with that.

**Comment by johnramsden** [comment]
@sdimitro I was under the impression the other libraries were kind of building blocks to provide core ZFS functionality and wasn't sure if it was a suitable place to put high-level ZFS functions. I'd be definitely satisfied with the functionality being added to the existing library though if it makes more sense.

**Comment by johnramsden** [comment]
The other thing is, it stated in libzfs_core that the functions should correspond 1:1 to ioctls

https://github.com/zfsonlinux/zfs/blob/4d044c4c1d68ed518fe37eea61a4cc77048940fb/lib/libzfs_core/libzfs_core.c#L53-L55

Would these new high-level function really make sense to be ioctls? Or is it more of a guideline, and doesn't necessarily have to be true for every function?

**Comment by sdimitro** [comment]
Hey @johnramsden,
My suggestion was more about @mskarbek's needs on creating/destroying pools example. Libzfs_core is indeed supposed to be a thin layer on top of the existing ZFS ioctls.

**Comment by johnramsden** [comment]
@sdimitro I see. So there isn't a suitable current location for high-level ZFS functions then? It still might make sense to have a new library?

**Comment by alek-p** [comment]
High level `zfs` task are available through channel programs.

`zpool` functionality is not exposed there however.

**Comment by kpande** [comment]
work should instead be focused on expanding ZCP with `zpool` functionality.

**Comment by ahrens** [comment]
**Speaking to the general idea of adding new library functionality:**

libzfs_core is a low-level interface.
libzfs is relatively high-level.

It would be appropriate to add "helper functions" (which some of these appear to be) into libzfs.  I don't think there's a need for another library (and this PR does not add a new library, it just adds some functions to libzfs).

It is nontrivial to add most `/sbin/zpool` operations to channel programs since channel programs operate entirely in syncing context, but most zpool-level operations (e.g. add/remove device) operate in a combination of open context and syncing context.

**To comment on the specific interfaces this PR is adding:**

- `libzfshl_snapshot`: create a snapshot + open handle
I don't see this as adding a ton of value, but as a convenience function it would be fine to add this to libzfs if other folks find it useful.

- `libzfshl_clone`: create a clone with properties
This seems functionality the same as the existing `zfs_clone()`, it just uses a new struct to take the list of properties.  I guess if you've built a bunch of infrastructure around the new representation of properties, this could be useful?  But the new prop representation is equivalent to the existing nvlist representation, so I don't see a lot of value there.

- `libzfshl_get_prop*`: getting properties (with handling for all the different types of properties, e.g. user props, user/groupused, written, etc)
This is already handled quite well by channel programs, thanks to work by @shartse.  It would be appropriate to add a libzfs helper function to run an appropriate channel program to retrieve properties by string-name.

**Comment by johnramsden** [comment]
I took a look at ZCP, and I think they pretty much do provide all the functionality that I need, I guess I'll close this PR for now.

I still think it might be beneficial to have a library that provides a way within C to invoke functions equivalent to all of the `zfs` subcommands. Maybe a better way to do this would be to refactor [cmd/zfs](https://github.com/zfsonlinux/zfs/tree/master/cmd/zfs) so that's the same code could be used to double as a library where equivalents of all of the `zfs_do_*(...)` functions could be called.

**Comment by ahrens** [comment]
> have a library that provides a way within C to invoke functions equivalent to all of the zfs subcommands ... equivalents of all of the `zfs_do_*()` functions

That sounds fine to me; it would be a truly high level interface.

**Comment by johnramsden** [comment]
Okay, I guess I might as well continue with that work here then. 

@ahrens So does something like my [last commit](https://github.com/zfsonlinux/zfs/pull/7677/commits/dbfba67c11b61c370830053e72ce2001216c5990) make sense? I tried to convert `zfs_do_clone(...)` do something reusable. If that seems reasonable I'll continue to convert the rest of the functions in the same way. 

I had a question about error output though. What is the usual way of expressing an error if it's in a non cli area of the code? For example in [`zfs_mount_and_share(...)`](https://github.com/zfsonlinux/zfs/pull/7677/commits/dbfba67c11b61c370830053e72ce2001216c5990?utf8=%E2%9C%93&diff=unified#diff-360f49637f7a2623dfe669705e3e92fbR308) output is printed to stderr if a problem occurs. Should Library functions print nothing and just return success or failure, and have all error output be contained in the cli code? Or should I print what the problem is to stderr when an error occurs in library functions?

---

I'm having trouble with the adding the new function when I compile. 

``` 
zfs_main.o: In function `zfs_do_clone':
/home/john/Workspace/C/zfs/cmd/zfs/zfs_main.c:802: undefined reference to `libzfs_cmd_zfs_do_clone'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:670: zfs] Error 1
make[2]: *** [Makefile:606: all-recursive] Error 1
make[1]: *** [Makefile:783: all-recursive] Error 1 
```

Is there something else I need to do to have the new functions work in libzfs?

**Comment by johnramsden** [comment]
I'm not sure what to do about functions that print to stdout. Should I just skip the `get` function, since it is just gathering info? Return an array of strings? Not sure about this one.

Second thing is, with the functions that print to stderr, it doesn't seem right to print error messages from a library. For example, if the destroy function fails it will print different things depending on the situation, say _"could not find any snapshots to destroy; check snapshot names"_. 

Should I just return an error message or code for each situation where an error code would be printed?
This way the user calling the function knows what error occurred, and in the `cmd/zfs` code we can print the error.

**Comment by ahrens** [comment]
@johnramsden Yes, error handling is the difficult part of a high-level library.  I'm not sure there are any easy answers for you here.

**Comment by johnramsden** [comment]
@ahrens OK, thanks. Wasn't sure if there was a convention I was supposed to follow.

**Comment by johnramsden** [comment]
This is going to end up being a lot more code than I thought, so I'm not sure how long it will take me to go through the rest of the commands. I have now done most of the preparation work, and have a few, commands working, saving to a buffer. 

I also had to make some changes in a few other files related to printing errors, to allow them to save to a buffer.

**Comment by johnramsden** [comment]
If anyone can help I'm having a bit of trouble figuring out what's causing a test failure since I added the 'upgrade' command 0a7ba96. 

Here is an excerpt from a failed [test](http://build.zfsonlinux.org/builders/Fedora%2028%20x86_64%20%28TEST%29/builds/750): 

```
abd_cmp_buf(abd, buf, n) == 0 (0x30 == 0x0)
ASSERT at ../../module/zfs/abd.c:902:abd_return_buf()/usr/sbin/ztest(+0x8a07)[0x55bdca1c2a07]
/lib64/libpthread.so.0(+0x11fb0)[0x7fb554d34fb0]
/lib64/libc.so.6(gsignal+0x10b)[0x7fb55499af4b]
/lib64/libc.so.6(abort+0x12b)[0x7fb554985591]
/lib64/libzpool.so.2(+0x5246e)[0x7fb555faa46e]
/lib64/libzpool.so.2(+0x53808)[0x7fb555fab808]
/lib64/libzpool.so.2(+0x10f434)[0x7fb556067434]
/lib64/libzpool.so.2(+0x4ac67)[0x7fb555fa2c67]
/lib64/libpthread.so.0(+0x7564)[0x7fb554d2a564]
/lib64/libc.so.6(clone+0x3f)[0x7fb554a5e31f]
child died with signal 6
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdb        30G  943M   27G   4% /mnt 
``` 

So it seems to be a failure in the abd_cmp_buf function from [module/zfs/abd.c#L902](https://github.com/zfsonlinux/zfs/blob/fd7265c646f40e364396af5014bbb83e809e124a/module/zfs/abd.c#L902). I can't figure out why the commit would be causing this failure.

**Comment by behlendorf** [comment]
@johnramsden it looks like you just got unlucky.  Both of the ztest failures have been observed rarely in other PRs and are unrelated to your changes.

**Comment by johnramsden** [comment]
@behlendorf I'm getting it on every commit now, which makes me wonder if it _is_ something I have done.

**Comment by johnramsden** [comment]
Found a better solution to the problem which I am going to need to change a fair bit about this pr. I will update it soon.

**Comment by johnramsden** [comment]
If I could get a bit of a review on this by anyone, it would be appreciated. Just wondering whether or not my approach is sound.

I [was](https://github.com/johnramsden/zfs/tree/libzfshl_message_list) adding data directly to a buffer using a linked list, and passing a pointer to the list to every function that needed to add to it. Modifying every function that needs to print to proved to be very invasive to the code base, and I didn't think it was feasible.

A [new approach](https://github.com/zfsonlinux/zfs/blob/d5046359768db387e00d18bd731245d0b7ee97ab/lib/libzfs/libzfs_output.c#L167) I I'm trying is opening up a buffer to a stream with [open_memstream](https://linux.die.net/man/3/open_memstream). This gives you a file object you can use like stderr/stdout, which makes changing the code base a lot easier since it just means replacing `fprintf(stdout, "")` with `fprintf(stro(), "")`. Every call to `stro()` or `stre()` will add information to a list and open up a new memstream every time the stream changes between stderr and stdout, this way the list can just be walked through in order to get the output later.

If `use_stdout == B_TRUE`, the old way of printing everything to `stdout` will be used, and `stre()` and `stro()` just return `stderr` and `stdout`. This is the default unless changed. Currently the way I am changing this to `B_FALSE` is with a `init_stream_list(...)` function which sets up a linked list, and allocates anything needing allocating. 

Something I'm having a bit of trouble with is knowing whether or not I need to be replacing stderr and stdout in files outside of `lib/libzfs`, since I'm not sure how much code gets called to libraries outside of there from libzfs. Is it okay for me to just replace everywhere in the codebase stderr/stdout are used with a call to `stro()` or `stre()`? Or is that not necessary?

It ends up being a lot of trouble trying to stop any output from occurring since in the current zfs code, things just get printed directly all the time. Should I abandon the idea of stopping all output from the libraries? Should a library that is going to be used externally not print anything ever?

**Comment by loli10K** [comment]
> Modifying every function that needs to print to proved to be very invasive to the code base, and I didn't think it was feasible.

Exactly, that would also make syncing with upstream very challenging.

> A new approach I I'm trying is opening up a buffer to a stream with open_memstream.

Again, considering the need to push/pull patches from upstream we should probably use APIs that are known to be supported on other platforms: with that in mind i don't think `open_memstream` would work on OpenZFS (https://www.illumos.org/issues/7092).

**Comment by johnramsden** [comment]
@loli10K I was a bit worried about that. Since I'm now starting my second right through I figured it was probably the right time to ask.

What about going ahead and moving the calls to a separate file, as done with [zfs clone](https://github.com/zfsonlinux/zfs/blob/d5046359768db387e00d18bd731245d0b7ee97ab/lib/libzfs/libzfs_cmd.c#L158-L160) but leaving the printing as is. Meaning users that end up using it will get input sent to stderr/stdout. Part of what this means is that everything should stay the same for ZFS, but if people want to use the library externally it will be a lot easier.

**Comment by loli10K** [comment]
@johnramsden i'm not opposed to such a change as long as it doesn't break existing functionality and is accepted upstream, though it's not yet clear to me, from the "Motivation and Context" section of the PR template, why libzfs_core or ZCP cannot be used and improved/expanded where needed.

**Comment by johnramsden** [comment]
@loli10K Well, lzc is just supposed to be a 1 to 1 match with ioctls, so I dont think it's the right place for expansion.

As for ZCP, I guess maybe that is the way to go. They aren't available yet in the zfs version i'm on, so I kind of discounted them. Guess I just need to wait for the next release.

**Pull request closed without merging**
