### PR TITLE
Dummy for spl 577

### PR DESCRIPTION
**Pull request by tuxoko**
Signed-off-by: Chunwei Chen <david.chen@osnexus.com>
Requires-spl: refs/pull/577/head

### CODE REVIEW

**Comment by behlendorf** [comment]
It looks like there's really been quite a lot of churn in the kernel's rw sem implementation recently.  Can you point me at the kernel commit where this changed.

You can rebase zfsonlinux/spl#577 on the latest spl/master to resolve the aarch64 and kernel.org build failures.

**Comment by tuxoko** [comment]
Rebased. I link the kernel commit in the commit message in https://github.com/zfsonlinux/spl/pull/577

**Comment by tuxoko** [comment]
You didn't miss that. I added that after your comment. :smiley:

**Comment by behlendorf** [comment]
@tuxoko that makes me feel a little better!

With this patch applied I was able to run all of the ZFS Test Suite with a mainline 4.8 kernel.

**Pull request closed without merging**
