### PR TITLE
Illumos 5056 - ZFS deadlock on db_mtx and dn_holds

### PR DESCRIPTION
**Pull request by chrisrd**
Pull in Illumos 5056 with a largely mechanical application of Illumos patches.

Let's get the buildbots chewing on this patch stack...

(See also #3239, #3240)

### CODE REVIEW

**Comment by chrisrd** [comment]
Sorry, I need some help here...

There have been two similar buildbot failures with this patch set:

http://buildbot.zfsonlinux.org/builders/fedora-21-x86_64-builder/builds/920/steps/shell_17/logs/stdio
http://buildbot.zfsonlinux.org/builders/fedora-18-x86_64-builder/builds/2996/steps/shell_17/logs/stdio

```
VERIFY(list_is_empty(list)) failed
PANIC at list.h:88:list_destroy()
```

The stack traces are basically like:
```
deactivate_super
  deactivate_locked_super
    zpl_kill_sb
      kill_anon_super
        generic_shutdown_super
          zpl_put_super
            zfs_umount
              zfs_sb_free
```

I think the `VERIFY` is coming from:
```
  zfs_sb_free
    list_destroy(&zsb->z_all_znodes)
      ASSERT(list_is_empty(list));
```

...where the `list_destroy()` isn't visible in the call trace because it's declared `static inline`.

Before calling `zfs_sb_free()`, `zfs_umount()` calls `zfs_sb_teardown()` which in turn iterates over the `z_all_znodes` list:
```
        for (zp = list_head(&zsb->z_all_znodes); zp != NULL; zp = list_next(&zsb->z_all_znodes, zp)) {
                if (zp->z_sa_hdl)
                        zfs_znode_dmu_fini(zp);
        }
```

`zfs_umount()` then calls `zfs_sb_free()` which does the `list_destroy()` which hits `ASSERT` per above.

The thing is, even without this current patch set applied, if `z_all_znodes` isn't empty before getting into `zfs_umount()`, I can't see anything which would drain `z_all_znodes` (nor any waiting for a taskq which might be draining it) between iterating over the list in `z_all_znodes()` and destroying it in `zfs_sb_free()`.

Does that mean that in (unpatched) master, `z_all_znodes` is actually always empty before we get into `zfs_umount()` (and therefore the iteration in `zfs_sb_teardown()` is superfluous), and the patch set has somehow caused `z_all_znodes` to be not empty before `zfs_umount()`?

Presumably the fact that the majority of the buildbots didn't see this problem means there's a race here somehow. Is it a missing `taskq_wait()` or something?

I'm pretty lost here. Any help would be appreciated!

**Comment by kernelOfTruth** [comment]
@chrisrd in previous iterations of this pull-request something similar already occured: https://github.com/zfsonlinux/zfs/pull/3240#issuecomment-88260165

**Comment by chrisrd** [comment]
@kernelOfTruth yes, I think that instance was the earlier buildbot log mentioned above, i.e.:

http://buildbot.zfsonlinux.org/builders/fedora-21-x86_64-builder/builds/920/steps/shell_17/logs/stdio

**Comment by chrisrd** [comment]
Two buildbot failures on my 3c54650 debug build:

1. http://buildbot.zfsonlinux.org/builders/ubuntu-12.10-amd64-builder/builds/3022
Failure in `test import`. No idea what happened there, `test dmesg` doesn't show anything (outside of the added debug logging). On the other hand, the actual failed test output looks the same as...

2. http://buildbot.zfsonlinux.org/builders/ubuntu-13.04-amd64-builder/builds/2961
Failure in `test import`. `test dmesg` looks like #3165

Unfortunately neither is the `VERIFY(list_is_empty(list)) failed` I'm actually trying to track down. On the other hand, the added debug logging shows that it's normal for the `z_all_znodes` list to be non-empty in `zfs_sb_teardown()` and not cause problems in `zfs_sb_free()`. Perhaps this code at the end of `zfs_sb_teardown()` is what's normally draining `z_all_znodes`:
```
        /*
         * Evict cached data
         */
        if (dsl_dataset_is_dirty(dmu_objset_ds(zsb->z_os)) &&
            !zfs_is_readonly(zsb))
                txg_wait_synced(dmu_objset_pool(zsb->z_os), 0);
        dmu_objset_evict_dbufs(zsb->z_os);
```

...but if that's the case, that doesn't explain how we're hitting:
```
zfs_sb_free
    list_destroy(&zsb->z_all_znodes)
      ASSERT(list_is_empty(list));
```

Hmmm, I should have added the same sort of debug logging to `zfs_sb_free()` as well... I'll add that and try again.

**Comment by chrisrd** [comment]
One buildbot failure on my @eb51e56 debug build:

1.http://buildbot.zfsonlinux.org/builders/ubuntu-10.04.3-amd64-builder/builds/2730/steps/shell_9/logs/stdio
Failure in `test ztest`: ztest: ../../module/zfs/vdev.c:1774: Assertion `scn->scn_phys.scn_min_txg <= vdev_dtl_min(vd) (0x429 <= 0x3)' failed.

Still no sign of the `VERIFY(list_is_empty(list))` failure. I'm starting to think the random mix of failures are endemic rather than related to the patch stack being tested.

I'll rebase to current `HEAD` @f42d7f4 `Use vmem_alloc() in spa_config_write() ` and push once more to see what pops up.

**Comment by chrisrd** [comment]
Yay! We finally got another `VERIFY(list_is_empty(list))` failure, and it's even instrumented to some degree:

http://buildbot.zfsonlinux.org/builders/centos-7.0-x86_64-builder/builds/1817/steps/shell_17/logs/stdio
```
...
[ 2698.754741] zfs_sb_teardown: z_all_znodes contains i_ino=151441, mode=0x8180
[ 2698.754748] zfs_sb_teardown: z_all_znodes contains i_ino=151444, mode=0x8180
[ 2698.754773] zfs_sb_teardown: unmounting=1 zsb->z_os=[set] len(zfs_all_znodes)=17503
...
[ 2698.902703] zfs_sb_free: z_all_znodes contains i_ino=151441, mode=0x8180
[ 2698.902703] zfs_sb_free: z_all_znodes contains i_ino=151444, mode=0x8180
[ 2698.902703] zfs_sb_free: len(zfs_all_znodes)=1647

```
So, in `zfs_sb_teardown()` we had 17,503 entries on our `zfs_all_znodes` list. By the time we hit `zfs_sb_free()` a few lines of code later, we still had 1,647 entries on the list, just before we try to delete the list and blow up because the list isn't empty.

I.e. we should be waiting on ***something*** to drain the list. It probably works "most of the time" because, from the other buildbot logs, most of the time the list is empty or has only a few members when we hit `zfs_sb_teardown()`, then by the time we get to `zfs_sb_free()` whatever it is that drains the list has had time to do it's work. So, now to find what's draining the list and to work out how to wait for it...

**Comment by chrisrd** [comment]
For anyone following along, the `VERIFY(list_is_empty(list))` failures have moved to #3281

**Comment by behlendorf** [comment]
@chrisrd great job porting all these patches from Illumos / FreeBSD.  I've looked them over and they look good to me and they pass the testing.  However, I wanted to check with you first to see if you have any reservations about these.

**Comment by chrisrd** [comment]
@behlendorf the only reservations I had were around the buildbot failures (#3281) which I think we're now confident are a separate issue. I've been running this patch stack on my own servers (rsync w/ millions of small files and directories) for a couple of weeks now without any problems.

**Comment by behlendorf** [comment]
@chrisrd thanks, I just wanted to double check.  I haven't observed any issues either.  This entire patch stack has been merged to master:

6186e29 Illumos 5592 - NULL pointer dereference in dsl_prop_notify_all_cb()
6ebebac Illumos 5531 - NULL pointer dereference in dsl_prop_get_ds()
0c66c32 Illumos 5056 - ZFS deadlock on db_mtx and dn_holds
d683ddb Illumos 5314 - Remove "dbuf phys" db->db_data pointer aliases in ZFS
945dd93 Illumos 5310 - Remove always true tests for non-NULL ds->ds_phys
9925c28 Illumos 5095 - panic when adding a duplicate dbuf to dn_dbufs
5aea364 Illumos 5038 - Remove "old-style" flexible array usage in ZFS.
8951cb8 Illumos 4873 - zvol unmap calls can take a very long time for larger dat
58c4aa0 Illumos 4975 - missing mutex_destroy() calls in zfs
ca227e5 Illumos 3897 - zfs filesystem and snapshot limits (fix leak)
788eb90 Illumos 3897 - zfs filesystem and snapshot limits

**Pull request closed without merging**
