### PR TITLE
minor improvement to abd_free_pages()

### PR DESCRIPTION
**Pull request by jxiong**
It doesn't need to have a loop to free page in a single scatterlist
entry because it should be single or compound page. The pages can be
freed in one invocation to __free_pages() for both cases.

Signed-off-by: Jinshan Xiong <jinshan.xiong@gmail.com>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [-] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [-] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by ryao** [comment]
This looks right to me at a glance. The kernel's own `free_compound_page()` sends a free through the same code paths as this.

@tuxoko What do you think?

**Comment by tuxoko** [comment]
I think we were suppose to do page merging, so that one single sg chunks can have multiple compound pages, but that part didn't get merged yet. We should see what's the performance implication for merging and decide what to do with it.

**Comment by ryao** [comment]
I am curious if the loop is iterating once or on each page that is part of a compound page. If it is once, then this is a negligible change.

**Comment by ironMann** [comment]
What @tuxoko said. The loop is only accessing the first page of compound pages, skipping the rest with `nth_page()`.

**Pull request merged**
