### PR TITLE
Man page fixes

### PR DESCRIPTION
**Pull request by rlaager**
I had a pile of in-progress man page fixes from a couple years ago. I found these while cleaning up my ZFS source directory. I've cleaned everything up and it should be ready for review.

### CODE REVIEW

**Comment by behlendorf** [comment]
a0b9ef8 - Supported for delegations is very close (see #4487 I've got 3 test cases left to fix), so we won't want to make those changes.

Aside from that this LGTM but there's a lot here to digest.

**Comment by rlaager** [comment]
I've updated this to remove the changes related to "unprivileged users".

I also moved some changes to the correct commits (no net effect change on the end result).

I also simplified the discussion of reservations on volumes.

**Comment by behlendorf** [comment]
Thanks!  LGTM

**Comment by rlaager** [comment]
I found a slight issue with one change here. Fix in #4655.

**Comment by behlendorf** [comment]
OK, I'll take a look.  I suspect we'll end up finding a few other tweaks will want to make as well.

**Pull request closed without merging**
