### PR TITLE
Honor xattr=sa dataset property

### PR DESCRIPTION
**Pull request by nedbass**
ZFS incorrectly uses directory-based extended attributes even when
xattr=sa is specified as a dataset property or mount option. Support to
honor temporary mount options including "xattr" was added in commit
0282c4137e7409e6d85289f4955adf07fac834f5. There are two issues with the
mount option handling:

* Libzfs has historically included "xattr" in its list of default mount
  options with no value specified. Omitting the value implies xattr=on or
  directory-based xattrs, so the dataset is configured to use
  directory-based xattrs regardless of the xattr dataset property value.
  Address this by removing "xattr" from the list of default mount
  options.

* The option parser incorrectly treats the xattr mount option as a
  boolean value. Even if xattr=sa is specified, the parser translates
  that to xattr=on. Address this by treating the option as a scalar
  value.

Issue #3787

Signed-off-by: Ned Bass <bass6@llnl.gov>

### CODE REVIEW

**Comment by dweeezil** [comment]
I really wish we could move to a reference-counted feature flag to manage SA xattrs and use the ```xattr``` property as a boolean as is the case with other OpenZFS implementations.

**Comment by dweeezil** [comment]
One other salient point is that Solaris has ```MNTOPT_XATTR``` which is interpreted by their VFS whereas Linux has no such flag.  An argument could be made for completely removing the handling of xattr/noxattr in libzfs.

**Comment by behlendorf** [comment]
We should plan to do exactly that for the next tag.  In addition I think we should take the opportunity to fix some of the other rough edges too.   We'll want to carefully think through the behavior we want from a user perspective. 

In the meanwhile we can address this in a point release with a minimal fix.

**Comment by nedbass** [comment]
Updated patch to use saxattr and dirxattr mount options instead of xattr=sa and xattr=dir. This mirrors the valid dataset property values and adheres to mount option naming conventions. Also eliminates ugly string handling from the option parsing code.

**Comment by nedbass** [comment]
Added new mount options to `mount.zfs`.

**Comment by behlendorf** [comment]
Merged as:

3af56fd Honor xattr=sa dataset property

**Pull request closed without merging**
