### PR TITLE
Change zed.service to zfs-zed.service in man page

### PR DESCRIPTION
**Pull request by gjedeer**
The original service does not exist:

```
# systemctl enable zed.service
Failed to enable unit: Refusing to operate on linked unit file zed.service
```

### Types of changes

- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by kpande** [comment]
my dude, you need a Signed-off-by.

**Comment by gjedeer** [comment]
It's a trivial change and I don't really care about attribution, as far
as I'm concerned, close this PR and have it fixed by someone from the
project.

**Comment by Ornias1993** [comment]
@gjedeer Thats not possible, someone else cant signoff on your code.
Even if you don't want to, as soon as you post it online its "all rights reserved", unless you specify otherwise. Which means someone else posting it would commit a copyright violation or at the very least cant signoff on it (because by signing off you state you have all the rights for the code, which someone else hasnt)

**Comment by Ornias1993** [comment]
Done.

**Comment by gjedeer** [comment]
> @gjedeer Thats not possible, someone else cant signoff on your code.
> Even if you don't want to, as soon as you post it online its "all rights reserved", unless you specify otherwise. Which means someone else posting it would commit a copyright violation or at the very least cant signoff on it (because by signing off you state you have all the rights for the code, which someone else hasnt)

Yeah, except you have my written permission to do it in this ticket. Anyway, thanks and sorry for causing more trouble than it's worth, glad that you fixed it.

**Pull request closed without merging**
