### PR TITLE
Add mount option parsing.  Add support for [ug]id= mount options.

### PR DESCRIPTION
**Pull request by dweeezil**
A mount option parsing framework has been added in zfs_vfsops.c and is
used in zfs_domount().  It uses the native linux helper functions for
this purpose.  The code skeleton has been borrowed largely intact from
the standard vfat driver.

New mount options have been added as follows:

    uid=<user> gid=<group>
        Existing files will appear to have the specified user or group.

    dirowner dirgroup
        Newly-created files will be assigned the owner or group of their
        containing directory when, respecitvely, uid=<user> or gid=<group>
        are in force.

### CODE REVIEW

**Comment by dweeezil** [comment]
This is a functional WIP which I'm posting as a pull request both for feedback and because other may find it useful.

I've migrated most of my removable storage to ZFS and have wanted this functionality for some time to deal with disparate user/group IDs between systems and have been using this patch with success.

I'd like to see this concept extended to work in the context of ```zfs mount``` possibly by the way of additional filesystem properties and/or additional command-line options.  Among other ideas, one that I thought would be useful would be for filesystems to have an ```altmount``` property and also a ```mountoptions``` property to be used in conjunction with an new ```zfs mount``` command line option when a pool is imported on a foreign system.  Taken to the extreme, I could see having a property which would allow to specify mount points based on the host name of the system on which the mount is being performed.

At the very least, the option parsing code (mainly lifted from ```fs/fat/inode.c```) seems to be useful in its own right.

**Comment by dweeezil** [comment]
I've extended this patch to use filesystem properties.   By design, they're currently treated much more like traditional mount options and are, therefore, only interpreted at mount time ("zfs import" or "zfs mount").

As I mentioned above, I'm looking for feedback on the overall concept, utility and implementation.

This patch has been a big help in dealing with my portable media and also for my various personal systems on which I've started using zfs send/recv to synchronize but on which my uid differs.

**Comment by dweeezil** [comment]
I've decided that I don't like adding the mount option parsing to the kernel module and also that I don't like the semantics of the string-valued properties.  Instead, I'm going to re-implement this feature so there are only a pair of new filesystem properties, "uidinherit" and "gidinherit" which will, both cause the uid/gid to be inherited based on the owner/group of the mounted-on directory and also control the newly-created owner/group in a similar manner.  This should give the desired behavior for removable/replicated filesystems with only 2 new filesystem properties.

**Comment by dweeezil** [comment]
I'm going to take a different and simpler approach with this and will open a new pull request when it's ready.

**Comment by behlendorf** [comment]
This is very similar to the `uid|gid` options provided by filesystems such as affs, devpts, fat, hfs and others.  I can see how this kind of functionality would be very helpful when working with removable media.  In can also see how it could end up causing a lot of confusion.

I think the idea of using properties instead of mount options is a good one, and inheriting the uid/gid from the moint point is a clever way to usually get the right behavior.  However, this does introduce a few corner cases because Linux (unlike Illumos/FreeBSD) allows you to mount a filesystem concurrently under multiple mount points.  Those mount points may have different uid/gids and that would need to be reconciled somehow.

You might also want to consider allowing for different inheritance policies.  For example, you've made a good case for using the mountpoint uid/gid.  But what about using the uid/gid of the filesystems root inode or the current parent?  There may be cases where this is desirable, although I confess non leap immediately to mind.

uidinherit=<__off__ | mountpoint | root | parent>
gidinherit=<__off__ | mountpoint | root | parent>

It would also be nice is somehow the current inherited uid/gid for a dataset could be checked.  Lastly have you throught about how this would interact with ACLs?

**Pull request closed without merging**
