### PR TITLE
[NON-production] [ABD2] git-rebase of #3441 ABD: linear/scatter dual typed buffer for ARC (ver 2) [Dec. 30th, 2015_pt]

### PR DESCRIPTION
**Pull request by kernelOfTruth**
This is the rebase on a more up-to-date zfs master than last time (December 30th 2015, part of the commits included)

to make sure that all build or other issues are caught by the buildbot.

Compile-tested without errors but this doesn't say anything ...

(not entirely sure if how I rebased "Fix vdev_queue_aggregate() deadlock" was correct and does work with ABD2 - so letting the buildbots do some TESTs)

This rebase includes the commit "Fix vdev_queue_aggregate() deadlock"

which appears to be getting triggered reliably on my current system state - thus updating to a newer master branch state to avoid that

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
the buildbots are ignoring the last commit for whatever reason, so experimentally removing to trigger testing of TEST builds,

perhaps removing the "Enable scatter ABD support for SHA256" commit and re-pushing will do ?

**Comment by kernelOfTruth** [comment]
okay, looks like one after another TEST buildbots go offline, perhaps maintenance in the background ...

**Comment by kernelOfTruth** [comment]
according to first results it seems it doesn't work that way :/

so waiting for tuxoko to refresh ...

**Comment by behlendorf** [comment]
@kernelOfTruth it looks like the buildbot had a hiccup with EC2.  I've given it a kick to get it going again, but it may take it a few hours to clear the back log.  You can always check to [buildbot waterfall](build.zfsonlinux.org/waterfall) page to see what it's working on at any given moment.

**Comment by kernelOfTruth** [comment]
@behlendorf thanks for restarting it, that waterfall view looks great,

in the past I resorted to the other pages but this one appears to be the best :+1:

**Comment by kernelOfTruth** [comment]
_*stupid buildbot*_ !

why do you keep on ignoring the last (30+X) commit ?

**Comment by kernelOfTruth** [comment]
sweet ! :cake: 

first buildbot TEST results look promising

**Comment by behlendorf** [comment]
@kernelOfTruth usually it's not ignoring, it's just busy testing a commit (or 30 of them) from another PR.

**Comment by kernelOfTruth** [comment]
@behlendorf most of the times - it appears to be that,

but the few times tuxoko's ABD patchstack got tested it was 31 commits and there was no output at all for the 31st,

so I assumed that there was some sort of limit where it's ignoring additional commits.

Might just be that I have to wait some longer - patience is such a virtue, especially nowadays ...

Thanks !

**Comment by kernelOfTruth** [comment]
closing in favor of https://github.com/zfsonlinux/zfs/pull/4225

**Pull request closed without merging**
