### PR TITLE
[WIP] ZFS master 18.12.2015+illumos 4950

### PR DESCRIPTION
**Pull request by kernelOfTruth**
[rebased to more up-to-date master]

see https://github.com/zfsonlinux/zfs/pull/3629 ,
https://github.com/zfsonlinux/zfs/pull/3891

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
Issues with mutexes ?

**Comment by kernelOfTruth** [comment]
:balloon:  https://www.illumos.org/issues/6334 Illumos Cannot unlink files when over quota
since it's related

**Comment by behlendorf** [comment]
Replaced by #4259.  @kernelOfTruth I hope you don't mind me hijacking this but I've updated the delete_now changes and opened a new PR.

**Comment by kernelOfTruth** [comment]
@behlendorf no, I don't mind at all :)

I would have liked to get those changes working but my understanding is still pretty limited - so it's kind of stupid to further delay the inclusion of this PR

Thanks

**Comment by behlendorf** [comment]
@kernelOfTruth it gets easier the more you do it.  :)  Note you can always run same tests the buildbot does locally.  Just grab the test script and run it either directory or with `runurl`.

**Comment by kernelOfTruth** [comment]
@behlendorf I'll take a look into it, thanks !

do you guys ( @dweeezil ) have a dedicated test box for this or a specific partition where you run the tests on ?

I've got only this (production) box with solely the /home partition on ZFS - so I guess it would be  rather elaborate to run these tests, no (exporting /home, unloading modules, compiling, loading new modules, creating, etc. etc.) ?

so in the most cases I assume it's faster when the buildbots run the tests

**Pull request closed without merging**
