### PR TITLE
Linux 4.8 compat

### PR DESCRIPTION
**Pull request by behlendorf**
Compatibility patches for Linux 4.8.

### CODE REVIEW

**Comment by behlendorf** [comment]
@tuxoko @dweeezil along with zfsonlinux/spl#564 compatibility patches for Linux 4.8 for review.  Thus far the required changes have been very minor.

**Comment by dweeezil** [comment]
@behlendorf Running a kernel at torvalds/linux@8448cefe, SPL at zfsonlinux/spl@0484fbb  and ZFS at 0a4e3b6, writes to disk vdevs aren't actually writing anything.  I'm investigating the BIO changes further.

**Comment by dweeezil** [comment]
Something has broken the way we're using the BIO layer in the newest kernels but nothing obvious has jumped out.  So, I've been looking at all the kernel commits tagged with "block:" and am doing a little pseudo-bisection to see if I can narrow it down a bit.  Backing off the kernel to torvalds/linux@43b62ce makes writes work again which leaves about 40 relevant commits to examine.

**Comment by behlendorf** [comment]
@dweeezil thanks digging in to this.  I haven't had a chance to boot a kernel with these changes yet but I certainly will look in to it.  Definitely let me know if you identify the issue.

**Comment by dweeezil** [comment]
@behlendorf I've gotten a few more bisection steps done so I should be getting close.

**Comment by tuxoko** [comment]
I think we cannot use bio->bi_rw = XXX, we need to use bio_set_op_attrs.

**Comment by tuxoko** [comment]
torvalds/linux@f21508211d2b16e65821abd171378fa6ece126fe
This one introduce `bio_set_op_attrs` helper but doesn't change the encoding of bi_rw
torvalds/linux@4e1b2d52a80d79296a5d899d73249748dea71a53
This one change to encoding of bi_rw

**Comment by dweeezil** [comment]
@tuxoko For some reason, I was under the impression that they kept the encoding of ```bi_rw``` compatible with legacy code which used assignments but apparently that's not the case.

**Comment by dweeezil** [comment]
@behlendorf There's one other change I think we ought to make and that's to streamline the handling of ```bi_rw```.  See dweeezil/zfs@eef4b2e for a patch which I layered on to your PR.  Of course, in light of the need to use the new accessor helpers, it'll have to change even a bit more.

**Comment by tuxoko** [comment]
My kernel build is so unstable, I couldn't even boot it now...
I'll probably wait a bit before working on or testing this issue.

**Comment by behlendorf** [comment]
Yes, that's almost certainly the issue.  The initial commit I was looking at didn't change that encoding, that happened latter in torvalds/linux@4e1b2d5 as @tuxoko points out.  Sorry about that.

@dweeezil streamlining the bi_rw handling makes sense.  Rather than me trying to incorporate your fixes perhaps you could open a new PR when you're ready with your proposed updated version.

**Comment by tuxoko** [comment]
https://github.com/zfsonlinux/zfs/pull/4899

**Pull request closed without merging**
