### PR TITLE
zfs send -p needs full snapshot list

### PR DESCRIPTION
**Pull request by dweeezil**
A send stream with properties contains an nvlist "fss" describing
the source snapshots and their properties.  As of commit
057485504e3a4502c265813ab58e9ec8ffc2a3be, this list may not include
all the snapshots on the source.  In particular, it only includes the
snapshots which actually are sent and, furthermore, it is only sent when
either "zfs send -p" or "zfs send -R" are used.

The snapshot pruning code enabled under "zfs receive -F" depends on a
complete fss[id[snaps]] list.  If it's not complete, the filesystem can
be damaged at worst or, at best, left in it's renamed state (renamed to
"<fs>-recv-<pid>-<x>".

This commit suppresses the snapshot pruning for non-recursive streams
since they still include the complete list of snapshots in fss[id[snaps]].

### CODE REVIEW

**Comment by dweeezil** [comment]
I've updated the comment of this pull request to reflect the actual fix employed in dweeezil/zfs@9533354.

**Comment by behlendorf** [comment]
LGTM but I haven't had a change to manually test it.  @dweeezil do you have any reservations about this patch aside from the compatibility concern?  I suppose another option would be to revert 057485504e3a4502c265813ab58e9ec8ffc2a3be

**Comment by dweeezil** [comment]
@behlendorf An equivalent of the 0574855 patch is currently sitting at https://reviews.csiden.org/r/141/ but it doesn't look like @avg-l has had a chance to look into the issue I brought up.  I suspect this will eventually land in illumos and it does sound like it solves a real performance issue when there are lots of properties.

I have been running my fixed version on all my personal systems since I submitted the pull request and do a fair bit of send/recv between them and stock 0.6.3 systems and haven't seen any problems so far.  Furthermore, examination with ```zstreamdump``` does show it is doing the RIght Thing.  I certainly don't have any reservations about my fix.

**Comment by behlendorf** [comment]
@dweeezil thanks for the clarification.  This LGTM I've merged it to master.

e890dd8 Produce a full snapshot list for zfs send -p

**Comment by avg-I** [comment]
@dweeezil I actually followed this issue but had to work on other things and sort of suspended my work on this. Then I was trying to implement an alternative solution where the send side would behave in the original fashion, but the receive side would select a range of snapshots to which the received properties would need to be applied. Unfortunately, I am a little bit stuck there.

BTW, could you please update the [illumos review ticket](https://reviews.csiden.org/r/141/) so that the problem appears as an [issue](https://www.reviewboard.org/docs/manual/dev/users/reviews/issue-tracking/) so that it is clear that the current code there has this serious bug? Thanks!  It seems that I as a review submitter can not add an issue to the review (which is silly).

**Comment by avg-I** [comment]
Commenting in this long closed PR to let you know that I ended up fixing the original issue that was fixed in ZoL by 0574855 in a different way.
Please see https://www.illumos.org/issues/5380 
https://github.com/illumos/illumos-gate/commit/471a88e499c660844f4590487ce7c4d5a7090294

Could you please review that and see if it would be okay to replace 05748550 and e890dd85a75 with the illumos version?

**Comment by behlendorf** [comment]
@avg-I thanks for point this out.  We did merge your new Illumos 5380 commit to master, https://github.com/zfsonlinux/zfs/commit/4c3c6b6.  It looks to me like we can revert your older  https://github.com/zfsonlinux/zfs/commit/057485504e3a4502c265813ab58e9ec8ffc2a3be change.  It would be great if you could open a PR which reverts the old fix and even better if you could also add a simple test case to verify the fix.  Thanks!

**Pull request closed without merging**
