### PR TITLE
zfs-0.8.2 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Motivation and Context
Proposed patchset for zfs-0.8.2.

### Description
This is the proposed patchset for the zfs-0.8.2 point release.

### How Has This Been Tested?
Buildbot will test.  It did test build on Fedora 30 w/5.2.7 kernel.  I still need to test on an 5.3-rc kernel.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by tonyhutter** [comment]
Buildbot will only test 30 commits at a time.  To test out this patchset, I've squashed all the commits in #9164 .

**Comment by chungy** [comment]
I am curious, is there a conscious decision to not include e5db31349484e5e859c7a942eb15b98d68ce5b4d?

Debian is including this patch for 0.8.1, possibly other Linux distros too.

**Comment by jumbi77** [comment]
Is there any reason why not to merge all commits in master to 0.8.2 ([https://github.com/zfsonlinux/zfs/compare/zfs-0.8-release...master](url))? Since there is no major new feature upstreamed in master since 0.8 i guess we can include all commits, right?

**Comment by DSpeichert** [comment]
I would like to see #9061 (8e556c5) included since it fixes a very probable panic/crash. It is a bug fix.

**Comment by tonyhutter** [comment]
@chungy we've been going back an fourth on whether or not to include the SIMD patch, but I just got the OK from @behlendorf, and I've included it in my latest push.

@jumbi77 this actually is the first time we have merged all the non-new-feature commits to a point release.  That's why there's 89 commits this time (a record?)  I left off the major features patches and any patches which depended on those.

@DSpeichert thanks for the heads-up.  I included it in my latest push.

**Comment by aerusso** [comment]
If f88d069cbbbdff9a67a9be523cfb470cef707e07 is included, 19d61d63faa359afee5b3d7eb233bb786bc0de1c (closing #9174) should definitely be included, too.

**Comment by behlendorf** [comment]
As mentioned by @ghfields let's include #9202 and #9042 is this patch stack.

**Comment by jb55** [comment]
I was able to get my NixOS machine working on 5.3-rc7 with this patchset, although I had to revert a8f2fe672dab23dd97cb73b3fb385a72efe978c5 since that broke the NixOS build.

**Comment by tonyhutter** [comment]
Sorry about the lack up updates - I was on vacation for three weeks.  @behlendorf has sent me a list of addition patches to add/remove.  I'm adding those in...

**Comment by c0d3z3r0** [comment]
> I was able to get my NixOS machine working on 5.3-rc7 with this patchset, although I had to revert [a8f2fe6](https://github.com/zfsonlinux/zfs/commit/a8f2fe672dab23dd97cb73b3fb385a72efe978c5) since that broke the NixOS build.

@jb55 what exactly breaks?

**Comment by jb55** [comment]
@c0d3z3r0 can't remember exactly, but nixos doesn't have a /usr/share dir so I guess it was something to do with that.

**Comment by c0d3z3r0** [comment]
Then I guess it‘s a nixos packaging problem

**Comment by c0d3z3r0** [comment]
> Then I guess it‘s a nixos packaging problem

I was wrong... @jb55 see https://github.com/zfsonlinux/zfs/pull/9344

**Comment by tonyhutter** [comment]
Unfortunately we're seeing some bugs with the SIMD patches (https://github.com/zfsonlinux/zfs/issues/9346), so I've removed them from the patchset. :disappointed:

**Comment by eli-schwartz** [comment]
Would it be possible in the future, when patches have existed for over a month on master and are urgently needed for new kernel versions, to backport them into the maintenance branch immediately? :)

It's a bit awkward every time there is a kernel update, zfs no longer compiles, and downstream distributors for zfs have to desperately hunt around to figure out whether there is a fix, and if so, what the fix is. It's a contributory cause to the bad reputation zfs has on Linux distros with recent kernels.

I think it would be hugely helpful if commits marked for backporting were backported faster, and possibly also released faster (especially when those commits have known fixes for building on newer kernels). Maintenance releases are, or should be, free, so why not use them as often as possible in order to make users' lives easier?

**Comment by tonyhutter** [comment]
@eli-schwartz I can sympathize.  Note that this release has taken particularly long since I went on vacation for three weeks after putting out the initial patchset.  There's also been some iterating on the patch list as we've encountered bugs.  Also, "backport them into the maintenance branch immediately" involves a lot more steps than you would think.  The branch has to be tested, packages built and signed, repos updated and tested, docs updated, websites updated, support for new distro versions added, etc.  I agree that overall it would be better to have quicker, smaller releases though.

**Comment by freswa** [comment]
Maybe we could release 0.8.2 as a compatibility release only with the patches needed for kernel 5.3 (https://github.com/zfsonlinux/zfs/commit/041205afee7e151a0ac10c9b5314186cf65417dc and https://github.com/zfsonlinux/zfs/commit/e7a99dab2b065ac2f8736a65d1b226d21754d771) and postpone the rest of the changeset to 0.8.3 until docs and testing are finished.

**Comment by Baughn** [comment]
It would be nice. Choosing between stable GPU drivers and a working filesystem isn't a happy experience. Is there a shortage of manpower for that type of work, and if so, is there any way I can help as someone unfamiliar with the codebase?

**Comment by eli-schwartz** [comment]
>  Also, "backport them into the maintenance branch immediately" involves a lot more steps than you would think. The branch has to be tested, packages built and signed, repos updated and tested, docs updated, websites updated, support for new distro versions added, etc. I agree that overall it would be better to have quicker, smaller releases though.

Well, my idea was that in order to iterate for quicker, smaller releases it would be helpful if the first of these steps was done in a bit of a rolling fashion. It's not necessary to release new versions for every other patch, but doing as much work to test it as early as possible would help prepare for new versions -- hopefully the decision "let's release 0.8.2" could then be reduced to "there's several good fixes on the stable branch, and some of those fixes make it work on kernel 5.3, so now would be a good time to release", and then you could simply tag it and update documentation/release notes and that's it.

At a minimum I think it would be tremendously helpful to establish a policy "if there are changes needed to compile on a new kernel, then cut a new stable release with just those changes, and those changes alone". And try to do that at least a few days/week before a kernel release is expected to be announced, so that no one needs to scramble the day Linus publishes said release announcement.

**Comment by eli-schwartz** [comment]
@tonyhutter I see https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.2 is out now, but it only contains the assets:
- zfs-0.8.2.sha256.asc
- zfs-0.8.2.tar.gz

It is missing:
- zfs-0.8.2.tar.gz.asc

cf. #8557

**Comment by tonyhutter** [comment]
@eli-schwartz good catch!  Thanks, it's up now:
https://github.com/zfsonlinux/zfs/releases/download/zfs-0.8.2/zfs-0.8.2.tar.gz.asc

**Comment by eli-schwartz** [comment]
Great, thanks, deploying Arch Linux packages now.

**Comment by tonyhutter** [comment]
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.2

**Comment by colmbuckley** [comment]
@tonyhutter Just checking - it seems from the thread above that https://github.com/zfsonlinux/zfs/pull/9042 (commit https://github.com/zfsonlinux/zfs/pull/9042/commits/320813b428e9f7cc1fd9cd32f2c1b538a4496ebf) was *intended* to be included, but was left out. Just an oversight, or anything I can do?

**Comment by tonyhutter** [comment]
@colmbuckley  I can't remember exactly, but most likely it was because it didn't merge cleanly.  There were a few other patches we wanted in but had to leave off because of merge conflicts.  We'll try to get it in 0.8.3.

**Pull request closed without merging**
