### PR TITLE
This is the Fletcher4 algorithm implemented in pure C, but using mult…

### PR DESCRIPTION
**Pull request by rdolbeau**
…iple counters using algorithms identical to those used for SSE/NEON and AVX2.

This allows for faster execution on core with strong superscalar capabilities but weak SIMD capabilities.

### CODE REVIEW

**Comment by behlendorf** [comment]
Here are performance results from the same A53 system.  The superscalar performance is significantly better than the neon results.  Are you proposing this as a replacement to the neon patches or in addition to?

```
$ cat /proc/spl/kstat/zfs/fletcher_4_bench 
0 0 0x01 -1 0 87345122151000 87355749882000
implementation   native         byteswap       
scalar           1003882322     750979509      
superscalar      1696136799     1329388562     
superscalar4     1977939913     1692356453     
aarch64_neon     1190841913     1042880269     
fastest          superscalar4   superscalar4 
```

**Comment by rdolbeau** [comment]
@ironMann No cores with 4 ALUs that I know of. But superscalar4 still seems to help at least X-Gene 1, in particular for byteswap. Better latency hiding perhaps?

As for the 16 local variables, they still fit easily in the 32 GP registers - but on x86-64 indeed they are going to spill; on my Haswell "superscalar4" is slower than "superscalar". This is really for the "other architectures": if they have at least 2 ALUs and 32 registers, this is likely faster than "scalar".

... I don't have a Risc-V RV64I to check that theory though :-) POWER anyone? (I can't afford a Talos workstation...)

**Comment by rdolbeau** [comment]
@behlendorf I would say in addition, if that's acceptable; on A57
"superscalar" are worse than NEON (and not even better than regular
"scalar"). On other cores, "superscalar" are better. Having all
implementations, if that is not too much code, would be best I think.

**Comment by rdolbeau** [comment]
@behlendorf I'm OK with it ; beware there's two commits because the second (which only fix comments) also fix the SSE comment.

**Pull request merged**
