### PR TITLE
Add a statechange notify zedlet

### PR DESCRIPTION
**Pull request by don-brady**
Now that ZED has internal fault diagnosis and the `statechange` event is generated for faulted states, we can replace the `io-notify` and `checksum-notify` zedlets with one based on statechange.

##### Example notification:
```
Subject: ZFS device fault for pool 0xD48BD446CF382EF5 on serenity

The number of I/O errors associated with a ZFS device exceeded
acceptable levels. ZFS has marked the device as faulted.

 impact: Fault tolerance of the pool may be compromised.
    eid: 1080
  class: statechange
  state: FAULTED
   host: serenity
   time: 2016-11-07 21:46:20-0700
  vpath: /dev/disk/by-id/scsi-350000394a8ca4fbc-part1
  vphys: pci-0000:04:00.0-sas-phy0-lun-0
  vguid: 0xEA7D3A5FA3665469
  devid: scsi-350000394a8ca4fbc-part1
   pool: 0xD48BD446CF382EF5
```

### CODE REVIEW

**Comment by tonyhutter** [comment]
LGTM

**Comment by behlendorf** [comment]
@don-brady can you rebase this against master to resolved the merge conflict.

**Comment by behlendorf** [comment]
@don-brady I've rebased it.

**Comment by don-brady** [comment]
At offsite meetings but managed to rebase.  Looks like you have already got one?  It was just the makefile conflict, right?

**Comment by behlendorf** [comment]
Yes, just a trivial <akefile conflict.  I took the liberty of rebasing this PR as an experiment to see if I could do that as a maintainers.  It turns out I can.

**Pull request merged**
