### PR TITLE
add callbacks to taskq create

### PR DESCRIPTION
**Pull request by mattmacy**
adds callbacks to taskq_create to support async COW changes

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by scineram** [comment]
"support async COW changes"

Are these the infamous Spectra Logic improvements?

**Comment by allanjude** [comment]
> 
> 
> "support async COW changes"
> 
> Are these the infamous Spectra Logic improvements?

This is one of the prerequisites, yes.

**Comment by mattmacy** [comment]
> 
> 
> "support async COW changes"
> 
> Are these the infamous Spectra Logic improvements?

A working branch with the full async COW changes is here: 
https://github.com/mattmacy/networking/commits/wca/projects/dmu-context-crypto-0914

I saw a 2.5x speedup on unaligned streaming writes on raidz to SSDs before running in to some single thread bottleneck. My hope is to minimize the actual dbuf state change and async dmu diffs so that I can get this upstreamed in parallel with ZoF work.

**Comment by behlendorf** [comment]
Could you point me at the relevant async COW code which makes use of this interface.  It's not clear, to me at least, how having a per-thread taskq ctor and dtor would be beneficial.

**Comment by behlendorf** [comment]
Closing PR for now. This is an issue we intend to revisit after the initial OpenZFS refactoring is complete.

**Pull request closed without merging**
