### PR TITLE
disable EDONR on FreeBSD

### PR DESCRIPTION
**Pull request by mattmacy**
FreeBSD uses its own crypto framework in-kernel which, at this time,
has no EDONR implementation.

Signed-off-by: Matt Macy <mmacy@FreeBSD.org>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
[x] On FreeBSD zpool create will create a pool without the feature as expected.
[x] On FreeBSD this newly created pool cannot set the checksum type to "edonr" or enable the feature.
[x] This pool can be imported on Linux, exported, then re-imported on FreeBSD.
[x] This pool can be imported on Linux, but after enabling the edonr feature setting the checksum to edonr and writing some data, it can no longer be imported on FreeBSD (as expected).

**Comment by behlendorf** [comment]
It looks like we might need to add `/* CSTYLED */` in a few places to resolve the style checker warnings.  At some future date we'll probably also want to move the edonr ZTS back in to the common code since I believe they are supported on MacOS.

**Comment by lundman** [comment]
Ordinarily, it would be desirable to add the functionality to FreeBSD rather than to take it out of ZFS. But the general feel of edonr is not particularly good (https://crypto.stackexchange.com/posts/55446/revisions) to the point where I wonder if we should remove it from all platforms. But we only use it as a checksum, so there isn't any immediate pressure to do so.

**Comment by mattmacy** [comment]
> Ordinarily, it would be desirable to add the functionality to FreeBSD rather than to take it out of ZFS. But the general feel of edonr is not particularly good (https://crypto.stackexchange.com/posts/55446/revisions) to the point where I wonder if we should remove it from all platforms. But we only use it as a checksum, so there isn't any immediate pressure to do so.

We'll probably add it eventually, but AFAIU it's only really useful for dedup and the broader community considers the current dedup implementation broken by design. So there's no pressure to add it.

**Comment by mattmacy** [comment]
> It looks like we might need to add `/* CSTYLED */` in a few places to resolve the style checker warnings. At some future date we'll probably also want to move the edonr ZTS back in to the common code since I believe they are supported on MacOS.

We'll need platform specific run files regardless. Adding the tests to osx, and linux's run files doesn't seem like much of an imposition.

**Comment by kpande** [comment]
> dedup implementation broken by design

well, at least until you have a very fast metadata vdev holding the DDT. then it is quite wonderful. YMMV.

**Comment by bghira** [comment]
>  broader community considers the current dedup implementation broken by design

fwiw this was mostly resolved by special vdev support with DDT offload.

**Pull request merged**
