### PR TITLE
SSE, AVX-128 & AVX2 vectorized RAID-Z1/2/3 parity computation [rebase to 09.03.2016]

### PR DESCRIPTION
**Pull request by kernelOfTruth**
rebase for buildbot test of the vectorized RAID-Z parity computation from https://github.com/zfsonlinux/zfs/pull/3374 For discussion: SSE-vectorized (should work on any X86-64 cpu) RAID-Z2 parity computation

### CODE REVIEW

**Comment by sempervictus** [comment]
Thank you!

Any chance you have the same for ABD? :)
I'm test-building the new SHA256 code @tuxoko pushed in my version of this branch (working off @tomgarcia's abd2 branch of the original PR), would be nice to consolidate the disparate SIMD PRs...

**Comment by kernelOfTruth** [comment]
@sempervictus unfortunately no,

I attempted to rebase it but it already was too late, also I wasn't sure whether to choose the abd-avx or abd-sse branch

**Comment by tomgarcia** [comment]
It would actually be my abd2 branch. Abd-avx and abd-sse were just to force it to use one instruction set or the other, for more consistent testing. Sorry about the confusing branch names.

**Comment by sempervictus** [comment]
@tomgarcia: could you possibly perform the merge/update? It looks like there's new raidz related code in the abd_next branch which wasn't present in September and the merge conflicts look daunting. Plus, with the new SIMD code @IronMann is pushing, it might be worth while to consolidate the efforts and push the results into testing and master or some maintained branch so we dont have to keep asking you guys to update these PRs for years. One of the issues we run into is that basically all the patch stacks have ABD, so anything which conflicts is hard to test at any reasonable scale.

**Comment by tomgarcia** [comment]
@sempervictus At the moment I'm too busy, but sometime next week I should have time to perform the update.

**Comment by sempervictus** [comment]
@tomgarcia: thank you very much.

**Comment by tomgarcia** [comment]
@sempervictus just updated my master branch, and started working abd_next. Do you just want abd_next updated, or abd2 also? Not sure what's happening with the different abd versions.

**Comment by tomgarcia** [comment]
@sempervictus the abd_next version is now in my [abd_next](https://github.com/tomgarcia/zfs/tree/abd_next) branch.

**Comment by behlendorf** [comment]
Closing.  Vectorized RAIDZ has been merged to master.

**Pull request closed without merging**
