### PR TITLE
Illumos 5987 zfs prefetch code needs work

### PR DESCRIPTION
**Pull request by kernelOfTruth**
Illumos 5987 zfs prefetch code needs work
Reviewed by: Adam Leventhal <ahl@delphix.com>
Reviewed by: George Wilson <george.wilson@delphix.com>
Reviewed by: Paul Dagnelie <pcd@delphix.com>
Approved by: Gordon Ross <gordon.ross@nexenta.com>

diverged code base from Illumos:

[module/zfs/dbuf.c]
5f6d0b6 Handle block pointers with a corrupt logical size

[module/zfs/dmu_zfetch.c]
c65aa5b Fix gcc missing parenthesis warnings
428870f Update core ZFS code from build 121 to build 141.
79c76d5 Change KM_PUSHPAGE -> KM_SLEEP
b8d06fc Switch KM_SLEEP to KM_PUSHPAGE

account in module/zfs/dmu_zfetch.c for ISO C90 - mixed declarations and code - warnings

References:
https://www.illumos.org/issues/5987 zfs prefetch code needs work
illumos/illumos-gate@cf6106c 5987 zfs prefetch code needs work

Porting notes:

Module parameters (new/changed):
[in module/zfs/dmu_zfetch.c]

replaced zfetch_block_cap with zfetch_max_distance (Max bytes to prefetch per stream (default 8MB; 8 * 1024 * 1024))

changed zfs_prefetch_disable from int to boolean_t (B_False) ;
typedef boolean_t bool; in lib/libspl/include/sys/types.h

Ported-by: kernelOfTruth kerneloftruth@gmail.com

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
Still needs the integration of the man pages ... :information_source: 


Will attempt to update the man pages on a later point in time - since I'll be on the move starting with tomorrow and the following days :8ball:

**Comment by kernelOfTruth** [comment]
Note to self:

Probably will need dealing with

ISO C90 errors ...

**Comment by kernelOfTruth** [comment]
"Cumulative" pull-request including:

https://github.com/zfsonlinux/zfs/pull/3574 Illumos 5745 zfs set allows only one dataset property to be set at a time
https://github.com/zfsonlinux/zfs/pull/3611 Illumos 5746 more checksumming in zfs send
https://github.com/zfsonlinux/zfs/pull/4142 Illumos 5960 zfs recv should prefetch indirect blocks, Illumos 5925 zfs receive -o origin=

Leaving those open to be able to have the buildbot (TEST) runs on an up-to-date master or other occasions ...

**Comment by kernelOfTruth** [comment]
@dweeezil @behlendorf according to the Illumos issue tracker entry (https://www.illumos.org/issues/5987) this should help with lock contention issues, performance and perhaps as a bonus also stability

**Comment by kernelOfTruth** [comment]
```
In file included from /usr/src/linux-4.3.3_dtop-II.2_BFS-VRQ/include/linux/module.h:18:0,
                 from /usr/src/spl-0.6.5/include/sys/sysmacros.h:28,
                 from /usr/src/spl-0.6.5/include/sys/types.h:29,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/include/sys/zfs_context.h:37,
                 from /var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/dmu_zfetch.c:30:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/dmu_zfetch.c: At top level:
/usr/src/linux-4.3.3_dtop-II.2_BFS-VRQ/include/linux/moduleparam.h:146:27: error: expected ‘)’ before ‘&’ token
  param_check_##type(name, &(value));       \
                           ^
/usr/src/linux-4.3.3_dtop-II.2_BFS-VRQ/include/linux/moduleparam.h:126:2: note: in expansion of macro ‘module_param_named’
  module_param_named(name, name, type, perm)
  ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/dmu_zfetch.c:288:1: note: in expansion of macro ‘module_param’
 module_param(zfs_prefetch_disable, boolean_t, 0644);
 ^
/usr/src/linux-4.3.3_dtop-II.2_BFS-VRQ/include/linux/moduleparam.h:147:25: error: ‘param_ops_boolean_t’ undeclared here (not in a function)
  module_param_cb(name, &param_ops_##type, &value, perm);     \
                         ^
/usr/src/linux-4.3.3_dtop-II.2_BFS-VRQ/include/linux/moduleparam.h:224:39: note: in definition of macro ‘__module_param_call’
  = { __param_str_##name, THIS_MODULE, ops,   \
                                       ^
/usr/src/linux-4.3.3_dtop-II.2_BFS-VRQ/include/linux/moduleparam.h:147:2: note: in expansion of macro ‘module_param_cb’
  module_param_cb(name, &param_ops_##type, &value, perm);     \
  ^
/usr/src/linux-4.3.3_dtop-II.2_BFS-VRQ/include/linux/moduleparam.h:126:2: note: in expansion of macro ‘module_param_named’
  module_param_named(name, name, type, perm)
  ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/dmu_zfetch.c:288:1: note: in expansion of macro ‘module_param’
 module_param(zfs_prefetch_disable, boolean_t, 0644);
 ^
```

so boolean values are not permitted for kernel module settings ?

hm ...

**Comment by kernelOfTruth** [comment]
CC: @FransUrbo now I'm in a position where a bool value is used by upstream (Illumos),

reference: https://github.com/zfsonlinux/zfs/pull/1993 Change disable/enable flags to booleans

@behlendorf should an int value be used instead of bool ?

(I'm very thankful for FransUrbo's reference: https://github.com/FransUrbo/zfs/commit/30cfd70c1e838aa743cf1cd65f28160a6025e762 )

**Comment by kernelOfTruth** [comment]
Buildbots - roll out ! :rocket:

**Comment by dweeezil** [comment]
@kernelOfTruth This one, illumos 5987, definitely caught my eye some time ago.  I can't count how many times I've disabled prefetch while doing various types of testing after noticing it leading to excessive contention or some other performance problem

I'm glad to see this and other illumos commits getting ported (wow, there are sure a lot of them).

**Comment by behlendorf** [comment]
> I'm glad to see this and other illumos commits getting ported (wow, there are sure a lot of them).

@kernelOfTruth first off, thank you porting all these changes from Illumos.  I haven't been ignoring them, but there are so many that I felt I needed to take a step back and get a complete view of what has and has not been ported from Ilumos.  I've [posted my analysis](https://github.com/zfsonlinux/zfs/wiki/Illumos-Tracking) on the zfs wiki and I'd like to use it as a starting point for:

1) Pulling in anything we're missing (we did miss a few things).
2) Tracking new Illumos changes going forward

Please feel free to update to page to correct mistakes or add new ZFS changes as they are merged to Illumos.  Now that I can clearly see what order the Illumos changes were made in I'll be starting with the oldest ones which have not yet been merged and working to get them in ZoL.

**Comment by kernelOfTruth** [comment]
@dweeezil I really hope that most of the ZoL specific issues (less performance, lock contention, potential lockups, etc. missing features) can be ironed out in a rather short time now that the wiki page with the Illumos commits exists - I don't own a "big" box or have access to it but if I read correctly you, ryao and others of the frequently visiting folks do - so I'm pretty curious what these changes will provide

@behlendorf great ! sure, I've pushed a few pull-requests and made some modifications for existing pull-requests and/or existing alternative fixes in ZoL

**Comment by kernelOfTruth** [comment]
superseded by: https://github.com/zfsonlinux/zfs/pull/4180
+
updated the wiki

**Pull request closed without merging**
