### PR TITLE
Support parallel build trees (VPATH builds)

### PR DESCRIPTION
**Pull request by FransUrbo**
Add VPATH to make sure it's possible in a different directory and not
clutter the source with build results (such as Makefiles, *.o and *.a
files etc).

See https://github.com/zfsonlinux/spl/pull/362 for SPL part of the fix.

Closes: #1082

### CODE REVIEW

**Comment by FransUrbo** [comment]
@behlendorf Could we get something like this in before 0.6.5?

**Comment by behlendorf** [comment]
Sure if we can get patches we're happy with.  I recall we ran in to some issues last time we looked at this.

**Comment by FransUrbo** [comment]
I've reopened and refreshed this. "Works for me", although I have yet to figure out how to run <code>autoreconf</code> from some other place than the top source dir. It leaves 'stuff' behind, which would be nice to get rid of.

With this, we technically don't need any <code>.gitignore</code> files, but I have not included the removal of them in the PR. Might need some discussion perhaps?

**Comment by behlendorf** [comment]
@FransUrbo can you rebase this branch on master and force update it to trigger the automated testing.

**Comment by FransUrbo** [comment]
Thought I did, but apparently not. I've done that now.

**Comment by behlendorf** [comment]
Refreshed, slightly modified, and merged as:

47a4a6f Support parallel build trees (VPATH builds)

**Pull request closed without merging**
