### PR TITLE
[ZFS 0.7.x] Cherry-pick support for setting correct bin paths for initramfs-tools scripts

### PR DESCRIPTION
**Pull request by Conan-Kudo**
### Motivation and Context
For my custom builds for ZFS, I need these changes to be able to make functional `initramfs-tools` scripts for my Debian systems using `initramfs-tools` instead of `dracut`.

### Description
Cherry pick the following commits from master:
* cb3b0419baeecd15cc6891cdccfe0d5d815edd36
* e2d936e0f893084384a0d29ddf2edfd9f68deaf2

### How Has This Been Tested?
Built the code locally using `./configure` and was able to successfully regenerate initramfs without errors.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@behlendorf Is it just me, or does it seem like something is busted with running CI against 0.7.x?

**Comment by behlendorf** [comment]
@Conan-Kudo not broken, but it does need a hint to know that it needs to build the SPL.  You need to add the following to the commit message,

```
Requires-spl: spl-0.7-release
```

**Comment by Conan-Kudo** [comment]
@behlendorf it looked like it attempted and failed to checkout the spl-0.7-release branch anyway...

**Comment by Conan-Kudo** [comment]
@behlendorf I've added the flag, let's see how this goes...

**Comment by Conan-Kudo** [comment]
@behlendorf Looks like it worked okay...

**Comment by behlendorf** [comment]
Closing, this has been included in #8374

**Pull request closed without merging**
