### PR TITLE
Placeholder PR for BSD fetch support

### PR DESCRIPTION
**Pull request by mattmacy**
Signed-off-by: Matt Macy <mmacy@FreeBSD.org>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Closing PR for now. This is an issue we intend to revisit after the initial OpenZFS refactoring is complete.

**Comment by Ornias1993** [comment]
@behlendorf Just for the sake of public clearity:
Considering the amount of non-github coorporation between the ZFS development groups, do you mean "We, from ZoL" or "We, ZoL and ZoF"?

**Comment by behlendorf** [comment]
Good question.  What I mean is this functionality is desired on both Linux and FreeBSD, and anyone who wants to get involved with OpenZFS is welcome to help work on it.  For the moment, this work is a lower priority then getting the bulk of the ZoF merged.  After the merge, and a FreeBSD CI bot is added, it will be easier to implement this in a portable way and test it.

**Comment by Ornias1993** [comment]
@behlendorf Yeah sorry for my confusion, my post was made prior to the ZoL + ZoF = OpenZFS merger/namechange... Taking that announcement into account it's quite clear now, thank you! :)

**Pull request closed without merging**
