### PR TITLE
[RFC][WIP] Vectorized RAIDZ generate and reconstruct methods [abd]

### PR DESCRIPTION
**Pull request by ironMann**
abd version of #4328, on @tuxoko:abd_next and rebased on top of @zfsonlinux:master 

This is a new implementation of RAIDZ1/2/3 routines using x86_64 scalar, SSE, and AVX2 instruction sets. Included are 3 parity generation routines (P, PQ, and PQR) and 7 reconstruction routines, for all RAIDZ level. On module load, a quick benchmark of supported routines will select the fastest for each operation and they will be used in runtime. Original implementation is still present and can be selected via module parameter.

Patch contains:

- specialized gen/rec routines for all RAIDZ levels,
- new scalar raidz implementation (unrolled for speed),
- two x86_64 SIMD implementations (SSE and AVX2 instructions sets),
- fastest routines selected on module load (benchmark).
- cmd/raidz_test tool for math exactness verification, code coverage and benchmark

New zfs module parameter:
```
- zfs_raidz_math_impl (string, can be changed online): selects the implementation to use
    "fastest" - use the fastest math available
    "original" - use the original raidz code
    "cycle" - cycle through all available impl for each new vdev_raidz (default in userspace tests)
    "scalar" - new scalar impl
    "sse" - new SSE impl if available
    "avx2" - new AVX2 impl if available
```

### CODE REVIEW

**Comment by sempervictus** [comment]
Thank you, building now.

**Comment by sempervictus** [comment]
Managed to build this manually since the Ubuntu packaging is quite broken with the new test suite, initial results from the benchmark in dmesg on a test node:
```
[Sun Mar 27 04:50:34 2016] RAIDZ_math: [avx2   ] is not supported.
[Sun Mar 27 04:50:34 2016] RAIDZ_math: [gen_p  ] scalar     704.035 MB/s
[Sun Mar 27 04:50:34 2016] RAIDZ_math: [gen_p  ] sse       1012.325 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [gen_pq ] scalar     233.821 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [gen_pq ] sse        469.827 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [gen_pqr] scalar     105.282 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [gen_pqr] sse        281.404 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_p  ] scalar     571.697 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_p  ] sse        833.865 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_q  ] scalar     200.204 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_q  ] sse        508.289 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_r  ] scalar     151.660 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_r  ] sse        425.526 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_pq ] scalar     116.184 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_pq ] sse        362.959 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_pr ] scalar      93.641 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_pr ] sse        306.724 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_qr ] scalar      63.613 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_qr ] sse        249.257 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_pqr] scalar      44.362 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [rec_pqr] sse        194.549 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [gen_p  ] original   639.399 MB/s
[Sun Mar 27 04:50:35 2016] RAIDZ_math: [gen_pq ] original   201.598 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [gen_pqr] original    92.875 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [rec_p  ] original   508.597 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [rec_q  ] original   171.533 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [rec_r  ] original    24.927 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [rec_pq ] original   109.059 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [rec_pr ] original    13.917 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [rec_qr ] original    13.928 MB/s
[Sun Mar 27 04:50:36 2016] RAIDZ_math: [rec_pqr] original     9.872 MB/s
```
FIO is running, should have some rational results tomorrow.

**Comment by sempervictus** [comment]
FIO results didn't show any improvement - bottleneck is at the 4K/8K volblocksize ZVOLs it seems.
Send/recv on an SSE backup target with Z2 and Z3 however got noticeably better with the Z3 target writing at the same speed the Z2 source reads now.
I'm still a bit stuck with wider testing - this is done on a specific module built for a specific kernel on 3 systems. DKMS packaging still eludes me with the pkg-zfs bug (#198) being a show stopper.
No sign of data corruption yet... ran ~20 hours of abusive FIO tests and no crashes either. So far, so good. Thanks again @ironMann.

**Comment by ironMann** [comment]
@sempervictus thank you for testing. I'm not sure what your test setup is, but I expect most improvements in scenarios where system CPU is under strain, either underpowered CPU or handling many pools at the same time (like HPC loads under Lustre). Also, RAIDZ3 operations are significantly faster now, especially reconstruction. See here for reference [pdf](http://fias.uni-frankfurt.de/~neskovic/zfs/zfs_vect.pdf)

**Comment by ironMann** [comment]
@tuxoko I've made some changes and additions to your abd work (on top of `abd_next` branch). Mainly I added 2 new iterator methods for my raidz work, and some more code to make abd buffers and iterators more consistent with regard to length of the buffers and so on. It looks like I have not broken anything, so  could you review and maybe upstream the changes in commit `aec47b5` ?

**Comment by sempervictus** [comment]
A week into some pretty heavy use and testing, i've thrown this stack into a prod system with a RAIDZ2 and a RAIDZ3 pool. So far, so good it seems, havent observed any related crashes, removing and replacing a disk in the Z3 only took a few hours (11 disk, 3t, Z3 of Barracuda's, not Constellations, with dm-crypt), while consuming znapzend streams from multiple hosts and datasets per host at 15m intervals along the way into the pool (backup tier).

Thank you very much @ironMann.

**Comment by ironMann** [comment]
New version unifies algorithm implementation for scalar and vector versions. Now only small pieces of native asm are required to support an instruction set. This should apply for ARM also.
Scalar reconstruction is now up to 10x faster than original code, due to more lookup tables tweaks.

@behlendorf I'm now pretty much done with performance optimizations and algorithm tweaks. There is some code bloat in glue code due to keeping the original code in. I've been asked if the code is going to be used by other openZFS distros, because they are used as NFS servers. If so, now would be a good time to join the review party.
@sempervictus Thanks for testing (production use)! There's a new tool that you can run to at least check
for bit exactness of different implementations: `raidz_test -S` It will run for a while, sweeping through some parameter space, but it should not fail. It is purely user-space, and does not require zfs module to be loaded.

**Comment by behlendorf** [comment]
@ironMann awesome work, I'll set aside some time to make another round of reviews.  @jxiong @tuxoko if you have time to look this over as well that would be great.

A few quick high level comments/questions:

* The addition of the `raidz_test -S` test case is excellent, but let's go one step farther and add it to the ZFS Test Suite.  This way it will be run regularly and we'll immediately catch any potential future issues. I'd suggest adding a few high value tests in `tests/zfs-tests/tests/functional/raidz/` and try to keep the run time under 5-10 minutes if possible.

* I know we discussed merging this after ABD but how disruptive do you feel it would be to do this first and the then apply ABD on top of it?  This came together a lot faster than I was expecting and it's a shame to have it delayed.

**Comment by ironMann** [comment]
@behlendorf ABD adds significant overhead in terms of performance and code bloat when compared to simple linear buffer version of the code. I am pondering whether it would be better to `vmap()` all the data and parity pages into a contiguous vm area during the lifetime of the raidz_map, i.e. between `vdev_raidz_map_alloc() and vdev_raidz_map_free()`. That way, the raidz and checksum computation would not need to be aware of the scatter pages. The code would be much simpler, and multiple page mapping/unmapping would be avoided. Finally, ABD patch would only need to do `vmap()/vunmap()`, without touching the rest of `vdev_raidz` code. I have no idea if this goes against some fundamental reason or idea of ABD patch. Would like comments on this idea.

I'll make `raidz_test` a bit more screen friendly and add it to the ZFS Test Suite.

**Comment by tuxoko** [comment]
@ironMann 
How much performance penalty are talking about? Do you measure that in userspace or kernel space? ABD in kernel space will try to allocate physically contiguous page when possible. So ideally, it shouldn't cause a lot of scatter pages. But userspace ABD doesn't do that.

**Comment by ironMann** [comment]
@tuxoko I'm mainly talking about kernel, AFAIK there's no real use-case for raidz in user space. Raidz calculation would naturally access elements from each raidz column, which means strided access on the zio allocated buffer. Nature of kmap() functions prevent me to have each of the columns mapped at the same time, so the ABD version of the code must iterate column by column and reload/update/save the intermediate results which adds to the performance issue. Then there's a multiple `kmap()/kunmap()` of the same pages in case of short raidz columns, where multiple columns fit to the same memory page.
The numbers I observe in kernel benchmarks are about 30% lower for reconstruction paths, where the problems I listed are more pronounced.

**Comment by behlendorf** [comment]
@ironMann it would be best to avoid vmap() since it can potentially be very expensive.  This is one of the the issues at the very heart of the ABD changes.

**Comment by tuxoko** [comment]
@ironMann 
If it is kmap that limits the implementation, then we would want to consider don't use kmap at all for !CONFIG_HIGHMEM.

**Comment by ironMann** [comment]
@tuxoko I'm not sure kmap() makes a lot difference in !CONFIG_HIGHMEM case, it should just a bit math on the page address. And the algorithm would need to process column by column to be usable anywhere. Only a truly linear, randomly accessible buffer, would make the implementation simpler and faster to make a difference.

@behlendorf To answer your original question about merging this before abd: It is be possible to keep abd semantics of the implementation: [vdev_raidz_math_impl.h](https://github.com/ironMann/zfs/blob/wip-simd-abd_next/module/zfs/vdev_raidz_math_impl.h). The code needs only few of the abd helper methods, and two new I added [abd_raidz_[gen|rec]_iterate()](https://github.com/ironMann/zfs/blob/wip-simd-abd_next/module/zfs/abd.c#L581-L733). They should be simple to implement for current, non abd buffers, and replace when abd lands. Better and faster solution for current situation, I have initially started in #4328, is completely incompatible with abd.

**Comment by tuxoko** [comment]
@ironMann 
Could you be more specific on which functions suffer from it so I can take a look.

**Comment by ironMann** [comment]
@tuxoko Here's an [example](https://github.com/ironMann/zfs/blob/wip-simd-abd_next/module/zfs/vdev_raidz_math_impl.h#L443) In function `raidz_reconstruct_q_impl ()`, I first need to init the missing data column (L459-L464), then to call the syndrome calculation routine once per data column (L480), combine the code column (L485) and finally reconstruct the data(L489). All of these steps have to be performed separately for abd buffers. 
In linear buffer case, all steps can be combined into a single for loop. The main reason speed suffers is the conceptual change of accessing abd buffers.

**Comment by tuxoko** [comment]
@ironMann 
So what you need is direct access to iterator, so you can do works in one pass rather than multiple pass?

**Comment by ironMann** [comment]
@tuxoko yes, computing in one pass would require access to unspecified number of memory pages at once, which means access to an iterator for every data and parity disk at the same time. `kmap_atomic()` can't have unbounded nesting so I had to use the 'one at a time' approach as described above.

**Comment by tuxoko** [comment]
Yes, and in !CONFIG_HIGHMEM, you don't really need kmap_atomic anyway.

We need the kmap, kmap_atomic only for 32bit, and it works pretty well for most of the cases where we only worries about two buffers at most. But it there's that much a performance difference, we should consider different approach, maybe a stripped down and efficient iterator that don't do kmap.

**Comment by ironMann** [comment]
Yes, indeed. In that case, I would need one version of raidz math implementation for CONFIG_HIGHMEM (current one) and another, hopefully much simpler and faster for !CONFIG_HIGHMEM. This translates to having 2 versions of [vdev_raidz_math_impl.h](https://github.com/ironMann/zfs/blob/wip-simd-abd_next/module/zfs/vdev_raidz_math_impl.h)

**Comment by behlendorf** [comment]
@ironMann the way it worked out it looks like it's going to logically make more sense to merge this functionality before the ABD changes.  We'll then need to follow up latter with your changes to adapt them for ABD.

Can you please open a new PR with these changes rebased on master.  I think it also makes sense to squash the RAIDZ work in to a single commit.  Locally, we'll get the new RAIDZ code on some hardware and do some additional torture testing.

**Comment by ironMann** [comment]
@behlendorf This is now updated in the original #4328
I've refactored the code once again to be compatible as much as possible with abd patches, when they arrive. So, let's move the discussion there.

Note:
From discussion we had here: the current, non-abd, raidz code should 'morph' into a abd-raidz for !CONFIG_HIGHMEM configuration. But for HIGHMEM case, a new abd buffer handling need to be added. This is localized in a single file, and I've already implemented it here.

**Comment by rdolbeau** [comment]
2016-05-16 21:35 GMT+02:00 Brian Behlendorf <notifications@github.com>:
> @ironMann the way it worked out it looks like it's going to logically
make more sense to merge this functionality before the ABD changes.

So, functionality like #3374 in may'15 before ABD was mentioned then ? ;-)
;-)

Whatever gets merged; ping me afterward so I can try and merge my AVX-512
and NEON stuff (I can test both) from my obsolete ABD port (I think #4328
only has SSE/AVX2).

Cordially,

--
Romain Dolbeau

**Comment by sempervictus** [comment]
@ironMann: would you be able to rebase these changes against the current master? Seems there's been significant divergence and my builds atop this branch keep breaking.

This PR has been running in our production systems for a while now, including dealing with several resilvers of 3T disks in a Z3 using the SSE path. So far so good

**Comment by ironMann** [comment]
@sempervictus Some new code went into master that lacks abd support (like avx2 fletcher). It would need full abd support. Unfortunately, I have zero time in next two weeks...

Also, I'm working on RAID-Z  code for inclusion in master at #4328, I meant to update this patch when that's done.
I'll let you know if I manage to find some time for this.

**Comment by jxiong** [comment]
@ironMann @behlendorf I have already had a patch to support abd for avx fletcher. I will push a patch to github soon.

**Comment by sempervictus** [comment]
@ironMann. @jxiong: thank you both, will add both updates to our test stack as they hit.

**Comment by behlendorf** [comment]
Since #4328 has been merged to master I'm going to close this issue out.  Now that it's merged it should be easier to maintain support for ABD.  Hopefully the raidz and fletcher avx patches can be added to the ABD patch stack.  @jxiong can you post a link to your abd fletcher avx patch.

**Comment by ironMann** [comment]
I don't know if this comm channel is still open:

@sempervictus I've rebased simd raidz patches on top of [tuxoko:zfs-0.6.5.7-abd](https://github.com/tuxoko/zfs/tree/zfs-0.6.5.7-abd)
That is the best I can do for now: [ironMann:raidz-abd](https://github.com/ironMann/zfs/tree/raidz-abd). 
The patch does not include new sse2 impl. (not yet in the master).
I still might tune stuff here and there, but for the most parts patch is complete (and very lightly tested).

@tuxoko The patch requires some changes and additions to adb core. I've also changed some minor things lightly. It would be a good time to have them reviewed and added to the stack. commit: [abd changes](https://github.com/ironMann/zfs/commit/84adc455ca2f674888125b05d19ec310d1d5a279)

**Comment by tuxoko** [comment]
@ironMann 
Thanks, I'll take a look.

**Comment by sempervictus** [comment]
Thank you very much, we will start a new patch stack. So far I've been
manually cherry picking from master and prs over the last
abd-vectorized-raid commit. Its been great, especially on our lower backup
tiers which run large raidz3 pools doing a ton of writes and killing disks
every month or so.

**Comment by ironMann** [comment]
@sempervictus you're welcome. I would appreciate if you could share some details on your pools, like width, disk size, and have you observed significant reduction in scrub/repair with the simd patch.
I was planning to look into #1277 and #3625 next, but my work project is shifting to other direction, and I don't really know how much would such feature pay off.

**Comment by sempervictus** [comment]
@ironMann: i took a look at that branch, and it seems significantly behind what we've composed over the last few months. I need to take a bit of time to figure out what's changed and how. If there's anyway you could rebase over master (even reverting commits like the fletcher one), it would help a ton.

Far as pool composition goes, the pools are either 13-disk Z3 3Ts (long term) or 8disk Z2 4Ts, workload-wise, the 3Ts take differential snapshots from multiple sources every 15m, and the 4Ts both run container/kvm workloads and absorb hourly snapshots from the 3Ts. All vdevs are dm-crypt volumes atop the physical disks.

Actual production systems which run Cinder volumes and virtualized HA controllers (with ceilometer which seems to love writing things to disk) on separate pools, and the Cinder volumes vary in composition from Z2 consistent storage to SSD-only span pools (or even non ZFS spans) for "silly IO"  workloads which do not require long term consistency. There's a lot of delta on the ZVOLs, especially given the 15m incremental snaps. Tenant-side, given that this particular stack is currently undergoing our validation process, its seeing fio, tiotest, database workloads, and some cassandra being run atop it to shake out the bugs.

The resulting workload on the snapshot-waterfall topology is a bunch of writes which get discarded along with their snapshot reference every hour or so (we run 15m->1h,1h->24h.... intervals). This is "not nice" to the RAIDZ3 pools which absorb deltas from all the nodes above them concurrently in the waterfall at regular intervals, so they lose disks on occasion, and rebuilds used to be a massive pain.

I have a resilver pending (when one of my team can get to the datacenter, spares are reserved for the 2nd failure) on a Z3, for which i'll post the system specs, load, and resilver time once we complete the operation (sometime in the next week).

**Comment by ironMann** [comment]
@sempervictus I can rebase raidz on any abd stack you have, but I'm not the right person to make full master rebase. I don't know the rest of zfs internals well enough, and also I'm short with time currently. Sorry... (if need be, I can adapt fletcher4 to abd, that part I'm familiar with)

Thank you for detailed writeup of your raidz use cases. It seem that your setup would benefit from 2-phase resilver feature.

**Pull request closed without merging**
