### PR TITLE
Add zfs-load-key.sh to .gitignore

### PR DESCRIPTION
**Pull request by behlendorf**
### Description

The generated zfs-load-key.sh file should have been added to
the .gitignore file as part of commit 7da8f8d8.

### Motivation and Context

Keep the build system clean.

### How Has This Been Tested?

Locally.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
@prometheanfire would you mind reviewing this tiny fix.

**Comment by prometheanfire** [comment]
sure, lgtm, doesn't effect anything running at least

**Comment by dinatale2** [comment]
@behlendorf There appears to be a `contrib/dracut/90zfs/zfs-load-key.sh` in master at the moment. Should that be removed?

**Comment by behlendorf** [comment]
@dinatale2 yes it should, thanks!  Refreshed PR.

**Pull request merged**
