### PR TITLE
Fix shell scripts to comply to shellcheck style check (WIP)

### PR DESCRIPTION
**Pull request by FransUrbo**

### CODE REVIEW

**Comment by FransUrbo** [comment]
Ok, getting closer. I had to rewrite the <code>shellcheck</code> target slightly, it gave a couple of false positives (i.e., checking files it shouldn't etc). Should be safe to merge only that (and when I do a force push, that shouldn't be included in the PR), but maybe hold off on that a little longer until we've ironed out ALL that needs to be done?

**Comment by FransUrbo** [comment]
To fix the rest, I probably have to wait for a/the new version of <code>shellcheck</code> (due to issue https://github.com/koalaman/shellcheck/issues/380). It's to blunt of a tool to use for automated testing.

**Comment by FransUrbo** [comment]
I'm starting to wonder if I should split each type fix into its own commit for easier review… The patch is currently 6k4 lines long!!

**Comment by behlendorf** [comment]
Breaking it up per-file would be pretty reasonable way to go.

**Comment by behlendorf** [comment]
Closing for now.  I'm all for fixing up the various core scripts so they pass shell check.  However, I think we need to do it a file, or maybe sub-directory, at a time.  This way those changes can be realistically reviewed.  The huge patch here can definitely act as that starting point for anyone wanting to tackle this.

**Pull request closed without merging**
