### PR TITLE
Fix SA header size accounting

### PR DESCRIPTION
**Pull request by nedbass**
The functions sa_find_sizes() and sa_build_layout() fail to account
for the additional 2 bytes of SA header space when calculating whether
a variable size attribute might spill over. They may consequently
determine that an attribute will fit in the bonus buffer along with a
spill block pointer, when in reality the attribute would be partially
overwritten by the spill block pointer if spill over occurs. This also
causes an inconsistency between the SA header size and the number of
variable size attributes in the layout, tripping an assertion when
debugging is on. The following reproducer demonstrates the problem.

  ln -s $(perl -e 'print "z" x 20') file
  setfattr -h -n trusted.foo -v $(perl -e 'print "z" x 200') file

Even though sa_find_sizes() computes the index of the attribute where
spill-over will occur, sa_build_layouts() discards the result and
recomputes it itself. As it turns out, both functions get it wrong.
Since this computation is awkward and, as history has shown, easy to
screw up, let's just do it in one place. This patch fixes the bug in
sa_find_sizes() and updates sa_build_layout() to use the result
computed there.

Also improve the comments in sa_find_sizes().

Issue #3070
Signed-off-by: Ned Bass <bass6@llnl.gov>

### CODE REVIEW

**Comment by nedbass** [comment]
@dweeezil please review when you have a chance, thanks.

**Comment by behlendorf** [comment]
LGTM.  The refactoring and comments help make this code more understandable.

**Comment by dweeezil** [comment]
LGTM.  As an additional little stress-testing experiment, I ran a series of similar tests with a hacked module which perturbed the canonical ordering of the SAs such that ZPL_SYMLINK was placed before ZPL_ACES.  The result is that the spill ends up containing ZPL_ACES and ZPL_SA rather than ZPL_SYMLINK and ZPL_SA.  It worked perfectly fine.

**Comment by behlendorf** [comment]
Thanks guys, I'm hopeful this is the last one!  Merged as:

a62d1b0 Fix SA header size accounting

**Pull request closed without merging**
