### PR TITLE
update zed man page date stamp to a real month

### PR DESCRIPTION
**Pull request by cmosetick**
If "Octember" is an inside joke or something, please disregard!

### CODE REVIEW

**Comment by behlendorf** [comment]
image

**Comment by staticinstance** [comment]
haha ;)

**Comment by behlendorf** [comment]
Let's hold off updating this until the next time the zed man page is updated.  Octember was supposed to be that reminder.  :)

**Comment by cmosetick** [comment]
Thanks @behlendorf

**Pull request closed without merging**
