### PR TITLE
[test] abd: sort and merge allocated pages for scatter abd

### PR DESCRIPTION
**Pull request by ironMann**
Perform sorting and merging of allocated pages in order to reduce size of sg.
Algorithm performs full front and back merging with already allocated pages.

Additionally:
- Kstats that show success of merging with and without sorting.
- Limit zfs_abd_scatter_max_order module parameter

### CODE REVIEW

**Comment by dorvan** [comment]
to alla guys and in particular to @ironMann, Really compliments for your great work.

**Comment by ironMann** [comment]
@rdolbeau Let's move the discussion over here, not to poison the main thread. I'm not 100% sure, but I believe you only need to adjust final parameters for the new methods in `math_impl.h`. Can you share what you have so far? I might be able to help.

> BTW it seems the new code will add a lot of loads & stores in the inner loops :-/

courtesy of ABD buffers :) But, there's still room for improvement ...

**Comment by ironMann** [comment]
@rdolbeau 
> Also the GEN_P_* stuff is still defined in avx2 but apparently never used... 

You're right. gen_p code uses ADD_* macros. I'll clean up.

**Comment by rdolbeau** [comment]
@ironMann WiP on https://github.com/rdolbeau/zfs/tree/openzfs-abd-patchset

**Comment by rdolbeau** [comment]
@ironMann Cleaned-up version should be 3a735d4b8d8c53abd8933fbce6783156951136b3 in https://github.com/rdolbeau/zfs/tree/openzfs-abd-patchset

**Comment by kernelOfTruth** [comment]
The buildbots have passed but I better ask before I take the plunge:

I need to update my kernels asap since there's a data corruption issue/regression with Btrfs (since 4.7),

thus I'd like to take the opportunity to update ZFS, too

My system is facing pretty high memory fragmentation (when using zram as /var/tmp[/portage] and swap partition in RAM [32 GB !]

and thus after 1-2 days of uptimes certain compilations fail to succeed (e.g. firefox or chromium etc.) in that setup.

Is this PR ready for (albeit bleeding edge) production testing ?

Thanks

**Comment by ironMann** [comment]
@kernelOfTruth This commit only makes some housekeeping structures smaller. It will probably make more difference in fragmented system. Actual allocation strategy is identical to main ABD PR.
There's a debugging print to syslog currently, which might be annoying if you build DEBUG.
Main cause of mem fragmentation should be also fixed in the #5135

**Comment by tuxoko** [comment]
@ironMann 
Do you have any stat on the benefit and overhead of sorting?
Doing sorting seems pretty heavy handed, I would prefer we don't do it.

**Comment by behlendorf** [comment]
@rdolbeau your 3a735d4 patches LGTM and works well.  I've verified all the RAIDZ tests pass for neon and neonx2.  Performance is down somewhat in the micro benchmark compared to the pre-ABD versions presumably due to the additional loads and stores but it's still much better than original.  And there's always room for further improvement.  @ironMann your avx512f changes works as expected too!

@ironMann I'm going to close this issue out since I've pulled everything but your sorting/merge changes in to #5135 which should be merged shortly.  After it's merged go ahead and  open a new PR with this proposed optimization so we can discuss it there.

**Pull request closed without merging**
