### PR TITLE
zfs send -p also prunes remote snapshots that did not exist on sending side

### LINKED ISSUE #5341: `zfs send -p | zfs receive -F` destroys all other snapshots
From the man page of zfs receive:

> When a snapshot replication package stream that  is  generated  by  using  the  `zfs send -R`  command  is received,  any snapshots that do not exist on the sending location are destroyed by using the zfs destroy -d command.

I never used `-R`, but I did add `-p` to the send command (`zfs send -p -I ...`) because I wanted to transfer the properties along with the snapshots. But then the receive side (with `-F`) behaved as if I was sending a replication stream: it deleted all snapshots that didn't exist on the sending side.

This was not expected at all. Is this a bug in send, receive, or in the documentation? 

Edit: if this is the expected behavior, I'll submit a PR to make it clearer in the man pages.

### PR DESCRIPTION
**Pull request by kpande**
update man page to mention that `send -p` causes snapshot deletion on `zfs recv`

closes #5341

Signed-off-by: Kash Pande <kash@tripleback.net>

### How Has This Been Tested?
Rendered locally.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by allanjude** [comment]
Am I missing something, I thought -p was 'send properties'?

**Comment by kpande** [comment]
yes, it is. but it also ends up removing remote snapshots that didn't exist locally, so we should at least document that.

**Comment by allanjude** [comment]
> 
> 
> yes, it is. but it also ends up removing remote snapshots that didn't exist locally, so we should at least document that.

Does it do this without -F? or only with -F on the receive side?

**Comment by kpande** [comment]
```
[/home/kash]-[root@fezzik]-[0]-[10101]
[:)] # zfs send -p -I rpool/misc/src@final rpool/misc/src@new1 | zfs recv -F rpool/misc/dest
[/home/kash]-[root@fezzik]-[0]-[10102]
[:)] # zfs list -t snap -r rpool/misc/src                                                   
NAME                        USED  AVAIL     REFER  MOUNTPOINT
rpool/misc/src@final          0B      -       24K  -
rpool/misc/src@1550296804     0B      -       24K  -
rpool/misc/src@11168          0B      -       24K  -
rpool/misc/src@30848          0B      -       24K  -
rpool/misc/src@11173          0B      -       24K  -
rpool/misc/src@11210          0B      -       24K  -
rpool/misc/src@11192          0B      -       24K  -
rpool/misc/src@11182          0B      -       24K  -
rpool/misc/src@new1          14K      -       24K  -
[/home/kash]-[root@fezzik]-[0]-[10103]
[:)] # zfs list -t snap -r rpool/misc/dest                                                  
NAME                         USED  AVAIL     REFER  MOUNTPOINT
rpool/misc/dest@final          0B      -       24K  -
rpool/misc/dest@1550296804     0B      -       24K  -
rpool/misc/dest@11168          0B      -       24K  -
rpool/misc/dest@30848          0B      -       24K  -
rpool/misc/dest@30843          0B      -       24K  - < removed from source filesystem
rpool/misc/dest@11173          0B      -       24K  -
rpool/misc/dest@11210          0B      -       24K  -
rpool/misc/dest@11192          0B      -       24K  -
rpool/misc/dest@11182          0B      -       24K  -
rpool/misc/dest@new1           0B      -       24K  -
[/home/kash]-[root@fezzik]-[0]-[10104]
[:)] # 

```

**Pull request closed without merging**
