### PR TITLE
Enhance [-V|--version] to conditionally emit git version string

### PR DESCRIPTION
**Pull request by TerraTech**
### Motivation and Context

Amends PR #8567

It will test and conditionally emit the git revision string if available.  I was working on this change, but the referenced PR was merged before I submitted the updated code.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by behlendorf** [comment]
Thanks for following up with a new PR so we can hash this out.  I think this change might be what we want to do, but before doing this I wanted to explore another other possible solution.

What we have today is the following version information.  Both of these approaches have their advantages and drawbacks depending on your perspective:

* `ZFS_META_ALIAS` - This is generated at `./configure` time and is composed of `ZFS_META_NAME`, `ZFS_META_VERSION`, and `ZFS_META_RELEASE`.  The last release component is either derived from the output of `git-describe` or the `Release:` field in the top level `META` file.  This is convenient for releasing tagged versions since it's not dependent on building from a git tree.  Plus downstream packagers are free to modify the release string as they see fit.  It does support including git commit information in the release when building from an arbitrary commit, but has the downside of requiring re-running configure which is slow.

* `ZFS_META_GITREV` - This is generated at `make` time which means it will be up to date with the last commit in your local git tree.  This is great for developers who need to iterate quickly since the `ZFS_META_GITREV` is unconditionally updated even for incremental builds.  However, it does require you to be working in a git tree, and it does require your changes be locally committed.  Since this is typically the case for developers it can be super convenient.

That said, in my opinion it's `ZFS_META_ALIAS` is what we want to be printing by default for two reasons.
1) While useful to developers, I'd argue end users are the primary consumers of `zfs --version`.  In which case, we should be reporting whatever additional the distribution specific release information was provided.  Not a hash which is likely to not exist in the ZoL source tree.
2) More importantly, when building from the same source I think we want the kmod `/sys/module/zfs/version` and `zfs_version_userland()` versions to match exactly.  That means we need to pick a specific constant since this is what's required by the kernels `MODULE_VERSION` macro.

Given that, what if we instead added a command line option to the `zfs version` subcommand to specifically output the user and kernel gitrev.  This would make the version reporting unambiguous and be convenient.  The loaded kmod's gitrev is available in the `/proc/sys/kernel/spl/gitrev` file.  Thoughts?

**Comment by TerraTech** [comment]
@behlendorf I am open to whatever design you feel it needs to be.  The work I did was addressing the need to emit a version string and also satisfy the requests it be the git version if available.  Beyond that, I'm willing to leave it as is in current iteration or it can be expanded on if the macros are made available that provides the consistency you are looking for.  FWIW, I'm not personally interested in the git revision, I think it makes the output a bit clunky, I was only adding it because it seems to have been desired by others to emit.  As far as two line output, I think it is ok since programmatically you can read whichever one you want (userland/kernel) as the output is consistent.

**Comment by Conan-Kudo** [comment]
The way I'd been handling it downstream is by mutating the META file used as input for everything...

```spec
# Embed downstream version in module
sed -e 's/^Version:.*/Version:      %{version}/' -e 's/^Release:.*/Release:      %{release}/' -i.orig META
```

Since that feeds into everything else, my version information is easily captured...

**Comment by behlendorf** [comment]
@TerraTech I'd like to close this for now and leave the reporting as is.  We can revisit this if there's a real need to make further changes.

**Pull request closed without merging**
