### PR TITLE
Require libblkid when building

### PR DESCRIPTION
**Pull request by FransUrbo**
Use '--without-blkid' to disable.

Includes @behlendorf #2502 pull request.

Closes: #2448

### CODE REVIEW

**Comment by ryao** [comment]
@behlendorf @FransUrbo People in #zfsonlinux on freenode who built the code from source are having issues because they didn't link against libblkid. Something like this would prevent that. I think we should revisit merging it for 0.6.4.

**Comment by FransUrbo** [comment]
@ryao if you want to run with this, you have my blessing.

**Comment by ryao** [comment]
I just read the scrollback to refamiliarize myself with this. @behlendorf If you have a chance, would you check to see if blkid exhibits the same problem on RHEL7?

**Comment by behlendorf** [comment]
I've opened #3166 with a refreshed version of this patch stack.  That should answer the RHEL7 question.  Also be aware there's some libblkid work going on in https://github.com/karelzak/util-linux/pull/155 for ZFS.

**Pull request closed without merging**
