### PR TITLE
Explicit block device plugging when submitting multiple BIOs.

### PR DESCRIPTION
**Pull request by thegreatgazoo**
Without plugging, the default 'noop' scheduler will not merge the BIOs which are part of a large ZIO. The Linux BIO currently is limited to 1M, so this would only affect ZFS blocks larger than 1M.

The graph below shows average write request size during copying an 1G ubuntu image to a single drive zpool with 16M recordsize:
io

The requests reached at about 1M. The next graph shows the same thing with this patch applied:
io plug

The requests reached at about 5M.

### CODE REVIEW

**Comment by thegreatgazoo** [comment]
Forgot to mention: /sys/block/*/queue/max_sectors_kb needs to be large enough to enable large IO requests.

**Comment by dweeezil** [comment]
I don't think EL (2.6.36) kernels have the explicit block plug/unplug functions.

**Comment by adilger** [comment]
It looks like the queue plugging interface was added in commit v2.6.38-rc6-12-g73c1010, which puts it just after EL6 if one goes by the kernel version.  However, it wouldn't be surprising if RHEL backported this patch to their kernel, but that doesn't seem to be the case:

zfs-0.7.0/module/zfs/vdev_disk.c: In function '__vdev_disk_physio':
zfs-0.7.0/module/zfs/vdev_disk.c:527: error: storage size of 'plug' isn't known
zfs-0.7.0/module/zfs/vdev_disk.c:597: error: implicit declaration of function 'blk_start_plug'
zfs-0.7.0/module/zfs/vdev_disk.c:605: error: implicit declaration of function 'blk_finish_plug'

**Comment by thegreatgazoo** [comment]
Will add a configure test.

**Comment by thegreatgazoo** [comment]
@adilger I think the bio_count can be set to zio size divided by max bio size, or in the case of abd simply set to the # of frags divided by BIO_MAX_PAGES. Or we'd even consider the drive's max_sectors_kb. It can be a lot smarter than a simple 16.

**Pull request merged**
