### PR TITLE
Refactor SYSV init and initramfs (Phase 2)

### PR DESCRIPTION
**Pull request by FransUrbo**
- Rearrangement of some source directories.
  - Move the SYSV init scripts into the contrib directory. This isn't really part of the ZFS/ZoL code, so it's more appropriate to put it in the contrib directory.
  - Make sure the zfs-functions library file and the zfs 'defaults' file is in a separate directory (contrib/shell-common), to indicate it's significance for everything that needs generic functions in shell (sh) script code.
- Refactoring of common code between the SYSV init and initramfs scripts. 
  - Move code from the SYSV init and initramfs scripts that is better served in a common code base library (zfs-functions).
  - Use "${VAR}" instead of "$VAR".
  - Add some comments to functions that didn't have any.
  - Create zfs_run_cmd() which records stderr, exit code etc.
  - zfs_set_ifs() needs to be a global func. Use this in zfs_run_cmd() before we run the actual command.
  - Dracut have the func emergency_shell() which does a little more. For those that don't have it, just run '/bin/sh -i -l'.
  - Minor fix/change to read_mtab():
    - Strip control characters (space - \040) from /proc/mounts GLOBALY, not just first occurrence.
    - Don't replace unprintable characters ([/-. ]) for use in the variable name with underscore. No need, just remove them all together.
  - Move code snippet that fetches and mounts recursive filesystems into the new recursive_mount_filesystems() function.

In the discussion in https://github.com/FransUrbo/zfs/commit/9815562119d808b9ef8e08fc9dad659574e9a6bd#commitcomment-11919415, we talk about a three stage process. This PR is "Phase 2" and should preferably be applied as one of the first after the tag (because it rearranges code directories etc, which might be somewhat disruptive).

### CODE REVIEW

**Comment by FransUrbo** [comment]
@behlendorf How far of is 0.6.5? I had expected it to be tagged (quite) some time ago. But if you're waiting for the ADB stuff to (which I'd recommend NOT to get in here now, it would be nicer to have 0.6.5 "out the door" instead of delaying even further just for that - it can wait), maybe you should consider this PR for this release after all?

It contain some bug fixes and issues I've seen with the current init and initrd scripts…

It's not as dangerous as it looks. The primary part is move stuff into the <code>contrib</code> directory (neither the SYSV init, initrd or dracut is _really_ part of the core ZoL code so it's better suited in the <code>contrib</code> dir - we should probably move the systemd stuff there to, but it was a little out of scope for this PR, unless you think it's appropriate) and move some code from the initrd script into the common <code>zfs-functions</code> script where it does more good.

I haven't touch any dracut stuff in this PR (which I'm know you're "afraid" of). This PR _only_ touches "my" init and initrd scripts..

**Comment by FransUrbo** [comment]
I've rebased the PR against latest master and the init/initrd commit which is now in there. I also took the time to split up the different parts of the PR into separate commits.

Just FYI, I really hate the last commit myself, but it should be done. I'm very much for ignoring it, but I think it should (not need) to be done eventually/at some point… :(

**Comment by FransUrbo** [comment]
I've split up the fixes, which can be considered regressions, into three different commits. At least the last two of those might be considered for the next release tag..

**Comment by FransUrbo** [comment]
The "Some function improvenments to the SYSV init and initramfs scripts" commit might be better of as a separate pull request, but I leave it up to @behlendorf to decide that. It's in here for now..

This PR consists of three major parts, subdivided into separate commits:
1. Refactoring (moving code into the generic <code>zfs-functions</code> script)
2. Improvements (which should possibly be in a separate PR)
3. Minor fixes to existing code (possibly also a separate PR).

and the dreaded and super-ugly last "shell check fixes"… I'm not even sure I want that any more, but I leave it up to "the powers that be" to decide it's fate. It's to ugly for me to look at now :)

**Comment by FransUrbo** [comment]
@behlendorf Do we have an (approximate) ETA on this?

**Comment by behlendorf** [comment]
I'd like to get more eyes on these changes.  @ryao can you look these over.

**Comment by behlendorf** [comment]
There are some nice improvements in these proposed patches.  Unfortunately, they never got the attention they deserved in terms of reviewers and testing.  As such I was never comfortable with merging them to master.  If someone would like to continue with this work my suggestion would be to start with the most important changes and open new PRs against master.  Keeping the PRs small and as functionally independent as possible will make it easier to review and test the changes.  Closing.

**Pull request closed without merging**
