### PR TITLE
Initramfs cherry fixes

### PR DESCRIPTION
**Pull request by FransUrbo**
Cherry picking from #3559 for next 0.6.5.x point release.

Closes: #3782

### CODE REVIEW

**Comment by behlendorf** [comment]
@FransUrbo sorry I didn't get to these patches last week.  I wanted to address the major stability issues first so they could be stress tested over the weekend.  As for these patch some of them go a little farther than I would have expected for a stable release, but they all look reasonable.  Aside from the cleanup patches are these all things users have encountered?

**Comment by FransUrbo** [comment]
Yes, I got a little overzealous when splitting up everything "bug fix related" from "Phase 2" into separate commits for your consideration. I knew from the start that some of these isn't "back port material", but I rather let you decide what isn't and what is…

As I've commented inline, my intention with any that would be accepted wasn't going to go into <code>master</code> ONLY, directly, into the 0.6.5.x branch(es). They're all present in the "Phase 2" which I _did_ expect to go into master…

If you rather accept X number of them, rebase them into one commit when you commit them, and then push them to master and then merge that commit into the 0.6.5.x branch, that's fine by me. I'll just rebase my "Phase 2" accordingly, but that wasn't my intention...

**Comment by behlendorf** [comment]
Let me pull @nedbass in to this conversation since he's officially maintaining the release branch, not me.   Generally speaking we thought that as a matter of policy it's best to cherry-pick fixes from master on to the release branch.  This makes it easy to verify that a specific fix appears on both the master and a release branch.

So with that in mind what I'd like to do is merge __all__ the following patches in to master after they're refreshed to address any comments.  Then rebase, review, and merge the remaining phase 2 changes in to master fairly quickly.  This way @nedbass can easily cherry pick some (or all) of these, since we'll need to get his buy off on what's appropriate.  Here's my feelings about the following changes and which ones should be in the release branch.

* Small very safe changes, which address issues people have actually hit and would immediately benefit from.

f1a8289 Fix update-rc.d commands in postinst.
55bedb2 * Add a config option "ZPOOL_IMPORT_O
7f54cd1 Before trying to mount a filesystem 
5ae6625 * Remove some 'local' variables that 
c4e9767 * Add a ZFS_POOL_IMPORT to the default
f634dd7 * Remove "sort" from find_pools() and
e81d4ea * Minor fix/change to read_mtab():

* Nice improvements we definitely want, but they don't directly fix anything and pose a tiny (but non-zero) risk of accidentally breaking something.  I could be talked in to these if they're causing user pain today.

4551cb6 * Wrap call to decrypt_fs(), zfs comm
6054957 * Create check_boolean() to check if  (I'd pull the DO_OVERLAY_MOUNTS fix out and apply that above)
4f8f71b Fixing some (minor) issues discovered

**Comment by FransUrbo** [comment]
I would somewhat argument AGAINST putting

4551cb6 * Wrap call to decrypt_fs(), zfs comm
4f8f71b Fixing some (minor) issues discovered

in the release branch. The first gives the unfortunate side effect that pools with spaces can't be imported any more :(. I was hoping to get some help with that in the "Phase 2" PR. But it's outside the scope _now_.

The second isn't something anyone have actually seen (yet). Or if they did, they didn't think about it (it's very subtle). I bet very, very few is running with debugging on and that second one is just to get slightly more output.


The

6054957 * Create check_boolean()

is something people _have_ been hitting though. At least twice. _Possibly_ in zfsonlinux/pkg-zfs#175, but it's not verified yet. It have been seen elsewhere though, but I don't have the issue number.

Other than that, I agree with your picks. I've updated the PR with your comments. I have NOT removed the ones you did not pick, nor did I rebase them into one. I'll let you/nedbass do that at your discretion.

**Comment by behlendorf** [comment]
@FransUrbo OK, it sounds like we're largely in agreement.  I can see how the check_boolean fix could mitigate some possible issues so I'll pull everything but the following, squash them in to a single commit and merge it to master for Ned to cherry pick.

4551cb6 * Wrap call to decrypt_fs(), zfs comm
4f8f71b Fixing some (minor) issues discovered

**Comment by nedbass** [comment]
I am in agreement.

**Comment by behlendorf** [comment]
@FransUrbo @nedbass I'm proposing merging behlendorf/zfs@fd00e217445bca8257412a9d92f7e2f012d8d794 in to master to be cherry picked to the release branch.  Does this look good to both of you.

**Comment by nedbass** [comment]
The only thing I'm slightly squeamish about are the `check_boolean()` changes. As I read it, there is a change in behavior in the `do_start()` functions that could theoretically cause breakage. Before, anything that wasn't "off", "no", or "0" (ignoring case) was treated as set, whereas now anything that isn't "yes" or "1" is treated as unset. So maybe someone out there has something like "On" in their config file? That would be unsupported syntax, yes, but I still dislike gratuitous functional changes in point releases.

**Comment by FransUrbo** [comment]
@nedbass If you like, I could add <code>On</code> to the list of "set" values… ? I think that's a reasonable assumption…

And the <code>do_start()</code> problem/change in functionality was fixed in my latest push (4cb74e3b9f96f17ea26daf3a817f72c0733a561e).

And technically, the config option haven't been around long enough to have a huge difference in a lot of users. And I think we need to check for "set", not "unset" (because "unset" could also mean that the option is commented out).

**Comment by behlendorf** [comment]
Good thought.  I'll extend the `check_boolean()` function to include `on`.  I can add that to the final merged version.  Aside from that this looks good to me and I think moving everything to a standard function as soon as possible to make everything consistent is a good thing.

**Comment by FransUrbo** [comment]
@behlendorf If you could apply this patch (and update the commit log) as well (or I could push a new commit), I'd appreciate it. @nedbass have a point about <code>On</code>:

```
diff --git a/etc/init.d/zfs-functions.in b/etc/init.d/zfs-functions.in
index 486d2f0..06f4cc9 100644
--- a/etc/init.d/zfs-functions.in
+++ b/etc/init.d/zfs-functions.in
@@ -316,7 +316,7 @@ check_boolean()
 {
        local var="$1"
 
-       echo "$var" | grep -Eiq "^yes$|^1$" && return 0 || return 1
+       echo "$var" | grep -Eiq "^yes$|^on|^1$" && return 0 || return 1
 }
 
 # Check to see if we're running in debug mode
diff --git a/etc/init.d/zfs.in b/etc/init.d/zfs.in
index f4753b2..14bf493 100644
--- a/etc/init.d/zfs.in
+++ b/etc/init.d/zfs.in
@@ -1,7 +1,8 @@
 # ZoL userland configuration.
 
-# To enable a boolean setting, set it to yes, Yes, YES (or any case combination
-# thereof) or to 1. Anything else will be interpreted as unset.
+# To enable a boolean setting, set it to yes, Yes, YES, on, On (or any
+# case combination thereof) or to 1. Anything else will be interpreted
+# as unset.
 
 # Run `zfs mount -a` during system start?
 ZFS_MOUNT='yes'
```

But as I said, I don't think it's much of a problem. Think… :)

**Comment by woffs** [comment]
What about true/false? Sorry ;-)

**Comment by FransUrbo** [comment]
@behlendorf If you could incorporate <code>true</code> as well while you're at it, that would be super. Thanx @woffs, good call!

**Comment by FransUrbo** [comment]
@behlendorf I'm happy with your merge, go for it...

**Comment by behlendorf** [comment]
@woffs OK by me, better now than latter.  OK, take a look a behlendorf/zfs@t1ffd57a5b2fc82d20b6bb305d0f4aada563417af, @FransUrbo I changed you wording somewhat in the comment, since we're making it more permissive I don't think we need to be that explicit.

**Comment by FransUrbo** [comment]
@behlendorf I'm good with that. I just worry that people won't get that it's case insensitive… But it's perfectly fine, maybe they don't really need to know.

**Comment by nedbass** [comment]
LGTM

**Comment by behlendorf** [comment]
OK merged as, let's move any remaining rework to a new issue and keep it only on master if possible.

5773296 Init script fixes

**Pull request closed without merging**
