### PR TITLE
Always continue recursive destroy after error

### PR DESCRIPTION
**Pull request by alek-p**
### Description
This patch switches recursive destroy to always do a best-effort recursive destroy.

### Motivation and Context
Currently, during a recursive zfs destroy the first error that is encountered
will stop the destruction of the datasets. Errors can happen for a variety of
reasons including competing deletions and busy datasets. Switching to
a best-effort destroy seems like a good idea.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
@alek-p you'll need to rebase this on the very latest master and force update the PR.  Your running builds were cancelled when the buildbot was restarted.

**Comment by ahrens** [comment]
This change could apply on other platforms as well, where `-f` already has a specific meaning.  It might not be a great idea to overload the meaning of `-f`.

**Comment by behlendorf** [comment]
Overloading this flag felt like it was in the same spirit of what the existing `-f` was trying to accomplish. 
 However, if you'ld rather we add a new flag for this I'm fine with that too.

**Comment by ahrens** [comment]
I think the spirit of the existing `-f` is "do whatever it takes to do what I said".  Whereas this change is saying, "It's OK if you can't do what I said, just try your best."

**Comment by ahrens** [comment]
TBH I think it would be more reasonable to make "try your best" be the default, than to conflate it with `-f`.  It wouldn't break the interface, since we don't say what order we will try to do the destroys in, we can just say that we did all the destroyable filesystems, and then hit the non-destroyable ones and failed.

**Comment by alek-p** [comment]
Thanks for the reviews, I'm good with both adding something like `-F` or making best-effort the default. I do think it makes a lot of sense to always do a best effort recursive destroy so I'll go with that approach.

**Pull request merged**
