### PR TITLE
Hold lock as a writer when modifying se_taskqid

### PR DESCRIPTION
**Pull request by alek-p**
### Description

snapentry_expire() and zfsctl_snapshot_unmount_cancel() could modify
zfs_snapentry_t's se_taskid while holding the snapshot lock as readers.
This leads to a race on se_taskid manifested in hitting the se_taskqid
assert in zfsctl_snapshot_unmount_delay_impl().

This patch switches the locks to write locks to reflect the functions'
true intentions. The patch also adds some asserts in order to
document our assumptions about these functions.

### Motivation and Context

We've seen the assert fire while testing in the Datto lab:
```
[2985333.968482] VERIFY3(se->se_taskqid == ((taskqid_t)0)) failed (6290 == 0)
[2985333.979621] PANIC at zfs_ctldir.c:375:zfsctl_snapshot_unmount_delay_impl()
[2985333.990973] Showing stack for process 17335
[2985333.990977] CPU: 9 PID: 17335 Comm: java Tainted: P           OE   4.4.0-67-generic #88-Ubuntu
[2985333.990979] Hardware name: Supermicro X9DRD-7LN4F(-JBOD)/X9DRD-EF/X9DRD-7LN4F, BIOS 3.2 01/16/2015
[2985333.990981]  0000000000000286 0000000008a44152 ffff88293db8b9d8 ffffffff813f86d3
[2985333.990984]  ffffffffc1088eff 0000000000000177 ffff88293db8b9e8 ffffffffc0438872
[2985333.990986]  ffff88293db8bb70 ffffffffc043893b 0000000008a44152 ffff882d00000030
[2985333.990988] Call Trace:
[2985333.990998]  [<ffffffff813f86d3>] dump_stack+0x63/0x90
[2985333.991010]  [<ffffffffc0438872>] spl_dumpstack+0x42/0x50 [spl]
[2985333.991016]  [<ffffffffc043893b>] spl_panic+0xbb/0xf0 [spl]
[2985333.991086]  [<ffffffffc0f219d6>] ? zfs_refcount_add+0x16/0x20 [zfs]
[2985333.991142]  [<ffffffffc0f6e848>] ? zfsctl_snapshot_find_by_objsetid+0x68/0xc0 [zfs]
[2985333.991192]  [<ffffffffc0f60fb7>] ? fzap_add_cd+0x147/0x200 [zfs]
[2985333.991202]  [<ffffffff8183c497>] ? _raw_spin_lock_irqsave+0x37/0x40
[2985333.991212]  [<ffffffffc0436630>] ? taskq_cancel_id+0xd0/0x130 [spl]
[2985333.991259]  [<ffffffffc0f6eeb2>] zfsctl_snapshot_unmount_delay_impl+0x82/0x90 [zfs]
[2985333.991310]  [<ffffffffc0f6efa2>] zfsctl_snapshot_unmount_delay+0x52/0xd0 [zfs]
[2985333.991360]  [<ffffffffc0fb40f7>] zpl_revalidate+0xe7/0x110 [zfs]
[2985333.991366]  [<ffffffff8121a0af>] lookup_fast+0x24f/0x330
[2985333.991368]  [<ffffffff8121b779>] walk_component+0x49/0x300
[2985333.991371]  [<ffffffff8121cd01>] link_path_walk+0x191/0x5b0
[2985333.991373]  [<ffffffff8121b16b>] ? path_init+0x1eb/0x3c0
[2985333.991376]  [<ffffffff8121d5e9>] path_openat+0xa9/0x1330
[2985333.991381]  [<ffffffff81101d9e>] ? futex_wake_op+0x2ee/0x620
[2985333.991385]  [<ffffffff810b5269>] ? update_curr+0x79/0x160
[2985333.991387]  [<ffffffff8121fa61>] do_filp_open+0x91/0x100
[2985333.991390]  [<ffffffff8122d366>] ? __alloc_fd+0x46/0x190
[2985333.991393]  [<ffffffff8120df08>] do_sys_open+0x138/0x2a0
[2985333.991398]  [<ffffffff8106b544>] ? __do_page_fault+0x1b4/0x400
[2985333.991401]  [<ffffffff8120e08e>] SyS_open+0x1e/0x20
[2985333.991404]  [<ffffffff8183c672>] entry_SYSCALL_64_fastpath+0x16/0x7
```

### How Has This Been Tested?

I've unit tested this by scripting some operations on .zfs dir but testing completely is hard since can't repro the race at will.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
Thanks for spotting this.  It appears `zfs_rename_002_pos` reliably triggers an issue with this patch which needs to be explained.

```
[ 6193.865576] VERIFY(txg_list_empty(&dp->dp_dirty_dirs, txg)) failed
[ 6193.870603] PANIC at spa.c:6655:spa_sync()
[ 6193.873928] Showing stack for process 3776
[ 6193.877008] CPU: 0 PID: 3776 Comm: txg_sync Tainted: P           O    4.8.1-1.el7.elrepo.x86_64 #1
[ 6193.877995] Hardware name: Xen HVM domU, BIOS 4.2.amazon 11/11/2016
[ 6193.885073]  ffffffff81353baf 0000000060d5341d ffff8800aa197b58 ffffffff81353baf
[ 6193.885073]  ffffffffa080b50c 00000000000019ff ffff8800aa197b68 ffffffffa052a144
[ 6193.885073]  ffff8800aa197cf0 ffffffffa052a20f 0000000000013d2c ffff880100000028
[ 6193.885073] Call Trace:
[ 6193.885073]  [<ffffffff81353baf>] ? dump_stack+0x63/0x84
[ 6193.885073]  [<ffffffff81353baf>] dump_stack+0x63/0x84
[ 6193.885073]  [<ffffffffa052a144>] spl_dumpstack+0x44/0x50 [spl]
[ 6193.885073]  [<ffffffffa052a20f>] spl_panic+0xbf/0xf0 [spl]
[ 6193.885073]  [<ffffffff8115d31e>] ? stack_trace_call+0x4e/0x80
[ 6193.885073]  [<ffffffff8173c587>] ? ftrace_call+0x5/0x34
[ 6193.885073]  [<ffffffff817386b5>] ? mutex_unlock+0x5/0x20
[ 6193.885073]  [<ffffffffa052a155>] ? spl_panic+0x5/0xf0 [spl]
[ 6193.885073]  [<ffffffffa06b7925>] ? multilist_is_empty+0xa5/0x120 [zfs]
[ 6193.885073]  [<ffffffffa06c6e50>] spa_sync+0x11f0/0x1220 [zfs]
[ 6193.885073]  [<ffffffff811f57b5>] ? kfree+0x5/0x170
[ 6193.885073]  [<ffffffffa0522e3a>] ? spl_kmem_free+0x2a/0x40 [spl]
[ 6193.885073]  [<ffffffffa0522e15>] ? spl_kmem_free+0x5/0x40 [spl]
[ 6193.885073]  [<ffffffffa06dbf4c>] txg_sync_thread+0x2ec/0x570 [zfs]
[ 6193.885073]  [<ffffffffa06dbc60>] ? txg_init+0x2c0/0x2c0 [zfs]
[ 6193.885073]  [<ffffffffa0525caa>] thread_generic_wrapper+0x7a/0xc0 [spl]
[ 6193.885073]  [<ffffffffa0525c30>] ? __thread_exit+0x20/0x20 [spl]
[ 6193.885073]  [<ffffffff810a1128>] kthread+0xd8/0xf0
[ 6193.885073]  [<ffffffff8173ad3f>] ret_from_fork+0x1f/0x40
[ 6193.885073]  [<ffffffff810a1050>] ? kthread_park+0x60/0x60
```

**Comment by alek-p** [comment]
deadlock was my concern as well, but I haven't found conflicting stacks yet but I'll think about what else we can do here.

**Comment by alek-p** [comment]
I haven't had time to look at this again and probably won't have time to do so in the near future.
Would it be preferable to close this and convert it to a bug instead of a PR?

**Comment by behlendorf** [comment]
@alek-p yes, I think that would be best.  Can you please open a new bug with the needed details and close out this PR.  You can link to issue to this closed PR to so we won't lose this discussion.

**Pull request closed without merging**
