### PR TITLE
Fix zfs_putpage() lock inversion (again)

### PR DESCRIPTION
**Pull request by behlendorf**
This is a follow up commit to 74328ee which correctly resolved a lock
inversion between zfs_putpage() and zfs_free_range().  Unfortunately,
in the process it accidentally introduced another inversion between
zfs_putpage() and zfs_read().  The page must be unlocked before taking
the range lock.  This patch corrects that issue.

In addition, because the locking rules here are subtle a block comment
has been added clearly explaining why the ordering here is critical.

Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>
Issue #2976

### CODE REVIEW

**Comment by behlendorf** [comment]
@dweeezil @ryao could you please take a look at this.  Commit 74328ee was responsible for the recent rash of testing failures on master, this commit resolves the failure which was accidentally introduced.

**Comment by dswartz** [comment]
"must be help in order to prevent a lock inversion with the"

should be

"must be held in order to prevent a lock inversion with the"

**Comment by behlendorf** [comment]
@dswartz Thank you, I've refreshed the patch.

**Comment by behlendorf** [comment]
Merged as d958324f97f4668a2a6e4a6ce3e5ca09b71b31d9.  This will resolve the recent rash for test failures on master.

**Comment by dweeezil** [comment]
Sorry I didn't get a chance to look at this until after the fact, but it LGMT anyway.

**Pull request closed without merging**
