### PR TITLE
Reintroduce IO accounting on zvols on Linux 3.19+

### PR DESCRIPTION
**Pull request by ryao**
zfsonlinux/zfs@e20cd6f7a8922709b1aa2ecefd783390102d79e0 caused us to 
lose IO accounting on zvols. When I originally wrote that last year, the
symbols we needed to maintain IO accounting were GPL exported, but
torvalds/linux@394ffa503bc40e32d7f54a9b817264e81ce131b4 provided
suitable symbols for restoring this functionality 4 months later.  We
can call them to restore the IO accounting on Linux 3.19 and later as
well as any older kernels where that patch is backported.

Closes zfsonlinux/zfs#3741

Signed-off-by: Richard Yao <ryao@gentoo.org>

### CODE REVIEW

**Comment by sempervictus** [comment]
This seems to break AC's generation of the configure file:
```
checking for -Wno-unused-but-set-variable support... yes
checking for -Wno-bool-compare support... no
./configure: line 20741: syntax error near unexpected token `;'
./configure: line 20741: `	; do'
```
That region ends up looking like this:
```
20721 
20722         if test $rc -ne 0; then :
20723 
20724         else
20725                 if test "x$enable_linux_builtin" != xyes; then
20726 
20727         grep -q -E '[[:space:]]
20728                 { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
20729 $as_echo "yes" >&6; }
20730 
20731 $as_echo "#define HAVE_GENERIC_IO_ACCT 1" >>confdefs.h
20732 
20733         [[:space:]]' \
20734                 $LINUX_OBJ/$LINUX_SYMBOLS 2>/dev/null
20735         rc=$?
20736         if test $rc -ne 0; then
20737                 export=0
20738                 for file in
20739                 { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
20740 $as_echo "no" >&6; }
20741         ; do
20742                         grep -q -E "EXPORT_SYMBOL.*(
20743                 { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
20744 $as_echo "yes" >&6; }
20745 
20746 $as_echo "#define HAVE_GENERIC_IO_ACCT 1" >>confdefs.h
20747 
20748         )" \
20749                                 "$LINUX/$file" 2>/dev/null
20750                         rc=$?
20751                         if test $rc -eq 0; then
20752                                 export=1
20753                                 break;
20754                         fi
20755                 done
20756                 if test $export -eq 0; then :
20757                         rc=1
20758                 else :
20759                         rc=0
20760                 fi
20761         else :
```

Seems autoconf is doing something strange here. Any thoughts on what this might be? The exact same issue is visible around line 29934, with the surrounding 40 lines appearing identical at first pass.

**Comment by ryao** [comment]
@sempervictus I had not looked at ZFS_LINUX_TRY_COMPILE_SYMBOL's arguments carefully enough to notice that it added a couple for explicitly specifying a symbol and file containing it and autoconf was happy with it. That is fixed now.

**Comment by ryao** [comment]
Hmm... this doesn't seem to be working like I expected it to work. I will debug it when I find time.

**Comment by ryao** [comment]
The latest version works properly.

**Comment by behlendorf** [comment]
This patch looks good, however there are two minor style issue to address.

```
./include/linux/blkdev_compat.h: 347: #define followed by space instead of tab
./include/linux/blkdev_compat.h: 348: #define followed by space instead of tab
make: *** [cstyle] Error 1

**Comment by ryao** [comment]
@behlendorf The cstyle issue should be fixed.

**Comment by sempervictus** [comment]
Seems to work now, slowly pushing out to other testbeds, if all goes well will hit prod tomorrow.

**Comment by behlendorf** [comment]
The updated version looks good to me.  The test failures we all due to known issues or the VMs running out of free space in the case of the ztest seg faults.  Merged as:

8198d18 Reintroduce IO accounting on zvols on Linux 3.19+

**Pull request closed without merging**
