### PR TITLE
3.12 compat, 4.0 compat for super_operations shrinker callbacks

### PR DESCRIPTION
**Pull request by dweeezil**
3.12 API change - A node ID argument was added to the nr_cached_objects
and free_cached_objects callbacks in struct super_operations.

4.0 API change - The node ID and nr_to_scan arguments to the
nr_cached_objects and free_cached_objects callbacks in struct
super_operations were replaced with a single struct shrink_control
argument.

Also, the return value from each callback should be long.

I've not tested this yet, however, it means we've not had the ```nr_cached_objects``` callback enabled for quite some time, if ever.  I found this while looking into #3303.

### CODE REVIEW

**Comment by dweeezil** [comment]
I'm going to leave this as-is until it gets through the buildbots.

Although it does "fix" an error, it may actually make matters worse because the value returned by the ```nr_cached_objects``` callback is a lie and will cause the kernel's ```prune_super()``` to put less pressure on the the dentry and inode caches rather than more.

Unless we can do something useful in the ```free_cached_objects``` callback, I'd suggest we remove both of them from ZoL.  These callbacks appear to have been added mainly to support xfs and the manner in which it stores per-allocation group data.

**Comment by dweeezil** [comment]
Following on to @chrisrd's comment regarding my note above, #3350, which is running a kernel on which the autoconf test will actually work, provides a bit more evidence we should either get rid of the callback or simply have it return zero for the time being.  I'd suggest having it return zero to leave the callbacks in place mainly for documentation.  In fact, I'll update the pull request accordingly.

**Comment by behlendorf** [comment]
@dweeezil I agree.  We should update these callbacks so that they simply return zero but leave them in place.  I strongly suspect we're going to have a use for them once the ARC is integrated with the page cache.  At that point we should be able to abandon out existing overly broad shrinker hook in favor of something per-filesystem like this.

**Comment by dweeezil** [comment]
Updated pull request with commentary as to potential future use.

**Comment by behlendorf** [comment]
@dweeezil it looks like this is going to need a second look to resolve the build failures.

**Comment by dweeezil** [comment]
I'll look into the failures.  I clearly need to try it with a handful of intermediate kernels.

**Comment by behlendorf** [comment]
@dweeezil since #3495 takes care of the 3.12 compat issues (and will hopefully get merged tomorrow) we'll want to refresh this patch to just cover the minor 4.0 scan control issue.

**Comment by behlendorf** [comment]
Closing as stale.  #3495 addressed the Linux 3.12 compatibility issue and we can open a new pull request for the remaining less critical 4.0 issue.

**Pull request closed without merging**
