### PR TITLE
#4388 Prefetching data doesn't appear to be working

### PR DESCRIPTION
**Pull request by kernelOfTruth**
Account for the fact that rw_tryupgrade(&zf->zf_rwlock)

in module/zfs/dmu_zfetch.c could fail:

drop the rwlock
	rw_exit(&zf->zf_rwlock)
and reacquire
	rw_enter(&zf->zf_rwlock, RW_WRITER);

suggested by rottegift (Sean Doran) and lundman (Jorgen Lundman)

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/issues/4388

**Comment by prometheanfire** [comment]
what are the performance improvement characteristics of this?

**Comment by kernelOfTruth** [comment]
this http://buildbot.zfsonlinux.org/builders/Ubuntu%2014.04%20x86_64%20%28TEST%29/builds/783/steps/shell_9/logs/stdio

vs.

http://buildbot.zfsonlinux.org/builders/Ubuntu%2014.04%20x86_64%20%28TEST%29/builds/779/steps/shell_9/logs/stdio

around 2% 

This benchmark is of course not representative,

provided prefetch works again for data there should be potentially way more improvement in store ...

**Comment by kernelOfTruth** [comment]
**sigh**,

closing, 

re-opening another pull-request,

why on earth is git (or to be more precise - myself am) confusing different git accounts ?

:question:

**Comment by kernelOfTruth** [comment]
superseded by:

https://github.com/zfsonlinux/zfs/pull/4391


Sorry for the inconvenience,

classic case of PEBCAK :blush:

**Comment by rottegift** [comment]
The rw_tryupgrade failure blocks zfetch, which is the intelligent file 
prefetching, and you'd expect to see the biggest difference when there 
are or especially multiple reader threads doing forwards sequential, 
backwards sequential, or evenly strided accesses to a (zpl) file.

The bit of code I offered up has been running on my (o3x) systems since 
mid-October without problem.

With a bit more than two days of uptime:

kstat.zfs.misc.zfetchstats.hits: 33641401
kstat.zfs.misc.zfetchstats.misses: 3433891137
kstat.zfs.misc.zfetchstats.max_streams: 3427851539

@lundman IIRC we figured at the time that blocking is rare and 
short-lived, but certainly letting zfetching fail in those cases in 
order to be more like Illumos doesn't strike me as a bad idea.   It'd be 
interesting to benchmark and in particular to count how frequently the 
zfetching is not done as a result.

(If on an Illumos system the rw_tryupgrade failed frequently, it'd 
depress zfetching so much that someone ought to complain :) )

**Pull request closed without merging**
