### PR TITLE
fix typesetting of Errata #4

### LINKED ISSUE #8712: Errata #4 warning has a very long line due to a missing newline
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 29
Linux Kernel	| 5.0.10-200.fc29.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.0-rc4_35_gde3e0b914
SPL Version	| 0.8.0-rc4_35_gde3e0b914

### Describe the problem you're observing

After commit b3b60984ee191bdbb00b91842053c83581854db7, the warning message about Errata #4 has a very long line due to a missing newline at the end of the first part of the message in ``status_callback()''.

### Describe how to reproduce the problem
````
$ zpool status
  pool: ssddata
 state: ONLINE
status: Errata #4 detected.
Existing encrypted snapshots and bookmarks contain an on-disk incompatibility.
        This may cause on-disk corruption if they are used with 'zfs recv'. action:  To correct the issue, enable the bookmark_v2 feature. No additional
        action is needed if there are no encrypted snapshots or bookmarks. If preserving
        the encrypted snapshots and bookmarks is required, use a non-raw send to backup
        and restore them. Alternately, they may be removed to resolve the
        incompatibility.
   see: http://zfsonlinux.org/msg/ZFS-8000-ER
````

In addition a few other lines in the action: portion of the message are longer than 80 characters when printed out.

### PR DESCRIPTION
**Pull request by JMoVS**
fixes #8712

Signed-off-by: Justin Scholz <git@justinscholz.de>

Added some missing tabs and newlines, **was not able to verify myself though that it fixes the problem.** Could someone with access to a linux verify before merging? For both the import and the status callback?

### Description

Tried to catch all tabs and new lines that were still missing

### How Has This Been Tested?

Wasn't able to test, please verify it before merging.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by JMoVS** [comment]
@behlendorf I can update, but in your output in the first case, there are 7 spaces in the 7 lines after the first missing at the beginning including in the "see" line.

**Comment by JMoVS** [comment]
@behlendorf Thanks for testing and the fix! I pulled your branch and force-pushed, so this PR should be updated properly now.

**Comment by rlaager** [comment]
@JMoVS I'm confused about the status of this. To me, the first output from @behlendorf does not line up.

**Comment by behlendorf** [comment]
> To me, the first output from @behlendorf does not line up.

The alignment of the `zpool import` output is unfortunately expected.  The left 'column' of this output has been one character wider than the `zpool status` output (9 vs 8) for a while now, and all of the 'action' messages are indented with a single tab.

Offhand I'm not sure why this is the case, and I agree making the alignment consistent is the right thing to do.  But I think addressing that is outside the scope of this PR, and it really warrants its own.

@rlaager assuming you agree could you review and approve this PR.

**Pull request merged**
