### PR TITLE
rename reservation tests from *.sh to *.ksh

### PR DESCRIPTION
**Pull request by ikozhukhov**
rename reservation tests from *.sh to *.ksh

### Motivation and Context

we have ksh with zfs tests and have to use the same extension with others tests

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by richardelling** [comment]
If we're going to change the names, can we change them to be more descriptive rather than numbered? For example rename `reservation_001_pos.sh` to `reservation_avail_space.ksh`

**Comment by ikozhukhov** [comment]
could you help identify mapping of number to correct description?
i can to it

**Comment by richardelling** [comment]
Also, you'll want to verify that any CI/CD exclusions are appropriate and references in: 
- `linux.run`
- `zts-report.py`

Here's my proposal.

| old | new | notes
|---|---|---
| reservation_001_pos.sh | reservation_dataset_size.ksh | 
| reservation_002_pos.sh | reservation_pool_avail.ksh | 
| reservation_003_pos.sh | reservation_multiple_sets.ksh | 
| reservation_004_pos.sh | reservation_space_released.ksh | 
| reservation_005_pos.sh | reservation_none.ksh | 
| reservation_006_pos.sh | reservation_inside_outside.ksh | 
| reservation_007_pos.sh | reservation_peers_unaffected.ksh | 
| reservation_008_pos.sh | reservation_reduce.ksh | zts-report.py
| reservation_009_pos.sh | reservation_fs_none.ksh | 
| reservation_010_pos.sh | reservation_fs_destroy.ksh | 
| reservation_011_pos.sh | reservation_quota.ksh | 
| reservation_012_pos.sh | reservation_basic_function.ksh | 
| reservation_013_pos.sh | reservation_props_persist.ksh | 
| reservation_014_pos.sh | reservation_quota_as_limit.ksh | 
| reservation_015_pos.sh | reservation_volume_none.ksh | 
| reservation_016_pos.sh | reservation_volume_destroy.ksh | 
| reservation_017_pos.sh | reservation_volsize.ksh | 
| reservation_018_pos.sh | reservation_inherit.ksh | 
| reservation_019_pos.sh | reservation_auto.ksh | 
| reservation_020_pos.sh | reservation_fs_clone.ksh | 
| reservation_021_neg.sh | reservation_fs_refreservation.ksh | 
| reservation_022_pos.sh | reservation_volume_clone.ksh | 

@jwk404 can comment further

**Comment by lundman** [comment]
If you guys are in cleaning up the tests a bit, perhaps one would could convince you guys to pull in
`7512 Simplify the Makefiles in zfstest` and
`8204 Makefile changes in zfstest cannot cope with empty directories`
?

**Comment by ikozhukhov** [comment]
we are just with renaming of reservation*.sh tests

**Comment by ikozhukhov** [comment]
i'd like to see it integrated as is and rename to different name by separate PR.
right now it helps with merged to DilOS and sync tests results.

**Comment by richardelling** [comment]
I'm ok with the simple name changes for now. I'll open an issue for the renames that expands the scope to be more comprehensive.

**Pull request merged**
