### PR TITLE
Style check shell scripts

### PR DESCRIPTION
**Pull request by FransUrbo**
If the command "shellcheck" exists, then find all shell scripts and run shellcheck on them.

### CODE REVIEW

**Comment by FransUrbo** [comment]
@behlendorf Sure, good idea.

I've started fixing some of the warnings etc, but my fingers and eyes hurt :). Still 1478 warnings left :(.

I'll do another force push with the splitted targets.

**Comment by behlendorf** [comment]
I've merged the Makefile change to master but it appears the fixes patch has broken `zconfig.sh`.  When that get's refreshed with a fix let's move it in to a new pull request.

**Comment by FransUrbo** [comment]
Thanx, yeah the fixes was never meant to be merged. I'm only half way through, and I haven't gone over the fixes and verified that they're actually valid.

Besides, we can't really start using it (automatically) yet. There's just to many existing errors/warnings/notes, some valid, but many isn't. I've filed an issue with shellcheck - https://github.com/koalaman/shellcheck/issues/380 - because it sometimes (there's probably a couple of hundred in ZoL) tags things as "not ok", even though they are, programmatically.

Luckily, it's only done if <code>shellcheck</code> is actually installed, so we need not worry. I'll keep at it [continuing with the fixes], but considering the amount of work, I'm doing it on the 'back-burner'. I'll push that to another PR and keep that updated "every now and then" (so someone can continue the work if/when my fingers starts bleeding :).

**Comment by FransUrbo** [comment]
@behlendorf I'm about finished with #3435 (still need to go through it in detail a couple of more times and there's still _a lot_ of things not fixed), but started to notice that it have 618 ... "complaints" about <code>config/ltmain.sh</code>. This isn't ours, so maybe we should ignore that file as well? Or find a newer version that might be better (in regards to style check at least).

**Comment by behlendorf** [comment]
Or just exclude it and the other generated scripts from the check.

**Pull request closed without merging**
