### PR TITLE
Remove xdr_control() dependency

### PR DESCRIPTION
**Pull request by behlendorf**
The nvs_xdr_nvpair() function uses the xdr_control() interface as
an additional sanity check for the size parameter.  The spl.ko
module provides this functionality in the kernel but it is not
provided by glibc for user space.

Since this additional sanity check is not required only enable
for the kernel.  This check can be potentially implemented for
user space through the standard Linux XDR interface.

Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>
Issue #2254

### CODE REVIEW

**Comment by clandmeter** [comment]
@behlendorf building on musl with this patch and the removal of libtirpc will break the build with:

```nvpair_alloc_system.c:29:23: fatal error: rpc/types.h: No such file or directory```

and

```../../module/nvpair/nvpair.c:32:23: fatal error: rpc/types.h: No such file or directory```

**Comment by behlendorf** [comment]
@clandmeter this is because all of the xdr functionality is provided by `libtirpc` correct?  So we need and option to link against the library for libmusl.  Can you point me at your original patch.

**Comment by clandmeter** [comment]
Do you mean this one?

https://github.com/alpinelinux/aports/blob/master/testing/zfs-grsec/0002-Add-support-for-libtirpc.patch

p.s. this patch is made by @ncopa and not me.

**Comment by behlendorf** [comment]
That's the one, let me see about updating this patch accordingly.

**Comment by behlendorf** [comment]
@clandmeter refreshed.  This patch is based of all of the previous ones and works for me on CentOS with the standard libc and with the libtirpc-devel package.  Please review and test.

**Comment by clandmeter** [comment]
@behlendorf seems it cannot find the installed libtirpc, am i doing something wrong here?

config.log http://tpaste.us/37po

**Comment by behlendorf** [comment]
I'm not familiar with Alpine but it looks like `/usr/include/tirpc/rpc/xdr.h` expected to be able to include `/usr/include/rpc/types.h` which doesn't exist.  What provides that header in Alphine Linux?

```
configure:32215: checking tirpc/rpc/xdr.h usability
configure:32215: gcc -c -Os -fomit-frame-pointer -Os -fomit-frame-pointer conftest.c >&5
In file included from conftest.c:140:0:
/usr/include/tirpc/rpc/xdr.h:46:23: fatal error: rpc/types.h: No such file or directory
compilation terminated.
configure:32215: $? = 1
configure: failed program was:
```

It also seems like I may have introduced another problem since all the testers failed.  I'll look in to that.

**Comment by clandmeter** [comment]
@behlendorf  It looks like its looking in the wrong location. libtirpc provides /usr/include/tirpc/rpc/types.h so my guess is we need do similar as:
 https://github.com/alpinelinux/aports/blob/master/testing/zfs-grsec/0002-Add-support-for-libtirpc.patch#L189

**Comment by behlendorf** [comment]
@clandmeter I had been hoping to avoid adding that in to the path.  However, because of how tirpc was packaged it appears it's somewhat unavoidable.

**Comment by behlendorf** [comment]
@clandmeter OK, one more time.  Updated to add the needed include path for libtirpc. The _--with-tirpc/--without-tirpc_ configure options have been added to override the default tirpc check results.  This shouldn't be required for musl libc as long as the libtirpc devel packge is installed but they're available.

**Comment by clandmeter** [comment]
@behlendorf nice, this looks good.

I still have one outstanding issue left regarding zfs and musl. I need to pass -lintl to $LIBS to correctly link to libintl(gettext). I will create a separate issue for this.

**Comment by behlendorf** [comment]
@clandmeter thanks for the review and testing.  Merged as:

1ab3678 Add support for libtirpc

**Pull request closed without merging**
