### PR TITLE
Enable building the DKMS package on Debian-based distributions

### PR DESCRIPTION
**Pull request by Conan-Kudo**
### Description
This pull request adds the ability to generate DKMS packages that are compatible and installable for Debian and derivatives.

This depends on zfsonlinux/spl/pull/657.

### Motivation and Context
This change is intended to fix zfsonlinux/zfs/issues/6044.

### How Has This Been Tested?
I built it and installed the DKMS packages on Debian 9.0 (Stretch) for x86_64/amd64. The packages installed and did the right things (built the module and installed it).

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [x] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by behlendorf** [comment]
@Conan-Kudo could you please add the following line to the ZFS commit comment.  It will ensure this PR gets tested with its SPL counterpart.

```
Requires-spl: refs/pull/657/head
```

**Comment by Conan-Kudo** [comment]
@behlendorf Does it matter which commit I put it in, or do I need to put it into both?

Also, do these requests also apply to spl, as I think I saw similar things there.

**Comment by behlendorf** [comment]
You need only add it to the top ZFS commit, and yes please make the same changes to the SPL PR.  You'll want to push the SPL updates first then the ZFS updates.

I also have a few tweaks to the buildbot I'll push for review which allow it to optionally use dkms packages I'll push once I'm sure they work.

**Comment by Conan-Kudo** [comment]
@behlendorf The requested changes are done in SPL and ZFS PRs.

**Comment by MasterCATZ** [comment]
Thank You, I have been dreading updating my kernel lately will see how 4.13 goes

**Pull request merged**
