### PR TITLE
Test zfsonlinux/spl#372

### PR DESCRIPTION
**Pull request by ryao**
Requires-spl: refs/pull/372/head
Signed-off-by: Richard Yao <ryao@gentoo.org>

### CODE REVIEW

**Comment by ryao** [comment]
@behlendorf filebench and the xfstests seem to be segfaulting on Amazon.

http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20%28TEST%29/builds/635/steps/shell_10/logs/console

I imagine that the SPL should have already been built at that point, so it is not clear to me what is is compiling that causes the segfault.

**Comment by ryao** [comment]
@behlendorf This passed the buildbot. :)

**Comment by behlendorf** [comment]
@ryao that spurious error came when building filebench which I haven't seen before but it clearly unrelated.

**Comment by behlendorf** [comment]
Merged as:

zfsonlinux/spl@0b43696 random_get_pseudo_bytes() need not provide cryptographic strength entrop

**Pull request closed without merging**
