### PR TITLE
iSCSI support for ZoL

### PR DESCRIPTION
**Pull request by FransUrbo**
Add support for the <code>shareiscsi</code> property.

It currently (as of Sept 2, 2014) supports four different iSCSI target implementations (in this order of discovery):
* IET             http://iscsitarget.sourceforge.net
* STGT    http://stgt.berlios.de
* SCST    http://scst.sourceforge.net
    Requires that SCST was compiled with /sys support (the default).
* LIO     http://linux-iscsi.org

It supports the following (official) options to the property:
* name (or iqn)
* lun
* type
* iomode - ignored for LIO
* blocksize - ignored for STGT
* initiator (or acl) - only for LIO, STGT and SCST
* authname
* authpass

### CODE REVIEW

**Comment by pavel-odintsov** [comment]
Any progress here, folks? It's really important feature because almost all customers of ZFS use it for building big SAN with iscsi.

**Comment by behlendorf** [comment]
@pavel-odintsov perhaps.  It would be very helpful if you could try the proposed patches.  If they meet your needs in their currently form we may be able to get them in.

**Comment by sempervictus** [comment]
@pavel-odintsov: we've run either the stack in this PR or a fork of @FransUrbo's branch on github in almost every ZoL build we've ever done. Its been working great, and i'm all for merging it in.
@behlendorf i'm all for merging this, its worked great so far

**Comment by behlendorf** [comment]
@FransUrbo cab you refresh these patches against master so we can get the updated buildbot results and get this merged.

**Comment by behlendorf** [comment]
I've squashed these two commits together and opened #3116 to get a fresh run by the buildbot on these changes.  My plan to in spend some time reviewing them and if they look safe and reasonable get them merged.

**Comment by FransUrbo** [comment]
@behlendorf I made them two commits, because I'm unsure of the second one - I wanted some input on it before acceptance.

**Comment by behlendorf** [comment]
We'll merge this right after the upcoming tag.

**Comment by FransUrbo** [comment]
@behlendorf So... You said that before 0.6.3 as well... Not good enough for 0.6.4 either?!

**Comment by pdf** [comment]
Wait, what hapened here? @FransUrbo why is this closed?  Now both issues are closed, and your branch is deleted?

**Comment by FransUrbo** [comment]
> Wait, what hapened here? @FransUrbo why is this closed? Now both issues are closed, and your branch is deleted?
> 

It's quite clear that this isn't going in… It's been waiting for two and a half years (granted, I've rewritten it twice since then, but still) and now it's been pushed to the next tag AGAIN. I simply don't have any interested in pursuing this any more. 

Brian wants ZED to do this, so anyone that want/need iSCSI support in ZoL will just have to wait for it to be done 'correctly' (in zed).

**Comment by behlendorf** [comment]
@FransUrbo Yes, I did and I'm sorry about that.  But the absolute last thing I want to do is accidentally break something subtle before a tag.  A tag which is already overdue.  I should have gotten this pushed over the finish line and merged right after 0.6.3 as planned then it would have had sufficient time to soak in master.  But I didn't.

My concern is that this patch touches a considerable bit of `zfs_main.c` and I'm not 100% comfortable that it doesn't introduce a regression.  If we could get a someone _other than myself_ to step up review the code and sign off on this patch I'm open to merging it.  I know many people have reported success with this patch but I think it needs another set of eyes on it.  I should said that more clearly earlier.

It's true I would like to explore the idea of having the ZED take care of this but I'm not hell bent on that solution.

**Comment by therealprologic** [comment]
@FransUrbo @behlendorf Can we get some momentum on this and get this patch going again and properly reviewed as suggested in the comments? I think I'm not the only one that wants native iSCSI support in ZOL :)

**Comment by sempervictus** [comment]
@behlendorf: IMHO, ZED is going to be its own can of sandworms, and pushing something which has had *this* much testing among the community into a shallow grave because it doesnt meet the aspirations of how everything in ZFS *should* work is a mistake. First off, persistent iSCSI settings in ZFS allow for fast failover to snapshot recipient hosts. Secondly, given how much work @FransUrbo has put into this, it would probably not help in the overall effort of attracting more developers to the project if viable code is canned like this.

Can we open this back up and at least leave it for people to use from github? Better yet, push out 0.6.4 and make this the first commit in 0.6.5's roadmap.

**Comment by therealprologic** [comment]
he here!

**Comment by behlendorf** [comment]
> Can we open this back up and at least leave it for people to use from github? Better yet, push out 0.6.4 and make this the first commit in 0.6.5's roadmap.

@sempervictus I'd like nothing better, it wasn't my intention to kill this off and I definitely should have handled this better.  When I [commented](https://github.com/zfsonlinux/zfs/pull/1099#issuecomment-75830250) that I wasn't comfortable merging this before the 0.6.4 tag I didn't expect it to be closed.  I just hoped to delay the merge until right after the tag.  But since I did this exact same thing before the 0.6.3 tag and then _didn't_ merge it I can understand why @FransUrbo is justifiably upset.  I should have been clearer about my reservations.

I still feel this patch is too risky to merge before the 0.6.4 tag since it does make some non-trivial changes to common code in the utilities.  However, I think we can definitely merge it right after the tag.  That will give us a few months to shake it out in master and discover if I'm just being overly cautious (hopefully I am).

For those who need this patch it's still available in #3116.  I opened this pull request a few days ago to run it through a fresh round of testing and so I could start carefully looking over the code.  Again, if we could get another set of eyes on this I'd feel much better about it.  I'm not an iSCSI expert, and once it's in the tree I feel obligated to support it.  Hopefully with @FransUrbo's help!

As for doing this in the ZED I agree that is absolutely going to be a ton of work.  We still need to build some needed infrastructure even to make it possible.  And then to get it working and tested will take a considerable amount of effort.  That's not something which is going to happen soon.

**Comment by maci0** [comment]
+1

**Comment by GregorKopka** [comment]
@behlendorf now that 0.6.4 is out: maybe reopen this one so it will not get lost?

**Comment by kpande** [comment]
I don't know if this is a great idea - shouldn't it be outside the scope of ZFS to configure your iSCSI targets? Why are they supposed to be so closely linked? There's no 'sharedrdb' or 'shareaoe'.. is ZFS supposed to control every aspect of file services, like systemd? :-)

**Comment by pdf** [comment]
@kpande sharenfs/sharesmb/shareiscsi are standard features on other ZFS implementations.  Also, you might consider toning down the hyperbole a little.

**Comment by kpande** [comment]
@pdf In FreeBSD, shareiscsi is not used and illumos has just one iSCSI target.

**Comment by pdf** [comment]
@kpande fine, FreeBSD doesn't support it, but that's probably only because they didn't have a target until the 10.0 release, clearly it's not considered out of scope though.  To answer some of your other questions, go look at the PR.  Bringing systemd into the conversation is straight-up flame-bait.  Should we also drop sharenfs and sharesmb because you don't want ZFS to 'control every aspect of file services'?  ZFS has been accused of layering violations before, but IMO those 'violations' are some of the reasons it's nice to administer.

**Comment by kpande** [comment]
well, since you're bringing up sharenfs and sharesmb:

sharenfs is currently taking solaris configuration and translating it into linux NFS configuration. since ZFS is meant to be cross-platform and all, and you've gotta have your properties work on both systems, this is how it must be. if I had a choice, I'd remove 'sharenfs' from ZFS too.

sharesmb is currently using the 'net' system binary to contact the samba daemon. That's a hack, it should be using samba libraries and APIs. if I had my choice, sharesmb would be removed too.

Since ZFS is becoming OpenZFS which is cross-platform, maybe it's time to shed some past artifacts from Solaris.

**Comment by pdf** [comment]
@kpande you're entitled to your opinion, however there are real advantages to having shares defined on the filesystem, like being able to `zfs send|zfs receive` and have your shares configured on the receiver automatically.

**Comment by behlendorf** [comment]
> I had my choice, sharesmb would be removed too.

@kpande @pdf this is a bit of a digression but this isn't too far from where I've suggested things should go.  The `sharenfs` and `sharesmb` properties won't be removed but they will be less tightly coupled to ZFS.  Specifically, the existing C implementation would be removed and replaced by ZED scripts which are triggered by ZFS events are responsible for performing the sharing.  The thought is that this would be far more portable, flexible, and maintainable.  It's something @dun and I have talked about and are laying the groundwork for.

**Comment by pdf** [comment]
@behlendorf this sounds like a good long-term plan.  Do you have a link to the discussion/design notes?

**Comment by kpande** [comment]
@behlendorf that's how it should be - I believe, even on other platforms, because it would allow FreeBSD or illumos to "support" third-party iscsi targets like iet or tgt without patching the OS.. just by bringing your own custom zedlets.

**Comment by behlendorf** [comment]
@pdf I'm sure I've had this discussion before in the tracker but at the moment I can't seem to find it.  @dun and I have fleshed out a nice design for this but we haven't posted it anywhere, we should so it can be commented on.  But the gist of it is we need to extend the existing event infrastructure to minimally allow:

1) User space utilities can inject events such as mount/unmount, share/unshare, etc.
2) Optionally block on those events and received a return status code.

**Comment by chjohnst** [comment]
+1 for an awesomeness

**Comment by prometheanfire** [comment]
@behlendorf is this shelved due to the branch being closed, the preference of using ZED or some other reason?

**Comment by FransUrbo** [comment]
Anyone who's still interested in this, give a thumbs up on the top/initial comment so we can judge how many's interested.

**Comment by sempervictus** [comment]
Seeing this via email, so can't thumbs up far as I know, but I am very
interested. BTW, LIO is the defacto Linux iscsi impl (god knows why when
scst has been around forever), so this work does make sense in master.
While most use cases we have now are automated procedures - create zvol,
configure lio, inform the broker of both, it would be quite useful to have
this for one-off systems, or for telling Cinder-volume to create+export in
one op.

On Jul 15, 2016 08:13, "Turbo Fredriksson" <notifications@github.com> wrote:

Anyone who's still interested in this, give a thumbs up on the top/initial
comment so we can judge how many's interested.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zfsonlinux/zfs/pull/1099#issuecomment-232936236>, or mute
the thread

**Comment by FransUrbo** [comment]
@sempervictus This works with LIO as well. It haven't had as much testing as SCST (which I've used in production together with this patch for 3+ years).

If you're interested in Cinder, you might want to have a look at "my" Openstack-ZFS driver: https://github.com/FransUrbo/Openstack-ZFS

**Comment by sempervictus** [comment]
We generally use scst too, but turns out it doesn't work in lxc whereas lio
does.
Will look over that code, any reason its not in openstack? You seem a much
better candidate for writing something like this than some infosec nerd.

**Comment by FransUrbo** [comment]
On Jul 20, 2016, at 6:33 AM, RageLtMan wrote:

> Will look over that code, any reason its not in openstack? You seem a much
> better candidate for writing something like this than some infosec nerd.

Thanx :). But I'm taking to many short cuts (chief among them is to use "shareiscsi", which isn't officially available yet). I can't justify getting this in Cinder proper with that 'limitation'.

But I'm not discounting the possibility for the future. I just want much more eyes on it before I even consider it - "with enough eyeballs, all bugs are shallow" I think HE said.. :)

**Comment by bjquinn** [comment]
On my phone, so not seeing the thumbs up either, but add me to the count.  Would love to see this integrated.

**Comment by dhojnik** [comment]
Hi there

I would like to try @FransUrbo his OpenStack-Cinder-ZFS-Mothership-Godlike-Driver :) ... using on Ubuntu 16.04 with Root ( / ) on ZFS. Do I have to apply this patch and recompile zfsonlinux on Ubuntu? Or it is now inside master?

root@sackgesicht:~# apt-cache show zfsutils-linux
Package: zfsutils-linux
Priority: extra
Section: admin
Installed-Size: 779
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Darik Horn <dajhorn@vanadac.com>
Architecture: amd64
Source: zfs-linux
Version: 0.6.5.6-0ubuntu15
Replaces: zfs
Provides: zfs
Depends: init-system-helpers (>= 1.18~), zfs-doc (= 0.6.5.6-0ubuntu15), libblkid1 (>= 2.16), libc6 (>= 2.14), libnvpair1linux, libuuid1 (>= 2.16), libuutil1linux, libzfs2linux, libzpool2linux, python3:any (>= 3.3.2-2~), python3
Recommends: zfs-dkms, zfs-zed
Suggests: samba-common-bin (>= 3.0.23), nfs-kernel-server, zfs-initramfs
Conflicts: zfs, zfs-fuse
Filename: pool/main/z/zfs-linux/zfsutils-linux_0.6.5.6-0ubuntu15_amd64.deb
Size: 275568
MD5sum: 0d10700f55ce11d21f068eb0e607d258
SHA1: e1b254eae05011cd05c9d6d145e45f175a2bf518
SHA256: 79b15f9f839691280626edd0419937885e9008f3b0aba06b80c91d1f3dc9b05f
Description-en: Native OpenZFS management utilities for Linux
 This package provides the zpool and zfs commands that are used to
 manage OpenZFS filesystems.
Description-md5: 7b0f98269f6c33505790717cd478736c
Homepage: https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.6
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Phased-Update-Percentage: 0
Supported: 5y

**Comment by kpande** [comment]
this is not the place for such support requests, please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) instead.

**Comment by mailinglists35** [comment]
does this PR apply to master or 0.7.x?

**Pull request closed without merging**
