### PR TITLE
Illumos 2605 want to resume interrupted zfs send [rebase February 29th]

### PR DESCRIPTION
**Pull request by kernelOfTruth**
Reviewed by: George Wilson <george.wilson@delphix.com>
Reviewed by: Paul Dagnelie <pcd@delphix.com>
Reviewed by: Richard Elling <Richard.Elling@RichardElling.com>
Reviewed by: Xin Li <delphij@freebsd.org>
Reviewed by: Arne Jansen <sensille@gmx.net>
Approved by: Dan McDonald <danmcd@omniti.com>

References:
https://www.illumos.org/issues/2605
https://github.com/illumos/illumos-gate/commit/9c3fd1216fa7fb02cfbc78a2518a686d54b48ab8

Porting notes:

The tests from Illumos in usr/src/test/zfs-tests were left out
Further the following files which don't exist in ZoL:
usr/src/cmd/truss/expound.c
usr/src/lib/libzfs/common/mapfile-vers
usr/src/lib/libzfs_core/common/mapfile-vers
usr/src/pkg/manifests/system-test-zfstest.mf

From a readability point of view the changes in [module/zfs/dmu_traverse.c]
from https://github.com/zfsonlinux/zfs/commit/ecfb0b5f42c3662e36d5cd444c0aa2ebc8501589 Fix misuse of input argument in traverse_visitbp
appear to be the optimum - also there's no functional change,
when going with upstream the compiler would likely complain about ISO C90 errors - so only switching
cdnp = buf->b_data;
to
child_dnp = buf->b_data;

diverged code base from Illumos:

[cmd/zstreamdump/zstreamdump.c]
https://github.com/zfsonlinux/zfs/commit/37f8a8835a88da6122e2526d6aaeeef75556a7bd Illumos 5746 - more checksumming in zfs send

[include/sys/zfs_ioctl.h]
https://github.com/zfsonlinux/zfs/commit/0cee24064a79f9c01fc4521543c37acea538405f Speed up 'zfs list -t snapshot -o name -s name'

[module/zfs/zfs_ioctl.c]
https://github.com/zfsonlinux/zfs/commit/13fe019870c8779bf2f5b3ff731b512cf89133ef Illumos 3464 zfs synctask code needs restructuring

[module/zfs/dmu_send.c]
https://github.com/zfsonlinux/zfs/commit/b58986eebf3c47c946393da4b968ee33edaea99e Use large stacks when available
https://github.com/zfsonlinux/zfs/commit/044baf009aac4935eca0f96477eb3c43e95d758a Use taskq for dump_bytes()
ISO C90 - mixed declarations and code: 	struct send_block_record *to_data;
					struct receive_ign_obj_node *n;
account for 'missing braces around initializer' in 'struct send_thread_arg to_arg ='
ISO C90 - mixed declarations and code: 	void *payload = NULL;
					nvlist_t *nvl = fnvlist_alloc();
					uint64_t one = 1; uint64_t zero = 1;
					char recvname[ZFS_MAXNAMELEN];
					uint64_t val;
					uint32_t payloadlen = drc->drc_drr_begin->drr_payloadlen;
					size_t payload_len = 0;

[module/zfs/dsl_dataset.c]
Illumos 4185 add new cryptographic checksums to ZFS: SHA-512, Skein, Edon-R
hasn't landed yet, thus
' #include <sys/zio_checksum.h>
is still missing,

' #include <sys/dmu_send.h>
however is needed

further
replaced
fletcher_4_native(compressed, compressed_size, NULL, &cksum);
with
fletcher_4_native(compressed, compressed_size, &cksum);

ctx_template argument was removed (purpose: the template will be reused to make initialization more efficient)

C99 or C11 mode: declare 'int i' at the beginning of the function.

ISO C90 - mixed declarations and code: 	char buf[256];
					zio_cksum_t cksum;
					char *propval = kmem_asprintf("%u-%llx-%llx-%s",
					char recvname[ZFS_MAXNAMELEN];
					dsl_dataset_t *recv_ds;

[libzfs_sendrecv.c]
' #include <sha2.h>
isn't listed in the header list since sha2, sha256 is implemented differently in ZoL.

replace
fletcher_4_native(compressed, len, NULL, &cksum);
with
fletcher_4_native(compressed, len, &cksum);

declare 'int nread, i;' at the beginning of the function

https://github.com/zfsonlinux/zfs/commit/b8864a233c569edcc57c686f3ea8cd1ae3b89153 Fix gcc cast warnings

[module/zcommon/zfs_prop.c]
https://github.com/zfsonlinux/zfs/commit/11b9ec23b98eefe1e7bde0033dc8285f94cb0b90 Add full SELinux support

[module/zfs/dmu_traverse.c]
https://github.com/zfsonlinux/zfs/commit/ecfb0b5f42c3662e36d5cd444c0aa2ebc8501589 Fix misuse of input argument in traverse_visitbp
https://github.com/zfsonlinux/zfs/commit/79c76d5b65b19a602d4c7a340da7bf90d4a0c4f8 Change KM_PUSHPAGE -> KM_SLEEP
https://github.com/zfsonlinux/zfs/commit/a16878805388c4d96cb8a294de965071d138a47b Reduce stack for traverse_visitbp() recursion
https://github.com/zfsonlinux/zfs/commit/b8d06fca089fae4680c3a552fc55c512bfb02202 Switch KM_SLEEP to KM_PUSHPAGE
https://github.com/zfsonlinux/zfs/commit/47050a88ac1445f3557030d0d7e61b8a397a5476 Fix stack traverse_impl()
ISO C90: place 'uint64_t obj, error;' at the beginning, further replace 'err' with 'error'

[man/man8/zfs.8]
Part of the sections for 'zfs receive' and 'zfs send' was rewritten and reordered to approximate upstream.

Ported-by: kernelOfTruth kerneloftruth@gmail.com

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
referencing: https://github.com/zfsonlinux/zfs/issues/3896

**Comment by kernelOfTruth** [comment]
Appears like the (TEST) buildbot runs don't like the stress ?

in the last pull-request several of them also passed out - hm ...

**Comment by behlendorf** [comment]
@kernelOfTruth thanks for working on this.  It appears zfstress is triggering a NULL dereference with this patch.  You can see the backtrace in the [Amazon TEST console log](http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20%28TEST%29/builds/773/steps/shell_12/logs/console).  This patch is definitely on my list is things to review.

**Comment by ptx0** [comment]
@kernelOfTruth any luck with the bug?

**Comment by behlendorf** [comment]
Replaced by #4742.

**Comment by behlendorf** [comment]
@kernelOfTruth @ptx0 the testing failure was caused by a buffer overrun in the original OpenZFS patch.  Ironically after I identified the issue I discovered that a fix was applied to OpenZFS last week.  I've added the upstream fix to the #4742 patch stack.

**Comment by kernelOfTruth** [comment]
@behlendorf sorry for the long absence from the project, live's currently demanding that I focus solely on totally different things

I'm glad that this issue could be sorted out

Exciting changes are ahead (encryption, more hashes, avx acceleration, etc.) :+1:

**Pull request closed without merging**
