### PR TITLE
Linux 4.0 compat: bdi_setup_and_register()

### PR DESCRIPTION
**Pull request by behlendorf**
The 'capabilities' argument which was passed to bdi_setup_and_register()
has been removed.  File systems should no longer pass BDI_CAP_MAP_COPY.
For our purposes this means there are now three different interfaces
which must be handled.  A zpl_bdi_setup_and_register() wrapper function
has been introduced to provide a single interface to the ZPL code.

* 2.6.32 - 2.6.33, bdi_setup_and_register() is not exported.
* 2.6.34 - 3.19, bdi_setup_and_register() takes 3 arguments.
* 4.0 - x.y, bdi_setup_and_register() takes 2 arguments.

I've also taken this opportunity to remove HAVE_BDI because kernels
older then 2.6.32 are no longer supported.  All kernels newer than
this will have one of the above interfaces.

Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>
Issue #3128

### CODE REVIEW

**Comment by tuxoko** [comment]
This looks good to me.

**Comment by behlendorf** [comment]
@tuxoko Thanks for the review it's appreciated!  I've just refreshed this to address the minor style issues flagged by the buildbot.  No other changes.

**Comment by behlendorf** [comment]
Merged as:

8c45def Linux 4.0 compat: bdi_setup_and_register()

**Comment by bill-mcgonigle** [comment]
I wasn't making it past configure with g4c7b7ee.  I got:

    /root/src/zfs/zfs/build/conftest.c:106:3: error: ignoring return value of ‘bdi_setup_and_register’, declared with attribute warn_unused_result [-Werror=unused-result]
       (void) bdi_setup_and_register(&bdi, name);
       ^
    cc1: all warnings being treated as errors

apparently because `bdi_setup_and_register` is `__must_check` (4.0.0-rc3 from Fedora koji, built locally) and `ZFS_LINUX_COMPILE_IFELSE` adds `-Werror`. 

I modifed the test to:

    -               (void) bdi_setup_and_register(&bdi, name);
    +               int ignore_error = bdi_setup_and_register(&bdi, name);
    +               (void)ignore_error;

and that seems to work.  The first line to deal with unchecked returns, the second for unused variables.  It's ugly for sure.

**Comment by behlendorf** [comment]
@bill-mcgonigle Thanks for catching this and proposed a fix.  The way we've handled this in the other autoconf tests is by setting -Wno-unused-but-set-variable to disable the warning.  I've open up #3179 with a proposed fix it would be great if you could verify it solves the issue.

**Pull request closed without merging**
