### PR TITLE
zfs-0.7.6 patchset

### PR DESCRIPTION
**Pull request by tonyhutter**
### Description
Test 0.7.6 patchset in buildbot

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

### CODE REVIEW

**Comment by loli10K** [comment]
I've been working on some nits (plus one functional fix) that could be included in this release: unfortunately i've been doing night shifts lately so i don't have much time to work on those changes, but i can hopefully push something this weekend.

Can we wait a couple of days to release 0.7.6? Thanks

**Comment by tonyhutter** [comment]
@loli10K not a problem.  Just put the PRs in https://github.com/zfsonlinux/zfs/projects/15 when you're done and I'll cherry-pick them.

**Comment by loli10K** [comment]
Apologies for the delay, the PR i would like to get included is https://github.com/zfsonlinux/zfs/pull/7088; it's needed to be able to manage some specific backup scenarios via zfs send/recv.

Again, i'm sorry and thanks.

**Comment by kpande** [comment]
I'd rather not put something that hasn't had any testing into a stable release, let's not delay it any further.

**Comment by tonyhutter** [comment]
@kpande  yea I agree that it's always best to get soak time on patches first.  However, it's not uncommon for us to pull in a last-minute patch if it seems low-risk.  In this particular case, I was also ok with delaying the release a little, since I knew I needed extra time to troubleshoot a packaging issue I was seeing on my 0.7.6 test builds.

**Comment by tonyhutter** [comment]
Apparently buildbot (or github) can't test more than 30 commits.  I've squashed them in #7109 for testing.

**Comment by tonyhutter** [comment]
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.6

**Comment by chrisrd** [comment]
@tonyhutter The last line of the https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.4 release notes is:
```
Linux 4.15 compat: timer updates #670 #671
```
I don't know if it's too late to change, but these should specify they're SPL issues, and hopefully link across there...

There was a question on zfs-discuss about this:

http://list.zfsonlinux.org/pipermail/zfs-discuss/2018-February/030483.html

**Comment by tonyhutter** [comment]
@chrisrd thanks for the info. I updated the 0.7.6 page and will break out ZFS/SPL changes going forward.

**Pull request closed without merging**
