### PR TITLE
Illumos 5960 zfs recv should prefetch indirect blocks, Illumos 5925 zfs receive -o origin=

### PR DESCRIPTION
**Pull request by kernelOfTruth**
Illumos 5960 zfs recv should prefetch indirect blocks
Illumos 5925 zfs receive -o origin=

Reviewed by: Prakash Surya <prakash.surya@delphix.com>
Reviewed by: Matthew Ahrens <mahrens@delphix.com>

depends on #3574 Illumos 5745 zfs set allows only one dataset property to be set at a time
depends on #3611 Illumos 5746 more checksumming in zfs send

diverged code base from Illumos:

[lib/libzfs/libzfs_sendrecv.c]
b8864a2 Fix gcc cast warnings
325f023 Add linux kernel device support
5c3f61e Increase Linux pipe buffer size on 'zfs receive'

[module/zfs/zfs_vnops.c]
3558fd7 Prototype/structure update for Linux
c12e3a5 Restructure zfs_readdir() to fix regressions

[module/zfs/zvol.c]
function
@zvol_map_block(spa_t *spa, zilog_t *zilog, const blkptr_t *bp,
is non-existent in ZoL

[module/zfs/dmu.c]
in function
dmu_prefetch(objset_t *os, uint64_t object, uint64_t offset, uint64_t len)
int i
is initialized before the following code block (c90 vs. c99)

[module/zfs/Makefile.in + lib/libzpool/Makefile.am]
47a4a6f Support parallel build trees (VPATH builds)

[module/zfs/dbuf.c]
fc5bb51 Fix stack dbuf_hold_impl()
9b67f60 Illumos 4757, 4913
{4757 ZFS embedded-data block pointers ("zero block compression") ,
 4913 zfs release should not be subject to space checks}
{reference} 34229a2 Reduce stack usage for recursive traverse_visitbp()

[module/zfs/dmu_send.c]
b58986e Use large stacks when available
241b541 Illumos 5959 - clean up per-dataset feature count code
{reference} 77aef6f Use vmem_alloc() for nvlists
00b4602 Add linux kernel memory support

[module/zfs/zvol.c]
9965059 Prefetch start and end of volumes

[module/zfs/dmu_send.c, C90 warnings - previous commits, code thus less clear to read]
Illumos 5746 more checksumming in zfs send

[module/zfs/dbuf.c, ISO C90 - mixed declarations and code]
arc_flags_t aflags =
uint64_t nextblkid = dpa->dpa_zb.zb_blkid >>
dmu_buf_impl_t *db = dbuf_find(dn->dn_objset, dn->dn_object,
zio_t *pio = zio_root(dmu_objset_spa(dn->dn_objset), NULL, NULL,
blkptr_t *bp = ((blkptr_t *)abuf->b_data) +
dbuf_prefetch_arg_t *dpa = kmem_zalloc(sizeof (*dpa), KM_SLEEP);
dsl_dataset_t *ds = dn->dn_objset->os_dsl_dataset;

[module/zfs/dmu_send.c, ISO C90 - mixed declarations and code]
dnode_phys_t *blk = abuf->b_data;
uint64_t dnobj = zb->zb_blkid * (blksz >> DNODE_SHIFT);
error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode: for (struct receive_ign_obj_node *n =
struct send_block_record *to_data;
struct receive_ign_obj_node *n;
struct receive_ign_obj_node *last_object;
uint64_t last_objnum = (last_object != NULL ?

FIXME: man/man8/zfs.8
FIXME: different manpage format, currently I don't "get it" yet

Ported-by: kernelOfTruth kerneloftruth@gmail.com

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
I need some help with

```
dh->dh_fail_sparse = fail_sparse;
```

not sure how to properly change this in accordance with the fact that in dbuf_hold_impl
fail_sparse was changed from 
```int``` type to 
```boolean_t```


And with the man page entries - they currently don't make any sense to me - I've stared at them for some time but still couldn't give any meaning  to the way they are written

I remember in the past having seen man pages between illumos and ZoL were the changes (and matching parts) were obvious - but this time unfortunately it's not :(

**Comment by kernelOfTruth** [comment]
Sorry, these changes depend on

https://github.com/zfsonlinux/zfs/pull/3574 Illumos 5745 zfs set allows only one dataset property to be set at a time
https://github.com/zfsonlinux/zfs/pull/3611 Illumos 5746 more checksumming in zfs send

so unless those are in master, this is the easiest way to get the code in a proper shape.

ZFS master state is from December 9th for now

It would be nice if the buildbots actually tested this - but I'm keeping an reserved attitude this time,

not yet compile-tested - will do that another time, it's rather late already here (local time)

**Comment by kernelOfTruth** [comment]
Still fails during compilation - but at least most of the errors are _*really*_ meaningful now

**Comment by kernelOfTruth** [comment]
http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20x86_64%20%28TEST%29/builds/261/steps/shell_2/logs/make

This error doesn't make any sense !

```
/tmp/zfs-build-buildbot-mQEbFDAO/BUILD/zfs-kmod-0.6.5/_kmod_build_3.13.0-48-generic/../zfs-0.6.5/include/sys/dmu.h:48:30: fatal error: sys/zio_priority.h: No such file or directory
 #include <sys/zio_priority.h>
                              ^
compilation terminated.
make[7]: *** [/tmp/zfs-build-buildbot-mQEbFDAO/BUILD/zfs-kmod-0.6.5/_kmod_build_3.13.0-48-generic/module/zcommon/zfs_deleg.o] Error 1
make[6]: *** [/tmp/zfs-build-buildbot-mQEbFDAO/BUILD/zfs-kmod-0.6.5/_kmod_build_3.13.0-48-generic/module/zcommon] Error 2
make[6]: *** Waiting for unfinished jobs....
  CC [M]  /tmp/zfs-build-buildbot-mQEbFDAO/BUILD/zfs-kmod-0.6.5/_kmod_build_3.13.0-48-generic/module/zfs/blkptr.o
In file included from /tmp/zfs-build-buildbot-mQEbFDAO/BUILD/zfs-kmod-0.6.5/_kmod_build_3.13.0-48-generic/../zfs-0.6.5/module/zfs/blkptr.c:21:0:
/tmp/zfs-build-buildbot-mQEbFDAO/BUILD/zfs-kmod-0.6.5/_kmod_build_3.13.0-48-generic/../zfs-0.6.5/include/sys/zio.h:32:30: fatal error: sys/zio_priority.h: No such file or directory
 #include <sys/zio_priority.h>
```

the file is there :question:

**Comment by kernelOfTruth** [comment]
Still needs the integration of the man pages ... :information_source:

**Comment by kernelOfTruth** [comment]
Note to self:

:balloon:  man pages

:balloon: @zvol_map_block(spa_t *spa, zilog_t *zilog, const blkptr_t *bp,
in module/zfs/zvol.c is missing - what does it provide in Illumos ?

:balloon: module/zfs/zvol.c check whether the parameters *_really_* were added correctly


@behlendorf Could you please particularly take a look at the modifications in module/zfs/zvol.c whether the changes to dmu_prefetch were correct ?

**Comment by behlendorf** [comment]
@kernelOfTruth the `zvol.c` change looks reasonable but I'll take a much closer look when I fully review this whole change for merging.

**Comment by kernelOfTruth** [comment]
@behlendorf okay, great,

thanks ! :)


Could someone please post sample output with 

```zfs receive -o origin=```

currently the following two lines don't clearly reveal their difference by staring at the man page :(


```
 .Nm
 .Cm receive
 .Op Fl Fnuv
+.Op Fl o Sy origin Ns = Ns Ar snapshot
 .Ar filesystem Ns | Ns Ar volume Ns | Ns Ar snapshot
 .Nm
 .Cm receive
 .Op Fl Fnuv
 .Op Fl d Ns | Ns Fl e
+.Op Fl o Sy origin Ns = Ns Ar snapshot
 .Ar filesystem
 .Nm
```


anyway - will take a look at it a different time

**Comment by behlendorf** [comment]
@kernelOfTruth since the dependencies have been merged could you rebase this and master and force update the branch.

**Comment by kernelOfTruth** [comment]
@behlendorf I've opened a new pull-request and updated the wiki

superseded by:

https://github.com/zfsonlinux/zfs/pull/4179

**Pull request closed without merging**
