### PR TITLE
implementing json in zfs list cli command

### PR DESCRIPTION
**Pull request by goulvenriou**
Hi, Alyseo's team has implemented a new version of zfs list during the european open zfs hackaton at Ecole 42.
Here is the second version .
Comments are welcome.

### CODE REVIEW

**Comment by goulvenriou** [comment]
I'm trying to reproduce the buildbot issue on ubuntu 12.10, but no success so far ! Any info or help on this one will be appreciated. In addition this distro is not supported since May 2014 : is it really of interest to keep it within builedbot process and pull request validation ?

**Comment by yada** [comment]
Guess git clone issue on spl for centos7.0 and ubuntu14.04 are internal errors : correct ?

**Comment by behlendorf** [comment]
@yada yes, cloning is definitely an internal error.  Perhaps a timeout to github due to a networking issue some some such.  There are also still a handful of known issues in the buildbot hits which need to be run down, check the issues tagged [Test Suite](https://github.com/zfsonlinux/zfs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Test+Suite%22) to see if it's already known.  This way you can tell if it's something introduced by the patch stack.

As for keeping 12.10 around it is officially no longer supported but unless it's causing issues we tend to keep them around for the additional test coverage.  Specifically to ensure we're testing on a wider range of kernels.

In this case the ztest failure was caused by #2302 which is a known issue in both ZoL and illumos.  It would be great to fix because we hit it fairly often due to the volume of automated testing which is run.

**Comment by yada** [comment]
Any idea on this one :
http://buildbot.zfsonlinux.org/builders/ubuntu-14.04-amd64-current-builder/builds/2963/steps/shell_4/logs/stdio

Cause it does not seems to be related to our code ?

**Comment by behlendorf** [comment]
@yada see #3421, it's a build failure with an outstanding patch under review due to a change in the 4.1 kernel.  Don't sweat that one.

**Comment by yada** [comment]
@behlendorf : Ready to merge ? Need some love on this one so the team can create next pull requests next week ;-)

**Comment by behlendorf** [comment]
@yada sorry I haven't had a chance to look this over.  But I'll try and get you some feedback so you can add the missing functionality.  Ideally, I think it would be nice to merge this all in one patch stack.

**Comment by yada** [comment]
@behlendorf No worries, we know what it is ;-) Any feedback on this one could help to confirm we are on the right track. Agree and fine with us for a global merge, it just gonna be pretty huge... Will be great to have feedback or pull requests validation to avoid a big check at the end (just my 2 cents).

PS : Do you think it can be included in 0.6.5 ?

**Comment by behlendorf** [comment]
@yada if we can finalize it in the next month or so I suspect we can get this in the next tag.  To help make that happened I'm taken a note to find some time to get you a round of review comments.

**Comment by yada** [comment]
@behlendorf Perfect, thank you Brian

**Comment by behlendorf** [comment]
@yada sorry about the delay,  I have just started to review this but let me provide you some high feedback here and ask a few questions first.  I'll make some more detailed technical comments inline with the patches.  Bare with me JSON is still new to me.

First off I think it's great how you've gone through and used Orderly to layout the JSON schema for all the commands.  I presume Orderly doesn't have a problem consuming the Github markdown files since the schemav1.0 directory looks like it contains the results.

For those us, like me, who aren't already highly familiar with JSON I think it would be valuable to have a README.md file in the json/ directory which describes what everything is.  Explain what are the orderly files?  How do I use them to create the schema?  Perhaps this should be automated as part of configure?  How can I use the schema to validate the output of the commands?  How do we extend the Orderly files when making changes to the commands?  All the basic stuff developers need to know.  I see you've put some information in the top level README.md but I think it's more appropriate to have this under the json/ directory.

As for the existing STATUS.md I think it's fine to keep that in the pull request while this is still being worked on but once everything is implemented we'll want to drop it.  Also is that status right?  It indicates that you've got code for most the commands but I don't see that in this pull request.  Just code for `zfs rename` and `zfs list`.

You'll want to add Makefile.am's to the json directory so that all these files get properly included in the `make dist` tarball.  We'll also want to sort if any of this documentation should be packaged for end users.  But that's a minor issue for when everything else is done.

Regarding the code it would be great if you could refresh the pull request with the latest version with everything squashed together.  It makes it much easier to use the inline code comments.  But let me comment on what I see in this current pull request and make some suggestions.

I don't think it's desirable to add `zfs_json_*` specific functions which are very close identical to their non-json counterparts.  Instead I think it would be best to extend the existing `libzfs_handle_t` with a ` zfs_json_t *` member.  When non-NULL you can add the "error" to the `json->nv_dict_error`.  This should allow you to use the existing error function with minimal modification.

Embedding the json in the handle like this should also allow you to pass it around easily without having to add an argument to all of the functions.  This is in part why a handle is created.  You might also find that you need to pass the json handle around through a callback in the cases where there isn't a handle.  Did you exploring doing this and run in to other issues?

One last minor nit I see a lot of stray trailing whitespace in the patch.  We'll want to clean that up.  I personally find  that the colorized diffs from `git log` do a nice job highlighting.

Anyway, I'm happy to make another round of comments if you can refresh this with the latest code.

**Comment by yada** [comment]
@behlendorf : We will add a README.md in json directory with more informations on the different types of format... agree.

Orderly has been added based on a comment from Richard Elling :
https://www.mail-archive.com/developer@open-zfs.org/msg00922.html

Online tool is here : 
http://orderly-json.org/tryit

It is a nice and easy way to present json schema and convert real json command outputs. Consider the json schemas as json specs, it is done manually and fix for each commands. When making changes to a command, json schemas must be updated accordingly if necessary.

Regarding STATUS.md, you are right : it is what we have in lab and do not reflect what has been released on github. Will be updated in our next pull request.

Json directory and doc, not sure if it necessary to add json schemas in documentation or tarball ? But agree on the fact we need to agree on this important point.

In next pull request (next week normally), you should have around 25 commands so you gonna have a better idea of what has been done and how. We must do it by pool so our code can be as generic as possible (avoid copy/paste... between commands).

Regarding our zfs_json_* specific functions, this is the cleanest way we founded to do generic codes between commands, we tried what you have suggested but lot's of issues with commands which use recursive loops (like : zfs list, zpool list, zfs get...). I suggest you wait for our next pull request with much more commands on this specific topic.

Regarding : 
"One last minor nit I see a lot of stray trailing whitespace in the patch. We'll want to clean that up. I personally find that the colorized diffs from git log do a nice job highlighting."

I think it has been done to avoid cstyle.pl warning, will check with the dev team here. Unless I did not understand you point (give us some samples in this case please) ?

Thanks

**Comment by behlendorf** [comment]
> It is a nice and easy way to present json schema and convert real json command outputs...

I think using Orderly is a fine idea.  I just want to ensure that those of us who aren't already familiar with it can get a high level summary of why it's there, what it does, and how to use it.  Very much like what you just posted here.

> Json directory and doc

Definitely anything added to the git repository should be part of the tarball which is what gets officially distributed.  We don't want people downloading the tarballs to be missing anything important.  This could just be the Orderly files if you want to automatically generate the schema files during the build.  That might be handy, assuming it's easy, because it would make it clear that the Orderly files are the authoritative source to be updated and they're always be consist with the schema files.

> In next pull request 

Awesome, I look forward too it.

> give us some samples in this case please

You can use `git diff --check` to automatically identify all the locations where there's white space errors.  For example when a line ends with a space or tab.  Here are the first few warnings I see when running it against the patch in this pull request

```
$ git diff --check
README.markdown:28: trailing whitespace.
+First install the dependencies 
README.markdown:36: trailing whitespace.
+Next install the spl  (on the master branch) : 
README.markdown:78: trailing whitespace.
+    "stderr": "", 
README.markdown:81: trailing whitespace.
+            "available": "1030422528", 
README.markdown:82: trailing whitespace.
+            "mountpoint": "/tank", 
...
```

**Comment by yada** [comment]
@behlendorf : Will be great if you guys can review our latest pull request which including all zfs commands (zfs diff is missing today) and team will work on zpool commands asap.

Like said in the commit message : this is pretty big refactoring in order simplify next updates and follow-up...

I know it is a pretty huge amount of code, but the sooner it is review and agreed the better it gonna be : pretty painful as you can imagine to modify our code on each commit till this is not integrated ;-)

PS: We finally saw the "trailing whitespace" issues during our rebase ;-) So should be all good now.

**Comment by behlendorf** [comment]
@yada I'll try to get to it but I'm pretty swamped at the moment.  In the meanwhile it would be great if you could rebase the entire branch on master the next time you refresh it and cleanup the patch stack.  That makes review so much easier.

**Comment by goulvenriou** [comment]
@behlendorf : I've rebase the branch on master , i hope your code review will be favorable , i continue to implement json in the other zpool command , some change are coming soon !

**Comment by goulvenriou** [comment]
Hi, in response to this pull request Alyseo's team has refactored the code to deliver single commit including all the jsonify code, the json output has been implements in all CLI commands.
the new pull request is available here: https://github.com/zfsonlinux/zfs/pull/3938
Regards.
Goulven

**Comment by behlendorf** [comment]
Closing is favour of #3938.

**Pull request closed without merging**
