### PR TITLE
Reduce stack usage of dmu_recv_stream function

### PR DESCRIPTION
**Pull request by lorddoskias**
Apparently the receive_writer_arg and receive_arg structures become
large when ZFS is compiled with debugging enabled. This results in
gcc throwing an error about excessive stack usage:

module/zfs/dmu_send.c: In function ‘dmu_recv_stream’:
module/zfs/dmu_send.c:2502:1: error: the frame size of 1256 bytes is
larger than 1024 bytes [-Werror=frame-larger-than=]

Fix this by allocating those functions on the heap, rather than
on the stack.

Signed-off-by: Nikolay Borisov <n.borisov.lkml@gmail.com>

### CODE REVIEW

**Comment by lorddoskias** [comment]
There is a typo (extra & when passing rwa to the receive writer thread so the receive tests hang indefinitely) can you please kill current run and use my latest pull request?

**Comment by behlendorf** [comment]
@lorddoskias I'll make sure to rerun any test failures with your latest version.

**Comment by lorddoskias** [comment]
@behlendorf Did the host timeout on this one? Also the crash in the ztest isn't very verbose

**Comment by behlendorf** [comment]
@lorddoskias it's not clear to me what happened either.  As for ztest the zloop script is supposed to dump backtraces but I haven't found it to be entirely reliably for reasons which I haven't carefully investigated yet.  We do have a few outstanding ztest issues which might have caused this so I'm rerunning that build.

**Comment by behlendorf** [comment]
@lorddoskias the patch LGTM but I was little surprised these two structures were that large so I dumped them.  It looks like receive_writer_arg grew considerably when the bqueue_t support was recently added which pushed us over the edge.  We should definitely move these to the heap as you've done but interestingly they only account for about half the stack frame size.

```
crash> struct -o receive_writer_arg
struct receive_writer_arg {
    [0] objset_t *os;
    [8] boolean_t byteswap;
   [16] bqueue_t q;
  [264] kmutex_t mutex;
  [312] kcondvar_t cv;
  [384] boolean_t done;
  [388] int err;
  [392] avl_tree_t *guid_to_ds_map;
}
SIZE: 400
crash> struct -o receive_arg
struct receive_arg {
    [0] objset_t *os;
    [8] vnode_t *vp;
   [16] uint64_t voff;
   [24] struct receive_record_arg *rrd;
   [32] struct receive_record_arg *next_rrd;
   [40] zio_cksum_t cksum;
   [72] zio_cksum_t prev_cksum;
  [104] int err;
  [108] boolean_t byteswap;
  [112] list_t ignore_obj_list;
}
SIZE: 144
```

**Comment by lorddoskias** [comment]
@behlendorf So i compiled the file with -fstack-usage and here is what gcc reports: 
With patch: `dmu_send.c:2350:1:dmu_recv_stream   240 static`
Without my patch: `dmu_send.c:2350:1:dmu_recv_stream   1336    static`

**Comment by lorddoskias** [comment]
@behlendorf  I think I found the culprit, pahole gives a slitghly different picture than crash: 

```
struct receive_writer_arg {
	objset_t *                 os;                   /*     0     8 */
	boolean_t                  byteswap;             /*     8     4 */

	/* XXX 4 bytes hole, try to pack */

	bqueue_t                   q;                    /*    16   592 */
	/* --- cacheline 9 boundary (576 bytes) was 32 bytes ago --- */
	kmutex_t                   mutex;                /*   608   200 */
	/* --- cacheline 12 boundary (768 bytes) was 40 bytes ago --- */
	kcondvar_t                 cv;                   /*   808   168 */
	/* --- cacheline 15 boundary (960 bytes) was 16 bytes ago --- */
	boolean_t                  done;                 /*   976     4 */
	int                        err;                  /*   980     4 */
	avl_tree_t *               guid_to_ds_map;       /*   984     8 */

	/* size: 992, cachelines: 16, members: 8 */
	/* sum members: 988, holes: 1, sum holes: 4 */
	/* last cacheline: 32 bytes */
};
nborisov@fisk:~/projects/zfs/myfork/zfs/module/zfs$ pahole -C receive_arg dmu_send.o 
die__process_function: tag not supported (INVALID)!
struct receive_arg {
	objset_t *                 os;                   /*     0     8 */
	vnode_t *                  vp;                   /*     8     8 */
	uint64_t                   voff;                 /*    16     8 */
	struct receive_record_arg * rrd;                 /*    24     8 */
	struct receive_record_arg * next_rrd;            /*    32     8 */
	zio_cksum_t                cksum;                /*    40    32 */
	/* --- cacheline 1 boundary (64 bytes) was 8 bytes ago --- */
	zio_cksum_t                prev_cksum;           /*    72    32 */
	int                        err;                  /*   104     4 */
	boolean_t                  byteswap;             /*   108     4 */
	list_t                     ignore_obj_list;      /*   112    32 */
	/* --- cacheline 2 boundary (128 bytes) was 16 bytes ago --- */

	/* size: 144, cachelines: 3, members: 10 */
	/* last cacheline: 16 bytes */
};

```

**Comment by behlendorf** [comment]
@lorddoskias that explains a lot, do you know what specific compile flag is causing that alignment?  Anyway, assuming the CentOS 7.1 builder passes this LGTM and if you're also happy with it I'll get it merged today.

**Comment by lorddoskias** [comment]
@behlendorf yes I'm happy with the overall result. Though, I'm not sure it's alignment per-se. So the first number in the comment is the beginning offset of the struct and the next number is the size. So in receive_writer_arg you have the bqueue which is almost 600 bytes + a 200 byte mutex and a 168 byte kcondvar. That's just 900 bytes worth of stack data. Now the bqueue looks like the following: 

```
struct bqueue {
	list_t                     bq_list;              /*     0    32 */
	kmutex_t                   bq_lock;              /*    32   200 */
	/* --- cacheline 3 boundary (192 bytes) was 40 bytes ago --- */
	kcondvar_t                 bq_add_cv;            /*   232   168 */
	/* --- cacheline 6 boundary (384 bytes) was 16 bytes ago --- */
	kcondvar_t                 bq_pop_cv;            /*   400   168 */
	/* --- cacheline 8 boundary (512 bytes) was 56 bytes ago --- */
	uint64_t                   bq_size;              /*   568     8 */
	/* --- cacheline 9 boundary (576 bytes) --- */
	uint64_t                   bq_maxsize;           /*   576     8 */
	size_t                     bq_node_offset;       /*   584     8 */

	/* size: 592, cachelines: 10, members: 7 */
	/* last cacheline: 16 bytes */
};
```

The bulk of it being the synchronization primitives. I will acquire relevant info from zfs which is built with no debug just to compare the size/layout of the structs.

**Comment by lorddoskias** [comment]
So building without --enable-debug for zfs doesn't change the sizes of the structure. So the only culprit left are actually compiler flags. And indeed in module/zfs/Makefile with --enable-debug there is an extra -Werror to EXTRA_CFLAGS, whereas with debug disabled the -Werror is not there.

**Comment by behlendorf** [comment]
@lorddoskias right so the possible culprits might be your gcc version, additional compiler flags added by your version of the kernels builds system, or possibly how you've built your kernel.  Regardless, it's clearly a thing which can happen (although interestingly it doesn't happen for any of the buildbot builders).

**Comment by behlendorf** [comment]
Merged as:

04bc461 Reduce stack usage of dmu_recv_stream function

**Pull request closed without merging**
