### PR TITLE
Activate LVM volume groups before looking for zpools

### PR DESCRIPTION
**Pull request by benalbrecht**
Using the script by @jgoerzen from zfsonlinux/pkg-zfs#102.

I'm not sure, whether this should be an extra script.
Maybe it would be better to add this functionality to the main zfs initramfs script?

### CODE REVIEW

**Comment by sempervictus** [comment]
Would this cause issues for the people running VGs out of their ZVOLs?

**Comment by behlendorf** [comment]
Aside from the error message this LGTM.  Can anyone, @jgoerzen, @benalbrecht,  comment on how much real user and testing has been done with this script?

**Comment by jgoerzen** [comment]
I put it on a couple of Debian systems back when I submitted that bug report, and it has been working fine.  Other than that, I can't say.

**Comment by behlendorf** [comment]
@benalbrecht if you can address the patch comments and refresh this pull request and verify it works as expected we can likely get this merged.

**Comment by benalbrecht** [comment]
addressed the comments and rebased.
the script still works as expected.

**Comment by zeigerpuppy** [comment]
As @sempervictus mentioned, I think this change is having a detrimental effect on mounting LVM groups *on top of* ZFS.  In Debian 9 (zfs-dkms 0.7.11-1~bpo9+1), I am finding that I have to run `vgscan` again after boot or else the LVM volumes are not enumerated.  
I am using LVM volumes for docker machines, so this also causes docker to fail to start.

**Pull request closed without merging**
