### PR TITLE
Rewrite of minor line-drawing function

### PR DESCRIPTION
**Pull request by scotws**
### Description
Replaces multi-line, looped function to draw a line of 72 dashes by a single line
of code. This is a minor, low-priority optimization. 

### How Has This Been Tested?
Tested in-tree on Ubuntu 16.04 LTS with stock ZFS version 0.6.5.9-2 with Python 2.7.12 and Python 3.5.2.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain `Signed-off-by`.
- [ ] Change has been approved by a ZFS on Linux member.

Signed-off-by: Scot W. Stevenson <scot.stevenson@gmail.com>

### CODE REVIEW

**Comment by scotws** [comment]
Oops. Sorry about that.

**Comment by gmelikov** [comment]
@scotws you can use rebase https://git-scm.com/docs/git-rebase or `commit --amend` and force push after, github will update PR accordingly.

**Comment by scotws** [comment]
@gmelikov Sorry, in the meantime I royally screwed up the local copy of my fork, and in the end did a clean refork of zfsonlinux/zfs to scotws/zfs. What is the easiest way forward for you, I resubmit the PR? Apols.

**Comment by scotws** [comment]
Wait, I think I have a better idea anyway after looking at the code again anyway. Will close this and resubmit new version soon.

**Pull request closed without merging**
