### PR TITLE
Revert "Fix issues with truncated files in raw sends"

### LINKED ISSUE #8540: PANIC at dnode.c:715:dnode_reallocate()  / Crash - interrupt took too long
Hi! I am not sure how to debug this. Any ideas?

filename:       /lib/modules/4.15.18-12-pve/zfs/zfs.ko
version:        0.7.13-pve1~bpo1

image

### PR DESCRIPTION
**Pull request by behlendorf**
### Motivation and Context

Resolve #8540 and #8565 which affect a more common use
case for send/recv.

### Description

This partially reverts commit 5dbf8b4ed.  This change resolved
the issues observed with truncated files in raw sends, #7378.
However, the required changes to `dnode_allocate()` appear
to have introduced a regression for non-raw streams which
needs to be understood, #8540 and #8565.

### How Has This Been Tested?

Locally built, pending full CI results.  Restores code to previous state.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by kpande** [comment]
reverted because it affects a more common use case?? so invisible corruption is preferable to a panic where no data is lost? I am confused here. do we actually care about data integrity?

**Comment by behlendorf** [comment]
This was done to ensure continued correct behavior of one of the most heavily used long standing features.  Raw send/recv is a great upcoming feature, but it has not yet been released.  And won't be until this issue is resolved.

**Comment by kpande** [comment]
and this issue wasn't even in a published release candidate... what is your point? correctness only matters to some users and not others? invisible corruption is already happening to users running RC3. as much as you'd like to think that it is not...

**Comment by beren12** [comment]
I think your bot had the best responses to this kpande…

"ZFS native encryption is currently broken and not recommended for use due to issue #6845"
and
"ZFS native encryption is currently in TESTING, and not for PRODUCTION use unless you UNDERSTAND THE RISKS. See #6845."

I mean the new bugs have been found but the answer is the same.
At least this isn't all of encryption, just raw sends for it.

**Pull request merged**
