### PR TITLE
Enhance vdev layer to maintain logical and physical block sizes

### PR DESCRIPTION
**Pull request by prakashsurya**
This is a port of the FreeBSD patches:

    * https://github.com/freebsd/freebsd/commit/cfd489a4ed1aa114d31ae863ee02e3d59afb9a14
    * https://github.com/freebsd/freebsd/commit/bd47afb2893407b47a1dc3c9165507d2aa77b5b7

I've only verified it compiles, so it probably still needs some work before landing.

### CODE REVIEW

**Comment by sempervictus** [comment]
@behlendorf: any thoughts on where this stands? Seems like a useful thing to have, and may save a reasonable quotient of sanity for users if it works.

**Comment by behlendorf** [comment]
@sempervictus these patches from FreeBSD has stalled out.  They haven't been merged in to illumos and those will definitely conflict with the pending large block patches.    It's also not completely clear to me exactly what problem they solve.  Aside from being a nice thing in general.

In fact, I'm going to close this pull request as stale for now until someone has time to revisit this.

**Comment by kpande** [comment]
doesn't freebsd have large block support?

**Comment by behlendorf** [comment]
It does.  And these things can co-exist.  But these changes would need to be updated to account for that.

**Comment by jumbi77** [comment]
Does someone may have time to have a look at it or even did already? Does this will fix the problem mentioned in #2024 too? Many thanks

**Pull request closed without merging**
