### PR TITLE
#4388 Prefetching data doesn't appear to be working (take2)

### PR DESCRIPTION
**Pull request by kernelOfTruth**
Account for the fact that rw_tryupgrade(&zf->zf_rwlock)

    in module/zfs/dmu_zfetch.c could fail:

drop the rwlock
	rw_exit(&zf->zf_rwlock)
and reacquire
	rw_enter(&zf->zf_rwlock, RW_WRITER);

suggested by rottegift (Sean Doran) and lundman (Jorgen Lundman)

Fixes: https://github.com/zfsonlinux/zfs/issues/4388 Prefetching data doesn't appear to be working.

### CODE REVIEW

**Comment by prometheanfire** [comment]
2-3% on a single disk?

I'm seeing 30% of perf (via scrubs) because of this issue on a 15 disk raidz3

**Comment by kernelOfTruth** [comment]
@prometheanfire I was referring to a specific benchmark result,

taking into account that throughput before capped out at 800 MB/s and with the regression at 300 MB/s,

that's an improvement of 260-270%,

yes - so 60 to 70% reduction comes close.

So this means that the prescient prefetch was also affected - thanks for your data :)

**Comment by prometheanfire** [comment]
ah, thanks for the confirmation :D

**Comment by kernelOfTruth** [comment]
The prefetching in this approach ( rw_enter - always prefetching - https://github.com/zfsonlinux/zfs/issues/4388#issuecomment-192054407 ) definitely makes a noticable change - the question now is whether it's save to use (locking, hardlock issues)

zpool import time decreased from 25-26 seconds to around 20 seconds,

folders with quite some content are being almost instantly displayed whereas previously it took several seconds.

This is just from some minor testing, I'll proceed to use and do some serious work over the following days (research, database usage, etc.) and see how fast & stable it'll turn out to be

**Comment by behlendorf** [comment]
This was fixed with zfsonlinux/spl@a6ae97caed620b0e9e0575346062c751f6f15483 which has been merged.  Closing.

**Pull request closed without merging**
