### PR TITLE
Fix memory leaks in zfsvfs_create_impl()

### PR DESCRIPTION
**Pull request by tcaputi**
This patch simply fixes some small memory leaks that can happen
during error handling in zfsvfs_create_impl(). If the function
fails, it frees all the memory / references it created.

Signed-off-by: Tom Caputi <tcaputi@datto.com>

### Motivation and Context
This issue was found while working on #8487 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by tonyhutter** [comment]
Is there a reason why you're not freeing `zfsvfs` in `zfsvfs_create()`?  Like:

```
zfsvfs_create(const char *osname, boolean_t readonly, zfsvfs_t **zfvp)
{
        objset_t *os;
        zfsvfs_t *zfsvfs;
        int error;
        boolean_t ro = (readonly || (strchr(osname, '@') != NULL));

        zfsvfs = kmem_zalloc(sizeof (zfsvfs_t), KM_SLEEP);

        error = dmu_objset_own(osname, DMU_OST_ZFS, ro, B_TRUE, zfsvfs, &os);
        if (error != 0) {
                kmem_free(zfsvfs, sizeof (zfsvfs_t));
                return (error);
        }

        error = zfsvfs_create_impl(zfvp, zfsvfs, os);
        if (error != 0) {
                dmu_objset_disown(os, B_TRUE, zfsvfs);
+               zfsvfs_free(zfsvfs);
        }
        return (error);
}
```

**Comment by tcaputi** [comment]
@tonyhutter This code really needs a good round of fixing to get rid of issues like this. A lot of the code in the zfsvfs layer is very hard to reason about memory leaks and should probably be rewritten / refactored a good bit to have more symmetry between alloc and free calls. Personally, I'm not really a fan of how `zfsvfs_create_impl()` works in general (it has an out-parameter that is just the input parameter if it succeeds). This fix simply addresses the problem here, but I think we should definitely revisit all this code at some point in the future.

**Comment by tonyhutter** [comment]
@tcaputi ok, can you add in a comment then just so people know, like:
```
/* 
 * Note: zfsvfs is assumed to be malloc'd, and will be freed by this function
 * on a failure.  Do not pass in a statically allocated zfsvfs.
 */
int
zfsvfs_create_impl(zfsvfs_t **zfvp, zfsvfs_t *zfsvfs, objset_t *os)
```

**Comment by tcaputi** [comment]
@tonyhutter your comments have been addressed.

**Pull request merged**
