### PR TITLE
[commit-tests] Multi pull-request + ABD2 buildbot crunch

### PR DESCRIPTION
**Pull request by kernelOfTruth**
With DeHackEd's  dehacked-bleedingedge4 as a base and adding several commits from some pending buildbots this should offer a glimpse on the sanity of near future code base ...

... builbot(s) - your turn !

(I _really_ hope that at least some of those final commits will be tested)

### CODE REVIEW

**Comment by kernelOfTruth** [comment]
```
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/arc.c:585:26: error: ‘arc_stats_t’ has no member named ‘arcstat_abd_hdr_size’
  atomic_add_64(&arc_stats.stat.value.ui64, (val))
                          ^
/usr/src/spl-0.6.5/include/sys/atomic.h:288:62: note: in definition of macro ‘atomic_add_64’
 #define atomic_add_64(v, i) atomic64_add((i), (atomic64_t *)(v))
                                                              ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/arc.c:1728:3: note: in expansion of macro ‘ARCSTAT_INCR’
   ARCSTAT_INCR(arcstat_abd_hdr_size, space);
   ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/arc.c: In function ‘arc_space_return’:
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/arc.c:585:26: error: ‘arc_stats_t’ has no member named ‘arcstat_abd_hdr_size’
  atomic_add_64(&arc_stats.stat.value.ui64, (val))
                          ^
/usr/src/spl-0.6.5/include/sys/atomic.h:288:62: note: in definition of macro ‘atomic_add_64’
 #define atomic_add_64(v, i) atomic64_add((i), (atomic64_t *)(v))
                                                              ^
/var/tmp/portage/sys-fs/zfs-kmod-9999-r1/work/zfs-kmod-9999/module/zfs/arc.c:1765:3: note: in expansion of macro ‘ARCSTAT_INCR’
   ARCSTAT_INCR(arcstat_abd_hdr_size, -space);
```

**Comment by kernelOfTruth** [comment]
Too much stuff, will only add select commits, base it on tuxoko_zfs/abd2_rebase-10.12.2015 and see how it goes ...

**Comment by kernelOfTruth** [comment]
Re-opening, even only for having the buildbot results of each single commit :+1:

**Comment by DeHackEd** [comment]
Sorry, there are known issues with my bleedingedge4 patches. Drop "Count ABD memory usage" entirely.

Sometimes I use github as storage for copying code between systems while I bang on it.

**Comment by kernelOfTruth** [comment]
@DeHackEd sure, done, thanks for letting me know !

Sadly the buildbot didn't pick up the last commit in https://github.com/zfsonlinux/zfs/pull/4094 
(Increase ZFS_OBJ_MTX_SZ further) like I had anticipated,

maybe I have to modify it, for it to recognize changes (was this already tested in the past by the buildbot ?)

Anyway - the results are encouraging and all commits related to ABD2 appear to be fine/flawless (3 still in queue)

**Comment by DeHackEd** [comment]
Oh, the nagios stuff fails cstyle so just drop those as well.

**Comment by behlendorf** [comment]
@kernelOfTruth yes the buildbot has been updated to build every commit in the stack because that can be done relatively quickly (~5 min per commit) but only to test to the top commit.  Even so if you force update the branch with a large number of commit frequently you can generate a ton of work for the buildbot.

**Comment by kernelOfTruth** [comment]
@behlendorf great improvement ! I like how you can see in a relatively short time how things stand :+1: 

Thanks

**Comment by kernelOfTruth** [comment]
Closing this since the pull-requests achieved their purpose (testing mainly the ABD2 changes for outstanding typos, oversights, bugs, etc.)

**Pull request closed without merging**
