### PR TITLE
lzjb: Check for input buffer overrun

### PR DESCRIPTION
**Pull request by rlaager**
This is a PR based on the comment from @rewolff here:
https://github.com/zfsonlinux/zfs/issues/3831#issuecomment-172832495

I take no position on whether this change is good or bad. I haven't even compiled it. I'm just "transferring" it to be a pull request, so it can get built by the buildbots, reviewed, etc.

@rewolff, if you want to resubmit this as your on PR, that'd be even better.

### CODE REVIEW

**Comment by behlendorf** [comment]
My only concern with this is the extra conditional _might ever so slightly_ impact performance.  However, since most people should now be using lz4, since it's better in all ways, adding this extra lzjb safety check is probably a good idea and will almost certainly have a negligible impact.

**Comment by behlendorf** [comment]
@rewolff could you comment on this.  Do you have any specific test cases you can share?

**Comment by rewolff** [comment]
I was working on a datarecovery. They had a HUGE RAID system with, by the time they get to me, two bad disks. I wrote some stuff to use, not the last revision, but  the second to last, if the last revision was stored on the disk I could not recover the data from. Of course this occasionally results in corruption or "bad input data" if something points to bad data. 

IIRC, I pulled that code from the FS driver and used it in my user-space utilities to decode the stuf file-by-file. I had to do the patch here to prevent my userspace code from segfaulting, and I decided to do the right thing and report things upstream.

**Comment by behlendorf** [comment]
@rewolff thanks for the additional background and reporting the issue so we're aware of it.  However, aside from potential data recovery scenarios this code has been problem free so I'd prefer not to merge to proposed additional check.

**Pull request closed without merging**
